### ISSUE TITLE
Make ProgressBar look more like pacman's

### ISSUE THREAD

**Issue by Tyilo** [actionless/pikaur#10]
The first of these progessbars is pacman's the second one is pikaur's:

```
(1/1) upgrading pikaur-git                         [----------------------] 100%
Reading repository package databases............................................
```

It would be better if pikaur used the same progessbar style as pacman.

It would also be neat if pikaur supported the ILoveCandy easter egg.

**Comment by actionless** [comment]
>ILoveCandy
idk, mb i can use yellow mouse 🐭  emoji and 'eat' red bottle🍼  (ketchup :D)  emojis

**Comment by actionless** [comment]
![2018-02-14--1518614358_1249x177_scrot](https://user-images.githubusercontent.com/1655669/36206283-bc2b9184-1189-11e8-9741-a2b3e77cb2b5.png)

**Comment by rmarquis** [comment]
Or remove it entirely. That progress bar is pretty much unnecessary.

**Comment by actionless** [comment]
on HDD repo packages are being read for quite a long, even on system with ssd it's about 3 seconds

**Comment by actionless** [comment]
i've speeded up package db reading and removed the progressbars :-)
