### ISSUE TITLE
Use the http_proxy and https_proxy environment variables

### ISSUE THREAD

**Issue by 6wheels** [actionless/pikaur#101]
Pikaur fails to read the AUR repository info.
It works nicely at home, but at work, and behind a proxy, it fails.

Do you use the http_proxy and https_proxy environment variables?

Here is the stack trace I have : 
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date                                                                                                                        0,0   B  0,00B/s 00:00 [c o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  o  ]   0%
 community                                                                                                                                  4,2 MiB  1736K/s 00:03 [-----------------------------------------------------------------------------------------------------] 100%
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
Exception in callback MultipleTasksExecutorPool.create_process_done_callback.<locals>._process_done_callback(<Task finishe...nreachable",)>) at /usr/lib/python3.6/site-packages/pikaur/async.py:174
handle: <Handle MultipleTasksExecutorPool.create_process_done_callback.<locals>._process_done_callback(<Task finishe...nreachable",)>) at /usr/lib/python3.6/site-packages/pikaur/async.py:174>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/pikaur/async.py", line 177, in _process_done_callback
    result = future.result()
  File "/usr/lib/python3.6/site-packages/pikaur/aur.py", line 56, in aur_client_task
    loop, AUR_HOST, self.uri, result_class=NetworkTaskResultJSON
  File "/usr/lib/python3.6/site-packages/pikaur/async_net.py", line 145, in https_client_task
    ssl=ssl_context, loop=loop
  File "/usr/lib/python3.6/asyncio/streams.py", line 81, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 786, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 110] Connect call failed ('5.9.250.164', 443), [Errno 101] Network is unreachable
```

**Comment by actionless** [comment]
if there are some volunteers to implement it sooner here is a good starting point: https://github.com/actionless/pikaur/blob/master/pikaur/async_net.py#L143-L146

**Comment by 6wheels** [comment]
I'd like to help but I don't know python very well.
A bit of research showed me urllib2 can be used to easily pass through a proxy.

**Comment by actionless** [comment]
actually i think what refactoring from asyncio to threading should resolve that (because then i'll be able to use urllib and so standard proxying mechanism) without any performace affect

**Comment by 6wheels** [comment]
That's great to hear!
I'm sorry I can't help for this, reading Python is painfull for me... It would take me ages to do something properly coded.

**Comment by actionless** [comment]
i've refactored aur rpc client to use urllib instead of asyncio, now it should very easy to refactor this

**Comment by 6wheels** [comment]
Hi @actionless,
I'm having some more troubles with the pikaur 0.10.x. But this time, I have no stack trace at all.
It just hangs after syncing the core, extra and community repositories.
It works without any problem at home (no proxy).

**Comment by actionless** [comment]
cc @jingyu9575

**Comment by jingyu9575** [comment]
@6wheels I have made a change (#152) in the proxy handling code to fix a 404 error (#132). Now the proxy is detected by python itself from environment variables.

My environment variables are: `http_proxy=http://proxy.server:port https_proxy=http://proxy.server:port`, and the new version can use the proxy without error. 

What are your values of http_proxy 
and https_proxy? Do you have no_proxy or REQUEST_METHOD set?

**Comment by 6wheels** [comment]
@jingyu9575 
I set my proxy variables globally in `/etc/profile.d/proxy.sh` (under archlinux) as follows:
```export http_proxy=http://theproxyhost:3128
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export no_proxy="localhost,127.0.0.1,localaddress,.mycorporation.net"
```

So yes, I have a `no_proxy` variable set, but only for local address and local network.
I don't understand the REQUEST_METHOD part?

I'd like to help, but with debug nor log, It's a bit difficult.

**Comment by 6wheels** [comment]
Sorry but as I said, it just hangs after syncing the community repo, really nothing more.
This is used to work in the previous version (after merging the PR you did for this issue).

And the problem is that pikaur does not ends. I have to force kill the process with ctrl-c, so the exit code is not representative. But here is the output of my console :
```
sabre@sabrewall ~ time pikaur -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
pikaur -Syu  0,50s user 0,09s system 0% cpu 2:46,89 total
 ✘ sabre@sabrewall ~ echo $?
130
sabre@sabrewall ~ cat /etc/profile.d/proxy.sh
export http_proxy=http://mylocalproxy:3128
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export no_proxy="localhost,127.0.0.1,localaddress,.mycorporation.net"
```

I could test a dev version with some more debug output if you can provide one (or just guide me to modify the source code to do so).

**Comment by actionless** [comment]
if it just hangs i am wondering if it could be not proxy-related at all but the same issue as here?
https://github.com/actionless/pikaur/issues/161

**Comment by 6wheels** [comment]
@actionless you're probably right, I'll try what you suggested in this issue. Thanks.

**Comment by 6wheels** [comment]
@actionless it seems to be same issue as #161. I'm getting the same stacktrace after commenting the 3 lines in the pikaur's main.py file.

**Comment by actionless** [comment]
@6wheels can you still reproduce it now?

**Comment by 6wheels** [comment]
@actionless Yes, I reproduced the problem with the current stable version. 
```
sabre@sabrewall ~ pikaur -Vq
Pikaur v0.10.1
Pacman v5.0.2 - libalpm v10.0.2
```

I'll try the git version to confirm it's fixed or not.

**Comment by actionless** [comment]
but latest stable is 0.10.3

**Comment by 6wheels** [comment]
Oh you're right, my bad, but since I couldn't update... :D

Anyway, the problem is solved! It does not hang anymore with 0.10.3.

Thanks again for your time!!!

**Comment by actionless** [comment]
thank you for testing/reporting!

**Comment by adlerweb** [comment]
I would like to reiterate on this topic. As far as I can tell the change in 40a1675c9d2ce1f1575c93892fdf3c93cfb4aec0 only affects pikaur itself while crawling through AUR, makepkg however is started via [systemd-run](https://github.com/actionless/pikaur/blob/979c1ee9a9abf3a06c0dbd99a6112b85b20c1d3d/pikaur/core.py#L140) in an mostly empty environment and doesn't know anything about the surrounding variables. As such Processes like git/curl/whatever called during _makepkg_ do not know about the proxy settings of the parent process and fail while connecting.

Most processes can be configured globally (git --system, makepkg.conf for curl, etc), however when a PKGBUILD calls something else (pjproject in my current case) the whole build falls apart.

Since there doesn't seem to be a way to convince systemd-run to [start with a prepopulated env or pull in something like /etc/profile.d/*](https://github.com/coreos/bugs/issues/1507): Does anyone over here know an solution for this? Alternatively we could alter the systemd-run-call to include the proper variables if set (-E http_proxy ...), however this would mean to add and maintain a good batch of additional code for this edge-case.

**Comment by actionless** [comment]
unfortunately it seems what

> Alternatively we could alter the systemd-run-call to include the proper variables if set (-E http_proxy ...), however this would mean to add and maintain a good batch of additional code for this edge-case.

is the way

would you try to come up with the patch?
