### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by AlexWayfer** [actionless/pikaur#106]
Hello!

I don't know Python very well, but I'm ready to try to help you (make some PRs).

But without tests it looks dangerous.

I think they'll be useful to many people.

Thanks.

**Comment by actionless** [comment]
Actually so far there is a small sorta test — during travis CI pikaur is getting installed and used to install mypy from AUR.
that one test in combination with mypy and pylint already was helpful catching the regressions however i will agree with you what adding more real tests will be helpful.
