### ISSUE TITLE
Please update FAQ with the typeface your are using in your terminal screenshot.

### ISSUE THREAD

**Issue by victorz** [actionless/pikaur#107]
I would love to know this -- it looks great! 😇 

Sorry to create an issue for this on your project, but I didn't know how else to get in contact with you to ask the question.

**Comment by actionless** [comment]
it called `Fantasque Sans Mono` (however i'm not sure that's worth adding to FAQ)

you can find my full dotfiles here:
https://github.com/actionless/dotfiles/blob/master/theme-h50-monovedek-lcars/.config/fontconfig/fonts.conf#L161

**Comment by AlexWayfer** [comment]
I think, those interested will able to find this issue with answer, maybe even via words "font" or "font-family". And there is no need to add this to FAQ.

**Comment by ishammahajan** [comment]
> it called `Fantasque Sans Mono` (however i'm not sure that's worth adding to FAQ)
> 
> you can find my full dotfiles here: [actionless/dotfiles@`master`/theme-h50-monovedek-lcars/.config/fontconfig/fonts.conf#L161](https://github.com/actionless/dotfiles/blob/master/theme-h50-monovedek-lcars/.config/fontconfig/fonts.conf#L161)

Oh my god you're a godsend. Thanks for the font, I love it! :)
