### ISSUE TITLE
Translation for ask_to_continue / prompt.py

### ISSUE THREAD

**Issue by guschtlswife** [actionless/pikaur#109]
I'm working on a german translation and I'm wondering how to deal with the [y/n] in ask_to_continue / prompt.py:71.
This doesn't seem to be covered by translations yet.
How is this supposed to be handled?

**Comment by actionless** [comment]
+ @Zopieux @Yardanico @Mauladen @alexandreslopes

**Comment by Zopieux** [comment]
I tried to translate that stuff in my [original commit](https://github.com/actionless/pikaur/commit/fbc81aff0475a2d035e9e4ce235438b8ff538471#diff-90d34a33af9e024f6a0b512cf53fd79cR8). Another contribution refactored prompt stuff and [removed](https://github.com/actionless/pikaur/commit/acdf2974986e2bda95deea10d7211d7407ad7de8#diff-90d34a33af9e024f6a0b512cf53fd79c) the translations.

`+` @JakeStanger

**Comment by guschtlswife** [comment]
I see, thanks!
So I guess I'll just provide a translation based on the current sate, without caring about that ask_to_continue() prompts at the moment.

**Comment by JakeStanger** [comment]
I'll get on fixing that now.

**Comment by actionless** [comment]
thanks @JakeStanger for the fix, now @guschtlswife can update the translation

**Comment by guschtlswife** [comment]
thanks everyone! PR coming soon...

**Comment by guschtlswife** [comment]
prompt.py:82
`return (answer == 'y') or (default_yes and answer == '')`

Isn't this supposed to be
`return (answer == Y) or (default_yes and answer == '')`
so that it checks for the translated answer in the return

**Comment by JakeStanger** [comment]
You're correct, I thought I changed that one but it must have slipped past me.
