### ISSUE TITLE
Running pikaur as  sudo

### ISSUE THREAD

**Issue by ChasNelson1990** [actionless/pikaur#110]
Hi, I'm new to Arch and, on a clean install (only gnome has been isntalled) and have installed pikaur as per the instructions here.
My natural instinct when installing a package is to sudo it - a habit from apt and dnf. So I tried 'sudo pikaur -Syu <package-name>' and got the following issue:

> ==> Installing missing dependencies...
> sudo: unable to open /run/sudo/ts/run-u744: Read-only file system
> 
> We trust you have received the usual lecture from the local System
> Administrator. It usually boils down to these three things:
> 
>     #1) Respect the privacy of others.
>     #2) Think before you type.
>     #3) With great power comes great responsibility.
> 
> sudo: no tty present and no askpass program specified
> ==> ERROR: 'pacman' failed to install missing dependencies.
> ==> WARNING: Failed to remove installed dependencies.
> Finished with result: exit-code
> Main processes terminated with: code=exited/status=1
> Service runtime: 294ms
> Command 'systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -p WorkingDirectory=/var/cache/pikaur/build/slack-desktop makepkg --syncdeps --rmdeps --force' failed to execute.
> Do you want to retry? [Y/n]

Which has been very confusing to me. However, I finally worked out that if I run 'pikaur -Syu <package-name>' (no sudo) - the dynamic user process (I think) asks for the sudo password and everything works fine. That's great now I know but it might be worth adding a catch for this.

I beleive pacaur will output a warning "You cannot perform this operation as root" if you try to sudo it. Maybe that's worth implementing in pikaur for people new to it like me.

**Comment by actionless** [comment]
the feature was added by @seirl so casting him to this thread since he's probably using a similar workflow (i'm usually running pikaur without sudo except for docker usecase)

**Comment by actionless** [comment]
btw i've also double-checked, `sudo pikaur -S pikaur-git` works as expected frmo my machine, so it seems there is some configuration issue related to sudoers

**Comment by seirl** [comment]
Yeah, there's a bug :/ We can't install deps from root as a dynamic user, and that's what makepkg does with --syncdeps. There should be two steps for deps, one where we install dependencies as root, and one where we make the package.

**Comment by AladW** [comment]
I was doing something similar for aurbuild then stopped because reimplementing `makepkg -r` was a pain in the ass. Things are much simpler if you use [https://git.archlinux.org/devtools.git/commit/?id=cda9cf436b2897b063c1e40efb144404aad8b821](makechrootpkg -U) instead.

Anyway what makepkg does is save the current installed packages with `pacman -Qq` then compare that at a later point. See https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n315

**Comment by actionless** [comment]
good, `devtools` are in `extra` so i think `makechrootpkg` would cause me to reimplement less of already existing tools logic

thanks a lot for your recommendation!

**Comment by AladW** [comment]
As I recall the only objection was that using makechrootpkg takes some amount of space, since you at least need one `base-devel` container (~700mb?). I don't think this is a big deal since Arch is oriented at desktop systems with sufficient storage anyway.

**Comment by actionless** [comment]
oh, i did actually forgot those details

mb it's possible to implement some option for makechrootpkg to use overlayfs with the original system? so makepkg will see all the packages installed but won't be able to affect the actual filesystem state

**Comment by AladW** [comment]
`systemd-nspawn` has something like this:

>-x, --ephemeral
>
>   If specified, the container is run with a temporary snapshot of its file system that is removed immediately when the container terminates. May not be specified together with --template=.
>
>    Note that this switch leaves host name, machine ID and all other settings that could identify the instance unmodified.

I still find it highly unlikely that pikaur matches the use case of people running Arch on 1GB compact flash cards...

**Comment by AladW** [comment]
Does `makepkg` create a pacman lock manually? As said, I'd just look at whatever it does and try to copy it as good as you can, until you agree on some other approach. 

Note: I'd probably put such functionality in some separate module explaing how this reimplementation is relevant to running `pikaur` as root.

**Comment by actionless** [comment]
> As said, I'd just look at whatever it does and try to copy it as good as you can, until you agree on some other approach.

point of my previous message regarding the lock is what where is a potential race condition here:
https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n1614

db could be altered between the moment deps were installed (and so pacman released the lock) and the moment when list of packages (-Qq) was saved

**Comment by AladW** [comment]
I see. (could be worth mentioning on pacman-dev) You'd still need to run `pacman -T` though, unless you used `--needed`.

**Comment by actionless** [comment]
@ChasNelson1990 @seirl please test

**Comment by ChasNelson1990** [comment]
If I run:
`sudo pikaur -Syu`
I get:
`don't run me as root.`
Thanks, I think that'll be very helpful for future peeps.

**Comment by actionless** [comment]
first update it from git, `pikaur -S pikaur-git`, next try it running with sudo

**Comment by ChasNelson1990** [comment]
Sorry, I thought I had pulled the latest git commit and build that using `makepkg`.
I've now used `pikaur-git` as suggested. Running
`sudo pikaur -Syu`
seems to just work, excellent.

**Comment by ChasNelson1990** [comment]
Actually... I've just tried to update signal, which builds with npm and I get the following (after 'Starting build()...')
```┌──────────────────────────────────────────────┐
│           npm update check failed            │
│     Try running with sudo or get access      │
│     to the local update config store via     │
│ sudo chown -R $USER:$(id -gn $USER) /.config │
└──────────────────────────────────────────────┘

┌──────────────────────────────────────────────┐
│           npm update check failed            │
│     Try running with sudo or get access      │
│     to the local update config store via     │
│ sudo chown -R $USER:$(id -gn $USER) /.config │
└──────────────────────────────────────────────┘
mkdir: cannot create directory ‘/.nvm’: Read-only file system
mkdir: cannot create directory ‘/.nvm’: Read-only file system
mkdir: cannot create directory ‘/.nvm’: Read-only file system
creating directory /.nvm/.cache/bin/node-v8.2.1-linux-x64/files failed
Binary download failed, trying source.
==> ERROR: A failure occurred in build().
    Aborting...
Finished with result: exit-code
Main processes terminated wioutput handler exiting
Command 'systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -p WorkingDirectory=/var/cache/pikaur/build/signal makepkg --force' failed to execute.```

**Comment by actionless** [comment]
i am not sure i can do anything about it, i think if you will directly run that build command through systemd-run you'll have the same result

**Comment by actionless** [comment]
@seirl what do you think?

**Comment by ChasNelson1990** [comment]
I obviously don't know how things work in the backend that well but if I run
`pikaur -Syu signal`
npm seems to ask for my sudo password. If I run
`sudo pikaur -Syu signal`
it doesn't and fails with the above error.
Is there anyway to identify anything that will use npm to build, presumably it appears as a dependency?, and spawn the build as non-sudo thread...
... now I've reread that back to myself it sounds more complicated than I thought... and a possible security issue?

**Comment by ChasNelson1990** [comment]
Maybe, rather than run a build as non-sudo, just output a warning?

**Comment by actionless** [comment]
let's wait for @seirl 's opinion on that

**Comment by seirl** [comment]
Thanks for the notice, I think we need to investigate what assumptions packages are allowed to make about their environment, because clearly this kind of errors show we don't setup a 100% correct environment. If this is a simple fix we should try it. If it's really complicated, maybe the best way to move forward is makechrootpkg... I'll try to look into that soon.

**Comment by seirl** [comment]
@ChasNelson1990 What's the package you're trying to build that calls npm?

**Comment by ChasNelson1990** [comment]
https://aur.archlinux.org/packages/signal/

**Comment by actionless** [comment]
i've tried with a different npm package (nodejs-tldr) and have slightly different log (`/root/.config` vs `/.config`):

```
==> Starting package()...                                                                                                 [2/342]
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
npm ERR! path /root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f62373eae173bb5ee216d0ff788
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f62373eae173
bb5ee216d0ff788'
npm ERR!  { Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f62373eae
173bb5ee216d0ff788'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f62373e
ae173bb5ee216d0ff788'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f62373eae173bb5ee216d0ff788' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f
62373eae173bb5ee216d0ff788\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/root/.npm/_cacache/index-v5/29/53/c669886bf3cd9606a8daccd98643a40e3f62373eae173bb5ee216d0ff788' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by actionless** [comment]
i think it should be fine now, feel free to reopen

**Comment by seirl** [comment]
Awesome, this is what I suspected to be the issue too. Just two nitpicks. We shouldn't give /private in the HOME as the symlink should be properly set up when pacman runs. Actually, we should just set it as /tmp, because /tmp with dynamic users is a private version disconnected from the real file system that is cleaned up after the service runs.

**Comment by seirl** [comment]
I don't have time to test it extensively right now, but the fix should just be:

```
diff --git a/pikaur/core.py b/pikaur/core.py
index c0f3d53..0b4b25c 100644
--- a/pikaur/core.py
+++ b/pikaur/core.py
@@ -48,7 +48,7 @@ def isolate_root_cmd(cmd: List[str], cwd=None) -> List[str]:
         'systemd-run', '--pipe', '--wait',
         '-p', 'DynamicUser=yes',
         '-p', 'CacheDirectory=pikaur',
-        '-E', 'HOME=/var/cache/private/pikaur',
+        '-E', 'HOME=/tmp',
     ]
     if cwd is not None:
         base_root_isolator += ['-p', 'WorkingDirectory=' + cwd]

```

**Comment by actionless** [comment]
> because /tmp with dynamic users is a private version disconnected from the real file system that is cleaned up after the service runs.

 i did honestly read the docs for dynamic users before doing this fix but probably missed that point, thanks!

**Comment by actionless** [comment]
@ChasNelson1990 please test if it works for you with the latest patch

**Comment by ChasNelson1990** [comment]
Updated with
`pikaur -S pikaur-git`
then ran
`sudo pikaur -S signal`
and it builds successfully through npm and installs without issue. Signal appears to work fine after install.
Is that what you wanted me to check? Or did you want any more details?

**Comment by seirl** [comment]
Yeah, I think if that works it should be fine. Feel free to open new bug reports if you encounter more problems with dynamic users! :+1:

**Comment by actionless** [comment]
@ChasNelson1990  thanks for checking!
