### ISSUE TITLE
Pikaur asks for passwords multiple times during upgrade (sudo)

### ISSUE THREAD

**Issue by Tyilo** [actionless/pikaur#114]
It would be nice if I was possible to just enter your password once, when running `pikaur -Syu --devel` and not multiple times.
This is problematic if I have some packages that takes a long time to build and I just want `pikaur` to upgrade my packages, without having to watch when I you have to enter my password again.

This could probably be implemented using seteuid/setegid.

**Comment by AladW** [comment]
Yes, that quick hack is pretty much what everyone decides to go with. Unfortunately it fails when the sudo timeout is set to 0.

Note: using setuid for this is absurd and hasn't worked for interpreted executables in two decades.

**Comment by actionless** [comment]
mb using polkit? :-) AFAIR it was more controllable

**Comment by AladW** [comment]
If you know how to use it, I suppose. There were some AUR helpers (or rather pacman GUIs) in the past that took this approach and did it wrong, opening up wide gaps in the default configuration.

**Comment by actionless** [comment]
@Tyilo as a workaround for now you can just run it with sudo, since Dynamic Users seems to be fixed

**Comment by actionless** [comment]
thanks for reporting! hopefully fixed

**Comment by SpineEyE** [comment]
This seems to work.
