### ISSUE TITLE
Error: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by Yumasi** [actionless/pikaur#12]
Hi !

I updated pikaur to the last version, and every command except -Ss fails with the following traceback:

> ~/.configuration(master) » pikaur -Syu
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
> :: Starting full system upgrade...
> Reading repository package databases..........................................
> :: Starting full AUR upgrade...
> Reading local package database................................................
> Traceback (most recent call last):
>   File "/home/treize/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur.py", line 8, in <module>
>     main()
>   File "/home/treize/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 244, in main
>     cli_entry_point()
>   File "/home/treize/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 196, in cli_entry_point
>     cli_upgrade_packages(args)
>   File "/home/treize/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/main.py", line 79, in cli_upgrade_packages
>     exclude_ignored_packages(not_found_aur_pkgs, args)
>   File "/home/treize/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/meta_package.py", line 212, in exclude_ignored_packages
>     for ignored_pkg in (args.ignore or []) + PacmanConfig.get('IgnorePkg', []):
>   File "/home/treize/.cache/pikaur/build/pikaur-git/src/pikaur-git/pikaur/core.py", line 325, in get
>     value = value.split()
> AttributeError: 'list' object has no attribute 'split'`

**Comment by actionless** [comment]
thanks for reporting!
