### ISSUE TITLE
Proceed with installation results in nothing to do

### ISSUE THREAD

**Issue by RyanDwyer** [actionless/pikaur#120]
$ pikaur -Syu
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
    :: Starting full AUR upgrade...
    Reading local package database...
    Reading repository package databases...
    Reading AUR packages info...
    
    :: AUR package will be installed:
     pikaur-git                            0.9.2+22+g2bb6b3a-1 -> 0.9.3-1
    
    :: Proceed with installation? [Y/n] 
    :: [v]iew package detail   [m]anually select packages
    >>y
    looking for conflicting packages...
    :: Starting full system upgrade...
     there is nothing to do

Pikaur fails to upgrade the package. I've seen this with python-pysdl2 and now pikaur-git.

I'm using the default autogenerated config file at ~/.config/pikaur.conf.

I'll debug it when I get around to it, but thought I'd ask here first in case it was a known issue or if I'm doing something wrong.

**Comment by actionless** [comment]
that bug already fixed in 0.9.3, so after upgrading it explicitly (`pikaur -S pikaur-git`) it should work

thanks for reporting anyway!
