### ISSUE TITLE
Pass --noconfirm to pacman

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#122]
Hi,
it's a little annoying to press Y/Enter for pikaur and for pacman when they both ask the same. For every little upgrade and every conflict, I need to confirm my decision to pikaur and pacman. Is there a reason why you don't just pass --noconfirm to pacman? Or maybe bypass pikaur confirmation if only packages from the official repositories are getting installed.
Thanks for for your work on the project.

**Comment by actionless** [comment]
@AladW how probable do you think to get something like that merged to pacman? just `--yes` option to answer Yes to the "main"/"default" question but normal interactive behavior in all other prompts

**Comment by AladW** [comment]
I guess that boils down to documenting the `--ask` flag. Or if you know the conflicts in advance, use `pacinstall foo --remove bar`.

**Comment by actionless** [comment]
but --ask flag is almost the opposite to that idea — it assumes `--noconfirm` for each question and just allowing to choose the boolean answer

**Comment by actionless** [comment]
and also, as it was discussed in couple of thread here and in other not pikaur-related talks, trying to forecast what pacman will ask and do something to prevent it (iue resolving conflict or choosing alternative manually) is re-implementation of pacman itself and both dev and user would like to avoid that

**Comment by actionless** [comment]
or i can include as a part of sourcetree patched pacman and make travis to double-check if the base source still up-to-date with the upstream

**Comment by AladW** [comment]
I do hope you're joking.

**Comment by actionless** [comment]
i know how it sounds but it's actually less painful way:
1) no need to re-implement pacman logic, just use `pacman -S --yes`
2) we have a warranty what version of the pacman is matching arch because on each pikaur commit we'll double check what we are using the latest revision of pacman

**Comment by SpineEyE** [comment]
Seriously though, where can I file feature requests for pacman? Because as it is implemented now, `--noconfirm` makes no sense if it's unsafe to be used. And at the same time it doesn't make sense to ask the user if he really wants to install something that he explicitly specified when starting the program.

**Comment by actionless** [comment]
you could also file a featurerequest to get a better weather outside

**Comment by AladW** [comment]
No offense, but that's the craziest idea any AUR helper has come up with so far. Closest was bauerbill which shipped its fork of makepkg (for the removed --pkg option). But eh - not my problem.

**Comment by Morganamilo** [comment]
At that point why not just fork Pacman and add AUR support.

**Comment by actionless** [comment]
but as it was descrived in my latest message, pacman sources will be fetched on the buildtime, so ni the repo i'll have only small patch with about 10-20 lines, which will be very easy to audit

and of course i am counting this more like a temporary solution until it will be addressed upstream, not as a permanent

**Comment by SpineEyE** [comment]
Why not fork pacman and change it so that it doesn't ask for a mere upgrade/install confirmation. That way, you don't need to include it in pikaur and don't even need to change any options when calling the pacman-fork. It would be transparent to the user and available for every aur helper.

**Comment by actionless** [comment]
yup, i was just thinking about provinding pacman executable with `--yes` option as an optional dependency, not to "poison" pikaur itself with it

**Comment by AladW** [comment]
It would also be completely unsupported by anyone but a random guy on the internet. Compare to pacutils which is actually made and supported by a pacman developer.

**Comment by actionless** [comment]
mb something like that could be added as a pacutil?

**Comment by AladW** [comment]
I still don't see the issue with using pacinstall which can remove and install packages at the same time... unless that reference you made to "reimplementing pacman by calculating conflicts".

**Comment by actionless** [comment]
and partial upgrade

**Comment by AladW** [comment]
At the same time you could ask the question - if you leave the conflict handling to pacman but reverse its original response - how do you confirm that the package replacement is the one the user actually wanted? If you calculate these things in advance like `aurman` does it's clear from the getgo what will happen and where.

**Comment by actionless** [comment]
>At the same time you could ask the question - if you leave the conflict handling to pacman but reverse its original response - how do you confirm that the package replacement is the one the user actually wanted?

i am not getting this question, particularly i didn't understood the part about "reverse"

**Comment by actionless** [comment]
just to clarify i mean to skip only this question:

`:: Proceed with installation? [Y/n]` on `pacman -S/Su/U`

**Comment by AladW** [comment]
Oh, I see what you mean now. Does `pacinstall --print-only` tell you if a conflict occurs and if only a package would be installed?

**Comment by actionless** [comment]
thanks, that could be a nice approach, using some libalpm-related tool as an external conflict resolver is something what i was looking for

**Comment by actionless** [comment]
hm, it seems what `--no-confirm` option is not working for conflicts in `pacinstall`

**Comment by AladW** [comment]
I have no means to test any of this but as https://github.com/andrewgregory/pacutils/issues/15#issuecomment-260215224 shows suggestions for a better --no-confirm could be good.

**Comment by actionless** [comment]
mb i'll also consider some tricks with stdin to just send `y` for the first question and next release stdin to the terminal

**Comment by AladW** [comment]
Right but what do you do with localized output from pacman then? Unless I misunderstood what you meant by "first question".

**Comment by actionless** [comment]
mb get from `pacman.mo` for the current locale :-)

**Comment by actionless** [comment]
so far i've managed to get it to work with a pseudo-tty (with hardcoded strings for english locale), now only locales part need to be done and it can be pushed

**Comment by SpineEyE** [comment]
Somehow, the output of pacman in the console is now constrained to 80 characters, although my console width is bigger. When I use `pacman -Syyu`, the download progress bar takes the whole 190 characters console width, with `pikaur -Syyu`, it only takes the 80.

Btw. pikaur doesn't forward both `y` to pacman, so it doesn't force a db refresh.

**Comment by actionless** [comment]
@SpineEyE thanks for testing, fixed that

**Comment by AladW** [comment]
Well, looks like that's quite a bit more involved in reimplementations than any sort of algorithm to compute conflicts or `--ask`.

**Comment by actionless** [comment]
wut? that's 'reimplementing' apps like pexpect/expect/etc

**Comment by SpineEyE** [comment]
Seems like the wrong display width (struck through above) was an error on my end somehow, can't reproduce it anymore.

**Comment by actionless** [comment]
@SpineEyE 
> was an error on my end somehow, can't reproduce it anymore.

no, it was probably fixed by https://github.com/actionless/pikaur/commit/4d71c97505fd5f0ba30c44fad21c33e83e488aa4 (was linked above)

**Comment by SpineEyE** [comment]
I see, cool!

**Comment by AladW** [comment]
>wut? that's 'reimplementing' apps like pexpect/expect/etc

Well, if you want to make life as difficult as possible with these horribly convoluted hacks that permeate the project, that's completely up to you...

**Comment by actionless** [comment]
but using `expect` is a common way of feeding interactive answer into the application which not allows that in its cli api

**Comment by actionless** [comment]
and regarding second point, it sounds a bit thought up because i have release plan (represented as milestones on github) which i almost not deviate
