### ISSUE TITLE
AUR dep which was previously explicitly installed gets incorrectly marked as a dependency 

### ISSUE THREAD

**Issue by Morganamilo** [actionless/pikaur#123]
Remember #116? Using that as an example:

I'm installing `nqp` for that to install it needs to update `moarmv` so Pikaur pulls it in as a dependency. After the install the install reason for `moarmv` gets changed from explicit to as a dependency.

`moarmv` was already installed so the install reason should not change.

**Comment by Morganamilo** [comment]
While this is fixed for -Su I have realised this does not apply to -S.


`nqp` depends on `moarvm>=2018.06`. If I have an earlier version of `moarvm` installed and I do `pikaur -S nqp`, `moarvm>=2018.06` gets pulled in as a dependency and changed from asexplicit to asdepends.

**Comment by actionless** [comment]
@Morganamilo are you sure you running the latest version?

i've made following steps to reproduce it:
1) installed `moarvm 2018.05-1`
2) pacman -Qi moarvm | grep Reason
`Install Reason  : Explicitly installed`
3) pikaur -S nqp
```
:: AUR package will be installed:
 nqp                                                        -> 2018.06-1
:: New dependency will be installed from AUR:
 moarvm (for nqp)                      2018.05-1            -> 2018.06-1
```
4) pacman -Qi moarvm | grep Reason
`Install Reason  : Explicitly installed`

**Comment by actionless** [comment]
it seems i can reproduce it only when the dep is already built and therefore installing from cache, thanks for investigation :-)

**Comment by actionless** [comment]
please check if the last patch helps
