### ISSUE TITLE
Show outdated AUR packages

### ISSUE THREAD

**Issue by Noammac** [actionless/pikaur#124]
If searching for packages, show packages that are marked as outdated as such.

For example:

Pacaur
![image](https://user-images.githubusercontent.com/19552683/38692110-7e1afc52-3e8b-11e8-9c06-3caf11b7882f.png)

Trizen
![image](https://user-images.githubusercontent.com/19552683/38692150-90e7c400-3e8b-11e8-883f-4d8137e25138.png)

**Comment by Morganamilo** [comment]
Look at the version colour ;)

**Comment by Noammac** [comment]
For comparison, pikaur (everything but the repo libretro version is outdated):

![image](https://user-images.githubusercontent.com/19552683/38693396-6d912b78-3e8f-11e8-9b6c-8b898d957ce0.png)

And it can't be the colour of the aur repo name, because trizen (which is up to date on the AUR) is of the same repo colour:

![image](https://user-images.githubusercontent.com/19552683/38693447-8d596d94-3e8f-11e8-85a4-780e80d08082.png)

**Comment by Morganamilo** [comment]
Ah I'm dumb and read the first image as pikaur, the sames being similar and all. Silly me.

**Comment by Morganamilo** [comment]
Out of curiosity which method do you prefer? Explicitly saying out of date or the colour change?

**Comment by Noammac** [comment]
I agree with @Yardanico, explicitly saying that a package is out of date is better both for users (who may have set pikaur or pacman not to use colours, or have made the colour for out-of-date and in-date the same) and for automation (you can grep for the "out-of-date" tag).

**Comment by SpineEyE** [comment]
As an argument for only colors, no "out-of-date": It looks more compact and is easier/faster to see. So best would be to offer an option, but I can see that it's more effort and the other option is needed for grep etc...

**Comment by Morganamilo** [comment]
I decided to have a go at python for the first time in a couple of years: #125
