### ISSUE TITLE
Crashes on trying to install mlterm

### ISSUE THREAD

**Issue by MartinSandfuchs** [actionless/pikaur#127]
running
`pikaur -S mlterm`
gives the following error:
`shutil.Error: [('~/.cache/pikaur/aur_repos/mlterm/.gitignore', '~/.cache/pikaur/build/mlterm/.gitignore', "[Errno 2] No such file or directory: '~/.cache/pikaur/aur_repos/mlterm/.gitignore'")]`
but installation with pacaur succeeds

**Comment by actionless** [comment]
that AUR package is broken, however pikaur should ignore such problems instead of failing:

```
$ ll /home/lie/.cache/pikaur/aur_repos/mlterm
drwxr-xr-x    - lie 14 Apr 18:29 .git
lrwxrwxrwx   30 lie 14 Apr 18:29 .gitignore -> /home/aksr/arch/pkg/.gitignore
.rw-r--r--  805 lie 14 Apr 18:30 .SRCINFO
.rw-r--r--  228 lie 14 Apr 18:29 mlterm.desktop
.rw-r--r-- 2.7k lie 14 Apr 18:29 PKGBUILD
```

**Comment by actionless** [comment]
actually, following symlinks when copying is sorta security flow, so i am raising the priority for solving this

**Comment by actionless** [comment]
thanks for reporting!
