### ISSUE TITLE
[Regression] Pikaur does not seem to take “provides” into account for installed packages

### ISSUE THREAD

**Issue by sboukortt** [actionless/pikaur#129]
I recently tried to use pikaur to upgrade [reaper](https://aur.archlinux.org/packages/reaper/). reaper depends on [jack](https://www.archlinux.org/packages/extra/x86_64/jack/), which on my machine is provided by [jack2](https://www.archlinux.org/packages/community/x86_64/jack2/). Pikaur fails to take that into account and insists on installing jack specifically:

~~~~
$ pikaur -S reaper
[…]
Reading local package database...
:: Installing repository dependencies for reaper:
resolving dependencies...
looking for conflicting packages...
:: jack and jack2 are in conflict. Remove jack2? [y/N] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: jack and jack2 are in conflict
Command 'sudo pacman --color=always --sync --asdeps jack' failed to execute.
Do you want to retry? [Y/n] n
Do you want to proceed? [y/N] n
~~~~

Bisecting seems to show that 6a1d9bf027e3b70b1f2ce09ddeb93449194943bb is the culprit.

**Comment by actionless** [comment]
thanks for reporting and debugging!
