### ISSUE TITLE
add `--edit` flag to force build files editing even if NoEdit set in the config

### ISSUE THREAD

**Issue by arivarton** [actionless/pikaur#130]
Seems to be "no" after the see build files choice appears but othwerwise the default is "yes". Might be some reasoning behind this that I'm not aware of.

![2018-04-16_17 29 26](https://user-images.githubusercontent.com/13208468/38825537-74da15ce-419c-11e8-8718-f62b033dfddf.png)

**Comment by arivarton** [comment]
Closed the issue since it's the same on the screenshot in the README so it's a deliberate choice not a bug.

**Comment by actionless** [comment]
or, to rephrase it simply, if pikaur proposing to show diff -- then `edit` default answer will be no, because it's being assumed what you already inspected the changed via git diff

**Comment by actionless** [comment]
btw if you just always going to press `N` all the time you could just pass `--noedit` or set `NoEdit=yes` in the config

**Comment by arivarton** [comment]
I usually press N all the time but thought it would be easier if I could just press enter so atleast the choice to edit would still be there.

Would be nice to have some way to bypass the NoEdit in the config. For example passing an argument with the package that you want to edit.

**Comment by actionless** [comment]
mb just `--edit` (not for specific package) to force `--noedit` to be canceled

then you can just install that one package which you want to edit with `--edit` flag and next install the rest

**Comment by arivarton** [comment]
Didn't realise you were asking a question there, thought it was already implemented. Just tried it now and it didn't work offcourse.

Yes an --edit parameter to force it would be nice.
