### ISSUE TITLE
Trying to install an aur package results in a 404 not found error

### ISSUE THREAD

**Issue by mc1472** [actionless/pikaur#132]
When I try to install an it says reading local package database and then give a trace back.
here's the [traceback](https://gist.github.com/mc1472/a8659be9a263c71c55de5eddbc7a11ef)

**Comment by actionless** [comment]
```
  File "/home/michael/pacman-packages/pikaur-0.9.3/src/pikaur-0.9.3/pikaur/aur.py", line 119, in aur_rpc_info
    result_json = get_json_from_url(
  File "/home/michael/pacman-packages/pikaur-0.9.3/src/pikaur-0.9.3/pikaur/aur.py", line 73, in get_json_from_url
    result_bytes = read_bytes_from_url(url)
  File "/home/michael/pacman-packages/pikaur-0.9.3/src/pikaur-0.9.3/pikaur/aur.py", line 67, in read_bytes_from_url
response = request.urlopen(req)
```

you could add `print(url)` statement to debug which exactly URL is causing the problem but so far it's looking more like a network connection-related problem

**Comment by mc1472** [comment]
sorry! it's my proxy server doing this. thank you for helping.

**Comment by jingyu9575** [comment]
@mc1472 I am affected by the same error. I cannot make it work with proxy servers. How did you solve it?

**Comment by actionless** [comment]
it should read `http_proxy` or `https_proxy` env vars

**Comment by jingyu9575** [comment]
`http_proxy` and `https_proxy` are both set to the proxy server. `curl` to the same url works with these environment variables.

I propose a change in #152. This fixes it for me and still uses the proxy.
