### ISSUE TITLE
Re-generate .SRCINFO only if PKGBUILD was actually changed by user

### ISSUE THREAD

**Issue by cg505** [actionless/pikaur#133]
It is often that pikaur will fail to pull an AUR repo because of uncommited local changes, but those local changes are just an added newline at the end of .SRCINFO. This can be overcome easily by hitting 'c', but it seems that pikaur's own SrcInfo.regenerate is probably causing the discrepancy. This happens on non-devel packages as well, so it makes me suspect the regeneration that takes place after we ask to edit the PKGBUILD. Then the git conflict doesn't actually come up until the next time we try to update that package.

Let me know if any more info is needed.

**Comment by actionless** [comment]
i think i can check checksum of PKGBUILD and regenerate .SRCINFO only if the checksum changed after editing the file

what do you think?

**Comment by cg505** [comment]
That seems reasonable. My initial concern is that the PKGBUILD might change but .SRCINFO would stay the same, but this would cause a conflict when updating in the future anyway.
