### ISSUE TITLE
pikaur gets confused by unity-editor

### ISSUE THREAD

**Issue by sboukortt** [actionless/pikaur#14]
Trying to install [unity-editor](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=unity-editor&id=1cab5b172f4459ea5b912a093d52a72d4bdca1e5) results in the following message from pikaur:

~~~~
Command "sudo pacman --upgrade --noconfirm /home/sami/.cache/pikaur/build/unity-editor/unity-editor-1:2017.3.1f1+20180216-1-x86_64.pkg.tar' # Prevent compressing of the final package

--download-location="${startdir}" \

--install-location="${pkgdir}${_prefix}" \

yes | unity-setup --components=$1 > "/tmp/$1.log"

sed -i "/^Version=/c\Version=${_version}${_build}" "${srcdir}/unity-editor.desktop" failed to execute.
~~~~

It seems that it might be getting confused by the `PKGEXT=` line.

**Comment by actionless** [comment]
thanks for reporting!

**Comment by actionless** [comment]
seems only part of the issue is solved

**Comment by actionless** [comment]
mb later it will be better to implement specific parser for such purpose
