### ISSUE TITLE
Problem comparing versions with git commits/revision

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#143]
```
$ python -c 'from pyalpm import vercmp ; print(vercmp("1", "2"))'
-1

$ python -c 'from pyalpm import vercmp ; print(vercmp("0.9", "0.10"))'
-1

$ python -c 'from pyalpm import vercmp ; print(vercmp("0.10", "0.10.1"))'
-1

$ python -c 'from pyalpm import vercmp ; print(vercmp("0.10+7", "0.10.1+7"))'
1

$ python -c 'from pyalpm import vercmp ; print(vercmp("0.10-7-1", "0.10.1-7-1"))'
1

$ python -c 'from pyalpm import vercmp ; print(vercmp("0.10-7", "0.10.1-7"))'
-1
```

@AladW is that an expected behavior or should be reported to alpm?

**Comment by AladW** [comment]
`alpm_pkg_vercmp` is one hell of a ride. See https://git.archlinux.org/pacman.git/tree/lib/libalpm/version.c

**Comment by actionless** [comment]
adding new `revision` version component to `parseEVR` would solve this case:
```
python -c 'from pyalpm import vercmp ; print(vercmp("0.10+7", "0.10.1+7"))'
```

but this one will still remain (however i am not sure what it's a legitimate version format in Arch):
```
python -c 'from pyalpm import vercmp ; print(vercmp("0.10-7-1", "0.10.1-7-1"))'
```

**Comment by actionless** [comment]
i don't think the real issue inside rpmvercmp can be fixed with a small patch, but i am looking into it now

**Comment by actionless** [comment]
as far as i remember initial implementation of that in pikaur, the best-working approach was instead of splitting version to fixed parts as parseEVR do now (to epoch, version and relese) but instead splitting both version to groups based on separators, ie roughly the algo is following:

    IF ALPHANUM
        add to existing group
    ELSEIF CHARACTER != CURRENT_SEPARATOR
        create new group

so in the folllowing examples the version will be splitted on smaller parts with the same separator and rpmvercmp will be able to compare them correctly:

`[0.10, ] and [0.10.1, ]`
`[0.10, 7, ] and [0.10.1, 7, ]`

**Comment by actionless** [comment]
so far my outcome what the best way to solve this will be to add a function similar to `parseEVR` so here https://git.archlinux.org/pacman.git/tree/lib/libalpm/version.c#n265 intead of `ret = rpmvercmp(ver1, ver2);`
it will first split ver1 and ver2 to arrays (as in the message above) by their separators groups and next will pass to rpmvercmp only each group

**Comment by AladW** [comment]
I still have trouble understanding what the actual issue is. Can you give an example of an actual AUR package satisfying `PKGBUILD(5)` where `vercmp` proves problematic?

**Comment by Morganamilo** [comment]
I have an example actually: https://github.com/trizen/trizen/issues/152. I've chocked it down to a bad `pkgver()` function, I don't know if you'd call it a valid bug in vercmp.

**Comment by actionless** [comment]
@AladW 

those versions looks correct, aren't they?

```
$ python -c 'from pyalpm import vercmp ; print(vercmp("0.10+7", "0.10.1+7"))'
1

$ python -c 'from pyalpm import vercmp ; print(vercmp("0.10+7-1", "0.10.1+7-1"))'
1
```

**Comment by AladW** [comment]
Right, compare https://www.archlinux.org/packages/extra/x86_64/gtkmm3/

**Comment by actionless** [comment]
```
$ python -c 'from pyalpm import vercmp ; print(vercmp("3.22+4+g3002ed86-1", "3.22.2+1+g3002ed86-1"))'
1
```

**Comment by actionless** [comment]
and `sort -V` for the examples above:

```
$ echo -e "3.22.0+4+g3002ed86-1\n3.22.2+1+g3002ed86-1" | sort -V
3.22.0+4+g3002ed86-1
3.22.2+1+g3002ed86-1

$ echo -e "3.22+4+g3002ed86-1\n3.22.2+1+g3002ed86-1" | sort -V
3.22+4+g3002ed86-1
3.22.2+1+g3002ed86-1
```

**Comment by AladW** [comment]
Oh well, if it's the same with `/bin/vercmp` I can see the problem...

**Comment by actionless** [comment]
yup, it is

**Comment by actionless** [comment]
closing since there is nothing need to be done here
