### ISSUE TITLE
Don't ask twice for replacements/conflicts

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#149]
instead use pikspect to feed the answer to the first question into pacman (he's asking the second question)

**Comment by AladW** [comment]
When does this second question occur, directly after the first or somewhere during the build process?

**Comment by AlexWayfer** [comment]
> When does this second question occur, directly after the first or somewhere during the build process?

The full log in the #148, which referencing this issue above. But the answer is "somewhere during the build process".

**Comment by actionless** [comment]
@AladW please mark it as solved in the table

**Comment by AladW** [comment]
Huzzah!

**Comment by AladW** [comment]
https://wiki.archlinux.org/index.php?title=AUR_helpers&diff=522238&oldid=522182

**Comment by AladW** [comment]
Note that the table suggestions this applies for a `pikaur` release, of which I don't know there's one with the new pikspect features.

**Comment by actionless** [comment]
@AladW done
