### ISSUE TITLE
A problem in search packages using multi-words

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#15]
Pikaur has some problem in search packages using multi-words with `-Ss`, for example, compared with pacaur:

```
pacaur -Ss plasma menu               
extra/kmenuedit 5.12.1-1 (plasma) [installed]
    KDE menu editor
aur/plasma-addons-customdesktopmenu-git 0.0.1-3 (1, 0.00)
    Custom desktop menu for Plasma5
aur/kim-frameworks 0.9.5-4 (1, 0.00)
    Plasma 5 Image Menu to compress, resize, convert, rotate and webexport
aur/kdeplasma-applets-actos-soundmenu-git 4.b6d5fa2-1 (2, 0.00)
    Very simple Sound Menu plasmoid with volume and playback (MPRIS) controls for the current media player
```

```
pikaur -Ss plasma menu                                   
Reading local package database..................................................................................................................
extra/kmenuedit 5.12.1-1 (plasma) [installed]
    KDE menu editor
```

**Comment by actionless** [comment]
https://aur.archlinux.org/rpc/?v=5&type=search&arg=plasma%20menu&by=name-desc
returns nothing

i'll see how it implemented in pacaur

**Comment by actionless** [comment]
weird, it looks about the same:
https://github.com/falconindy/cower/blob/master/src/aur.c#L73-L75

**Comment by XavierCLL** [comment]
mmm maybe the answer is the inner join of the following two request:

https://aur.archlinux.org/rpc/?v=5&type=search&arg=plasma&by=name-desc
https://aur.archlinux.org/rpc/?v=5&type=search&arg=menu&by=name-desc

but I have not tried it, but I think that's how it's done

**Comment by actionless** [comment]
i can't find any join in cower's code, i think the problem what i am escaping space somehow differently

**Comment by actionless** [comment]
url escaping is for sure the same, i'll try to dive deeper into cower's code, mb i still missing something

**Comment by actionless** [comment]
i still didn't found how it's joining the results but i've already found what it's sending request for each search word separately, so it's already enough to proceed in that direction

**Comment by XavierCLL** [comment]
very quickly fixed! thanks!
