### ISSUE TITLE
Pikaur don't work with su

### ISSUE THREAD

**Issue by Bundy01** [actionless/pikaur#155]
Hello,
I have to install sudo if I want pikaur 0.10.1-1 to work on Arch (Syu, Rsn...):

`Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 261, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 204, in cli_entry_point
    cli_upgrade_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 108, in cli_upgrade_packages
    pacman_args, args=args
  File "/usr/lib/python3.6/site-packages/pikaur/prompt.py", line 115, in retry_interactive_command_or_exit
    if not retry_interactive_command(cmd_args, args=args, **kwargs):
  File "/usr/lib/python3.6/site-packages/pikaur/prompt.py", line 98, in retry_interactive_command
    good = pikspect_spawn(cmd_args, **kwargs).returncode == 0
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 154, in pikspect
    subprocess.run(['sudo', '-v'])
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'
`

**Comment by Morganamilo** [comment]
You mention su in the tittle but sudo in the post, these are different programs. Try running `pacman -S base-devel` as root before trying to use pikaur.

**Comment by Bundy01** [comment]
Hi,
I confirm that pikaur does not work with su if sudo is not installed.

**Comment by Morganamilo** [comment]
Like I said su and sudo are separate programs and have nothing to do with each other. Pikaur needs sudo to work, su is irrelevant.

**Comment by Morganamilo** [comment]
Although it might be worth mentioning that seems as Pikaur can run as root you can use su to gain root then use pikaur. However Pikaur will not invoke su on it's own.

**Comment by Bundy01** [comment]
Can you tell me for what reason, I use "su" because I put my current account as a simple user.
Thanks :)

**Comment by Morganamilo** [comment]
su allows you to change user using the password of the user you are changing to.
sudo allows you to change user using your own password, as long as you are permitted by the sudoers config.

**Comment by Bundy01** [comment]
I wanted to delete sudo, because it was no longer useful to me:(
Thank you for your answers. May I close issue ?

**Comment by Morganamilo** [comment]
If you've you've installed sudo and it work sure.

**Comment by Bundy01** [comment]
Ok,
thanks.

**Comment by actionless** [comment]
if you don't want to install `sudo` for some reason you can do:
```bash
$ su
# pikaur -S whatever
```

**Comment by Morganamilo** [comment]
makepkg requires sudo though.

**Comment by Morganamilo** [comment]
Although thinking about it, I think makepkg only needs sudo for certain args so depending on how you implement it its possible pikaur works fine without sudo.

Still sudo is part of base-devel so I would not recommend removing it while also using AUR packages.
