### ISSUE TITLE
To be installed packages dependency mix-up

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#159]
Hi,
when I `pikaur -Syu`, pikaur wants to upgrade (among others):

```
:: AUR packages will be installed:
 linux-ck                              4.15.18-1           -> 4.16.6-2
 linux-ck-headers                      4.15.18-1           -> 4.16.6-2
 virtualbox-ck-host-modules            5.2.10-1            -> 5.2.10-2
```

It builds linux-ck fine, but doesn't install it yet and instead starts to build `virtualbox-ck-host-modules`. This package however, depends on linux-ck>=4.16 which is not installed at that point. It leads to the following warnings (`cat`) and error:

```
==> Entering fakeroot environment...
cat: /usr/lib/modules/extramodules-4.16-ck/version: No such file or directory
==> Starting package_virtualbox-ck-host-modules()...
/home/peter/.cache/pikaur/build/virtualbox-ck-modules/PKGBUILD: line 37: cd: dkms/vboxhost/5.2.10_OSE//x86_64/module: No such file or directory
==> ERROR: A failure occurred in package_virtualbox-ck-host-modules().
    Aborting...
Command 'makepkg --force' failed to execute.
Do you want to retry? [Y/n]  n
```

So if I understand correctly, pikaur should first install `linux-ck` (and `linux-ck-headers`) and then build/install `virtualbox-ck-host-modules`

---

Just some additional information why it's a bad idea to check dependencies without including pending upgrades: apparently, `aurman` also can't deal with this upgrade, it doesn't even begin to build:

```
error: failed to prepare transaction (could not satisfy dependencies)
:: virtualbox-ck-host-modules: installing linux-ck (4.16.6-2) breaks dependency 'linux-ck<4.16'
```

Edit: Sorry, I accidentally wrote `yay` instead of `aurman`. `yay` actually begins to build but with strange behavior. It asks multiple times for CPU architecture.

**Comment by actionless** [comment]
please show `pikaur -Vq`, i think i've already fixed that one

**Comment by SpineEyE** [comment]
```
Pikaur v0.10.1+27+g4071904
Pacman v5.0.2 - libalpm v10.0.2
```

Unfortunately cannot test it anymore as I already upgraded through trizen, sorry.
