### ISSUE TITLE
Show the origin of the repository per package or group

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#16]
With pacman, pacaur, yaourt show the origin of each package, for example in command to update like as:

```
pacaur -Syu

extra/kwin                     
core/libnghttp2          
core/linux
aur/skypeforlinux-preview-bin
```
For me is so important to know what is the repo of packages, mainly if is from aur or compiled repo.

In pikaur I see that the packages sorted by upgrade version level, I propose to order the packages by group of the repository and after by upgrade level, like:

```
pikaur -Syu

[core]
linux
libnghttp2

[extra]
kwin

[aur]
skypeforlinux-preview-bin
```
Thanks!

**Comment by actionless** [comment]
>> For me is so important to know what is the repo of packages, mainly if is from aur or compiled repo

that separation (between aur and repo) is already implemented when installing/upgrading packages

but yes, showing also repo name would be nice

**Comment by XavierCLL** [comment]
I propose grouping by each repo and show it only if there are packages to update in this repo and show it with tags in the header, example:
```
[core]
packages ...
[extra]
packages ...
[community]
packages ...
[multilib]
packages ...
[others]
packages ...
[aur]
packages ...
```

**Comment by actionless** [comment]
what do you think?


![2018-02-21--1519170479_1222x1108_scrot](https://user-images.githubusercontent.com/1655669/36455585-12b20382-16a1-11e8-8b00-efe5d7dbd0bd.png)

**Comment by XavierCLL** [comment]
Very good, I like it!! but missing just one thing, show in the "Respository packages" from which repository they come:
```
:: Repository packages will be installed:
core/linux .....
community/firefox-developer-edition ....
```
similar to "Third-party" block

**Comment by actionless** [comment]
is that really makes any difference? i was thinking it would be better not to overload myself with such information

**Comment by XavierCLL** [comment]
yes, is important, for example, if you use a testing repo is very important to know if the package comes from core, extra, community or testing. Besides, it is important (for example in my case) to pay more attention when the updates come from core.

**Comment by actionless** [comment]
good point regarding testing repos

could you elaborate more about why difference between other official repos could be important during upgrade?

**Comment by XavierCLL** [comment]
the packages from core repo are more delicate for the system, some packages required user intervention (like kernel modules, specific GPU drivers... )

**Comment by actionless** [comment]
i'm still nor convinced:
https://wiki.archlinux.org/index.php/official_repositories#core

**Comment by XavierCLL** [comment]
yes, of course, not all are critical packages in core. All Aur helpers included pacman show where the packages come from.

**Comment by actionless** [comment]
i'll leave this open for some time to think more about it

i just want to find a right balance between amount and usefulness of the information displayed

**Comment by actionless** [comment]
what about showing all the repo names only when choosing `:: [v]iew package detail`?
but in 'quick' view to show the names only for third-partys

**Comment by XavierCLL** [comment]
Maybe, but personally I don't like it, required more steps and this option is very rarely used by the user. There is another option proposed initially, show core, extra, community and/or testing repo by group:

```
:: Packages from core repository:
package1 ...
```

**Comment by XavierCLL** [comment]
Maybe, but personally I don't like it, required more steps and this option is very rarely used by the user. There is another option proposed initially, show core, extra, community and/or testing repo by group:

```
:: Packages from core repository:
package1 ...
package2 ...
:: Packages from extra repository:
package3 ...
package4 ...
:: Packages from archlinuxcn third-party repository:
package5 ...
package6 ...
```
For me, it is the best way for organizing and group for the user, what do you think?

**Comment by actionless** [comment]
for me it just like some extra distracting information

also creating more sections will make less effective for user experience sorting by version diff

**Comment by XavierCLL** [comment]
Yes I like minimalism and clean information, but in these type of tools (and after years using Archlinux and Aur helpers) the show the repositories is very useful information and critical using testing repo. Added more intervention to the user (and if the user knows that) for the view where the packages come from, for me is not the best option, I think that this tool must be by default show the minimum and necessary information (like that). That's just my point of view, after all, you are the main developer. I want to help to pikaur (even only with issue for now) with me some experience in Arch because I think pikaur are one of the best aur helper right now and very promising, thanks and keep the good development.

**Comment by actionless** [comment]
i am agree with importance of nothing what some packages are coming from third-party repo (so i did implmented that already) but showing that for official repos seems like a visual noise which could steal attention from some more important information

however i am still not closing the ticket for now, i think it will be good to leave it open in the status of 'discussion' to collect more opinions on this regard

**Comment by actionless** [comment]
i've decided to make it configable in the upcoming `~/.config/pikaur.conf`

**Comment by XavierCLL** [comment]
amazing solution!
