### ISSUE TITLE
Make diff viewing consistently use pager

### ISSUE THREAD

**Issue by t-animal** [actionless/pikaur#160]
Almost always `PKGBUILD` diffs are too large for the terminal. This results in a pager being shown by `git diff`. Therefore a common workflow is: `Y<Enter> (show diff), :q<Enter> (diff read), <Enter> (don't edit diff), Y<Enter> (show next diff)... `

However every now an then a diff does not fill an entire screen and no pager is shown. In these cases the above workflow may lead to unexpected behaviour (editing diff may be inadvertedly skipped). While with pikaur this is less of a problem than it was with pacaur (several diffs would be skipped), it is still somewhat annoying.

I propose settings `git config core.pager 'less -+F'` on the aur gits. This disables the "--quit-if-one-screen" option on less and results in a more consistent workflow. An alternative could be to introduce a pikaur setting that somehow manages the git config of aur gits.

**Comment by actionless** [comment]
thanks for reporting!
