### ISSUE TITLE
Hanging after running pikaur -Syu

### ISSUE THREAD

**Issue by jmauss** [actionless/pikaur#161]
After running pikaur -Syu, it outputs:
```
$ pikaur -Syu
:: Synchronizing package databases...
core is up to date
extra is up to date
community is up to date
multilib is up to date
_
```

And just hangs there. I can kill it without error, but it never returns back to the prompt.

**Comment by actionless** [comment]
`pikaur -Vq` please

**Comment by actionless** [comment]
and also `pikaur -Qu` and `pacman -Qu`

**Comment by Morganamilo** [comment]
Also might wanna see if `pikaur -Sy` and `pikaur -Su` fail individually.

**Comment by jmauss** [comment]
```
pikaur -Vq
pikaur v0.10.1
Pacman v5.0.2 - libalpm v10.0.2
```

```
pikaur -Qu
libaio    0.3.110-1    0.3.111-1
```

```
pacman -Qu
libaio    0.3.110-1 -> 0.3.111-1
```

**Comment by jmauss** [comment]
Also, scratch that libaio - updated with sudo pacman -Syu.
Here is what I get after:
```
pikaur -Vq
pikaur v0.10.1+39+g40ebd11
Pacman v5.0.2 - libalpm v10.0.2
```

```
pikaur -Qu
Reading local package database...
Reading repository package databases...
Reading AUR package info...
```

```
pacman -Qu
```

**Comment by actionless** [comment]
if it still fails, could you please comment out the following lines in /usr/lib/python3.6/site-packages/pikaur/main.py:
```python
286         signal.signal(signal.SIGINT, handle_sig_int)

289    except KeyboardInterrupt:
290        sys.exit(130)
```

and next hit Ctrl+C while it's hang up and paste the stacktrace

**Comment by actionless** [comment]
you can still downgrade `libaio` with `downgrade` AUR package

**Comment by jmauss** [comment]
Thanks for the info, but I was just noting libaio showed up when it wasn't being problematic.

Let me comment out the lines quick...

![capture](https://user-images.githubusercontent.com/11668753/39600228-bd2ae958-4ee3-11e8-9001-dea12cb4ccf1.PNG)
There is the results.

**Comment by actionless** [comment]
weird, are you pressing Ctrl+C while it's still syncing repositories or after it already hang up?

fro stacktrace it seems what it's still waiting for `pacman -Sy` command to finish

**Comment by jmauss** [comment]
This happens even after a reboot. I wait for it to hang - I will give it a few seconds more this time and post the output.

Same results. Even after waiting 60+ seconds.

**Comment by actionless** [comment]
thanks! so it seems the bug is what `pacman -Sy` command finished but pikaur is ont realizing that for some reason, i'll try to reproduce it now on my machine

btw, does it happen to you only in kernel console or also in some GUI terminal as well?

**Comment by jmauss** [comment]
Yep! This is in a VM without any kind of desktop environment. Haven't done anything fancy, really a pretty fresh install.

**Comment by actionless** [comment]
i'll try from a faster machine later on inside a VM, but on bare installation i can't reproduce it any way so far

may be, just a random guess, it somehow could be related to locales, could you please share `locale` command output?

**Comment by jmauss** [comment]
Here is the output of locale:

![capture](https://user-images.githubusercontent.com/11668753/39629957-7991c06e-4f73-11e8-802d-829e82f0bb42.PNG)

**Comment by actionless** [comment]
is that any difference if you'll do `env LC_ALL=en_US.UTF-8 pikaur -Syu` ?

**Comment by jmauss** [comment]
Still hangs after running that command.

**Comment by actionless** [comment]
while pikaur is hanging what is the output of `ps auxf | grep -v grep | grep -B 3 pacman`? I am wondering if pacman is still running or not

**Comment by jmauss** [comment]
I get no results running that command.

**Comment by actionless** [comment]
i've tried to replace `Popen.communicate` to `.wait` there (since i am still not able to reproduce the issue that's a random guess again)
please install the latest git version (`pikaur -S pikaur-git`) and try if it's still the same

**Comment by actionless** [comment]
Could you then just clone the repo and run it as ‘./pikaur.py’?

**Comment by IgnusG** [comment]
Did you try it in any other virtual env?

**Comment by jmauss** [comment]
Let me try another install or something. I usually just use it in a VM I can connect to for some tools, so setup has always been minimal. I will come back with whatever I find out after a new VM is set up.

**Comment by actionless** [comment]
oh, mb try to connect to your VM via SSH from some "reach" terminal?
just to see if issue somehow related to the tty capabilities or something

**Comment by jmauss** [comment]
Tried to connect through SSH with the same results. Also set up a brand new VM with a fresh minimal install (following the beginners guide) and am still getting the issue. I am using zsh but that shouldn't make a difference.

**Comment by actionless** [comment]
oh, that's a good point, i wasn't trying testing it with zsh, will do now

**Comment by jmauss** [comment]
It should be bash compliant, sorry for not mentioning it earlier.

**Comment by actionless** [comment]
no, not able to reproduce it with zsh as well :-(

**Comment by jmauss** [comment]
This is frustrating to say the least.... so I am sure its something on my end then but I don't know what it could be.

**Comment by actionless** [comment]
and what happens if you run this?
```
$ python -c "import subprocess ; subprocess.Popen(['bash', '-c', 'pacman -V ; sleep 2 ; pacman -V']).communicate()"
```

**Comment by actionless** [comment]
and 

```
$ python -c "import subprocess ; print(subprocess.Popen(['bash', '-c', 'pacman -V ; sleep 2 ; pacman -V'], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate())"
```

**Comment by actionless** [comment]
and 3rd one, the closest to subj:

```
$ sudo python -c "import subprocess ; print(subprocess.Popen(['bash', '-c', 'pacman -Sy ; sleep 2 ; pacma
n -Sy'], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate())"
```

**Comment by jmauss** [comment]
1, 2, and 3 respectively:
![capture](https://user-images.githubusercontent.com/11668753/39818969-cefab450-5367-11e8-9d5b-3799894f6fcc.PNG)
![capture2](https://user-images.githubusercontent.com/11668753/39818974-d19afb7a-5367-11e8-8535-e8b66233265a.PNG)
![capture3](https://user-images.githubusercontent.com/11668753/39818980-d32262c6-5367-11e8-9e24-14ff22dad951.PNG)

**Comment by jmauss** [comment]
Still hanging after the patch. I really appreciate you spending time trying to work through this - I am sure you have better things to do

**Comment by masterodie** [comment]
Having a similar problem here. Running inside VM, only a few packages, base and base-devel are installed. `pikaur -Sy` alone runs fine, `pikaur -Syu` or `pikaur -Su` hang after installation or building the first aur package, even if no package updates are available. `pikaur -S` with a repo package hangs after installation, `pikaur -S` with a aur package hangs after building the package. Querying with `pikaur -Q` also works fine for example. Also using zsh, but starting pikaur through bash makes no difference.

Running pacman through python itself like shown in the comment above works fine. Changing the locale or the patch don't fix it.

pikaur -Vq:
Pikaur v0.10.1-dev
Pacman v5.0.2 - libalpm v10.0.2

pacman -Qu produces no output

libaio version is 0.3.111-1

**Comment by actionless** [comment]
so far i see the only one thing you have in common -- you're runing inside VM, i think what could be different between bare and VM installation what could make that difference. or it just unrelated

**Comment by jmauss** [comment]
The only thing different between installations on my laptop and VM is the virtualbox tools - everything else is the same. I know for a fact that pikaur was working for me before I did a fresh install too, so I am wondering what changed...

**Comment by jmauss** [comment]
I went back and used pacaur (which uses your older work on cower) and this seems to run fine - doesn't seem to have anything to do with aur packages specifically. Must be somewhere in the VM installation, but I still cannot figure out what it could be.

**Comment by masterodie** [comment]
I'm using Hyper-V as hypervisor, so it seems not to be related to the type of virtualization used. Tried out some older versions and with version 0.9.3 upgrading or package installation works fine, with 0.10 it stops working for me.

**Comment by actionless** [comment]
btw, those 3 are all failing or only the last one?

```
$ python -c "from pikaur.pikspect import pikspect ; pikspect(['echo', 'test'])"

$ python -c "from pikaur.pikspect import pikspect ; pikspect(['pacman', '-V'])"

$ sudo python -c "from pikaur.pikspect import pikspect ; pikspect(['pacman', '-Sy'])"
```

**Comment by masterodie** [comment]
I have created a new vm with a barebones installation for you. The vhdx file should be convertable to qcow2 or whatever with qemu-img. Just base, base-devel, git and the dependencies for pikaur are installed. It's an EFI based Hyper-V version 2 image if that matters.

https://www.dropbox.com/s/h76v2oi09s2vbqt/pikaur.tar.xz?dl=0

**Comment by C4R2T3N** [comment]
I do have the same problem:

```
pikaur -Vq
Pikaur v0.10.2
Pacman v5.0.2 - libalpm v10.0.2
```

```
pikaur -Qu
Lese lokale Paketdatenbank...
Lese Repository-Paketdatenbank...
Lese AUR Paketinfos…
```

`pacman -Qu`

```
pikaur -Sy
[sudo] Passwort für ...: 
:: Synchronisiere Paketdatenbanken...
 core ist aktuell
 extra ist aktuell
 community ist aktuell
```

```
pikaur -Su
:: Starte komplettes AUR Upgrade...
Lese lokale Paketdatenbank...
Lese Repository-Paketdatenbank...
Lese AUR Paketinfos...
:: Starte vollständige Systemaktualisierung...
 Es gibt nichts zu tun
```

after the last line it hangs there

**Comment by rohithn93** [comment]
Hello,

Even I have the same error as above.

This is a newly installed Arch box on VMware.

**Comment by actionless** [comment]
@masterodie so i've downloaded it, there is a VHDX file inside, what i need to do to run it as a VM inside arch linux host?

**Comment by C4R2T3N** [comment]
Like I said the problem also occurs without VM. Please tell me how I can help if you need further information. Thank you for your work!

**Comment by masterodie** [comment]
The file should be convertable with `qemu-img convert -O qcow2 pikaur.vhdx pikaur.qcow2`. Then it's an image for [QEMU](https://wiki.archlinux.org/index.php/QEMU)

**Comment by actionless** [comment]
when i doing`qemu-system-x86_64 pikaur.qcow2` nothing happens after this point:
![2018-05-13--1526235917_748x502_scrot](https://user-images.githubusercontent.com/1655669/39970439-c272aefe-56eb-11e8-9d19-f00f2fd556d7.png)

**Comment by masterodie** [comment]
Damn, same thing for me here. after some further reading this seems not to work for the efi based images from Microsoft. Meanwhile i have tested a bit more and a fresh installation in a VirtualBox VM on a Arch host shows the same behaviour, while pikaur runs fine on the host itself.

Maybe just try to install i fresh Arch somewhere since C4R2T3N mentioned the error seems to occur even without a VM. Or I can upload that image too if you want. That boots with VirtualBox or qemu. This time i tested it beforehand.

**Comment by masterodie** [comment]
A fresh lxc container with only the dependencies for pikaur does not hang while upgrade.

btw problematic installations were done following the [Installation guide](https://wiki.archlinux.org/index.php/Installation_guide)

**Comment by ckotte** [comment]
I have the same issue with a new installation on Vagrant and VirtualBox... I don't have the issue om my Laptop, but this is an "old" installation...

**Comment by actionless** [comment]
yes, please upload an image which i can use to reproduce this

**Comment by masterodie** [comment]
Ok it is compressing right now. Will post the link when ready

**Comment by actionless** [comment]
thanks!

**Comment by masterodie** [comment]
@actionless Here it is: https://www.dropbox.com/s/3hl9n98cg2honre/pikaur.tar.xz?dl=0

This is just a .vdi disk image for VirtualBox so just create a new VM inside VirtualBox with this as virtual HDD or run it with `qemu-system-x86_64 pikaur.vdi`. 

Network is setup was done with [systemd-networkd](https://wiki.archlinux.org/index.php/Systemd-networkd) and set to dhcp, the root password is simply `root`, and i have created a user build without password for the aur git repo and your github repo.

**Comment by actionless** [comment]
thanks a lot! i am finally able to reproduce the problem

**Comment by actionless** [comment]
pushed a possible fix,

so far it seems the problem would reproduce on any 1-core setup, not only VM

**Comment by jmauss** [comment]
I was originally having this issue in my VM's which will are set to use 2 cores. I will try the git version shortly to see if its fixed.

**Comment by jmauss** [comment]
Update: Looks like its working now on my end - wondering how its working for everyone else?

**Comment by ckotte** [comment]
It works also on my side. However, I get the following error if a binary in a post-transaction hook is missing. Could this be related to your recent threading fix?

```
# pikaur -S pacaur
Reading local package database...
Resolving AUR dependencies...
Reading repository package databases...

:: AUR package will be installed:
 pacaur                                4.7.10-1            -> 4.7.10-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
looking for conflicting packages...
Do you want to edit PKGBUILD for pacaur package? [y/N] n

==> Making package: pacaur 4.7.10-1 (Mon May 14 18:08:14 CEST 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading 4.7.10.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    184      0 --:--:-- --:--:-- --:--:--   183
100 94187  100 94187    0     0  59839      0  0:00:01  0:00:01 --:--:--  493k
==> Validating source files with md5sums...
    4.7.10.tar.gz ... Passed
==> Extracting sources...
  -> Extracting 4.7.10.tar.gz with bsdtar
==> Starting build()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "pacaur"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: pacaur 4.7.10-1 (Mon May 14 18:08:17 CEST 2018)

loading packages...
warning: pacaur-4.7.10-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pacaur-4.7.10-1

Total Installed Size:  0.39 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y

(1/1) checking keys in keyring                                                                             [###############################################################] 100%
(1/1) checking package integrity                                                                           [###############################################################] 100%
(1/1) loading package files                                                                                [###############################################################] 100%
(1/1) checking for file conflicts                                                                          [###############################################################] 100%
(1/1) checking available disk space                                                                        [###############################################################] 100%
:: Processing package changes...
(1/1) reinstalling pacaur                               Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007f589f510700 (most recent call first):
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 103 in cmd_output_handler
  File "/usr/lib/python3.6/site-packages/pikaur/threading.py", line 64 in decorated
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f58ad800700 (most recent call first):
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 95 in cmd_output_handler
  File "/usr/lib/python3.6/site-packages/pikaur/threading.py", line 64 in decorated
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007f58b7fa6540 (most recent call first):
[1]    2613 abort (core dumped)  pikaur -S pacaur
```

Make binary available:

```
# pikaur -S pacaur
Reading local package database...
Resolving AUR dependencies...
Reading repository package databases...

:: AUR package will be installed:
 pacaur                                4.7.10-1            -> 4.7.10-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
looking for conflicting packages...
Do you want to edit PKGBUILD for pacaur package? [y/N] n

==> Making package: pacaur 4.7.10-1 (Mon May 14 18:09:21 CEST 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading 4.7.10.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    184      0 --:--:-- --:--:-- --:--:--   184
100 94187  100 94187    0     0  60844      0  0:00:01  0:00:01 --:--:--  223k
==> Validating source files with md5sums...
    4.7.10.tar.gz ... Passed
==> Extracting sources...
  -> Extracting 4.7.10.tar.gz with bsdtar
==> Starting build()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "pacaur"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: pacaur 4.7.10-1 (Mon May 14 18:09:24 CEST 2018)

loading packages...
warning: pacaur-4.7.10-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pacaur-4.7.10-1

Total Installed Size:  0.39 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y

(1/1) checking keys in keyring                                                                             [###############################################################] 100%
(1/1) checking package integrity                                                                           [###############################################################] 100%
(1/1) loading package files                                                                                [###############################################################] 100%
(1/1) checking for file conflicts                                                                          [###############################################################] 100%
(1/1) checking available disk space                                                                        [###############################################################] 100%
:: Processing package changes...
(1/1) reinstalling pacaur                                                                                  [###############################################################] 100%
:: Running post-transaction hooks...
(1/2) Saving installed packages...
(2/2) Arming ConditionNeedsUpdate...
```

Remove binary again:

```
pikaur -S pacaur                                                                                                                                        ✔  11  18:11:49 
Reading local package database...
Resolving AUR dependencies...
Reading repository package databases...

:: AUR package will be installed:
 pacaur                                4.7.10-1            -> 4.7.10-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> y
looking for conflicting packages...
Do you want to edit PKGBUILD for pacaur package? [y/N] n

==> Making package: pacaur 4.7.10-1 (Mon May 14 18:11:55 CEST 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading 4.7.10.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    194      0 --:--:-- --:--:-- --:--:--   194
100 94187  100 94187    0     0  59763      0  0:00:01  0:00:01 --:--:--  153k
==> Validating source files with md5sums...
    4.7.10.tar.gz ... Passed
==> Extracting sources...
  -> Extracting 4.7.10.tar.gz with bsdtar
==> Starting build()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "pacaur"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: pacaur 4.7.10-1 (Mon May 14 18:11:58 CEST 2018)

loading packages...
warning: pacaur-4.7.10-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pacaur-4.7.10-1

Total Installed Size:  0.39 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y

(1/1) checking keys in keyring                                                                             [###############################################################] 100%
(1/1) checking package integrity                                                                           [###############################################################] 100%
(1/1) loading package files                                                                                [###############################################################] 100%
(1/1) checking for file conflicts                                                                          [###############################################################] 100%
(1/1) checking available disk space                                                                        [###############################################################] 100%
:: Processing package changes...
(1/1) reinstalling pacaur                                                                                  [-----------------------------------------------------------Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fc537fff700 (most recent call first):
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 103 in cmd_output_handler
  File "/usr/lib/python3.6/site-packages/pikaur/threading.py", line 64 in decorated
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fc546604700 (most recent call first):
  File "/usr/lib/python3.6/site-packages/pikaur/pikspect.py", line 95 in cmd_output_handler
  File "/usr/lib/python3.6/site-packages/pikaur/threading.py", line 64 in decorated
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fc550daa540 (most recent call first):
[1]    4152 abort (core dumped)  pikaur -S pacaur
```

**Comment by actionless** [comment]
doesn't seem related to me, so please move it to a new ticket and supply info how to reproduce the minimal set up with the hook

so far what i see from stacktrace what while reading pacman's output something is crashing, btw when you'll do the same with only pacman does it also crashes with coredump?

**Comment by actionless** [comment]
> I was originally having this issue in my VM's which will are set to use 2 cores

in that case it's somehow related to the way how virtualized cpu is working (i've never tried running pikaur on single-core bare metal)

**Comment by actionless** [comment]
@masterodie could you check `pikaur-git` on your side please?

**Comment by masterodie** [comment]
@actionless First VM i tested works fine, but that's the same I sent to you, so maybe not the best test sample. Will boot windows in a few minutes and test if it's working there too.

**Comment by actionless** [comment]
thanks for investing your time in helping to finally catch the problem!
