### ISSUE TITLE
Pass arguments to makepkg

### ISSUE THREAD

**Issue by leoteodoro** [actionless/pikaur#162]
yaourt has --m-arg to pass something to makepkg
if I would like to install something with yaourt that I can't gpg verify (like libc++) I would do just "yaourt -S --noconfirm libc++ --m-arg --skippgpcheck", or just "--skipinteg, --skippgpcheck, --skipchecksums"...

**Comment by Morganamilo** [comment]
The flag is a good point (i prefer --mflags over --m-arg btw). Just want to point out you should really be importing keys rather than just ignoring them.

**Comment by AladW** [comment]
Not a robust approach though, since makepkg options (e.g. `--config`) may take paths that already contain white space. I guess you could try to come up with some quoting system, but that seems much effort to accomodate users not willing to read [the documentation](https://wiki.archlinux.org/index.php/Makepkg#Signature_checking).

**Comment by AladW** [comment]
An alternative is to use the end-of-options marker `--` for makepkg arguments, similar to `makechrootpkg`.
```
pikaur -S -- --some-makepkg-flag
```
With either approach:
* all `makepkg` options are reset to whatever is specified after `--`
  * unintuitive and might break things, but gives more flexibility
* `makepkg` options after `--` are _appended_ to existing makepkg options instead

**Comment by AladW** [comment]
You can't quote twice though since you have to split the "mflags" or whatever on whitespace.

**Comment by Morganamilo** [comment]
I didn't really think about the space thing. You could do it like `--cachedir` and have the flag multiple times with different values. Pacman uses `--` as an end of options flag like a lot of programs. I wouldn't want to change that.

**Comment by actionless** [comment]
@AladW could you please give an example?

**Comment by AladW** [comment]
```
makepkg --config "/mnt/windows/Documents and Settings/bloat.conf"
```
would split to
```
makepkg --config "/mnt/windows/Documents" "and" "Settings/bloat.conf"
```

**Comment by actionless** [comment]
why not like that?
```
pikaur -S pkg --mflags '--config "/mnt/windows/Documents and Settings/bloat.conf"'
```

**Comment by actionless** [comment]
> edit: maybe you can use some re-existing system for this like getopt, I don't know.

yup, i was thinking to use some of the existing parsers in python stdlib, it could reside in some quite unexpected place there... :D  (for example some copy functions are taken from distutils...)

> Add a separate --mconfig flag that takes a makepkg configuration verbatim

you mean to alter path to /etc/makepkg.conf?

**Comment by AladW** [comment]
you mean to alter path to /etc/makepkg.conf?

Right, that would cover the case of `makepkg --config` (for stuff like `PKGDEST`). `--config` (and `-p`, but that would have limited use) are the only makepkg options that have an extra argument from what I can see.
