### ISSUE TITLE
not possible to install an AUR package.

### ISSUE THREAD

**Issue by Bundy01** [actionless/pikaur#167]
not possible to install an AUR package.

` Reading the local package database...
Resolving AUR dependencies...

The AUR package will be installed:
 vrms-arch -> 0.1.0.r21.g4ef0a5c-1

Proceed with installation? [Y/n] 
package details select[m]annually the packages
>> 
looking for conflicting packages...
Modify PKGBUILD for the vrms-arch package? [O/n] n

Running as unit: run-u7206.service
Foutput handler exiting
The command 'systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/vrms-arch makepkg --force' command failed.
`

OS: Archlinux 64
Version Pikaur: 0.10.1-1

EDITED

**Comment by actionless** [comment]
please attach the full output text and the input command

**Comment by actionless** [comment]
please attach the full output

**Comment by Bundy01** [comment]
With pikaur 0.10.2-1:

``Running as unit: run-u7635.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=239
Service runtime: 2ms
The command 'systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/vrms-arch makepkg --force' command failed.``

**Comment by actionless** [comment]
and no lines between those?

```
Modify PKGBUILD for the vrms-arch package? [O/n] n

Running as unit: run-u7206.service
```

and what happends if you run in the terminal?

```
cd /var/cache/pikaur/build/vrms-arch && makepkg --force
```

**Comment by actionless** [comment]
and
```
which makepkg
```

**Comment by Bundy01** [comment]
> and no lines between  those?

no

> and what happens if you run in the terminal?
cd /var/cache/pikaur/build/vrms-arch && makepkg --force

My user account does not have administrator permissions. I use it to make updates.

**Comment by actionless** [comment]
(disregard my previous questions)

does the same happens when you gunning it without `sudo`?

**Comment by actionless** [comment]
or you mean what your user can't do sudo?

**Comment by actionless** [comment]
anyway, what happens if you're running makepkg for the same package directly from root?

do you have any interesting mount options of your /tmp?

**Comment by Bundy01** [comment]
> anyway, what happens if you're running makepkg for the same package directly from root?

cd /var/cache/pikaur/build/vrms-arch && makepkg --force
`ERROR: Running makepkg as root is not allowed because it could
cause catastrophic and permanent damage to your system.

==> ERROR : An unknown error has occurred. Exiting...`

/tmp is on my ram memory (tmpfs)

**Comment by Bundy01** [comment]
systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/vrms-arch makepkg --force

`Running as unit: run-u5274.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=239
Service runtime: 7ms`

**Comment by actionless** [comment]
```
systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/ echo test

systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/tmp makepkg


systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/tmp echo test
```

**Comment by actionless** [comment]
and `sudo systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/ ls -la`

**Comment by Bundy01** [comment]
`systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/ echo test
Running as unit: run-u5568.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=239
Service runtime: 7ms`


`systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/tmp makepkg
Running as unit: run-u5602.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=239
Service runtime: 6ms`

`systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/tmp echo test
Running as unit: run-u5628.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=239
Service runtime: 7ms`

**Comment by Bundy01** [comment]
`systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/ ls -la

Running as unit: run-u5753.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=239
Service runtime: 6ms`

**Comment by actionless** [comment]
are any examples from here working for you?
http://0pointer.net/blog/dynamic-users-with-systemd.html

it seems what you have some issue with dyamic users feature of systemd

**Comment by Bundy01** [comment]
I did not make those changes.

**Comment by Bundy01** [comment]
I'm thinking more about a problem with my single-user account. There must be a block for building AUR packages in root mode. I tried to install a package manually and I have a warning that prevents me from compiling. What's strange is that it goes with pamac-aur !?

**Comment by Yardanico** [comment]
@Bundy01 yeah, you can't use makepkg with root.

**Comment by Bundy01** [comment]
Problem solved by turning the account into an administrator. I close the issue
