### ISSUE TITLE
Support for hooks?

### ISSUE THREAD

**Issue by IsaakGroepT** [actionless/pikaur#168]
Hi

I'd like to implement an automated BTRFS snapshot feature that will take snapshots of several subvolumes before any updates are downloaded and installed. But instead of modifying the script manually, which will also get overwritten by next updates, I'd like to request a hook feature so I can create a hook script that pikaur will run pre or post the update task.

Why I can't just run multiple commands in this way `takesnapshot && pikaur -Syu` is because the snapshots have no way of knowing which packages were updated, so the descriptions will remain vague. If I can implement it properly in pikaur, I can add all the packages to the snapshot descriptions and keep it clear. Of course the hook feature would need to allow me to request data like the packages that are going to be installed.

What do you think of that?

**Comment by IsaakGroepT** [comment]
That's also a possibility :P :+1:

**Comment by actionless** [comment]
and also i think you could make it as a pacman hook, since after the build package will be installed by pacman anyway


feel free to reopen
