### ISSUE TITLE
Update list display + sorting

### ISSUE THREAD

**Issue by 6wheels** [actionless/pikaur#169]
The option UpgradeSorting from the sync section is great.
It would be nice if we also could choose how to sort the package list before upgrading: order by repo, versiondiff, package name.
Pacman already sorts packages by repository (core > extra > community etc.)

Another good thing would be to display "aur/" (with a different color), in front of package from aur, if the option AlwaysShowPkgOrigin is set to yes.

This second feature allows to filter output from a script. I actually have a script that checks for available updates, but I don't want to sync (-Sy) before a -Qu, because this needs root permission.

However, for the "check updates" feature, this could be combined with the already existing checkupdates command from pacman.

Feel free to split this issue into several ones if needed.

**Comment by actionless** [comment]
sorry, i didn't understood those two proposals, could you please elaborate more on them?

> It would be nice if we also could choose how to sort the package list before upgrading: order by repo, versiondiff, package name.



> This second feature allows to filter output from a script. I actually have a script that checks for available updates, but I don't want to sync (-Sy) before a -Qu, because this needs root permission.

**Comment by 6wheels** [comment]
Sorry, that wasn't clear. I'll try to specify the all proposals.

The first proposal would be to give the ability to sort the package list given by pikaur.
Currently, pikaur lists packages as follows:
```
:: Repository packages will be installed:
 core/gcc                              7.3.1+20180406-1    -> 8.1.0-1
 core/gcc-libs                         7.3.1+20180406-1    -> 8.1.0-1
 extra/intel-ucode                     20180312-1          -> 20180425-1
 core/linux-firmware                   20180314.4c0bf11-1  -> 20180507.8fc2d4e-1
 extra/python-packaging                16.8-2              -> 17.1-1
 extra/python2-packaging               16.8-2              -> 17.1-1
 core/tzdata                           2018d-1             -> 2018e-1
 core/file                             5.32-1              -> 5.33-1
 core/libgpg-error                     1.29-1              -> 1.31-1
 core/libidn                           1.33-2              -> 1.34-2
 core/man-pages                        4.15-1              -> 4.16-1
 community/python-keystoneauth1        3.5.0-1             -> 3.6.0-1
 community/python-monotonic            1.4-1               -> 1.5-1
 community/python-positional           1.1.2-1             -> 1.2.1-1
 community/python2-keystoneauth1       3.5.0-1             -> 3.6.0-1

:: AUR package will be installed:
 pikaur                                0.10.1-1            -> 0.10.3-1
```

The first part is not sorted. They are all mixed between core, community, extra etc.
I think it would be nice to sort them by origin if the AlwaysShowPkgOrigin option is set to true.
Moreover, a specific option could be used to set the sort order: by name, update date, version, repo etc.

In the second part of the display, the packages from aur should be prefixed by "aur/" if the  AlwaysShowPkgOrigin option is set to true.

Lastly, a check of aur updates and using the existing checkupdates command could be a nice feature too.

Hope this one is more comprehensible! ;)

**Comment by actionless** [comment]
i still can't see what is the difference between sync.UpgradeSorting and what you're proposing

**Comment by actionless** [comment]
and yeah, for a second thing please create a separate ticket, otherwise it's a mess

**Comment by 6wheels** [comment]
Ok I'll create more tickets to separate things, sorry.

So, this time I concentrate on sorting the display ;)
Either the sync.UpgradeSorting is not working or I don't understand what it does.

But I'll like package listing to be sorted, none of the repo,versiondiff or pkgname option produces the right order.
This is why I opened this ticket, because I understood that the sync.UpgradeSorting is used to sort in which order the package installation will be done.

Sorry if I totally misunderstood things...

**Comment by IgnusG** [comment]
I have the feeling you suggest sorting according to multiple values in steps. Like first sort/group by repo then within each group sort by for example version bump/name ... ?
I would like such a proposal but this could be difficult to implement :(

**Comment by 6wheels** [comment]
Here is an example to avoid anymore confusion.
The current pikaur display is:
```
 core/gcc                              7.3.1+20180406-1    -> 8.1.0-1
 core/gcc-libs                         7.3.1+20180406-1    -> 8.1.0-1
 extra/intel-ucode                     20180312-1          -> 20180425-1
 core/linux-firmware                   20180314.4c0bf11-1  -> 20180507.8fc2d4e-1
 extra/python-packaging                16.8-2              -> 17.1-1
 extra/python2-packaging               16.8-2              -> 17.1-1
 core/tzdata                           2018d-1             -> 2018e-1
 core/file                             5.32-1              -> 5.33-1
 core/libgpg-error                     1.29-1              -> 1.31-1
 core/libidn                           1.33-2              -> 1.34-2
 core/man-pages                        4.15-1              -> 4.16-1
 community/python-keystoneauth1        3.5.0-1             -> 3.6.0-1
 community/python-monotonic            1.4-1               -> 1.5-1
```

Here you can see that some core packages are displayed after some extra packages.
I think it would be clearer to sort package like this:
```
 core/file                             5.32-1              -> 5.33-1
 core/gcc                              7.3.1+20180406-1    -> 8.1.0-1
 core/gcc-libs                         7.3.1+20180406-1    -> 8.1.0-1
 core/libgpg-error                     1.29-1              -> 1.31-1
 core/libidn                           1.33-2              -> 1.34-2
 core/linux-firmware                   20180314.4c0bf11-1  -> 20180507.8fc2d4e-1
 core/man-pages                        4.15-1              -> 4.16-1
 core/tzdata                           2018d-1             -> 2018e-1
 extra/intel-ucode                     20180312-1          -> 20180425-1 
 extra/python-packaging                16.8-2              -> 17.1-1
 extra/python2-packaging               16.8-2              -> 17.1-1
 community/python-keystoneauth1        3.5.0-1             -> 3.6.0-1
 community/python-monotonic            1.4-1               -> 1.5-1
```

This implies sorting by group (core, extra etc...) and by naturally by package name.
I don't know how this is processed/implemented in pikaur, but 2 sort operations won't be so complicated, isn't?

Remember this should only by done if AlwaysShowPkgOrigin is true.
And this is juste about display not install execution.

**Comment by IgnusG** [comment]
The thing is this seems like a preference. I mean there could be someone who wants them sorted by version bump even when displaying repo origin. 
Or first by repo origin and then by version bump instead of name.

Hence more config options

**Comment by actionless** [comment]
@6wheels and could you please show what output do you have if you'll set UpgradeSorting to `repo`?

**Comment by 6wheels** [comment]
Ok so the sync.UpgradeSorting is the option that I am looking for isn't it?

Here is the full content of my ~/.config/pikaur.conf:
```
[sync]
AlwaysShowPkgOrigin = yes
DevelPkgsExpiration = 30
UpgradeSorting = repo

[build]
KeepBuildDir = no
NoEdit = no

[colors]
Version = 10
VersionDiffOld = 11
VersionDiffNew = 9

[ui]
RequireEnterConfirm = no
```

But yes, this is weird because it only appears on one host. It works on my desktop, I've just tested this morning. Is their some cache or seomething?

**Comment by IgnusG** [comment]
@6wheels do other sorting options work for you? Or is it always sorted the same no matter the option?

**Comment by 6wheels** [comment]
No, it's always the same no matter what option is given, but again, only on one machine.

**Comment by IgnusG** [comment]
Hmm, have you tried replacing pikaur with `pikaur-git`?
I think @actionless will also need the version you’re running:
```
pikaur -Vq
```

**Comment by actionless** [comment]
weird, i don't remember fixing that between 0.10.1 and 0.10.3 but anyway good what it's not reproduciable in the current version :-)
