### ISSUE TITLE
Prefix package name with "aur/" if AlwaysShowPkgOrigin is true

### ISSUE THREAD

**Issue by 6wheels** [actionless/pikaur#171]
To be more consistent with packages not in aur, it would be nice to have aur package names prefixed by "aur/".

This would also simplify using the pikaur output from a bash script.

This display would only be enable if the AlwaysShowPkgOrigin is set to true.

**Comment by IgnusG** [comment]
The output is already displayed under `AUR package[s] will be installed:` 
There can't be any confusion under what category they belong. I think this just adds bloat

**Comment by 6wheels** [comment]
@IgnusG, I don't agree because it is not consistent with the rest of the output if AlwaysShowPkgOrigin is enabled, which I use. Non-aur packages are displayed with `core/` or `community/` prefixes, where aur packages are not.
Plus, this would make things easier to parse in a bash script.
Finally, yaourt does this, and I think that was a good thing ;)

**Comment by IgnusG** [comment]
I also use this option - as I like to see their origin, that was a good addition :)
Does yaourt show text like `following aur packages will be installed`? Or is it just one list?

Parsing would definitely be easier with this. Although even better would be something like `porcelain` in git. But support for that is a whole different dev story

**Comment by 6wheels** [comment]
yaourt does not show 2 differents list:
```
[bebr@hades ~]$ yaourt -Syua
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 archlinuxfr is up to date
  python2-rackspace-auth-openstack : Orphan 
 Foreign packages: | 12 / 12

==> Package upgrade only (new release):
core/binutils                      2.30-3               3 -> 4
core/glibc                         2.27-2               2 -> 3
core/libtirpc                      1.0.3-1              1 -> 2
core/libtool                       2.4.6+40+g6ca5e224-5 5 -> 6
core/pacman                        5.0.2-2              2 -> 3
core/pinentry                      1.1.0-2              2 -> 3
extra/js52                         52.7.3-1             1 -> 2
community/rxvt-unicode-terminfo    9.22-5               5 -> 6

==> Software upgrade (new version) :
core/cryptsetup                    2.0.2-1              -> 2.0.3-1
core/dbus                          1.12.6-1             -> 1.12.8-1
core/dhcpcd                        7.0.1-1              -> 7.0.4-1
core/file                          5.32-1               -> 5.33-1
core/gcc                           7.3.1+20180406-1     -> 8.1.0-1
core/gcc-libs                      7.3.1+20180406-1     -> 8.1.0-1
core/gnupg                         2.2.6-1              -> 2.2.7-1
core/libaio                        0.3.110-1            -> 0.3.111-1
core/libgpg-error                  1.29-1               -> 1.31-1
core/libidn                        1.33-2               -> 1.34-2
core/libpsl                        0.20.1-2             -> 0.20.2-1
core/linux                         4.16.5-1             -> 4.16.8-1
core/linux-firmware                20180314.4c0bf11-1   -> 20180507.8fc2d4e-1
core/man-pages                     4.15-1               -> 4.16-1
core/nano                          2.9.5-1              -> 2.9.6-1
core/tzdata                        2018d-1              -> 2018e-1
extra/freetype2                    2.9-2                -> 2.9.1-1
extra/intel-ucode                  20180312-1           -> 20180425-1
extra/libnm                        1.10.6-3             -> 1.10.8-1
extra/libnm-glib                   1.10.6-3             -> 1.10.8-1
extra/libsoup                      2.62.1-1             -> 2.62.2-1
extra/networkmanager               1.10.6-3             -> 1.10.8-1
extra/python-packaging             16.8-2               -> 17.1-1
extra/python2                      2.7.14-3             -> 2.7.15-1
extra/python2-packaging            16.8-2               -> 17.1-1
extra/vim                          8.0.1542-2           -> 8.0.1838-1
extra/vim-runtime                  8.0.1542-2           -> 8.0.1838-1
extra/wget                         1.19.4-3             -> 1.19.5-1
community/docker-compose           1.21.1-1             -> 1.21.2-1
community/python-keystoneauth1     3.5.0-1              -> 3.6.0-1
community/python-monotonic         1.4-1                -> 1.5-1
community/python-netifaces         0.10.6-1             -> 0.10.7-1
community/python-oslo-utils        3.36.1-1             -> 3.36.2-1
community/python-pbr               4.0.2-1              -> 4.0.3-1
community/python-positional        1.1.2-1              -> 1.2.1-1
community/python2-keystoneauth1    3.5.0-1              -> 3.6.0-1
community/python2-monotonic        1.4-1                -> 1.5-1
community/python2-netifaces        0.10.6-1             -> 0.10.7-1
community/python2-oslo-utils       3.36.1-1             -> 3.36.2-1
community/python2-pbr              4.0.2-1              -> 4.0.3-1
community/python2-positional       1.1.2-1              -> 1.2.1-1
community/python2-simplejson       3.14.0-1             -> 3.15.0-1
community/youtube-dl               2018.04.16-1         -> 2018.05.09-1
aur/pikaur                         0.10.1-1             -> 0.10.3-1

==> New package :
community/python-os-service-types  1.2.0-2              (required by python-keystoneauth1)
community/python2-os-service-types 1.2.0-2              (required by python2-keystoneauth1)

==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------
==> 
```

**Comment by AladW** [comment]
Dumb idea all around since you might have local/unofficial repo that's called `aur`.

**Comment by Morganamilo** [comment]
I think it would be misleading for a repo to be called `aur` If it's a local repo you can name it what you like. alpm reserves a repo called `local` I think it's fair to reserve a pseudo repo called `aur`.

**Comment by AladW** [comment]
Fair point on `local`. That said I don't see much benefit in adding `aur` either when the convention is only used for stderr with a certain option enabled. adhoc parsing thereof (especially with localized output) is not robust and some other approach like a JSON summary of AUR updates should be considered instead.

Whatever the decision is it should be explicitly documented.

**Comment by actionless** [comment]
>  and when people add custom repos.

that's a good point, i'll take it

**Comment by AladW** [comment]
When you extend `-S` to give this convention an actual use, I wonder whether to use `aur` or `AUR`. I guess the lower-case spelling is the more popular... (I only know of `bauerbill` using latter)

**Comment by actionless** [comment]
since repo names and package names are using lowercase (at least those which i saw) it makes sense to spell it `/aur` as it was suggested in the ticket

**Comment by AladW** [comment]
Well, repo names can contain arbitrary characters. E.g. `[A    bC'$%  Foo]` is completely valid for some reason. But `local` is also lower-case so I guess `aur` can be the same.

**Comment by actionless** [comment]
> But local is also lower-case so I guess aur can be the same.
good point, i think it's enough to go that way

**Comment by actionless** [comment]
@Morganamilo resolved usecase from your example

still not sure if it makes sense to show that prefix it in the interactive prompt, mb only in -Qu output?

**Comment by actionless** [comment]
@6wheels 
please `pikaur -Qu` or`pikaur -Qua` in your scripts
