### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by 6wheels** [actionless/pikaur#172]
Currently, we can use `pikaur -Qu` to check if some packages need updating.
AUR package updates are correctly detected.

However, the official packages (not in aur) will not show unless a `pacman -Sy` is done before.
But this requires root permission, making `-Qu` useless in bash scripts.

Pacman provides the `checkupdates` command to do so.

pikaur could combine the use of the `checkupdates` with its current aur check to provide an up-to-date list of packages to upgrade.

Other than using the existing `-Qu` option, a new option could be used like `--devel` is, maybe `--checkupdates` or something shorter.

**Comment by actionless** [comment]
i am more up to `--checkupdates` flag and using the same command as `checkupdates` script do:

```bash

if [[ -z $CHECKUPDATES_DB ]]; then
	CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-${USER}/"
fi

trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT

DBPath="${DBPath:-/var/lib/pacman/}"
eval $(awk -F' *= *' '$1 ~ /DBPath/ { print $1 "=" $2 }' /etc/pacman.conf)

mkdir -p "$CHECKUPDATES_DB"
ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null
pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'

```

**Comment by actionless** [comment]
as for now you can do:
```
checkupdates && pikaur -Qua
```

**Comment by AladW** [comment]
Or, you could do something actually interesting and use the archweb JSON interface. Then you always have accurate output regardless of mirror status. See https://github.com/Jguer/yay/issues/369#issuecomment-386803852

**Comment by actionless** [comment]
thanks! it looks quite nicer when fakeroot, temporary files and locks
