### ISSUE TITLE
`--aur` doesn't work with `-Q`

### ISSUE THREAD

**Issue by mbunkus** [actionless/pikaur#173]
I'd like to list only those packages that have been installed from the AUR. The most obvious way for me would be `pikaur -Qa` or `pikaur -Q --aur`, but that doesn't work:

```
[0 mosu@sweet-chili ~] pikaur -Q --aur
pacman: unrecognized option '--aur'
```

This is Pikaur v0.10.3.r10.g681356b

**Comment by Morganamilo** [comment]
See `-m/--foreign`

**Comment by mbunkus** [comment]
That works fine for my current use-case, thanks.

I'd still argue that `pikaur -Q --help` shouldn't list `--aur` as an option when it doesn't actually evaluate that option and only passes it through to `pacman`. Or it should filter the option.

**Comment by actionless** [comment]
does `pikaur -Qsa` works as expected?

**Comment by mbunkus** [comment]
Nope, same problem:

```
[0 mbunkus@sweet-chili ~] pikaur -Qsa
pacman: invalid option -- 'a'
```

**Comment by actionless** [comment]
oh, my bad, i didn't got right the problem

so, i think, the right solution will be to write warning about incompatible options, like:
```
$ pacman -Syc
error: invalid option: '--clean' and '--refresh' may not be used together
```

**Comment by Bundy01** [comment]
the commande is:
`pikaur -Qm`
or
`pikaur -Qqm`

**Comment by actionless** [comment]
thanks for reporting!
