### ISSUE TITLE
changing the build directory

### ISSUE THREAD

**Issue by deathtrip** [actionless/pikaur#174]
Pikaurs default build directory setting can lead to heavy HDD usage when building large packges, or even the drive running out of space. Using /tmp by default would be better imo, or at least to provide an option to change it in the config file.

**Comment by Morganamilo** [comment]
See `BUILDDIR` in `makepkg.conf`.

**Comment by actionless** [comment]
@Morganamilo actually if disk space problem caused not by the build process but by a big repository setting  BUILDDIR in makepkg won't help

**Comment by actionless** [comment]
however i can't imagine such big repos in AUR, i was looking for max size limitations but haven't found it

**Comment by AladW** [comment]
`SRCDEST`. People should really have basic familiarity with the Arch tools like makepkg before using helpers.

**Comment by AladW** [comment]
Maybe link at the top that generally `makepkg(1)` and `makepkg.conf(5)` are important things to read

**Comment by actionless** [comment]
thanks for the suggestion! i've updated the FAQ text
