### ISSUE TITLE
Problem searching/installing a package in multiple repositories

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#175]
The same package but in different repositories is not showing in search/install queries:

![screenshot_20180519_222639](https://user-images.githubusercontent.com/11801453/40275418-0675a094-5bb4-11e8-873e-54306e7f29f7.png)

**Comment by actionless** [comment]
partially related to #171

**Comment by actionless** [comment]
@XavierCLL could you please give me the repos URLs so i can quicker reproduce the test environment for this?

**Comment by XavierCLL** [comment]
Hi @actionless, yes of course:

https://wiki.archlinux.org/index.php/unofficial_user_repositories#aur-archlinux

https://wiki.archlinux.org/index.php/unofficial_user_repositories#archlinuxcn

**Comment by actionless** [comment]
thanks for reporting!

**Comment by XavierCLL** [comment]
thanks to you for the quickly fixed :+1:
