### ISSUE TITLE
(question or missing feature) How install a package from specific repository?

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#176]
Hi, I don't know if this is already implemented or is a missing feature. I want to install a package that provides multiple repositories (include aur) but with pikaur I don't know how to do that, for example:

```
pikaur -Ss pikaur-git
Searching... [---]###
aur-archlinux/pikaur-git 0.10.3.r21.gd805c63-1 [installed] 
    AUR helper with minimal dependencies. Review PKGBUILDs all in once, next build them all without user interaction.    
aur/pikaur-git 0.10.3-1 [installed: 0.10.3.r21.gd805c63-1] (9, 2.78)
    AUR helper with minimal dependencies. Review PKGBUILDs all in once, next build them all without user interaction.
```

I want to force recompile the pikaur-git from AUR repository (aur/pickaur-git), pacaur use a very good flags for that `<repo>/<package>` such as `pacaur -S aur/pikaur-git`. But in pikaur:
```
pikaur -S aur/pikaur-git
Reading local package database...
:: warning: Following packages cannot be found in AUR:
    aur/pikaur-git 
```
The same appends with the testing repositories when I try to install specific packages from testing (using testing at the end of the list in pacman.conf)

**Comment by actionless** [comment]
try latest pikaur-git, it was implemented about an hour or two before you submitted the issue :D

**Comment by XavierCLL** [comment]
Yes! you are right, thanks!
