### ISSUE TITLE
Problems in looking for conflicting packages

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#181]
A strange package is suggested as replacement of an official package, this is not necessary, tested with pacman and pacaur and this conflicting packages does not happen. ('python2-numpy-mkl' comes from an unofficial repository (arch4edu), not from aur)

![a](https://user-images.githubusercontent.com/11801453/40313941-a2aab214-5cdc-11e8-9b72-690e8abd9771.png)

**Comment by actionless** [comment]
from which repository you have `python2-numpy` installed?

in which order those two repositories are placed in your /etc/pacman.conf?

**Comment by XavierCLL** [comment]
I have `python2-numpy` installed from `extra` repository, the arch4edu (https://github.com/arch4edu/arch4edu) is in the bottom of the list in /etc/pacman.conf

**Comment by actionless** [comment]
thanks for reporting!

**Comment by Morganamilo** [comment]
I left a comment on the AUR package `python2-numpy-mkl` to remove the replaces. It looks like arch4edu build using the AUR package so that should fix it.

**Comment by XavierCLL** [comment]
hi @Morganamilo, this issue was a repo priority problem in pikaur, not is a PKGBUILD problem in `python2-numpy-mkl`

**Comment by Morganamilo** [comment]
It's not a priority problem. `python2-numpy-mkl` should not have that replaces field at all. This is not what replaces it meant to be used for.

**Comment by XavierCLL** [comment]
Hi @actionless, there is another bug may be related to this issue, the order list in searching results is wrong related to the order in /etc/pacman.conf, for example:

![image](https://user-images.githubusercontent.com/11801453/40591441-f10750bc-61d6-11e8-980a-584a389e9642.png)

But in /etc/pacman.conf the [aur-archlinux] is in firsts location that the [archlinuxcn] repo. The installation order is good:

![image](https://user-images.githubusercontent.com/11801453/40591455-5540c392-61d7-11e8-9e6b-32b863222cad.png)

**Comment by actionless** [comment]
@XavierCLL pushed the fix, please test

**Comment by XavierCLL** [comment]
Perfect!! thanks again for the quick fix.

**Comment by actionless** [comment]
@XavierCLL i did few more fixes on ordering, please check if you're usecases are still fine

**Comment by XavierCLL** [comment]
@actionless  I tested in several cases in repo ordering and works very well!
