### ISSUE TITLE
fails to find newly created packages when PKGDEST is set

### ISSUE THREAD

**Issue by steven-omaha** [actionless/pikaur#186]
I just ran an update from 0.11.2-1 to 0.11.4-1 with pikaur itself. In `/etc/makepkg.conf`, I have set `PKGDEST=/var/cache/aur`, which works fine normally.

The update process just failed because the filename of the newly created package was created wrongly, namely `error: '/var/cache/aur/pikaur-0.11.4-1-any.pkg.tar.pkg.tar': could not find or read package`. The full log is provided [here](https://pastebin.com/WDbkxenU).

**Comment by actionless** [comment]
that's related to pacman update to 5.1: https://github.com/actionless/pikaur/issues/184

you need to install pikaur manually
