### ISSUE TITLE
pikaur -Syu fails with "'alpm.Package' object is not subscriptable"

### ISSUE THREAD

**Issue by steven-omaha** [actionless/pikaur#187]
pikaur 0.11.4-1

See the logfile [here](https://pastebin.com/0qj9A7Ti).

**Comment by actionless** [comment]
thanks for reporting!

**Comment by steven-omaha** [comment]
Why is the issue closed?

**Comment by actionless** [comment]
it's written why :D

**Comment by steven-omaha** [comment]
Sorry, my mistake. Thanks for the quick response!
