### ISSUE TITLE
Flickering cursor when downloading packages

### ISSUE THREAD

**Issue by ynakao** [actionless/pikaur#189]
When I download packages, cursor is flickering at progress bar.

![pikaur-02](https://user-images.githubusercontent.com/6405335/40717032-ead26116-6445-11e8-8341-504352ec1abc.gif)

On the other hand, when syncing package databases, such behavior doesn't happen.

![pikaur-01](https://user-images.githubusercontent.com/6405335/40717501-845236c6-6447-11e8-8c2d-71aea51128fb.gif)

**Comment by actionless** [comment]
i did some changes in pikspect module, could you please check if the problem still noticeable in the latest `pikaur-git` package?

**Comment by ynakao** [comment]
It seems this issue still exists in my environment. In addition, download indicators dissapeard when syncing package databases. pikaur version is v0.12.r24.g6a5727e.

![pikaur-03](https://user-images.githubusercontent.com/6405335/41137426-0e073d9c-6b16-11e8-9c9d-cbb72d73b73e.gif)

**Comment by actionless** [comment]
i did some more changes, could you please try again?

**Comment by actionless** [comment]
@Morganamilo i've disabled (in code) only the controversial part related to output hiding

**Comment by actionless** [comment]
thanks for checking!
it will never really go, because pacman is writing faster than pikaur could read, but if it's not so distracting anymore please close it

**Comment by ynakao** [comment]
I got it. Thanks again.
