### ISSUE TITLE
can't install ignored packages

### ISSUE THREAD

**Issue by jpkotta** [actionless/pikaur#192]
`pikaur -S ignored-package` and `pikaur -Su ignored-package` do not attempt to install `ignored-package`.  `pacman -S ignored-package` asks for confirmation, as does `pacman -Su ignored-package`.  To be clear, `ignored-package` is some ignored package, e.g. `IgnorePkg = ignored-package` in `pacman.conf`.

**Comment by pklapperich** [comment]
`` $ pikaur -Syu
...[snip]...
(could not find or read directory: --sysupgrade/var/lib/pacman/)
Command 'sudo pacman --color=always --sync -r --sysupgrade --ignore linux-zen --ignore xorg-server' failed to execute.
```

It looks like pikaur is parsing `/etc/pacman.conf` and then manually adding `--ignore` statements when calling `pacman`. This doesn't seem necessary. `pacman` already looks at its own conf and will ignore when appropriate.
