### ISSUE TITLE
Missing GPL notice in the source files?

### ISSUE THREAD

**Issue by steven-omaha** [actionless/pikaur#195]
From the [GPL v3, section 17](https://www.gnu.org/copyleft/gpl.html). 

> (...) attach the following notices to the program. It is safest to attach them to the start of each source file to most effectively state the exclusion of warranty; and each file should have at least the “copyright” line and a pointer to where the full notice is found.

Also:
> Also add information on how to contact you by electronic and paper mail.

**Comment by actionless** [comment]
1) isn't it enough having https://github.com/actionless/pikaur/blob/master/LICENSE ?

2) e-mail of each author is accessible via git commit log, appplication doesn't have a single author (as it comes from the `--version` message)

**Comment by steven-omaha** [comment]
> 1. isn't it enough having https://github.com/actionless/pikaur/blob/master/LICENSE ?
I have seen the `LICENSE`. The GPL thinks otherwise, and likes to make clear especially which files are under which license, even though the whole project is GPL only.
> 2. e-mail of each author is accessible via git commit log, appplication doesn't have a single author (as it comes from the --version message)
Correct. But from the installed package, users cannot directly see how to contact you. I think the GPL doesn't necessary _require_ this, but _suggests_ having the mail of the maintainer (which is you) in the project somewhere. Most people who are not familiar with github would think that they have to create an account to contact you, even though your mail is hidden in the commits. I think GPL wants to make it easy for people to reach out to authors, therefore they ask for providing an e-mail asdress.

This is completely up to you. I've seen multiple projects putting a short GPL reference in every file. [Just the first example I came across](https://github.com/zfsonlinux/zfs/blob/master/module/spl/spl-kobj.c).

**Comment by actionless** [comment]
> I have seen the LICENSE. The GPL thinks otherwise, and likes to make clear especially which files are under which license,

but could it be achieved with a smaller header? let's say:

```python
""" This file is licensed under GPLv3, see https://www.gnu.org/licenses/ """
```

> Most people who are not familiar with github would think that they have to create an account to contact you, even though your mail is hidden in the commits.

that's totally fine, i would be quite pissed off if people would contact me via e-mail instead of using issue-tracker on github

**Comment by steven-omaha** [comment]
> but could it be achieved with a smaller header? 

I think so. You could also refer to your `LICENSE`.

**Comment by actionless** [comment]
i think first of all i need to include to the built package :-)

**Comment by actionless** [comment]
i've tried to resolve half of the issue

**Comment by actionless** [comment]
also checked regarding the license for argarse.py fork: https://docs.python.org/dev/license.html , it should be fine:

> Note

> GPL-compatible doesn’t mean that we’re distributing Python under the GPL. All Python licenses, unlike the GPL, let you distribute a modified version without making your changes open source. The GPL-compatible licenses make it possible to combine Python with other software that is released under the GPL; the others don’t.
