### ISSUE TITLE
dependency resolution of repository packages misses some packages

### ISSUE THREAD

**Issue by steven-omaha** [actionless/pikaur#196]
This happened today on one of my machines. `pikaur` wants to install the requested packages and found 3 dependencies which it tells me about, but `pacman` later finds 5 dependencies.

    ~ $ pikaur -S python-pylint
    Lese lokale Paketdatenbank...
    
    :: Zu installierendes Repository-Paket:
     python-pylint                                             -> 1.9.1-1
    
    :: New dependencies will be installed from repository:
     python-astroid                                            -> 1.6.4-1
     python-isort                                              -> 4.3.4-1
     python-mccabe                                             -> 0.6.1-1
    
    :: Mit Installation fortfahren? [J/n] 
    :: [P]aketdetails anzeigen, Pakete [m]anuell auswählen
    >> 
    Suche nach in Konflikt stehenden Pakten...
    Lese Repository-Paketdatenbank...
    Löse Abhängigkeiten auf...
    Suche nach in Konflikt stehenden Paketen...
    
    Pakete (6) python-astroid-1.6.4-1  python-isort-4.3.4-1  python-lazy-object-proxy-1.3.1-1  python-mccabe-0.6.1-1  python-wrapt-1.10.11-1  python-pylint-1.9.1-1
    
    Gesamtgröße des Downloads:           1,13 MiB
    Gesamtgröße der installierten Pakete:  7,20 MiB

**Comment by actionless** [comment]
aha, i didn't kept in account what it should be recursive :-)

**Comment by actionless** [comment]
thanks for reporting!
