### ISSUE TITLE
Install prompt preview doesn't respect Usage option in pacman.conf

### ISSUE THREAD

**Issue by IgnusG** [actionless/pikaur#199]
I specified a third party repository (archlinuxcn) but set an explicit usage like this (Upgrade is disabled):
```
[archlinuxcn]
Server = https://cdn.repo.archlinuxcn.org/$arch
Usage = Sync Search Install
```

Doing a `sudo pacman -Syu` correctly ignores upgrades from this repository.
Calling `pikaur -Syu` tries to update them anyways

Expected:
pikaur respects the `Usage` field specified in pacman.conf

Running the latest git version

**Comment by actionless** [comment]
that's not implemented yet

**Comment by actionless** [comment]
instead of improving pikaur logic i am going to solve it differently, via wrapping pacman (that will also allow to remove some pikaur code, because less code is always better): https://github.com/actionless/pikaur/issues/201

**Comment by actionless** [comment]
@IgnusG could you please try now with the latest git version of pikaur?

**Comment by IgnusG** [comment]
Works without problems now. Nice work @actionless ;)

**Comment by IgnusG** [comment]
Pikaur 0.14 shows this behavior again

**Comment by actionless** [comment]
in 0.14 i've changed that place from `pacman -Su --print-format` to `pacman -S --print-format $(pacman -Quq)`, seems what `pacman -Qu` doesn't respect `Usage: Upgrade` so i'll revert that part to previous logic

**Comment by actionless** [comment]
not sure about the most latest referenced commit

feel free to reopen, thanks for reporting!

**Comment by actionless** [comment]
yup, it makes sense to handle them differently, fixed it
