### ISSUE TITLE
We should not have to press "Enter" to answer questions

### ISSUE THREAD

**Issue by Tromzy** [actionless/pikaur#200]
In other AUR helpers, it is not necessary to press Enter when questions such as ":: Proceed with installation? [Y/n]" are asked ; just press "Y" and that's it. On Pikaur, you have to press the key for the answer ("y", "n", etc.) and THEN press Enter ; it is an unnecessary step and it makes the process less fluid.

**Comment by actionless** [comment]
https://github.com/actionless/pikaur#requireenterconfirm-default-yes

**Comment by IgnusG** [comment]
Just to be 100% clear, the feature you are describing is configurable. You can enable/disable it in pikaur's config file

**Comment by Tromzy** [comment]
I did not know that, thanks !
