### ISSUE TITLE
Validation of the spanish translation

### ISSUE THREAD

**Issue by Bundy01** [actionless/pikaur#202]
Hi, 
I'm gonna need a Spanish speaker to validate my work.
If there are lines to modify, please indicate the number with your translation.
Thanks for your help :)

Translation file URL: https://github.com/Bundy01/pikaur/blob/master/locale/es.po

**Comment by actionless** [comment]
also i think it would be better to submit it as a pull request, so reviewever could easily comment it

**Comment by Bundy01** [comment]
Thanks to you for pikaur :). Pull-request done.

**Comment by actionless** [comment]
merged as is for now
