### ISSUE TITLE
Could Not Initialize last_seen_news.dat

### ISSUE THREAD

**Issue by jmauss** [actionless/pikaur#203]
I am getting this error on a fresh install of Arch with pikaur. Nothing seems to actually fail, but I am wondering why I am getting "Could not initialize /home/jmauss/.cache/pikaur/last_seen_news.dat" and how I can get rid of it. This is during "pikaur -Syu"

Thanks

**Comment by actionless** [comment]
thanks for reporting! please check if it helps

**Comment by jmauss** [comment]
Fixed, thanks!

**Comment by Xwang1976** [comment]
I have the same issue with a fresh install of pikaur on Archlinux.

**Comment by Xwang1976** [comment]
I've installed now  pikaur-git and I can't reproduce the issue with pikaur-git.

**Comment by actionless** [comment]
thanks for testing, new stable release (0.13) will be tonight or tomorrow
