### ISSUE TITLE
terminal doesn't print any input after exiting pikaur -Syu with n

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#207]
When I do `pikaur -Syu` and press anything else but `y` or `m`, my terminal doesn't print anything anymore when I press a key. But if I press enter, the commands are executed.

**Comment by actionless** [comment]
i can't reproduce it but i think i know the reason so i've did a commit, please check

**Comment by SpineEyE** [comment]
yup, works. Thanks.
