### ISSUE TITLE
Version mismatch triggered by java-runtime

### ISSUE THREAD

**Issue by darkgallium** [actionless/pikaur#208]
Hi !
It seems there is a problem in the way pikaur handles version mismatch. 
In fact, installing the AUR package `minecraft-launcher` raises the following exception on my PC : 
```
Version mismatch :
minecraft-launcher depends on 'java-runtime=8'
 found in 'PackageSource.REPO': '8.u172-2'
```
As I have version 8 of java (update 172-2) installed, pikaur should not raise this exception. Besides, using `makepkg -si` doesn't raise any exception of that sort. I think it has to do with java's version naming policy and the use of the letter u in the version name. You may want to create a java exception.

Your call :)

**Comment by actionless** [comment]
seems to be regression after 352d6d6d2c4c7f622d9d525e1b757d4948d06896, i'll address it

**Comment by actionless** [comment]
the case when jre8 package is locally installed looks good now, however for case where no jre installed yet i have a wrong prompt message (of first satisfying dependency, not of the one chosen by user)

**Comment by SpineEyE** [comment]
I'm no expert in this, but shouldn't the PKGBUILD contain `java-runtime>=8`?
Considering that `vercmp 8 8.u172-2` gives `-1`.

**Comment by actionless** [comment]
no, package is valid, jre8-openjdk indeed provides `java-runtime=8`, so i hope the commit referenced above got fixed that issue

**Comment by actionless** [comment]
fixed the case when no jre installed

now only one remaining part to fix -- show correct version of jre in prompt in such case

**Comment by actionless** [comment]
@darkgallium please check with `pikaur-git`

**Comment by darkgallium** [comment]
It works :) 
Thank you for your reactivity !

**Comment by actionless** [comment]
also created related ticket for the problem which i discovered while investigating this: https://github.com/actionless/pikaur/issues/211
