### ISSUE TITLE
disabling retry question after build failure

### ISSUE THREAD

**Issue by deathtrip** [actionless/pikaur#209]
Currently after a build failure, pikaur asks if you want to retry. Which if unanswered for too long, causes sudo timeout, stopping the process of installing successfully built packages. An option to automatically continue would prevent this, and optionally keeping a sudo loop when keeping the current behaviour.

**Comment by actionless** [comment]
there is a ticket already for implementing sudo loop to avoid asking sudo password multiple times if whole process takes longer than sudo timeout

> causes sudo timeout, stopping the process of installing successfully built packages.

you mean pikaur crashes at that point? or it just asks for password?

however i don't mind having config option like "SkipFailedBuilds"

**Comment by deathtrip** [comment]
> you mean pikaur crashes at that point? or it just asks for password?

it doesn't crash, what i meant is that you have to type your password again to install already built packages

**Comment by actionless** [comment]
thing with sudo is fixed already however option to skip failed builds still going to be added so the issue is still remain open
