### ISSUE TITLE
Add --devel flag like pacaur

### ISSUE THREAD

**Issue by Tyilo** [actionless/pikaur#21]

**Comment by Tyilo** [comment]
Probably also the `--needed` flag would be useful :)

**Comment by actionless** [comment]
--needed is already implemented

**Comment by actionless** [comment]
and regarding --devel i had different but similar idea:
 mark all `-git` AUR packages which were installed older than month ago as upgradeable

**Comment by actionless** [comment]
so, can you confirm if `--needed` option is working fine for you?

and what do you think about `-git` packages

**Comment by Tyilo** [comment]
> so, can you confirm if --needed option is working fine for you?

`--needed` seems to work as I would expect.

> and what do you think about -git packages

I think it would be nice to automatically mark `-git` packages as out of date after a certain amount of time. However it would also be a good idea to have a way of updating all `-git` packages right now (using something like `--devel`).

I think you should be able to choose how often you want to mark such packages as out of date using pikaur's config file.

I would probably also be a good idea to support `-svn` and others, see https://github.com/rmarquis/pacaur/blob/a0f232d40166117e70a0d74652a7e812826d3532/pacaur#L179

**Comment by actionless** [comment]
i've decided to implement config option DevelPkgsExpiration (days integer)

default DevelPkgsExpiration = -1 (never expire)

passing --devel will override DevelPkgsExpiration to 0 (always expired)

**Comment by actionless** [comment]
thanks for the proposal!
