### ISSUE TITLE
Error after installing from AUR when using Anaconda: ModuleNotFoundError: No module named 'pikaur'

### ISSUE THREAD

**Issue by ArniDagur** [actionless/pikaur#215]
After a seemingly successful installation of pikaur from AUR, I get the following error when using anaconda/miniconda:
```
[arni: pikaur-git]$ pikaur
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 4, in <module>
    from pikaur.main import main
ModuleNotFoundError: No module named 'pikaur'
```
I have tried both `pikaur` and `pikaur-git`.

Using vanilla python instead of anaconda/miniconda works just fine:
```
[arni: pikaur-git]$ /usr/bin/python3 /usr/bin/pikaur -V

      /:}               _
     /--1             / :}
    /   |           / `-/
   |  ,  --------  /   /
   |'                 Y      Pikaur v0.14.1.r0.g6a5dc14
  /                   l      (C) 2018 Pikaur development team
  l  /       \        l      Licensed under GPLv3
  j  ●   .   ●        l
 { )  ._,.__,   , -.  {      Pacman v5.1.0 - libalpm v11.0.0
  У    \  _/     ._/   \
```

**Comment by actionless** [comment]
`/usr/bin/env python3 /usr/bin/pikaur` or `/usr/bin/env python /usr/bin/pikaur` helps?

**Comment by actionless** [comment]
but generally i think anaconda doesn't have the same import path (`/usr/lib/python3.6/site-packages/pikaur/`)

**Comment by ArniDagur** [comment]
Yeah, as you can see above, using the vanilla executable works fine.

**Comment by ArniDagur** [comment]
```
[arni: ~]$ /usr/bin/env python3 /usr/bin/pikaur
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 4, in <module>
    from pikaur.main import main
ModuleNotFoundError: No module named 'pikaur'
```

**Comment by actionless** [comment]
is it working if you running git version directly via `anaconda pikaur.py` ?

**Comment by actionless** [comment]
i guess you still have problem with pyalpm though

**Comment by actionless** [comment]
so after building pyalpm with anaconda support (if that's possible) you could just run `anaconda setup.py install` in pikaur git repo to get it installed to the correct path

**Comment by caio96** [comment]
I'm having the same problem.
Changing `pikaur.py` `#!/usr/bin/env python3` to `#!/usr/bin/python3 ` solves it.

**Comment by actionless** [comment]
@caio96 thanks!
