### ISSUE TITLE
Inprecise prompt when package_A depends on package_B and package_C (provided by package_B)

### ISSUE THREAD

**Issue by ypnos** [actionless/pikaur#220]
Hello,

I wanted to install some software from AUR that depends on `jack2` package, which replaces the previously installed `jack` package.

So in the step _Installing repository dependencies for zam-plugins-git_, pacman removes `jack` and installs `jack2` in one go, as expected.

However, after making `zam-plugins-git`, apparently pikaur gets confused by the current situation and comes up with this error:

> :: error Failed to remove installed dependencies, packages inconsistency: jack:

Please see the [relevant console output](https://github.com/actionless/pikaur/files/2133110/pikaur-fail.txt)

Re-running the same command works, this time with jack2 already being installed, works as expected.

**Comment by actionless** [comment]
seems to be similar to this issue: https://github.com/actionless/pikaur/issues/194#issuecomment-399753284

let me quote myself:

> so far i think it could be solved only by building inside chroot using makechrootpkg or setting chroot env using systemd. both will require extra space for installing again all the deps chain for building the packages so i think to make such behavior optional

> and also first it will require implementing this (#136) to avoid building again aur deps of the package

> also i think to avoid reinstalling all the deps inside chroot each time mb to keep packcages installed in chroot between the builds but just if build fails to show such a prompt, related to #44 (comment):

[r]etry
[p]gp check skip
[c]hecksums skip
[f]lush chroot (show only if building inside chroot)
[s]kip building this package
[a]bort building all the packages

**Comment by actionless** [comment]
@ypnos by now you could workaround the problem by manually installing jack2 before

**Comment by actionless** [comment]
@ypnos i fixed most of the related bugs, now the only one problem remains:

`zam-plugins-git` depends and makedepends on both `jack` and `jack2`

currently in the install prompt pikaur shows only what `jack (provided by jack, jack2)` will be installed, not what particularly jack2 will be installed
