### ISSUE TITLE
The installed dependencies are required to be reinstalled

### ISSUE THREAD

**Issue by TheForgetTime** [actionless/pikaur#222]
When I installed some packages from AUR, the dependencies installed on my system were required to be reinstalled.
---

$ pikaur -S jetbrains-toolbox     
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 jetbrains-toolbox                1.9.3935-1      -> 1.9.3935-1

:: Proceed with installation? [Y/n] 
:: [v]iew package detail   [m]anually select packages
>> 
looking for conflicting AUR packages...
Do you want to edit PKGBUILD for jetbrains-toolbox package? [y/N] 

[sudo] auser 的密码：

Reading local package database...
:: Installing repository dependencies for jetbrains-toolbox:
Wraning：jdk8-8u172-1 已经为最新 -- reinstall
---
正在解决依赖关系...
正在查找软件包冲突...

软件包 (1) jdk8-8u172-1

全部安装大小：  367.28 MiB
净更新大小：    0.00 MiB

:: 进行安装吗？ [Y/n] n
Command 'sudo pacman --color=always --sync --asdeps java-runtime' failed to execute.
---
Do you want to retry? [Y/n] n
Do you want to proceed? [y/N]

**Comment by actionless** [comment]
what pikaur version do you use? i can't reproduce it

**Comment by TheForgetTime** [comment]
The pikaur I am using is the latest version.
This error is only repeated when I install the jetbrains-toolbox package in aur.
When editing PKGBUILD, I found that this package relies on a virtual package called "java-runtime", which matches the jdk8 package.
Then pikaur asked me to reinstall the jdk8 package, the other real packages are normal.

------Translated by https://www.google.cn


https://translate.google.cn/#zh-CN/en/%E6%88%91%E4%BD%BF%E7%94%A8%E7%9A%84pikaur%E6%98%AF%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84%E3%80%82%0A%E8%BF%99%E4%B8%AA%E9%94%99%E8%AF%AF%E5%8F%AA%E5%9C%A8%E6%88%91%E5%AE%89%E8%A3%85aur%E4%B8%AD%E7%9A%84jetbrains-toolbox%E5%8C%85%E6%97%B6%E9%87%8D%E5%A4%8D%E5%87%BA%E7%8E%B0%E3%80%82%0A%E5%9C%A8%E7%BC%96%E8%BE%91PKGBUILD%E6%97%B6%E6%88%91%E5%8F%91%E7%8E%B0%E8%BF%99%E4%B8%AA%E5%8C%85%E4%BE%9D%E8%B5%96%E4%BA%86%E4%B8%80%E4%B8%AA%E5%8F%AB%E2%80%9Cjava-runtime%E2%80%9D%E7%9A%84%E8%99%9A%E5%8C%85%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%8C%85%E5%8C%B9%E9%85%8D%E5%88%B0%E4%BA%86jdk8%E8%BF%99%E4%B8%AA%E5%8C%85%E3%80%82%0A%E7%84%B6%E5%90%8Epikaur%E8%A6%81%E6%B1%82%E6%88%91%E9%87%8D%E6%96%B0%E5%AE%89%E8%A3%85jdk8%E8%BF%99%E4%B8%AA%E5%8C%85%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84%E7%9C%9F%E5%AE%9E%E5%AD%98%E5%9C%A8%E7%9A%84%E5%8C%85%E6%AD%A3%E5%B8%B8

**Comment by actionless** [comment]
please upload the full output of the following commands:

```bash
pacman -Qsq jre
pacman -Qsq jdk
pacman -S java-runtime   # (press [N]o in prompt)
```

P.S. also i've just realized what you have jdk8 not from official repos, mb it have `Provides` or other field contents a bit different from openjdk8

**Comment by TheForgetTime** [comment]
Yes. The jdk I use is in archlinuxcn repos. He is an Oracle JDK 8 packaged from AUR.

$ pacman -Qsq jre   
--
jdk8

$ pacman -Qsq jdk
--
jdk8

$ pacman -Qi jdk8
--
<table>
<tr><td>Name : </td><td>jdk8</td></tr>
<tr><td>Version : </td><td>8u172-1</td></tr>
<tr><td>Description : </td><td>Oracle Java 8 Development Kit</td></tr>
<tr><td>Architecture : </td><td>x86_64</td></tr>
<tr><td>URL : </td><td>http://www.oracle.com/technetwork/java/javase/downloads/index.html</td></tr>
<tr><td>Software license : </td><td>custom:Oracle</td></tr>
<tr><td>Group : </td><td>None</td></tr>
<tr><td>Provided by: </td><td>java-runtime=8<br> java-runtime-headless=8<br> java-web-start=8<br> Java-environment=8<br> java-runtime-jre=8<br> Java-runtime-headless-jre=8<br> java-web-start-jre=8<br> Java-environment-jdk=8<br> java-openjfx=8</td></tr>
<tr><td>Depends on : </td><td>ca-certificates-java<br> hicolor-icon-theme<br> 
Java-environment-common<br> java-runtime-common<br> nss<br> xdg-utils</td></tr>
<tr><td>Optional dependencies : </td><td>alsa-lib: for basic sound support [installed]<br>
Eclipse-java: to use "Oracle Java Mission Control" plugins in Eclipse<br>
Gtk2: for Gtk+ look and feel (desktop) [installed]</td></tr>
<tr><td>Requested by : </td><td>jetbrains-toolbox</td></tr>
<tr><td>Optional dependency : </td><td>libbluray</td></tr>
<tr><td>Conflict and : </td><td>None</td></tr>
<tr><td>Replace : </td><td>None</td></tr>
<tr><td>Size after installation :</td><td> 367.28 MiB</td></tr>
<tr><td>Packager : </td><td>lilac (on behalf of ivan) &lt;qwIvan@users.noreply.github.com&gt;</td></tr>
<tr><td>Date of compilation : </td><td>Wednesday, April 18, 2018 18:23:10</td></tr>
<tr><td>Installation date : </td><td>Thursday, June 28, 2018 19:36:24</td></tr>
<tr><td>Installation Cause : </td><td>Dependency installation as another package</td></tr>
<tr><td>Installation script : </td><td>Yes</td></tr>
<tr><td>Certifier: </td><td>Digital Signature</td></tr>
</table>

$ sudo pacman -S java-runtime
--
<font color=#ffff00>Warning:</font> jdk8-8u172-1 is up to date -- reinstall
Resolving dependencies...
Looking for package conflicts...

Software package (1) jdk8-8u172-1

Total installation size: 367.28 MiB
Net update size: 0.00 MiB

:: Do you want to install? [Y/n] n

**Comment by actionless** [comment]
and `sudo pacman -S java-runtime --needed`

**Comment by TheForgetTime** [comment]
`$ pacman -Qi java-runtime` output is the same as `$pacman -Qi jdk8`

`sudo pacman -S java-runtime --needed` output :
Warning:  jdk8-8u172-1 is up to date -- skip
Noting to do today

**Comment by actionless** [comment]
please check with `pikaur-git` now

**Comment by TheForgetTime** [comment]
The problem fixed

**Comment by actionless** [comment]
thanks for reporting and testing!
