### ISSUE TITLE
Diff of PKGBUILD is not always shown

### ISSUE THREAD

**Issue by sh4nks** [actionless/pikaur#223]
Hey,

for some reason the diff is not always shown.

```# pikaur -Syu```
![image](https://user-images.githubusercontent.com/1510708/42047457-9245577a-7b00-11e8-97ab-306675c170a2.png)

I am using the default config (i.e. nodiff=no which indicates that the diff should be always be shown right?)

As I understand, it's not necessary to edit the PKGBUILD in order to view the diff right?

**Comment by actionless** [comment]
it's showing diff only if you already built previous version of this package with pikaur before, if not — you've proposed to read the full PGKBUILD via editing it

the reason why it's made like that -- because pkgver could not directly depend on the changes of aur repo

**Comment by sh4nks** [comment]
Ok, thanks for the explanation.
