### ISSUE TITLE
Pikaur becomes unresponsive after timeout

### ISSUE THREAD

**Issue by bertptrs** [actionless/pikaur#227]
When pikaur is left alone for quite some time (say, builds that take a while) it generally needs a sudo renewal to work again. However, when that times out, you get asked again, and then after some time, the cursor moves to the next line and nothing happens anymore.

Output looks like this (compilation section removed for brevity):

```==> Tidying install...
  -> Removing empty directories...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "openblas-lapack"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: openblas-lapack 0.3.1-1 (Mon 02 Jul 2018 10:45:46 CEST)

[sudo] password for bert: 
[sudo] password for bert: 

```

The only thing left then is to cancel the program with Ctrl+C, but that has issues:
- obviously, the built package is not updated, but also
- builddepends are not cleaned up and are no longer internally marked as such, so they won't be automatically removed.

You can still install the packages from the build files, where the finished packages are.

**Comment by actionless** [comment]
it should be fixed by https://github.com/actionless/pikaur/issues/114
