### ISSUE TITLE
Add fakeroot as dependency

### ISSUE THREAD

**Issue by MartinSandfuchs** [actionless/pikaur#231]
When trying to run `pikaur -Syyu` without fakeroot installed I get the following error:
`:: error: 'fakeroot' executable not found.` 
Which is a problem for all those who do not have base-devel installed

**Comment by Morganamilo** [comment]
>Which is a problem for all those who do not have base-devel installed

The solution is to install `base-devel`.

**Comment by actionless** [comment]
yup, https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites
