### ISSUE TITLE
Download PKGBUILD only

### ISSUE THREAD

**Issue by TheForgetTime** [actionless/pikaur#236]
how to download PKGBUILD only?
Or add this feature

like yaourt -G

**Comment by actionless** [comment]
i am thinking, should it be downloaded to pikaur's directory (~/.cache/pikaur/aur_repos/) or to the current one?

**Comment by actionless** [comment]
and also, if AUR package have some uninstalled AUR dependencies, should they also be downloaded? or mb make an option for that

**Comment by TheForgetTime** [comment]
>i am thinking, should it be downloaded to pikaur's directory (~/.cache/pikaur/aur_repos/) or to the current one?

Create a package name folder in the current directory and download in it.
Prevent file coverage

>and also, if AUR package have some uninstalled AUR dependencies, should they also be downloaded? or mb make a cli flag for that

Download it to the depneds folder by default and give a cli switch to turn it off.

**Comment by actionless** [comment]
mb also to download PKGBUILDs from ABS if the repo package will be specified?
