### ISSUE TITLE
Arch wiki update needed for handling common build problems (GPG keys, checksums, --skipinteg, ignore architecture)

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#238]
related change in readme:

https://github.com/actionless/pikaur/commit/3688d828591d307c6864c3b5ad8c1f581396b865#diff-04c6e90faac2675aa89e2176d2eec7d8

possible text for Specificity column:
`prompt to ignore PGP keys, checksums, architecture`

**Comment by soloturn** [comment]
added

**Comment by actionless** [comment]
thanks a lot!
