### ISSUE TITLE
No tab completion on AUR packages in ZSH

### ISSUE THREAD

**Issue by whnr** [actionless/pikaur#243]
```
Pikaur v1.2.1
Pacman v5.1.0 - libalpm v11.0.0
zsh 5.5.1 (x86_64-unknown-linux-gnu (with oh-my-zsh)
```
The readme says: AUR package names in shell completion (bash, fish, zsh)
But tab completion does not do anything for me when I try for example `pikaur -S pikau<tab>`

Should it work? Searching with e.g. `pikaur -Ss pikau` shows the package in the aur.

**Comment by actionless** [comment]
i did some sanity check now but i am not zsh user so feel free to improve the completion script

**Comment by whnr** [comment]
Wow. That was fast. Thank you very much. Works like expected for now!
