### ISSUE TITLE
pikaur crashes if HOME is not defined

### ISSUE THREAD

**Issue by lectrode** [actionless/pikaur#248]
```
$ pikaur -Vq
Pikaur v1.2.5.r0.g0899e72
Pacman v5.1.0 - libalpm v11.0.0
```

If the HOME environment variable is not defined, pikaur crashes. An (albeit poor) example of a circumstance where HOME would not be defined could be if pikaur was run as a service. If HOME is not defined, and the current user is root, HOME should probably be set to `/root`

##### Attached log:

```
$ pikaur -Su

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 29, in <module>
    from .print_department import (
  File "/usr/lib/python3.6/site-packages/pikaur/print_department.py", line 16, in <module>
    from .config import VERSION, PikaurConfig
  File "/usr/lib/python3.6/site-packages/pikaur/config.py", line 14, in <module>
    os.path.join(os.environ["HOME"], ".cache/")
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

**Comment by actionless** [comment]
thanks for

**Comment by Morganamilo** [comment]
You shouldn't just assume the home dir is `/home/ + username` that's not how it works.

**Comment by actionless** [comment]
in that case it will just write PathNotFound instead of KeyError

i don't think what more sophisticated handling of such scenario (unset HOME and custom /home/ root path) is worthy time investments

**Comment by Morganamilo** [comment]
If home is unset you should either get the home directory properly via passwd. Or the simpler solution is to just error out.

**Comment by actionless** [comment]
@Morganamilo found some goodies in the stdlib :-)

**Comment by lectrode** [comment]
That works, thanks! Very elegant solution to boot
