### ISSUE TITLE
pikaur extreme slow

### ISSUE THREAD

**Issue by qupfer** [actionless/pikaur#251]
Hi, on my new system, pikaur runs extremly slow. 
I thought it hangs, but was still running ;-)

Any ideas what could be wrong on my system or how to analyse this behaviour?

Thank You

```
pikaur -Vq
Pikaur v1.2.10.r8.g4565cc9
Pacman v5.1.1 - libalpm v11.0.1

```

##### Attached log:

normal compared to pacman or yaourt
```
pikaur -Sy  0,92s user 0,08s system 39% cpu 2,538 total
  0,00s user 0,00s system 86% cpu 0,002 total 
```
unnormal long. Maybe nice to know: It looks like it hangs before doing anything. I mean most time is gone before the first line of output is written.

```
pikaur -Su
:: Starte komplettes AUR Upgrade...
Lese Repository-Paketdatenbank...
Lese lokale Paketdatenbank...
Lese AUR Paketinfos...
:: Nichts zu tun.
pikaur -Su  5,77s user 3,71s system 3% cpu 4:22,11 total
  0,00s user 0,00s system 75% cpu 0,004 total 
```
```
pikaur -Syu  4,73s user 3,13s system 3% cpu 4:21,17 total
  0,00s user 0,00s system 89% cpu 0,002 total
```
```
pikaur -Ss cmake  1,00s user 0,12s system 0% cpu 2:10,35 total
  0,00s user 0,00s system 88% cpu 0,002 total    
```
yaourt  much faster
```
yaourt cmake  0,25s user 0,04s system 11% cpu 2,575 total
  0,00s user 0,00s system 84% cpu 0,002 total   
```

**Comment by actionless** [comment]
> looks like it hangs before doing anything. I mean most time is gone before the first line of output is written.

i suppose that's just the python interpreter starting

also i did `-Ss cmake` with pikaur and yaourt and results were quite close, 0.5-0.6 seconds in yaourt and 0.7-0.9 seconds in pikaur

`-Sy`: 1.1-1.2 seconds in yaourt and pikaur 1.5-1.6 seconds (this i think i could fix, because Sy command is being parsed by pikaur as `install zero packages but refresh db before` so it could be optimized)


what is `nproc` output on your machine?

**Comment by qupfer** [comment]
i got a pikau-git update, and after that, it looks runs normal.

**Comment by actionless** [comment]
@qupfer  so, can you still reproduce the issue? if so please paste your `nproc` output

**Comment by qupfer** [comment]
It looks, this behaviour was not directly pikaur related. Pikaur just make my problem(s) visible.
I forgot to define a hostname and hosts file for my new pc. 
So localhost could not be resolved correctly, and changing the wirless network also changed my hostname, what creates other problems (like invalid .Xauthority).
So I think, this problem slows down the python/pikaur process because it waits for some timeouts or something like this.
