### ISSUE TITLE
high(er) contrast color scheme

### ISSUE THREAD

**Issue by soloturn** [actionless/pikaur#252]
pikaur displays the old version in light yellow on white background, as well light green on white. or, when using a black background terminal, it displays the new version in dark red on black. these combinations are not so good to read. would be great if pikaur could detect the background and use 3 high contrast colors.

**Comment by actionless** [comment]
1) your terminal colorscheme probably need some improvement if some colors are not visible on default background
2) however you still can adjust the color choice in pikaur itself: https://github.com/actionless/pikaur#colors

**Comment by soloturn** [comment]
ok ... i tried this:
https://github.com/Anthony25/gnome-terminal-colors-solarized
