### ISSUE TITLE
stick with skip_integration_checks

### ISSUE THREAD

**Issue by soloturn** [actionless/pikaur#257]
https://github.com/actionless/pikaur/commit/3688d828591d307c6864c3b5ad8c1f581396b865 says:

```
                        _("[v] skip all validity checks"),
            elif answer == _("v"):
                skip_integration_checks = True
```

which sounds a little confusing. why not stick with "skip_integration_checks" ?

**Comment by actionless** [comment]
i've updated the label text, mb also to use different letter now for it, since `v` doesn't make any sense anymore

**Comment by Morganamilo** [comment]
`integration` does not seems to make any sense, maybe it doesn't mean what you think it means? Or you mean `integrity` instead?

**Comment by actionless** [comment]
updated once again, to match ` makepkg -h | grep skipinteg`

**Comment by actionless** [comment]
and also see https://github.com/actionless/pikaur/issues/258#issuecomment-410455993

**Comment by actionless** [comment]
@soloturn what do you think?

**Comment by actionless** [comment]
```
makepkg -h | grep skipinteg
  --skipinteg      Do not perform any verification checks on source files
```

**Comment by actionless** [comment]
however mentioning what it includes checksums and pgp is good idea

**Comment by actionless** [comment]
i've just checked makepkg script and --skipinteg actually doesn't skip any checks other than PGP and checksums, so it's useless to add that menu option since other two are already there

**Comment by Morganamilo** [comment]
Funny there's a little discrepancy between the usage and man help.

**Comment by actionless** [comment]
anyway good what raising this issue helped me to understand what that option is not needed at all :+1:
