### ISSUE TITLE
Add pacman extension options (-r, -a)

### ISSUE THREAD

**Issue by XavierCLL** [actionless/pikaur#26]
The pacman extension options implemented in pacaur are so useful: (-a, --aur) and (-r, --repo)

https://github.com/rmarquis/pacaur#pacman-extension-options

**Comment by actionless** [comment]
should it be applied only for `-Ss, -Su/-Syu, -Qu, -Qs` or also for some other options?

**Comment by XavierCLL** [comment]
pacaur implemented it for search, build, install, upgrade and clean, apart from the ones you mention, I think only one is missing: `-Sc`

**Comment by actionless** [comment]
right, haven't considered it because it's not implemented now

**Comment by actionless** [comment]
```fish
begin pacman -Sh ; pacman -Qh ; end | grep -e " -[ra]"
```
```
  -r, --root <path>    set an alternate installation root
  -r, --root <path>    set an alternate installation root
```

**Comment by actionless** [comment]
also i am not sure it makes sense to apply it to `-Qs` since i don't a reliable way to determine from where the package was installed

**Comment by rmarquis** [comment]
>  I think only one is missing: -Sc

No, pacaur implements it for -Sc too.

@actionless Yes, you shouldn't try to find the origin of that package anyway. These `--aur` and `--repo` options make sense when you want to restrict the operation to a specific source, but `-Qs` has only one source and that is the `local` database.

**Comment by XavierCLL** [comment]
yeah, `-Qs` is only for local database, isn't necessary.

**Comment by XavierCLL** [comment]
Hi @actionless, I test it and works perfectly with `--aur` and `--repo` but not with contraction `-a` and `-r`, for example, it is very useful for use in combination with `-Ssr` or `-Ssa`

**Comment by actionless** [comment]
i don't like idea of overriding `pacman`'s `-r`

**Comment by actionless** [comment]
just noticed what i forgot to implement it for -Sc/-Scc, fixed

**Comment by actionless** [comment]
i'm reopening this in order to add `-a` flag for `--aur` since it seems to be quite popular among users migrating over from yaourt/pacaur

but i still don't like to add `-r` flag for `--repo` to not override pacman

**Comment by rmarquis** [comment]
Note that `--root` and `-r` will be soon deprecated (replaced by `--sysroot`), and `-r` will not be used by pacman anymore.

**Comment by actionless** [comment]
thanks for info, for now on i'll add only `-a` and so will add `-r` as soon as pacman will deprecate it
