### ISSUE TITLE
Conflict resolution not skip conflict lines with invalid separator between name and version

### ISSUE THREAD

**Issue by bertptrs** [actionless/pikaur#261]
```
pikaur -Vq
Pikaur v1.2.17
Pacman v5.1.1 - libalpm v11.0.1
```

When resolving conflicts in packages, pikaur does not take specific version conflicts into account. This causes false positives. If you actually install the package however, pacman will not ask to remove the original since it doesn't actually conflict.

##### [Optional] Prerequisites:

- Have a package with a versioned conflict installed, such as [android-platform-22](https://aur.archlinux.org/packages/android-platform-22/)
- Install a package that provides the conflict, but at a different version, such as [android-platform](https://aur.archlinux.org/packages/android-platform/)

##### Attached log:

```
pikaur -S android-platform
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 android-platform                                           -> 5.1.1_r02-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
:: android-platform and android-platform-22 are in conflict. Remove android-platform-22? [y/N]
```
Note that this works two ways, if you have some specific android platform installed and you install the rolling platform, you get the same result.

**Comment by actionless** [comment]
that's a mistake in `android-platform-22: conflicts should have single `=` not `==`.
https://www.archlinux.org/pacman/PKGBUILD.5.html#_options_and_directives

**Comment by actionless** [comment]
idk why it's not failing in pacman, mb it's just skipping the conflict line which can't be parsed, i'll have a look intro it

**Comment by actionless** [comment]
now behavior should be the same as in pacman

thanks for reporting!
