### ISSUE TITLE
Build recovery prompt: add "[e] edit pkgbuild"

### ISSUE THREAD

**Issue by Mako88** [actionless/pikaur#269]
Howdy!

To speed things up I always use the --noedit parameter (and have set it in the config file). However on the rare occurrences when a package fails to build, and there is a list of options, it would be nice to have "edit PKGBUILD" as one of the options.

Thanks!

**Comment by actionless** [comment]
i was planning to add soon to build recovery prompt: `[e] edit pkgbuild`

**Comment by actionless** [comment]
fixed by https://github.com/actionless/pikaur/pull/362
