### ISSUE TITLE
Resolving dependencies issue

### ISSUE THREAD

**Issue by plague-doctor** [actionless/pikaur#27]
pikaur has problem with dependencies resolution for some packages.

**Installing with pikaur**

```
pikaur -S seafile-client

resolving dependencies...
Reading repository package databases...
Reading local package database...
Version mismatch:
 seafile-client depends on: 'seafile=6.1.5'
 found in 'aur': '6.1.5-2'

```

**same installed with pacaur:**

```
pacaur -S seafile-client
:: Package seafile-client not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (4) ccnet-6.1.5-3  libsearpc-1:3.0.8-2  seafile-6.1.5-2  seafile-client-6.1.5-2
Repo Packages (1) python2-simplejson-3.13.2-1

Repo Download Size:   0.00 MiB
Repo Installed Size:  0.37 MiB

:: Proceed with installation? [Y/n]
[...]
```

**Comment by actionless** [comment]
yeah, technically `6.1.5-2` is newer than `6.1.5` so if it would be criteria `seafile>=6.1.5` it would match, isn't it?

**Comment by plague-doctor** [comment]
Technically it is. Maybe a switch to allow 'fast-forward' packages in case a package version is the same but the release has progressed? Just a thought, as there is no such problem with pacaur, and it is rather difficult to chase up every aur-package provider...

**Comment by actionless** [comment]
hm, i can strip everything in the version after the dash (ie pkgrel) when comparing deps/conflicts versions

**Comment by plague-doctor** [comment]
That would be very nice and useful, but I would rather make it on a request (prompt or switch). Sometimes the patches (new releases) can screw the things up badly...

**Comment by actionless** [comment]
idk, mb adding inteactive prompt 'ignore version mismatch? [y/N]' could be a way to go

**Comment by polygamma** [comment]
actually it is 6.1.5-2 == 6.1.5 - https://www.archlinux.org/pacman/vercmp.8.html

**Comment by actionless** [comment]
thanks, mb i'll just call vercmp instead of implementing that logic
