### ISSUE TITLE
commit message difficult to read

### ISSUE THREAD

**Issue by soloturn** [actionless/pikaur#274]
as an example, commit https://github.com/actionless/pikaur/commit/7f045e5a5c89672978907d6cd455e4ede99a1689 is difficult to read as the format is not as expected by git and software dealing with git. https://gist.github.com/matthewhudson/1475276 for how linux torvalds would describe it.

**Comment by actionless** [comment]
github is splitting too long header line into header line and description, in other git clients it should be displayed fine
