### ISSUE TITLE
`pikaur -Suy` freezes, can't be killed with ctrl-C

### ISSUE THREAD

**Issue by ohjames** [actionless/pikaur#277]
```
pikaur -Vq
Pikaur v1.2.22
Pacman v5.1.1 - libalpm v11.0.1
```

##### [Optional] Prerequisites:
All of these commands just freeze. pikaur then can't be killed with ctrl-C (I use ctrl-Z then kill %1):

```
pikaur -Suya
pikaur -Suy
pikaur -S python
```

Probably many others. This started happening after fully upgrading my system today. Reinstalled pikaur twice, no difference.

##### Attached log:

```
% pikaur -S python
Reading repository package databases...
Reading local package database...

:: Repository package will be installed:
 python                                3.7.0-3              -> 3.7.0-3

(freezes like this)
```

**Comment by actionless** [comment]
please run the command again with `--debug` flag

**Comment by ohjames** [comment]
```
james@lonchil ~ % pikaur --debug -S python
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync python --print-format %r/%n

:: Repository package will be installed:
 python                                3.7.0-3              -> 3.7.0-3


```

Not much help, sorry!

**Comment by actionless** [comment]
and in debug mode Ctrl+C also not working?

**Comment by actionless** [comment]
if no luck, could you please try to bisect if it's a regression by checking few previous pikaur versions?

for that you could just clone the repo locally somewhere, `git checkout 1.2.21` and `./pikaur.py -Some args`

**Comment by actionless** [comment]
and you have `requireenterconfirm = no` in the config, right? with `yes` it will work?

**Comment by actionless** [comment]
please try with the latest pikaur-git

**Comment by ohjames** [comment]
@actionless yes to all three. Would be great if you could release a new version with the fix!

**Comment by actionless** [comment]
i was waiting for your feedback to avoid issuing the release with a _possible_ fix :-)
