### ISSUE TITLE
make sudo loop interval configurable (and -1 to disable it at all)

### ISSUE THREAD

**Issue by iroedius** [actionless/pikaur#278]
Whenever pikaur is doing something it clutters the logs with:

`Aug 22 16:08:18 <hostname> sudo[17088]:   <username> : TTY=pts/1 ; PWD=/home/<username> ; USER=root ; COMMAND=validate`

The above message appears in the logs every second pikaur is doing something, be it downloading and installing a package or simply idling waiting for user input. Is there any chance this can be reduced or hopefully eliminated by for example not using sudo for it?

I noticed no such messages appear when using the --dynamic-users option.

**Comment by actionless** [comment]
yes, that's sudo loop, it renews sudo permission every second

**Comment by actionless** [comment]
i can make sudo loop interval configurable (and -1 to disable it at all)

**Comment by iroedius** [comment]
That would be great.

**Comment by actionless** [comment]
thanks for reporting!
