### ISSUE TITLE
Idea: enable `--word-diff` when showing diffs

### ISSUE THREAD

**Issue by ExpHP** [actionless/pikaur#279]
Random thought I had when looking at the build files diff for one of my packages:  As an attack vector, somebody could probably easily substitute a character in the url with a Unicode confusable, and I would not notice as the changed lines are highlighted uniformly.

`git diff` has `--word-diff` and `--word-diff-regex` options that can be used to highlight finer-grained changes between lines.  Since the vast majority of changes tend to be to constants near the top of the file rather than build code, I think it may be a good idea to enable one of them.

**Comment by actionless** [comment]
as far as i understood here a guy is gonna work on it:
https://github.com/actionless/pikaur/pull/271

**Comment by actionless** [comment]
try now please with `pikaur-git` aur package
