### ISSUE TITLE
Can't edit PKGBUILD if a dependency is missing

### ISSUE THREAD

**Issue by lectrode** [actionless/pikaur#282]
```
$ pikaur -Vq
Pikaur v1.2.23.r4.g61b23f7
Pacman v5.1.1 - libalpm v11.0.1
```

##### Attached log:

```
$ pikaur -S --edit vlc-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
:: error: Dependencies missing for kdelibs
:: warning: Following package cannot be found in AUR:
    polkit-qt4
```

Ideally, even if certain dependencies cannot be found, editing the PKGBUILD should be possible. In this particular instance, I want to manually remove dependencies that are no longer needed.

**Comment by actionless** [comment]
related to this: https://github.com/actionless/pikaur/issues/280

**Comment by actionless** [comment]
so far it can be workarounded by `pikaur -U`, editing PKGBUILD, `pikaur -P`
