### ISSUE TITLE
pikaur with powerpill - package not found

### ISSUE THREAD

**Issue by wararjey** [actionless/pikaur#283]
I've discovered that pikaur does not play well together with powerpill. I am using powperill to speed up downloading of packages. However, the installation of a specific package failed:

```
Pikaur v1.2.23
Pacman v5.1.1 - libalpm v11.0.1
powerpill 2018.7-3
```

Prerequisites:
in pikaur.conf, set pacmanpath = /usr/bin/powerpill

##### Attached log:

```
pikaur -S flatpak
Reading repository package databases...
Reading local package database...
:: warning: Following package cannot be found in AUR:
    flatpak  

```
The error does not appear if I:
- use pacman without powerpill
- use powerpill
- use pikaur without powerpill
- use trizen with powerpill

Regards,

**Comment by actionless** [comment]
that's a bug in powerpill, it's not bypassing `pacman --print-format` (and mb some other flags) correctly

**Comment by Morganamilo** [comment]
Pikaur uses alpm right? You could use `alpm_sync_sysupgrade` instead of `pacman --print-format` if you wish.

**Comment by actionless** [comment]
direct alpm calls not taking i account pacman.conf, like excluded packages

**Comment by actionless** [comment]
(i previously were using pyalpm for such lookups but switched to pacman --print because of lots of small issues when pacman does a bit more logic than direct alpm call)

**Comment by Morganamilo** [comment]
Alright makes sense, stick to pacman then if it works better.
