### ISSUE TITLE
Nuitka vs Setuptools?

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#29]
currently PKGBUILD producing a single binary via nuitka

however pikaur has setup.py so can be installed as classical python package (but still package will create `pikaur` entrypoint to be called as executable)

**Comment by polygamma** [comment]
so why even bother about nuitka then?

**Comment by actionless** [comment]
because it's already implemented in PKGBUILD :-)

**Comment by Tyilo** [comment]
I think it would make more sense to just install it as a normal python package.

**Comment by actionless** [comment]
closed in d2a8d7044fa1ee1236f07f9af238a031fee70fed

**Comment by AladW** [comment]
Thanks for this. This was the first time I've heard of `nuitka`, and besides it being excessively slow it created a bunch of configuration files in `XDG_CONFIG_HOME`...
