### ISSUE TITLE
Changing ~/.cache/pikaur/aur_repos directory

### ISSUE THREAD

**Issue by Ape** [actionless/pikaur#290]
Is there a configuration option for changing `~/.cache/pikaur/aur_repos` directory?

`~/.cache` is a directory that should only contain temporary files that can be clean up without really losing any information. It's mostly used for files that can be generated or downloaded. I do think `~/.cache/pikaur/build` is a suitable directory.

However, the `aur_repos` includes information that cannot be regenerated without user effort. I carefully review PKGBUILD files and value the information used for the diffs. I would really like to move it somewhere else with a configuration option. I would also suggest moving the default location to `~/.local/share/pikaur` since that is a more suitable location.

**Comment by actionless** [comment]
good point
