### ISSUE TITLE
Aur Package version 

### ISSUE THREAD

**Issue by Worksihop** [actionless/pikaur#293]
# Pikaur v1.2.25
# Pacman v5.1.1 - libalpm v11.0.1

pikaur -Q dolphin
# ( result ) dolphin 18.08.1-2

pikaur -G dolphin
# (checked the PKGBUILD) version is 18.08.0-1

yay -G dolphin
# (PKGBUILD has  dolphin 18.08.1-2)

**Comment by actionless** [comment]
i can't reproduce it

**Comment by Worksihop** [comment]
deleted pikaur.conf and it fixed the problem

**Comment by actionless** [comment]
i have no idea how it could be related to config file, mb you just runned the command in different directory than previously?

if it already exists it won't be overwritten (but pikaur will write a warning)
