### ISSUE TITLE
root's pikaur.conf is used when running with AlwaysUseDynamicUsers = yes from normal user

### ISSUE THREAD

**Issue by jplatte** [actionless/pikaur#296]
When `AlwaysUseDynamicUsers` is enabled, the `NoEdit` setting is ignored.

```
$ pikaur -Vq
Pikaur v1.2.25
Pacman v5.1.1 - libalpm v11.0.1
```

##### Attached log:

```
$ pikaur -S nautilus-typeahead
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: New dependency will be installed from repository:
 packagekit (for nautilus-typeahead)                        -> 1.1.10-2

:: AUR package will be installed:
 nautilus-typeahead                    3.28.1-1             -> 3.30.0-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
Do you want to edit PKGBUILD for nautilus-typeahead package? [Y/n] 
```

**Comment by actionless** [comment]
that's expected behavior (just not obvious) — when you're using dynamic users that means what you're using sudo, so your config is located in `/root/.config/pikaur.conf`

**Comment by actionless** [comment]
however for the case when dynamic users are forced explicitly from non-root user, i can pass `--config-path /home/user/.config/pikaur.conf` to sudo-ed pikaur with dynamic users (but --config-path flag need to be implemented for that)

**Comment by actionless** [comment]
please try now

**Comment by jplatte** [comment]
It works as expected now. Thanks!
