### ISSUE TITLE
"Error: Too many package results" for searches that contain common words

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#298]
```
Pikaur v1.2.25.r16.g42e9724
Pacman v5.1.1 - libalpm v11.0.1
```

When I execute, for example, `pikaur -Ss firefox en`, pikaur outputs:

```
Searching... [###AUR returned error: URL: https://aur.archlinux.org/rpc/?v=5&type=search&arg=en&by=name-desc
Error: Too many package results.
```

Apart from the weird output format it doesn't deal with multiple search words the same way as yay and possibly pacman which both can handle this query, even when exchanging the order of the keywords. So it seems like yay searches in its internal package database while pikaur sends the query to the server and gets the error from the server?

Maybe a quick fix would be to send only the first word to the server and filter the results with following words?

**Comment by mattia-b89** [comment]
I agree with @SpineEyE  
```
pikaur -Ss firefox en
```
should work as
```
pikaur -Ss firefox | grep en
```
_(in fact, this query works)_

**Comment by actionless** [comment]
what if user wants `pikaur -Ss en firefox` ?

**Comment by actionless** [comment]
or one more case: `pikaur -S python en`


it's not impossible solvable -- i'm just saying what someone should describe, or better implement, robust logic for all possible cases

**Comment by mattia-b89** [comment]
I do not know how search logic works  
I'd like to expose my thought about it:  
search results should work as **sets**  
`pikaur -Ss firefox` should returns packages with word "_firefox_" in title (then in description), thus the _firefox set_  
```
                                                    pkgs

+--------------------------------------------------+
|                                                  |
|                                                  |
|                                                  |
|                                                  |
|                      XXXXXXXXXX  firefox         |
|                     X         XX                 |
|                     X           XX               |
|                     XX           XX              |
|                       XX         XX              |
|                        XXXXXXXXXXX               |
|                                                  |
|                                                  |
|                                                  |
+--------------------------------------------------+
```
`pikaur -Ss firefox en` should returns packages with words "_firefox_" in title (then in description) AND "_en_" in title (then in description), thus the interception of _firefox set_ and _en set_
```
                                                    pkgs

+--------------------------------------------------+
|                                                  |
|    firefox                                       |
|            XXXXXXXXXXX    XXXXXXXXXXXXXXXX       |
|          XXX          XXXX               XXX     |
|         XX              X XXX              X     |
|         X               X   XXX            X     |
|        X                X     XX          XX     |
|        XX               XXX    X        XXX      |
|         XX                 XXXXXXXXXXXXXX        |
|          XX                   XX         en      |
|            XXX              XXX                  |
|              XXXXXXXXXXXXXXXX                    |
|                                                  |
+--------------------------------------------------+
```
_**NB:** word order does not matter_

**Comment by actionless** [comment]
aur search not only package name but also package description

> pikaur -Ss firefox en should returns packages with words "firefox" in title (then in description) AND "en" in title (then in description), thus the interception of firefox set and en set

in your diagram you represent `en` as some sort of euler circle but you couldn't have it like that -- since aur can't return search results for it, it could be only **subset** of `firefox ` circle


but anyway thanks for trying to help

since more people have interest to this feature i found some time to implement it (see linked commit)


please test and let me know

**Comment by actionless** [comment]
currently sorting logic not related to search results, and relating them gonna be an over-engineering 

i'm not following what is the problem with 2/3

**Comment by actionless** [comment]
apparently new version of AUR RPC doesnt have such problem anymore:

```
$ pikaur -Ssq --aur firefox en
pentadactyl-git
firefox-extension-gnome-theme-tweak-git
firefox-hardening
firefox-onetab
firefox-searchengine-ddghtml
firefox-youtube-no-buffer-git
spidermonkey-git
```

**Comment by actionless** [comment]
oh no, it actually got worse - instead of giving an error it just silently cutting any extra results without option to paginate (or at least it's not documented yet officially, mb docs will be updated later)
