### ISSUE TITLE
Optionally grab the news from archlinux.org/feed/news/ when upgrading

### ISSUE THREAD

**Issue by r79** [actionless/pikaur#299]
Inspiration: https://www.reddit.com/r/archlinux/comments/9jnafm/how_frequently_you_updateupgrade_arch_linux/e6t1ae0/

The idea would basically be to add a little formatted parsed output of the feed on archlinux.org in order to inform the user of potential manual interventions when upgrading.

Screenshot:
![image](https://user-images.githubusercontent.com/6749862/46237678-6017b300-c386-11e8-92a6-90dd74a6a753.png)

I'd volunteer to add this feature myself if there's enough hype around it :)

**Comment by actionless** [comment]
you can reset the date in `~/.cache/pikaur/last_seen_news.dat`

**Comment by actionless** [comment]
if you still volunteer to work on some feature here is the good starting point: https://github.com/actionless/pikaur/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
