### ISSUE TITLE
AUR installations fail with the newest version

### ISSUE THREAD

**Issue by flocke** [actionless/pikaur#304]
I just installed pikaur on my netbook and now every time I try to install something from the AUR it fails (see log below). I use pikaur on my main system regularly and never had a problem like this before, so I assume something broke in the recent update (which I have not yet installed on my main system).

The log below is from pikaur-git but the same thing happens with the release version.

##### pikaur version:
```
[root@GLaDOS pikaur-git]# pikaur -Vq
Pikaur v1.3.0.1.r7.g701f3a4
Pacman v5.1.1 - libalpm v11.0.1

```

##### Attached log:
```
[root@GLaDOS pikaur-git]# pikaur -S flat-remix-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 flat-remix-git                                             -> r186.f65efbf3-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
Can't clone 'flat-remix-git' in '/root/.local/share/pikaur/aur_repos/flat-remix-git' from AUR:

Running as unit: run-u189.service
fatal: could not create leading directories of '/root/.local/share/pikaur/aur_repos/flat-remix-git': Permission denied
Finished with result: exit-code
Main processes terminated with: code=exited/status=128
Service runtime: 35ms

:: Try recovering?
[c] git checkout -- '*'
[r] remove dir and clone again
[s] skip this package
[a] abort
> a
```

**Comment by actionless** [comment]
please try with `pikaur-git` now

**Comment by flocke** [comment]
It still fails.

The directories under `/root/.local/share/pikaur/aur_repos/` do exist, but they are owned by `root`, which I assume is a problem for the build user that systemd creates. They also already existed before your last commit.

**Comment by actionless** [comment]
thanks for testing, i've reverted tht change for dynamic users

**Comment by flocke** [comment]
That did it, it's working again. Thank you.
