### ISSUE TITLE
Sync operations not displaying file sizes before confirmation

### ISSUE THREAD

**Issue by qtlis** [actionless/pikaur#311]
```
pikaur -Vq
Pikaur v1.3.1
Pacman v5.1.1 - libalpm v11.0.1
```

`pikaur -S` operations do not tell the user how large the download or the installed packages are going to be. Only after confirming does Pacman briefly show that information:

 ```
pikaur -S chromium
Reading repository package databases...
Reading local package database...

:: Repository package will be installed:
 extra/chromium                                             -> 69.0.3497.100-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y

resolving dependencies...
looking for conflicting packages...

Package (1)     New Version      Net Change  Download Size

extra/chromium  69.0.3497.100-1  164.59 MiB      46.16 MiB

Total Download Size:    46.16 MiB
Total Installed Size:  164.59 MiB

[…]
```

Compare with Pacman and Pacaur which show size information first (when possible), then ask for confirmation:

```
pacaur -S chromium
resolving dependencies...
looking for conflicting packages...

Package (1)     New Version      Net Change  Download Size

extra/chromium  69.0.3497.100-1  164.59 MiB      46.14 MiB

Total Download Size:    46.14 MiB
Total Installed Size:  164.59 MiB

:: Proceed with installation? [Y/n]
```

Moreover, `pikaur -R` behaves like the latter, which is an odd inconsistency:

```
pikaur -Rsc ktorrent
checking dependencies...

Package (5)  Old Version  Net Change

kparts       5.50.0-1      -1.85 MiB
kross        5.50.0-1      -1.79 MiB
libktorrent  2.1-1         -2.95 MiB
qca          2.1.3-1       -2.92 MiB
ktorrent     5.1.1-1      -11.72 MiB

Total Removed Size:  21.24 MiB

:: Do you want to remove these packages? [Y/n]
```

**Comment by iamironz** [comment]
+1
Is it really hard to implement?

**Comment by agalileev** [comment]
> Is it really hard to implement?

A few months ago I investigated this issue. I found that in all cases there is `pacman` package size output, not by pikaur.

When you type `pikaur -S <package>`, pikaur just show you list of the packages will be installed and ask for confirmation. If you confirm, pikaur pass all info to pacman with `--noconfirm` option, which in its turn show the packages size and do not ask for confirmation twice. But if you type `pikaur -R <package>` command, pacman is called immediately without `--noconfirm` option, show you total removed size and then stop to ask for confirmation.

I don't know how pacaur works,  but I think that it also simply passes parameters to pacman.

Pikaur use "InstallInfo" object as a container for package parameters, but there is no package size among them. I don't know how to implement the interaction with official repositories and AUR to fetch package size info (I do not have enough knowledge on this quesstion). So you can feel free to use my findings to contribure to the project :-)

**Comment by actionless** [comment]
> AUR to fetch package size info

this one not possible, aur couldn't know the resulting size of the package built from pkgbuild
