### ISSUE TITLE
Request: Ignore option in config

### ISSUE THREAD

**Issue by ImNtReal** [actionless/pikaur#312]
```
pikaur -Vq
Pikaur v1.3.1
Pacman v5.1.1 - libalpm v11.0.1
```
It would be helpful to have an option to ignore packages from the config file like the IgnorePkg option in pacman.conf

**Comment by actionless** [comment]
why can't you use IgnorePkg from pacman's config itself?

**Comment by ImNtReal** [comment]
I would rather not build an AUR package that I'm ignoring.

**Comment by actionless** [comment]
why can't you use IgnorePkg from pacman's config itself?

**Comment by ImNtReal** [comment]
I didn't realize pikaur honored that setting. I'll close this out, but it might not be a bad idea to mention that under the documentation about the --ignore switch.

**Comment by actionless** [comment]
if there are any pacman.conf options which are not honored please open a new issues for them
