### ISSUE TITLE
sudo timed out reading password

### ISSUE THREAD

**Issue by rihardsk** [actionless/pikaur#327]
```
pikaur -Vq
Pikaur v1.3.4
Pacman v5.1.1 - libalpm v11.0.1
```

When updating a large number of AUR packages it's often the case that i leave `pikaur` doing it's thing in the background and do something else while it builds everything. The problem is that i might miss the exact moment when `pikaur` asks me for the sudo password and it times out
```
pacman -Syua
# stuff happens, i go get some tee, come back and:
sudo: timed out reading password
```
and then i have to redo **everything**.

Please add a configuration option to make `pikaur` display a prompt every time before asking for a sudo password to ensure that the user is there when that happens.

[See this comment](https://github.com/kitsunyan/pakku/issues/16#issuecomment-395369391) where the same thing is discussed in regards to `pakku`.

**Comment by actionless** [comment]
please attach the full log, it doesn't make sense to me without extra details, because in case of timed out sudo password pikaur should show prompt "Do you want to retry [y/n]"

**Comment by rihardsk** [comment]
Unfortunately i don't have the original output anymore. I tried to replicate what happened by updating a few packages and suspending the process with Ctrl-z and then resuming so that the sudo password would time out, but now everything seems to be working as expected - it showed the prompt again and i was able to install everything.

Maybe the thing that was different was that i suspended my PC in the middle of `pikaur` building stuff and that somehow messed things up. I'll post some more details if i have any luck replicating the issue this way.

**Comment by actionless** [comment]
feel free to reopen if you'll have more data

thanks for trying anyway!
