### ISSUE TITLE
Handling inconsistent .SRCINFO?

### ISSUE THREAD

**Issue by jjgalvez** [actionless/pikaur#329]
how do I make pikaur install dependencies when building a package from the AUR? Trying to install a package form AUR I keep getting an dependency not met error. How do I make it resolve these error?
Thanks in advance

**Comment by actionless** [comment]
please report your issue following issue template

**Comment by jjgalvez** [comment]
```
pikaur -Vq

Pikaur v1.3.4
Pacman v5.1.1 - libalpm v11.0.1


```


##### [Optional] Prerequisites:



##### Attached log:

```
pikaur -S my-precious-package

pikaur -S qownnotes
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 qownnotes                        18.12.5-1       -> 19.1.0-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> 
looking for conflicting AUR packages...
Do you want to see build files diff for qownnotes package? [Y/n] 
n
Do you want to edit PKGBUILD for qownnotes package? [y/N] 


:: Starting the build:
==> Making package: qownnotes 19.1.0-1 (Tue 01 Jan 2019 01:57:06 PM EST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> qt5-websockets
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.

Command 'makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
------------------------
[s] skip building this package
[a] abort building all the packages
> 


```
Should't required packages be installed by default?

**Comment by actionless** [comment]
it have inconsistent .SRCINFO: https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=qownnotes

**Comment by actionless** [comment]
before the AUR package itself will be fixed you can choose to edit PKGBUILD and add some meaningless line (like `echo`), that will force pikaur to generate new .SRCINFO for manually edited PKGBUILD

**Comment by jjgalvez** [comment]
Thank you, I'll ping the package author that the .srcinfo needs updating. Next time I will check that before I post an issue.




Get Outlook for Android







On Tue, Jan 1, 2019 at 2:19 PM -0500, "Yauhen Kirylau" <notifications@github.com> wrote:












before the AUR package itself will be fixed you can choose to edit PKGBUILD and add some meaningless line (like echo), that will force pikaur to generate new .SRCINFO for manually edited PKGBUILD

**Comment by actionless** [comment]
no problem, thanks for reporting anyway!
