### ISSUE TITLE
Pointless sudo password challenge

### ISSUE THREAD

**Issue by thx1111** [actionless/pikaur#331]
Pikaur v1.3.5
Pacman v5.1.1 - libalpm v11.0.1

Running for the first time on archlinux32, pikaur generates a sudo password challenge, even though the user is already in /etc/sudoers, and sudo is working normally.  For instance:

````
$ pikaur -S my-precious-package

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for james:
````

This seems either pointless or broken.  Is pikaur suppose to do this?  Any thoughts or suggestions?

**Comment by actionless** [comment]
you mean it's asking for your password more than once? or what is the problem here?

**Comment by thx1111** [comment]
I don't understand how this is asking for the password at all.  In this case, the sudo user has been configured with "NOPASSWD" - which I should have mentioned.

And then, entering a password, and running pikaur a second time, there is no sudo password challenge.  Has pikaur stored the history of a successful password entry?

**Comment by actionless** [comment]
> with "NOPASSWD" - which I should have mentioned.

and if you open new terminal and type there `sudo -v` if it's asking you for a password?

**Comment by thx1111** [comment]
Hmm - on this machine, yes it does.  And on other machines that don't have a problem with pikaur, no.

But then, other sudo operations, such as `chown` on files owned by root, do not ask for a password.

As far as I know, the sudo configuration is the same on all these machines.  Did I mess-up?  Or, would this be a problem with sudo?  Do you know what's going on here?

**Comment by actionless** [comment]
>  And on other machines that don't have a problem with pikaur, no.

you mean on other machines pikaur works as expected with NOPASSWD?

**Comment by thx1111** [comment]
Yes - for both `pikaur` and `sudo -v`.  This one machine is old, i686, running Arch Linux 32.  The other machines are newer, 64 bit.  Maybe something is different in the code base, compared to the x86_64 packages?

**Comment by actionless** [comment]
from pikaur side -- no differences regarding architecture

**Comment by actionless** [comment]
there could be several reasons, i think the best place to ask could be arch-x32 community, since the issue is reproducing only there
