### ISSUE TITLE
Pikaur Freezes momentarily when issuing -Syu

### ISSUE THREAD

**Issue by bmccorm2** [actionless/pikaur#332]
I'm probably doing something wrong, but when i issue a pikaur -Syu, it hangs for ~5 sec, then queries the repos and does its thing.  If i immediately re run, it will not wait five seconds but immediately check the repos for updates.  This always happens if i open a fresh terminal and issue the command.  If i hit ctrl-c during the freeze, the output is showed in the screenshot below.

Thanks!

![initialpause](https://user-images.githubusercontent.com/11781610/51065413-e9fc2c80-15c1-11e9-9ba4-191101510b04.png)
![canceloperation](https://user-images.githubusercontent.com/11781610/51065420-f4b6c180-15c1-11e9-9d38-3f38fb1caf07.png)

**Comment by actionless** [comment]
i think it's systemd dynamic user is being initialized (though idk why it happens so long for you)

is the same happens if you run pikaur without sudo?

**Comment by bmccorm2** [comment]
You are 100% right.  If i run without sudo it starts to run as soon as I type my password in.  Well i'll go down this other rabbit hole then :)

Also - great work on this tool.  It is awesome!

**Comment by actionless** [comment]
you could double-check if running any command using sd dynamic users directly causing the same effect:
 `systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=test_dyn_users -E HOME=/tmp echo test`

**Comment by bmccorm2** [comment]
That output seems normal.  I did put the pikaur command (/usr/bin/pikaur) in the sudoers file so it does not require a password (because I am lazy :)  Maybe that has something to do with it?
![image](https://user-images.githubusercontent.com/11781610/51074775-47cf5980-1640-11e9-996a-2d70fcc252cb.png)

**Comment by actionless** [comment]
then please try running `sudo -v` in the described test scenario

**Comment by bmccorm2** [comment]
In a fresh terminal, I tried `sudo -v` and then `sudo pikaur -Syu`.  Still the same result :/

**Comment by actionless** [comment]
but when you hit Ctrl+C it's always inside `create_dirs` function?

**Comment by bmccorm2** [comment]
Yes correct.  Same as that initial screenshot I uploaded.

**Comment by actionless** [comment]
that's really weird, you can see here not much going on:

https://github.com/actionless/pikaur/blob/6d7d1580aafff95d6dd42026f79c56ca446810e4/pikaur/main.py#L285-L299

**Comment by bmccorm2** [comment]
What about the subprocess.py file?  

Any way i could add any logging to these files to get a better glimpse of what is happening?

**Comment by actionless** [comment]
subprocess is quite straight-forward, it just waiting the command to finish

i guess you could try recreating minimal example without pikaur involved, as a python file:

```python
import os
import subprocess
from typing import List


CACHE_ROOT='/var/cache/test_dyn_users'

def spawn(args):
    result = subprocess.Popen(args)
    result.communicate()
    return result


def running_as_root() -> bool:
    return os.geteuid() == 0


def create_dirs() -> None: 
    if running_as_root(): 
        # Let systemd-run setup the directories and symlinks 
        true_cmd = isolate_root_cmd(['true']) 
        result = spawn(true_cmd) 
        if result.returncode != 0: 
            raise Exception(result) 
        # Chown the private CacheDirectory to root to signal systemd that 
        # it needs to recursively chown it to the correct user 
        os.chown(os.path.realpath(CACHE_ROOT), 0, 0) 
    if not os.path.exists(CACHE_ROOT): 
        os.makedirs(CACHE_ROOT) 

def isolate_root_cmd(cmd: List[str], cwd=None) -> List[str]: 
    if not running_as_root(): 
        return cmd 
    base_root_isolator = [ 
        'systemd-run', '--pipe', '--wait', 
        '-p', 'DynamicUser=yes', 
        '-p', 'CacheDirectory=test_dyn_users', 
        '-E', 'HOME=/tmp', 
    ] 
    if cwd is not None: 
        base_root_isolator += ['-p', 'WorkingDirectory=' + cwd] 
    return base_root_isolator + cmd 

create_dirs()

```

**Comment by bmccorm2** [comment]
Ok i tried that and here is the output.  Sorry I'm not sure what to look for in here.
![1](https://user-images.githubusercontent.com/11781610/51081417-4f2c4c80-16ac-11e9-8e46-c9e69eef67f2.png)

**Comment by actionless** [comment]
run it as root

**Comment by bmccorm2** [comment]
Sorry it works fine :/

You think it is something wrong in my /etc/suoders file?  I have this line for this particular user: `bryan ALL=(ALL) NOPASSWD:/usr/bin/pacman,/usr/bin/pikaur`

![1](https://user-images.githubusercontent.com/11781610/51082040-d7661e00-16bb-11e9-97d4-29d2bb0108fa.png)

**Comment by actionless** [comment]
this is even more weird now -- create_dirs() is executed before pikaur splitted himself into multiple threads, so nothing more is running at the same moment as that function which is extracted into test.py

this could sound stupid, but please try just to exclude the last possibility i have in mind:

in test example rename both occurrences of `test_dyn_users` to `pikaur` and try again

**Comment by actionless** [comment]
exactly!

now please:
```
sudo du -sh /var/cache/private/pikaur/
sudo find /var/cache/private/pikaur/  | wc -l
```

**Comment by bmccorm2** [comment]
There you go :)

I'm guessing I need to clean that out and it will work like a charm.

![1](https://user-images.githubusercontent.com/11781610/51096140-97fd0780-1777-11e9-952d-1a634cdb94db.png)

**Comment by actionless** [comment]
yeah, either clean them up with `pikaur -Scc` or just don't use sudo

**Comment by actionless** [comment]
makepkg can run only from non-root user

**Comment by actionless** [comment]
if you have some good wording in mind, feel free to append the information learned from this ticket into FAQ section

**Comment by bmccorm2** [comment]
I'd be happy to write something up (I could also help you write up other things too if you want). Do I just write it up and email to you? I don't think i would be able to do a commit would I?

January 13, 2019 9:34 PM, "Yauhen Kirylau" <notifications@github.com (mailto:notifications@github.com?to=%22Yauhen%20Kirylau%22%20<notifications@github.com>)> wrote:
	if you have some good wording in mind, feel free to append the information learned from this ticket into FAQ section

**Comment by actionless** [comment]
you can edit it right from github UI:

![2019-01-15--1547507796_1021x167_scrot](https://user-images.githubusercontent.com/1655669/51147547-dcad9f00-185a-11e9-8618-d62dc73e029c.png)

btw, man page is generated from readme, so changes made to that text also will be displayed when you do `man pikaur`

**Comment by bmccorm2** [comment]
Sorry was on vacation....but I went ahead and added this to the README.md.

January 14, 2019 4:17 PM, "Yauhen Kirylau" <notifications@github.com (mailto:notifications@github.com?to=%22Yauhen%20Kirylau%22%20<notifications@github.com>)> wrote:
	you can edit it right from github UI:

	 (https://user-images.githubusercontent.com/1655669/51147547-dcad9f00-185a-11e9-8618-d62dc73e029c.png)

	btw, man page is generated from readme, so changes made to that text also will be displayed when you do man pikaur

**Comment by actionless** [comment]
unfortunately i still can't see your pull request

you can create it by this link (https://github.com/actionless/pikaur/compare/master...bmccorm2:patch-1)

so i did it myself: https://github.com/actionless/pikaur/pull/344
