### ISSUE TITLE
pikaur hangs after build failed, then sudo: unable to read password: Input/output error

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#336]
```
pikaur -Vq
Pikaur v1.3.6.r4.g9a4f09d
Pacman v5.1.2 - libalpm v11.0.2
```

##### [Optional] Prerequisites:

I didn't notice that the download failed and therefore some time passed before I returned to the terminal where I only looked at the password prompt and entered my password. After the first character (`b` is not actually the first character of my password, pikaur printed the usual output when building fails and then hang. I cancelled with ctrl+c and get my terminal prompt together with a sudo error.

##### Attached log:

```
pikaur -S linux-ck

...

==> ERROR: Failure while downloading http://ck.kolivas.org/patches/4.0/4.20/4.20-ck1/patch-4.20-ck1.xz
    Aborting...
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
------------------------
[s] skip building this package
[a] abort building all the packages
>  
   sudo: timed out reading password
                                   [sudo] password for user: 
sudo: timed out reading password
[sudo] password for user: 
sudo: timed out reading password
[sudo] password for user: 
sudo: timed out reading password
[sudo] password for user: 
sudo: timed out reading password
[sudo] password for user: 
sudo: timed out reading password
[sudo] password for user: 
sudo: timed out reading password
[sudo] password for user: b

Can't build 'linux-ck'.

Failed to build following packages:
linux-ck
linux-ck-headers
^C[:~] 1 $ 
sudo: unable to read password: Input/output error
```

**Comment by SpineEyE** [comment]
sudoloopinterval = 1

**Comment by actionless** [comment]
that's weird, when it's set to 1 -- that means what `sudo -v` command runs every second in the background so it shouldn't ask you for the password anymore after first entry right on pikaur start

**Comment by actionless** [comment]
can you reproduce the issue? for example by modifying some PKGBUILD to have wrong URL

**Comment by SpineEyE** [comment]
interesting, I can't reproduce it right now... Might be that my pc was in a weird inconsistent state, I remember that my wifi connection failed for some weird reason and I had to reactivate it... Whatever, if it happens again, I will post again

**Comment by actionless** [comment]
thanks, please create a new ticket referencing to this one if you'll get more info (i've only today learned what you can't reopen your issue on github :-) , before i was writing to people "reopen if needed" )
