### ISSUE TITLE
Searching with pikaur seg faults

### ISSUE THREAD

**Issue by blacktav** [actionless/pikaur#338]
```
pikaur -Vq

```
Pikaur v1.3.6
Pacman v5.1.2 - libalpm v11.0.2

##### Attached log:

```
pikaur -S my-precious-package
```
```
pikaur -Ss pikaur
Searching... [Segmentation fault (core dumped)
```
Searching with pikaur seg faults

**Comment by actionless** [comment]
update your pyalpm: https://github.com/actionless/pikaur/issues/337
