### ISSUE TITLE
Pikaur doing extra unecessary work for -Sy (only)

### ISSUE THREAD

**Issue by troyengel** [actionless/pikaur#339]
```
$ pikaur -Vq
Pikaur v1.3.6
Pacman v5.1.2 - libalpm v11.0.2
```
Very minor issue that is not really a bug but design I think. When running `pikaur -Sy` to only update the database indexes, Pikaur continues to load the databases off disk if they were updated (if you have a slow rotating HDD and many packages, it can take some time) then exits with "Nothing to do". (`pacman` just exits).

```
$ pikaur -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date

Reading repository package databases...
Reading local package database...
:: Nothing to do.
```
vs.
```
# pacman -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
```

* https://github.com/actionless/pikaur/blob/master/pikaur/pacman.py#L529

I _think_ it is because there is a call to `retry_interactive_command_or_exit()` embedded within the `refresh_pkg_db()` method, "fixing" it would require a small design change to separate them from each other. Maybe it's not something you want to do and we just leave it, too much work?

This of course makes perfect sense when combined with other options (`-Syu`, `-Sys`, etc.), it's only extra work when only `-Sy` is used on the CLI. Maybe if `refresh_pkg_db()` checks if only two arguments are sync+refresh (no others) it skips running `retry_interactive_command_or_exit()` as a simple solution?

**Comment by actionless** [comment]
and how `-Sc` related to `-Sy` or it's a typo?

**Comment by troyengel** [comment]
sorry, typo! It was early and I was still drinking coffee. :)

**Comment by actionless** [comment]
thanks for reporting!
