### ISSUE TITLE
Pikaur hangs on installing discord

### ISSUE THREAD

**Issue by targodan** [actionless/pikaur#34]
I installed pikaur via pacaur `pacaur -S pikaur-git`. When I tried to install discord via `pikaur -S discord` it requested the dependencies libc++ and libc++abi from aur. After saying no to viewing any PKGBUILDs pikaur went up to 100% CPU usage and stayed that way for hours until I killed it. No console output while that was the case.

**Comment by actionless** [comment]
problem can be reproduced also with just `./pikaur.py -S libc++` it seems something is wrong with the package:

here in the PKGBUILD [1] i see what package `libc++` depends on `libc++abi` [2] however i don't see any traces of dependency `libc++abi` on `libc++`

[1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libc%2B%2B
[2] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libc%2B%2B#n63

**Comment by actionless** [comment]
mb when building a splitted package aur adds basepkg automatically to depends of subpackage

**Comment by targodan** [comment]
Can't say anything about that. But when I used `pacaur -S discord` it installed libc++ and libc++abi and then discord with no problems.

**Comment by actionless** [comment]
i think my suggestion from the previous comment would solve the issue but maybe somebody around will know the right behavior for such case, if not -- later on i'll have a look to pacaur/cower to see how that's handled there

**Comment by actionless** [comment]
the problem wasn't related to deps resolving so it was quite clear to fix without getting more info

**Comment by targodan** [comment]
Great stuff. Thanks for solving this so quickly! 😄
