### ISSUE TITLE
`pikaur -Sw` doesn't do what I expect it to do 

### ISSUE THREAD

**Issue by cswl** [actionless/pikaur#343]
I build my AUR packages on a virtual machine. Hence I dont need to install the actual built package on the Virtual machine.

So I tried to use `pikaur -Sw` but it seems to install then remove the dependencies of the package itself.  

I dont mind the dependencies and make dependencies lingering on my virtual machine.. So an option or a new command be added to address this?

##### Version
```
pikaur -Vq
Pikaur v1.3.6.r7.g2432899
Pacman v5.1.2 - libalpm v11.0.2
```

##### Attached log:

Log: https://paste.pound-python.org/show/ROiOVqA928bkKhS1csvo/

**Comment by actionless** [comment]
i don't see any problem in your log

so i'll just ask you what is your expected result?

**Comment by cswl** [comment]
It installed all the deps packages from repo here.. here.. 
```
Packages (28) alsa-lib-1.1.8-1  flac-1.3.2-2  js52-52.9.0-2
              libasyncns-0.8+3+g68cd5af-2  libice-1.0.9-2  libogg-1.3.3-3
              libpulse-12.2-2  libsm-1.2.3-1  libsndfile-1.0.28-2
              libsoxr-0.1.3-1  libvorbis-1.3.6-1  libx11-1.6.7-1
              libxau-1.0.8-3  libxcb-1.13.1-1  libxdmcp-1.1.2-2
              libxext-1.3.3-2  libxfixes-5.0.3-2  libxi-1.7.9-2
              libxtst-1.2.3-2  orc-0.4.28-1  polkit-0.115+24+g5230646-1
              rtkit-0.11+10+g493a135-1  speexdsp-1.2rc3-3  tdb-1.3.16-1
              webrtc-audio-processing-0.3.1-1  xcb-proto-1.13-2
              xorgproto-2018.4-1  pulseaudio-12.2-2

Total Installed Size:  86.10 MiB

:: Proceed with installation? [Y/n] Y
```

Then it removed them all back again.. 
```
Packages (28) alsa-lib-1.1.8-1  flac-1.3.2-2  js52-52.9.0-2
              libasyncns-0.8+3+g68cd5af-2  libice-1.0.9-2  libogg-1.3.3-3
              libpulse-12.2-2  libsm-1.2.3-1  libsndfile-1.0.28-2
              libsoxr-0.1.3-1  libvorbis-1.3.6-1  libx11-1.6.7-1
              libxau-1.0.8-3  libxcb-1.13.1-1  libxdmcp-1.1.2-2
              libxext-1.3.3-2  libxfixes-5.0.3-2  libxi-1.7.9-2
              libxtst-1.2.3-2  orc-0.4.28-1  polkit-0.115+24+g5230646-1
              pulseaudio-12.2-2  rtkit-0.11+10+g493a135-1
              speexdsp-1.2rc3-3  tdb-1.3.16-1
              webrtc-audio-processing-0.3.1-1  xcb-proto-1.13-2
              xorgproto-2018.4-1

Total Removed Size:  86.10 MiB

:: Do you want to remove these packages? [Y/n] Y
```

That is just waste of time.. esp if I plan to upgrade the AUR package to next release
What I'm saying is it should only install the required packages to `make` it.. 

And Im fine with the repo pacakges being installed.. what I dont want is the AUR package itself being installed..

If the current way is what you wanna keep for `-w`
Maybe we could add another flag for just `make`ing the package?

**Comment by actionless** [comment]
how do you expect a package to be built without installing its dependencies?

**Comment by cswl** [comment]
The problem isnt with installing the dependencies it's removing them after the AUR package is built.

Currently `-Sw` implies dont install Repo packages too in that sense..
What I wanted was `install  repo dependencies to build this AUR package` but dont install the AUR package itself

**Comment by actionless** [comment]
> but dont install the AUR package itself

show me in the log what makes you think it got installed
