### ISSUE TITLE
Running silenced breaks input

### ISSUE THREAD

**Issue by es20490446e** [actionless/pikaur#346]
For example, after running:
`pikaur --sync --refresh --sysupgrade --noconfirm &> /dev/null`

The terminal no longer shows what you type, although it still responds to it.

**Comment by es20490446e** [comment]
Workaround (which likely suggests the fix):
```
saved=`stty --save`
stty -echo
pikaur --sync --refresh --sysupgrade --noconfirm &> null
stty ${saved}
```

**Comment by es20490446e** [comment]
@actionless Do you know why [TTYRestore.restore](https://github.com/actionless/pikaur/blob/master/pikaur/pikspect.py#L44) has commented elements?

**Comment by actionless** [comment]
leftovers from experimenting with it, not intentional

**Comment by es20490446e** [comment]
Taking the job 👍

**Comment by actionless** [comment]
thanks, good luck with that!

**Comment by es20490446e** [comment]
Sorry, but I won't be able to implement this. I'm overloaded.

**Comment by es20490446e** [comment]
This is fixed.

**Comment by actionless** [comment]
thanks for update!

**Comment by es20490446e** [comment]
My pleasure.
