### ISSUE TITLE
--devel should follow -u/-uu behavior on downgrade policy

### ISSUE THREAD

**Issue by otaj** [actionless/pikaur#358]
Hi, I have a slightly weird situation going on. There is a devel package (`gnome-shell-extension-system-monitor-git`) whose upstream repo is not really active, the only thing happening there are issues from users who complain when it's broken with almost every new release of gnome-shell.

Somebody forked the repo to make a fix already and so I download AUR Build files manually, changed the git source URL to fixed repo, because I know it will take forever for the upstream repo to merge it and built a new version of the package for myself. I left the name of the package the same, for when the upstream will be actually updated (or merged).

However, when I do `pikaur -Syu --devel --needed`, it also tries to "update" this particular package without a problem, even though underlying pacman is complaining about downgrading.

Yes, I know, it is a non-standard situation, which should not occur, however, "upgrading" devel package when the pkgver says it has lower version should not occur as well. The proposed solution is to check whether new pkgver is higher than the installed one, not only whether it differs (as is obviously how it is implemented now)

See the log below.

```
otaj@otaj-ntb: pikaur -Q gnome-shell-extension-system-monitor-git                                                                                                                                                                           
gnome-shell-extension-system-monitor-git 905.dcad49f-1
```

```
otaj@otaj-ntb: pikaur -Syu --devel --needed                                                                                                                                                                                                
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: AUR packages will be installed:
 gnome-shell-extension-system-monitor-git  905.dcad49f-1    -> devel

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: Downloading the latest sources for a devel package gnome-shell-extension-system-monitor-git...
:: warning: Not showing diff for gnome-shell-extension-system-monitor-git package (already reviewed)
Do you want to edit PKGBUILD for gnome-shell-extension-system-monitor-git package? [y/N] n
Do you want to edit gschemas.install for gnome-shell-extension-system-monitor-git package? [y/N] n

:: Starting full system upgrade...
 there is nothing to do
Reading local package database...
:: Package gnome-shell-extension-system-monitor-git is already built. Pass '--rebuild' flag to force the build.

loading packages...
warning: downgrading package gnome-shell-extension-system-monitor-git (905.dcad49f-1 => 900.2583911-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) gnome-shell-extension-system-monitor-git-900.2583911-1

Total Installed Size:  0.41 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                                 [----------------------------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                                               [----------------------------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                                                    [----------------------------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                                              [----------------------------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                                                            [----------------------------------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) downgrading gnome-shell-extension-system-monitor-git                                                                                     [----------------------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/2) Compiling GSettings XML schema files...
(2/2) Arming ConditionNeedsUpdate...
```

**Comment by actionless** [comment]
if you forked `gnome-shell-extension-system-monitor-git` package locally in order to change it's src url why haven't you also updated pkgname?

**Comment by otaj** [comment]
Yes, that's what I ended up doing in the end. However, I still stand behind my opinion that devel package upgrade should occur only when the new pkgver is higher than the one installed, not when it is different, which is what is happening right now

**Comment by actionless** [comment]
but i see from your log what 905 is bigger than 900

**Comment by otaj** [comment]
905 was already installed on the system. I asked pikaur to sync and upgrade needed devel packages (-Syu --devel --needed), it showed this line
```
 gnome-shell-extension-system-monitor-git  905.dcad49f-1    -> devel
```
which was expected. However, then it downloaded the sources to ~/.cache/pikaur/build, checked the pkgver, found out it was 900.2583911-1 and went on with building a package with a lower version because it was not matching the version installed so it thought it is necessary to update. Which I believe is not what should happen

**Comment by actionless** [comment]
now i recalled why it was implemented like that (to check `vercmp == 0`):

1) upstream/packager could change versioning schema (that was practically happening with quite a number of aur packages);
2) upstream force-pushed to remove some very wrong breaking commits (instead of doing revert).

**Comment by otaj** [comment]
Okay, that actually does make a lot of sense. Thanks for the info on why it is happening, I was quite confused by such behavior

**Comment by actionless** [comment]
do you think it's worth adding it to FAQ?

**Comment by otaj** [comment]
Might be.

BTW, just noticed another "unintuitive" behavior, pikaur does not respect IgnoreGroup for AUR packages. When I think about the reason why that would be, it once again does make sense, when the package is actually rebuilt from AUR, group is usually lost (I tend to put groups=('mods') to all packages where I modify PKGBUILD), but first time I encountered it, I was surprised.

**Comment by actionless** [comment]
you mean even if you building manually makepkg overwriting "groups" of created package?

**Comment by otaj** [comment]
No, in that case, of course, it is not overwritten.
But let's see a scenario - I manually download a package from AUR, find I need to slightly change its PKGBUILD, do so, put groups=('mods'), in there in the hope that when I do full system upgrade, this package won't be upgraded, and I will be instead notified by a warning, that a new version is available so that I can again change the PKGBUILD accordingly (which could be in the case of changed PKGBUILD matter of only changing source and shasums). But, when I do system upgrade, pikaur does not recognize, that installed package is in IgnoreGroup and offers to update it. And if you are on "autopilot" (yes, update all, etc.. I know it's bad and I should review it, but often I don't have time to do so), you easily miss it and are wondering, why is something broken.

**Comment by actionless** [comment]
so you  mean IgnoreGroup is just not working, other part of your story is just your steps to reproduce it, right?

yeah ,i am not sure what IgnoreGroup is implemented at all. could you please create a new ticket for this?

**Comment by otaj** [comment]
Yes, I will create a new issue.

**Comment by actionless** [comment]
thanks!

**Comment by Morganamilo** [comment]
>upstream/packager could change versioning schema 

This is what epochs are for.

>upstream/packager could change versioning schema 

No upstream should ever do that. If they do then that's on them and again epoch could solve this.

> had to force-push because of leaked credentials in some config files.

If this happens then the correct thing to do is invalidate the old creds and make new ones. Not try to cover up.

**Comment by actionless** [comment]
@Morganamilo 

but examples above all real

and any of them would result in ignored update if vercmp would be checking for `>`, not `!=`

if you have any better suggestion please share it

**Comment by Morganamilo** [comment]
The solution is to contact the AUR package maintainer and tell them to use epoch or a different pkgver format. I don't see why an AUR helper should go against how vercmp works just because some people may do things wrong.

**Comment by actionless** [comment]
but it's using vercmp to check if it returns 0 or not

the goal of --devel update in pikaur is to check if upstream revision is different from currently installing and if so — build it

**Comment by actionless** [comment]
however it could make sense to make an option for both, like in pacman `-Su` vs `-Suu`

**Comment by Morganamilo** [comment]
A pkgver function should always return a higher pkgver when new commits come in though.

Yes I think `-Su[u]` is exactly the way to go.

**Comment by actionless** [comment]
you mean to inherit behavior of --devel based of how many `-u` was passed?

**Comment by Morganamilo** [comment]
Yes.

>the goal of --devel update in pikaur is to check if upstream revision is different from currently installed and if so — build it

To me I think this should be.

>the goal of --devel update in pikaur is to check if upstream revision is **newer** from currently installed and if so — build it

Then use the extra -u to enable downgrades just like pacman.

**Comment by actionless** [comment]
i think also it could be nice to have a behavior case like `pikaur -Syu --devel --devel`, so normal packages will be upgraded as usually, but devel ones will be upgraded/downgraded
