### ISSUE TITLE
odd failures - pikaur vs pacaur - arch 32 - grub-git

### ISSUE THREAD

**Issue by thx1111** [actionless/pikaur#365]
pikaur -Vq

Pikaur v1.4.1
Pacman v5.1.3 - libalpm v11.0.3

Odd things - on Arch Linux 32, pikaur always asks for a password, even though the user is configured "NOPASSWD" in /etc/sudoers.  No such problem when running pacaur.

Building grub-git with pikaur fails with:
...
./bootstrap: done.  Now you can run './configure'.
mkdir: cannot create directory ‘/var/build/grub-git/src/grub/build_i386-pc’: File exists
==> ERROR: A failure occurred in build().
...
Again, no such problem when running pacaur.  Sorry - I'm not sure where the problem is.

**Comment by thx1111** [comment]
Hmm - pikaur will build grub-git again - only the *first time* - after removing *both* the build dir *and* ~/.cache/pikaur/build/grub-git/.  Also, if pacaur is used to build grub-git after pikaur has already been used to build grub-git, such that the build directory from the pikaur build still exists, then the pacaur build will also fail with the same error as with pikaur.

**Comment by actionless** [comment]
pikaur doesn't do anything with sudo except for just running `sudo -v`, you can turn it off in the config, see manpage/readme

regarding grub-git -- it's the way how grub-git behave, you can workaround their problem in pikaur by pressing `d` when build fails

**Comment by thx1111** [comment]
> pressing d when build fails

No, that does not work.  `~/.cache/pikaur/build/grub-git/` must be removed manually as well.  Try it.

The bigger issue here is that, while "workarounds" might be fine "after the fact", of actually already knowing the workaround, this cavalier attitude is "presuming the conclusion", that the user *already* knows about the "workaround", when, in fact, many hours of "trial and error" are really required to "discover" this workaround.  In practice, most users will not take the time or go to the trouble, with the practical effect being that pikaur, as a tool, is just "junk".

I encourage you to take this issue more seriously.

**Comment by actionless** [comment]
those options were added for a reason

i commiserate what you do "trial and error" instead of reading manpage
