### ISSUE TITLE
Change SRCDEST, BUILDDIR and PKGDEST in pikaur.conf

### ISSUE THREAD

**Issue by JulioJu** [actionless/pikaur#369]
Hi !

According to FAQ and the manpage, actually to change the folder where packages are  built and the cache directory, we must change `makepkg.conf`. Maybe it's not cool to change this file because it changes the configuration globally for makepkg. If we choose to use `makepkg -si` (without use pikaur) the default configuration of makepkg is changed and it's not very cool. 

With yaourt, we could change this directory in the config file. My goal is to not build on `~/.local/share/pikaur/build` but in `/tmp` (faster), and export to pacman cache. This feature are provided very easily with Yaourt.

Could we have that with pikaur, with pikaur.conf ;-) ?

From https://archlinux.fr/man/yaourtrc.5.html

> TMPDIR="/tmp"
> Specify the folder to save temporary files (default is /tmp).

> EXPORT=0
> Export built package to $EXPORTDIR or, if not defined to $PKGDEST (see makepkg.conf(5)). EXPORT=2 exports all built packages to pacman cache directory (see pacman.conf(5)).

> EXPORTSRC=0
> Export sources to $EXPORTDIR or, if not defined to $SRCPKGDEST or $PKGDEST (see makepkg.conf(5)).

> EXPORTDIR=""
> Specify the folder where yaourt exports built packages + sources.

Thanks in advance !

**Comment by actionless** [comment]
setting `BUILDDIR` as env var is not working?

**Comment by JulioJu** [comment]
@actionless thanks for your answer. 

It works, but maybe Pikaur could read pikaur.conf and set this environement variable ? As it, we could have this configurations only for Pikaur, and not for `makepkg` or others aur helpers. As it, no need to manually think to set environment variable before start a build, or change makepkg.conf. Maybe it could be easy ? 

Furthermore, in the README.md you could advise to change builddir to /tmp as on Ach Linux systems [/tmp is mount on RAM (very very faster)](https://wiki.archlinux.org/index.php/Tmpfs). 

If you are not ok, I close this.

**Comment by actionless** [comment]
sorry but i see no point to reimplement makepkg features and re-write in readme the contents from arch wiki, especiaaly so obvious as using tmpfs for speeding things up

**Comment by actionless** [comment]
however if you think what current FAQ could be improved (mb by linking related arch wiki topics) -- please submit a change to the readme
