### ISSUE TITLE
Sorry, user $username is not allowed to execute '/bin/true' as root on $hostname

### ISSUE THREAD

**Issue by stupidus89** [actionless/pikaur#37]
When running a pikaur command e.g. `pikaur -S $some-program`, it will ask for my sudo password, then complain that my user is not allowed to execute `/bin/true` (which is actually true, my user is only allowed to execute pacman via sudo). Then it will ask for my password again and proceed to install `$some-program`. 

Is there a reason, why pikaur tries to execute `/bin/true` the first time around, but then works anyway the second time?

**Comment by actionless** [comment]
it's asking sudo permission to get it before build, to not ask user to enter the password after the build
