### ISSUE TITLE
Fail to update package from git repo: "not a git repository"

### ISSUE THREAD

**Issue by alberdingk-thijm** [actionless/pikaur#374]
```
Pikaur v1.4.3
Pacman v5.1.3 - libalpm v11.0.3
```

##### [Optional] Prerequisites:

* Install `lain-git` through the AUR
* After a package upgrade, attempt to update `lain-git` via `pikaur -Syu`

##### Attached log:

```
pikaur -Syu lain-git
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date

:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
Resolving AUR dependencies...

:: AUR package will be installed:
 lain-git                         1695.724c7b9-1  -> 1697.3328e73-1

:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>>
looking for conflicting AUR packages...
Do you want to see build files diff for lain-git package? [Y/n]
Do you want to edit PKGBUILD for lain-git package? [y/N]

:: Starting full system upgrade...
 there is nothing to do
:: Downloading the latest sources for a devel package lain-git...
:: error: failed to retrieve latest dev sources:
==> Making package: lain-git 1697.3328e73-1 (Sun 19 May 2019 09:59:26 AM EDT)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Updating lain git repo...
Fetching origin
==> Validating source files with md5sums...
    lain ... Skipped
==> Extracting sources...
  -> Creating working copy of lain git repo...
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
==> ERROR: Failure while updating working copy of lain git repo
    Aborting...

Do you want to proceed? [y/N]

```

So far, every time `lain-git` needs to be updated, I have to first run `pikaur -Sc` to clear its cache files and then update.
Here are the contents of `$HOME/.cache/pikaur/build/lain-git/`. Note that there is indeed no subdirectory named `.git`, although the `lain` directory contains several `git` files.
I'm not sure if the source of this issue is a misconfigured PKGBUILD for `lain-git` or something on `pikaur`'s side, but as running `pikaur -Sc` solves the problem I thought I'd post about it here.

```
ls -a
total 24K
drwxr-xr-x 7 tim tim 4.0K May 19 10:01 lain
-rw-r--r-- 1 tim tim   41 May 19 09:59 last_installed.txt
drwxr-xr-x 3 tim tim 4.0K May 12 10:25 pkg
-rw-r--r-- 1 tim tim  880 May 19 09:59 PKGBUILD
drwxr-xr-x 3 tim tim 4.0K May 12 10:25 src
-rw-r--r-- 1 tim tim  393 May 19 09:59 .SRCINFO
```

**Comment by ikselven** [comment]
The same issue occurs updating `awesome-freedesktop-git`. I've always worked around it by answering the last prompt shown in the attached log of the above comment with "y". pikaur then offers the option "delete build dir and try again", which executes successfully.

**Comment by actionless** [comment]
> I'm not sure if the source of this issue is a misconfigured PKGBUILD for lain-git

yes

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lain-git#n30


`rm` should happen inside `pkgdir`, not inside source tree

(but generally it's better to copy files by some list or at least pattern, think what patterns could be also excluding)

**Comment by actionless** [comment]
btw you also can turn off build dir caching for `-git` packages:

https://github.com/actionless/pikaur#keepdevbuilddir-default-yes

**Comment by alberdingk-thijm** [comment]
Thanks for clarifying, @actionless! I'm guessing `lain-git` and `awesome-freedesktop-git` have this same error.

**Comment by lcpz** [comment]
I updated my `PKGBUILD`s.

> `rm` should happen inside `pkgdir`, not inside source tree

@actionless Please give a reference on this.

**Comment by actionless** [comment]
`man PKGBUILD`:

```
       srcdir
           This contains the directory where makepkg extracts, or copies, all source
           files.

           All of the packaging functions defined above are run starting inside
           $srcdir

       pkgdir
           This contains the directory where makepkg bundles the installed package.
           This directory will become the root directory of your built package. This
           variable should only be used in the package() function.
```

**Comment by lcpz** [comment]
Thank you for the copy-paste, but I still can't see anything that advises against that `rm`.

Simply put, that didn't work in your logic. Now it's fixed.

**Comment by actionless** [comment]
it's not about my logic, but about `makepkg --nobuild --noprepare --nocheck --nodeps` when running it when source directory exists but it became invalid git repo
