### ISSUE TITLE
Query all packages from AUR or official repos

### ISSUE THREAD

**Issue by krobelus** [actionless/pikaur#375]
```
pikaur -Vq
Pikaur v1.4.3
Pacman v5.1.3 - libalpm v11.0.3

```

I expect `pikaur -Q --repo` and `pikaur -Q --aur` to output all installed packages from the official repos and the AUR respectively.
Instead it tells me that
```
:: error: option '--repo' can't be used without '--sysupgrade'.
```
and if I add `--sysupgrade`, it only lists upgradeable packages.
Is this expected behavior?
Thank you

**Comment by actionless** [comment]
see https://github.com/actionless/pikaur/issues/173#issuecomment-389792722

**Comment by actionless** [comment]
to elaborate a bit more on it: once package got installed from AUR you can't determine if it was installed from AUR or it's just some other foreign package which you built manually (since there is no real difference between one and another)

**Comment by ikselven** [comment]
@krobelus:
Just a quickshot idea: If you add all packages you install from AUR to the package group "aur" by editing their PKGBUILDs, you'll be able to query them using `pacman -Qg aur`.

Obvious disadvantage is that you need to remember to edit the PKGBUILD each time you install a new package and possibly when updating packages from AUR.
