### ISSUE TITLE
LGTM alerts

### ISSUE THREAD

**Issue by hakavlad** [actionless/pikaur#379]
https://lgtm.com/projects/g/actionless/pikaur/alerts/?mode=list
How do you like it, @actionless?
113 alerts, 108 errors.

How about add LGTM badges to README?
What about enable PR code review via LGTM?

**Comment by actionless** [comment]
thanks for you message!

which tools that service is using under the hood?

most of the warnings are quite weird, however those 2 looking useful and i am wondering why `pylint` didn't found them/which linter produced them:

https://lgtm.com/projects/g/actionless/pikaur/snapshot/44627939e0dddb59e2bb866bcbc1fe0ded483dfa/files/pikaur/argparse.py?sort=name&dir=ASC&mode=heatmap#x742e94e7c9f1f30c:1 (btw the mistake is in the code which was copied from stdlib :) but warning itself seems valid)

https://lgtm.com/projects/g/actionless/pikaur/snapshot/44627939e0dddb59e2bb866bcbc1fe0ded483dfa/files/pikaur/conflicts.py?sort=name&dir=ASC&mode=heatmap#x9a16d09819b3d35e:1

**Comment by hakavlad** [comment]
>which tools that service is using under the hood?

>The technology behind LGTM is QL. Using QL, you can write a query to find a bug in your projects. Once you've found the original issue and fixed it, you can extend the query to find code patterns that are semantically similar to the original bug.

>The standard or built-in QL queries used on LGTM are all open source, and are constantly updated, pulling in shared knowledge from security teams at our customers, our in-house experts, and other QL users.

https://lgtm.com/help/lgtm/about-lgtm

**Comment by actionless** [comment]
i can't find `QL` in AUR

**Comment by hakavlad** [comment]
>i can't find QL in AUR

You can add https://github.com/semmle/ql in AUR and try again :)

**Comment by actionless** [comment]
thanks! the name is a bit hard to google

i'll look more into the tool

**Comment by actionless** [comment]
it seems they improved the tool during the last half a year: https://lgtm.com/projects/g/actionless/pikaur/alerts/?mode=list

there are only 6 warnings left, however they all either false positive or just ignoring `# noqa` hint

at this moment i can't justify it to be reasonable maintaining one more code quality tool (as already 4 of them are used and each of them require some attention to keep results effective)
