### ISSUE TITLE
Just a message of appreciation

### ISSUE THREAD

**Issue by ExpHP** [actionless/pikaur#38]
I just wanted to leave a message of appreciation here.

Earlier this week, I wrecked my computer, and have since then been rebuilding my arch setup on a new PC.  When it came time to download stuff from the AUR, I decided it was time to find something new.  Yaourt, which I had used on the previous machine, was *such a chore* to use.  I'd find myself having to keep coming back and babysitting it over a period of hours as it downloaded and installed font packages one by one.

As I was reviewing my alternatives, I dreamed of my ideal package manager, fixing all the issues of yaourt.  First and foremost, it would put all the human interaction at the beginning, showing all the git diffs and letting PKGBUILDs be edited, then batch together all the installations at once. No interactive prompts if there's more than one matching package, just dump me back into the console. And it'd have none of that silly "curses getch"-like stuff where you don't need to press Enter at a yes/no prompt (because then I need to slow down to prevent my muscle memory from hitting Enter).

Of course, the comparison of AUR managers on the Wiki doesn't exactly cover the workflow of using these tools, so I was left to basically try them all out.  If I couldn't find one that batched together the installs, I figured, I'd probably just "throw one together" in Python.  It'd take me "two days, tops" (which is programmer speak for "at least a week, possibly two or more, plus some hair loss").

Then I came upon yours, which said basically exactly what I was looking for right in the description.  Clearly, this has been written by one of my fellow brethren tormented by yaourt!  I have tried it out and so far the experience has been basically everything I could have asked for.

---

I have seen that maintaining a package manager can be a pretty thankless job; consider e.g. [pacaur](https://github.com/rmarquis/pacaur) whose maintainer has recently been driven away.  I know that this project is actually very young, and so the worst may be yet to come; in any case, I wanted to post a message of thanks, and to wish you the best of luck in continuing with this endeavor.

**Comment by actionless** [comment]
thanks for the kind words!

actually i've already risen a discussion regarding batch-PKGBUILDS-review thing ni aur wiki:
https://wiki.archlinux.org/index.php/Talk:AUR_helpers  -> "minimizes user interaction" is a misnomer
