### ISSUE TITLE
Feature request: reverse search results

### ISSUE THREAD

**Issue by lelgenio** [actionless/pikaur#380]
When searching for a package with many results, the best matches are buried in aur results, forcing you to scroll back. I propose reversing the results on regular searches and queries.
Important to note that the results on queries with the `-q/--quiet` flag should still retain their original order as to not break scripts.
```
$ pac -Ss package
aur/package-git 1.0-1 (0, 0)
    Description...
extra/package 1.0-1
    Description...

$ pac -Ssq package
package
package-git
```

**Comment by actionless** [comment]
could be added as config option/cli arg
