### ISSUE TITLE
Too many open files error 

### ISSUE THREAD

**Issue by jonas-kaiser** [actionless/pikaur#387]
Pikaur v1.4.3
Pacman v5.1.3 - libalpm v11.0.3

I tried installing the ros-melodic-desktop package using
```pikaur -S ros-melodic-desktop```

and after a (long) while, I got Python errno 24: Too many open files.

**Comment by actionless** [comment]
is it always reproducible?

**Comment by trevoravant** [comment]
I just got the same error with `pikaur -S ros-melodic-ros-base`

**Comment by actionless** [comment]
could you ensure what you're using `pyalpm` at least `0.8.5`?

i remember fixing something similar there before: https://github.com/archlinux/pyalpm/commit/ba84a5ea1a34d181f3ae08ead33502fe5c2c2cde

so if you have older version of it, such error could happen

**Comment by trevoravant** [comment]
I have version `0.8.5` installed. l upgraded all of my packages yesterday before I ran the `pikaur` command.

**Comment by actionless** [comment]
and could you see with lsof which files are opened?

**Comment by trevoravant** [comment]
Seems to work now! Thank you!
