### ISSUE TITLE
[translation] initial italian translation

### ISSUE THREAD

**Issue by mattia-b89** [actionless/pikaur#395]
I recently switched to pikaur from yaourt.
I am very happy about this solution; thank you @actionless for your work!

I'd like to contribute in this project and I've seen it's missing the Italian translation, so I started translating pikaur.

I translate half the strings: https://pastebin.com/xtpuKBz6

---

_even if I use English locale on my system, thus I would not be interested in translations, I truly believe that translated packages help first approach/help put close new users_

**Comment by actionless** [comment]
thanks for your feedback and effort to contribute to the project!

please create a PR when you done (you can do it just from GitHub UI from this page)

**Comment by mattia-b89** [comment]
I created the PR https://github.com/actionless/pikaur/pull/396
Closing this issue and moving there to continue the work
