### ISSUE TITLE
Providers not taken into account in deps solver

### ISSUE THREAD

**Issue by rmarquis** [actionless/pikaur#4]
I have `cower-git` installed, which provides `cower`.
When installing a package that requires `cower`, the dependency solver fails.

In addition to package names, you'll need to check providers here.

```
$ pikaur -S pacaur-git
resolving dependencies...
Reading repository package databases...
Reading local package database...

New packages will be installed from AUR:
    pacaur-git

:: Proceed with installation? [Y/n] y
Do you want to edit PKGBUILD for pacaur-git package? [Y/n]
error: target not found: cower
Can't build 'pacaur-git'.
Failed to build following packages:
pacaur-git
```

**Comment by actionless** [comment]
i fixed that particular problem yesterday already, but build for `pacaur-git` still not succeds.
so for me it now looks like that:
https://paste.ee/p/mAk89

**Comment by actionless** [comment]
i did more changes, now `pacaur-git` is building successfully

thanks for reporting, feel free to reopen if still errors

**Comment by rmarquis** [comment]
I'm afraid the issue is still present in version `0.3+17+gbb6f0d5-1`:

```
$ pikaur -S pacaur-git
resolving dependencies...
Reading repository package databases...
Reading local package database...

New packages will be installed from AUR:
    pacaur-git

:: Proceed with installation? [Y/n] y
Do you want to edit PKGBUILD for pacaur-git package? [Y/n] n
:: Installing repository dependencies for pacaur-git:
error: target not found: cower
Can't build 'pacaur-git'.
Failed to build following packages:
pacaur-git
```

```
$ pacman -Qs cower
local/cower-git 17.5.g59ecf02-1
    A simple AUR agent with a pretentious name
```

**Comment by actionless** [comment]
fixed that as well, please try again

**Comment by actionless** [comment]
what is the filename of the built package?

**Comment by rmarquis** [comment]
Not on my linux machine right now, but if that helps:
* I've defined PKGDEST in makepkeg.conf
* I'm using pacman-git, which doesn't create symlinks in the build directory anymore when PKGDEST is defined.

**Comment by actionless** [comment]
thanks, i'll try to address that tonight, shouldn't be too tricky

**Comment by rmarquis** [comment]
No, another error (`0.3+24+g7e8575e-1`):

```
$ pikaur -S pacaur-git
resolving dependencies...
Reading repository package databases...
Reading local package database...

New packages will be installed from AUR:
    pacaur-git

:: Proceed with installation? [Y/n] y
Traceback (most recent call last):
  File "/tmp/makepkg/pikaur-git/src/pikaur-git/pikaur.py", line 18, in <module>
    main()
  File "/tmp/makepkg/pikaur-git/src/pikaur-git/pikaur/main.py", line 503, in main
    cli_install_packages(args)
  File "/tmp/makepkg/pikaur-git/src/pikaur-git/pikaur/main.py", line 149, in cli_install_packages
    conflict_result = check_conflicts(repo_packages_names, aur_packages_names)
  File "/tmp/makepkg/pikaur-git/src/pikaur-git/pikaur/meta_package.py", line 214, in check_conflicts
    for installed_pkg_name, provides in local_provided.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by actionless** [comment]
i did few more fixes :-)

**Comment by rmarquis** [comment]
Yep, this time it is fixed!

A quick note since you're relaying on `makepkg --packagelist`: You can't really rely on simply adding `PKGEXT` since this can be and is sometimes overriden. There is however a [patch in queue](https://lists.archlinux.org/pipermail/pacman-dev/2018-February/022290.html) for pacman 5.1 (not in master branch yet) that should provide a robuster way to handling file path for pacman -U.

**Comment by actionless** [comment]
i've also added more code to handle such cases, what do you think about it?
https://github.com/actionless/pikaur/blob/master/pikaur/build.py#L327-L336

**Comment by rmarquis** [comment]
You mean to handle the architecture? I don't really have an opinion on this, since only 64bit is officially supported on Arch now.
