### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [actionless/pikaur#406]
Could you do a PyPI release?
Even if it is only to reserve the name to prevent namejacking.

**Comment by actionless** [comment]
https://pypi.org/project/pikaur/

thanks for your suggestion!

**Comment by jayvdb** [comment]
Thanks. https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pikaur packaged up.  6 tests fail in CliTest and NewsTest, mostly because my pacman rpm doesnt initialise a `core.db`.  I'll raise separate bugs as I have time to understand the problems.

**Comment by actionless** [comment]
also there are 4 tests which already fail on travis: https://travis-ci.com/actionless/pikaur/builds/131889324

but i hadn't time to look closer into them
