### ISSUE TITLE
pikaur asking for sudo password

### ISSUE THREAD

**Issue by kyak** [actionless/pikaur#408]
```
pikaur -Vq
Pikaur v1.5.3
Pacman v5.1.3 - libalpm v11.0.3

```

##### [Optional] Prerequisites:
sudo pacman works without a password:
```
# cat /etc/sudoers.d/user
user laptop= NOPASSWD: /usr/bin/pacman
```
##### Attached log:
Nevertheless, pikaur -Syu asks for sudo password
```
pikaur -Syu
[user@laptop ~]$ pikaur -Syu
[sudo] password for user:


Canceled by user (SIGINT)

```
The problem appeared after upgrade of pikaur 1.5.2-2 -> 1.5.3-1.

Using default .config/pikaur.conf

**Comment by actionless** [comment]
that change was done almost a year ago, not between 1.5.2 and 1.5.3, however it seems to be reasonable to revert it back

**Comment by actionless** [comment]
that change was done almost a year ago, not between 1.5.2 and 1.5.3, however it seems to be reasonable to revert it back

**Comment by kyak** [comment]
I don't quite understand. What I mean is that pikaur didn't ask for sudo password before. Recently it started to ask for a password for no apparent reason.

How should I configure pikaur so that it doesn't ask for sudo password?

**Comment by actionless** [comment]
try with `pikaur-git`, which is the latest git master

**Comment by kyak** [comment]
Oh, sorry, I've missed this commit where you had reverted this change. Thank you!

**Comment by spider-mario** [comment]
Actually, that was a regression in sudo 1.8.28: https://bugzilla.sudo.ws/show_bug.cgi?id=901

It was fixed in sudo 1.8.28.p1.

**Comment by actionless** [comment]
@spider-mario i'm not sure, in sudo ticket it's about `NOPASSWD ALL`, and here about `NOPASSWD: /usr/bin/pacman`

**Comment by spider-mario** [comment]
Well, it broke last week for me too when sudo 1.8.28 reached Arch (which would be a weird coincidence), which made me report that bug, and once it was fixed in 1.8.28p1 and pushed to Arch, it solved the problem for me. So, I would say that everything points to that ticket being relevant.

**Comment by actionless** [comment]
ok, so i'm reverting the change again :) please try

**Comment by bryce-lynch** [comment]
Here pikaur is now asking for sudo password (with sudo 1.8.29) again, anyone else having the same issue?

**Comment by actionless** [comment]
@bryce-lynch and if it's working if you manually revert this change:

https://github.com/actionless/pikaur/commit/605049ef239e234a261a50a427ab8e3ecbe3d79e

?

**Comment by bryce-lynch** [comment]
@actionless 

yes, reverting that change, with `user desktop= NOPASSWD: /usr/bin/pacman,/usr/bin/pikaur` in sudoers, works. No password asked. Before, both -Sy and -Su needed sudo password.
