### ISSUE TITLE
After using STDIN for installing repository package terminal input breaks under bash

### ISSUE THREAD

**Issue by CodingKoopa** [actionless/pikaur#411]
When using `stdin` to install an AUR package that has already been installed from a repository, the terminal will break. Characters typed in aren't visible, and `reset -w` must be ran to restore the usual state. Additionally, if `xargs` is used instead, the issue still occurs. Given the particular scenarios under which this occurs, I do have reason to believe that this is a different issue than #346.

### Pikaur Version
Pikaur version:
```
$ pikaur -Vq
Pikaur v1.5.3
Pacman v5.1.3 - libalpm v11.0.3
```
### Prerequisites:
- Have `xargs` installed (optional).
- Have a repository added to `pacman.conf` that provides an AUR package. In my testing, I've used [Chaotic-AUR](https://lonewolf.pedrohlc.com/chaotic-aur/):
```
[chaotic-aur]
Server = http://lonewolf-builder.duckdns.org/$repo/x86_64
Server = http://chaotic.bangl.de/$repo/x86_64
```
- Have an AUR package installed from a repository. In my testing, I've used `yuzu-canary-git` from Chaotic-AUR.
- I used [Konsole](https://konsole.kde.org/) as my console.
##### Attached log:
Installing the package if it isn't installed (which it is) via `|`:
```
$ echo "yuzu-canary-git" | pikaur -S --needed --noconfirm -
Reading repository package databases...
Reading local package database...

error: argument '-' specified without input on stdin
Command 'sudo pacman --color=always --sync --noconfirm --needed -' failed to execute.
Do you want to retry? [N]o (--noconfirm)
Do you want to proceed? [N]o (--noconfirm)
```
At this point, Pikaur exited, and the terminal broke.

Installing a package that doesn't exist:
```
$ echo "package-that-doesnt-exist" | pikaur -S --needed --noconfirm -
Reading repository package databases...
Reading local package database...
:: warning: Following package cannot be found in AUR:
    -
```

Installing the package if it isn't installed via `|` and `xargs`:
```
$ echo "yuzu-canary-git" | xargs pikaur -S --needed --noconfirm
Reading repository package databases...
Reading local package database...

warning: yuzu-canary-git-r12936.54b6d140d-1 is up to date -- skipping
 there is nothing to do
```
At this point, Pikaur exited, and the terminal broke in the same way.

**Comment by actionless** [comment]
thanks for reporting!

please try `pikaur-git`

**Comment by CodingKoopa** [comment]
Thank you for the response! I've installed `pikaur-git`:
```
Pikaur v1.5.3.r3.g4ad6979
Pacman v5.1.3 - libalpm v11.0.3
```
(I'm unsure as to why the Git commit shown there doesn't seem to correlate with 4ad6979.)

With the change in 4ad6979, `stdin` now works properly:
```
$ echo "yuzu-canary-git" | xargs pikaur -S --needed --noconfirm
Reading repository package databases...
Reading local package database...

warning: yuzu-canary-git-r12936.54b6d140d-1 is up to date -- skipping
 there is nothing to do
```
```
$ echo "yuzu-canary-git" | pikaur -S --needed --noconfirm -
Reading repository package databases...
Reading local package database...

warning: yuzu-canary-git-r12936.54b6d140d-1 is up to date -- skipping
 there is nothing to do
```
However, I'm still getting the issue where my terminal input is broken (that is, as described in the OP, that my terminal characters are invisible unless I run `reset -w`). I've confirmed in my testing that:
- This occurs both with Konsole, and in [getty](https://wiki.archlinux.org/index.php/Getty).
- This only occurs when using `stdin` or `stdin` + `xargs`.
- This only occurs with an AUR package provided by a repository. I have not had the issue occur with a package being provided by a repository, or with an AUR package built on the host system.

**Comment by actionless** [comment]
i'm not following why did you provided the commands to reproduce the testcases which are already fixed, but not those which are still not working fine

**Comment by CodingKoopa** [comment]
> i'm not following why did you provided the commands to reproduce the testcases which are already fixed, but not those which are still not working fine

Apologies for not being more clear - with 4ad6979, the commands given do their job correctly, so the output of those is somewhat superfluous. It's the state *after* running those commands that is problematic, that they leave the terminal in a broken state.

To better demonstrate, [here](https://youtu.be/YL05WaIF4q8) is a video of (re)installing a repository package, installing a locally built AUR package, and installing an AUR package from a repository. After the first two commands, I'm able to use the terminal as usual (demonstrated by typing "test"), but after the last one, none of my characters show until I run `reset -w`. I'm pretty confident that this isn't caused by my customized Bash prompt, because I was able to replicate the same effects on TTY 2, which doesn't seem to read my `~/.bashrc` at all.

**Comment by actionless** [comment]
thanks a lot for clarifying!

**Comment by actionless** [comment]
weird, i've tried installing the same package with and without third-party repo:

```
$ echo "pikaur-git" | ./pikaur.py -S --needed --noconfirm -
Reading repository package databases...
Reading local package database...

warning: pikaur-git-1.5.3.r3.g4ad6979-1 is up to date -- skipping
 there is nothing to do

$ echo "pikaur-git" | ./pikaur.py -S --needed --noconfirm -
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
looking for conflicting AUR packages...
:: Downloading the latest sources for a devel package pikaur-git...
:: warning: pikaur-git 1.5.3.r3.g4ad6979-1 AUR package is up to date - skipping
```

and keyboard input is still working

**Comment by actionless** [comment]
also i've tried with gnome-terminal as well -- no difference



could you try adding `-v` flag to pikaur to get more output?

**Comment by actionless** [comment]
(i just don't wanna install some unknown binary package for testing but don't have prepared Arch VM for testing)

**Comment by actionless** [comment]
does it happens only with yuzu package or with any package from that repo?

**Comment by actionless** [comment]
i've re-observed your video again and noticed an interesting detail:

![2019-10-20--1571608078_1725x806_scrot](https://user-images.githubusercontent.com/1655669/67166889-0ec4d200-f394-11e9-92ce-156be9f1bc48.png)


the last command is definitely not a latest pikaur version, it simply doesn't have such error message:

```
$ rg skipping pikaur
pikaur/print_department.py
412:        _("{name} {version} {package_source} package is up to date - skipping").format(
```


so that must be some local problem with your PATH your python stuff

**Comment by actionless** [comment]
alright, i found it out, it's a message from pacman:

```
$ sudo pacman -S mpv --needed
[sudo] password for lie:
warning: mpv-1:0.29.1-11 is up to date -- skipping
 there is nothing to do
```


so that means what i still need a pikaur's output with `-v` flag

**Comment by CodingKoopa** [comment]
> does it happens only with yuzu package or with any package from that repo?

In further testing, it actually does only happen with the yuzu package.

Output for another AUR package from the repo (terminal input **did not** break after this):
```
$ echo "octopi" | pikaur -S -v --needed --noconfirm -
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync --noconfirm octopi --print-format %r/%n
:: warning: octopi 0.9.0-3 REPO package is up to date - skipping
:: Nothing to do.
```
Output for the troublesome (?) package (terminal input did break):
```
$ echo "yuzu-canary-git" | pikaur -S -v --needed --noconfirm -
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync --noconfirm yuzu-canary-git --print-format %r/%n

=> sudo pacman --color=always --sync --verbose --needed --noconfirm yuzu-canary-git
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  /home/kyle/Documents/Projects/Bash/comet-observatory/config/pacman-hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : yuzu-canary-git
warning: yuzu-canary-git-r12936.54b6d140d-1 is up to date -- skipping
 there is nothing to do
```

**Comment by actionless** [comment]
yup, i see the difference is a second `pacman` call

thanks, it's a bit more clear now what's going on (still not 100% :D)

**Comment by actionless** [comment]
what happens if you just run `pacman --color=always --sync --noconfirm yuzu-canary-git --print-format %r/%n` ?

**Comment by CodingKoopa** [comment]
```
$ pacman --color=always --sync --noconfirm yuzu-canary-git --print-format %r/%n
chaotic-aur/yuzu-canary-git
```
(Where `chaotic-aur` is defined in the OP here.)

**Comment by actionless** [comment]
still no idea, i guess the only resort gonna be when i'll find some time to create a VM for testing this

**Comment by actionless** [comment]
also, tried myself installing other AUR package from third-party repo:

```
$ echo "pikaur-git" | pikaur -S --needed --noconfirm - -v
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync --noconfirm pikaur-git --print-format %r/%n

=> sudo pacman --color=always --sync --verbose --noconfirm --needed pikaur-git
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : pikaur-git
warning: pikaur-git-1.5.3.r3.g4ad6979-1 is up to date -- skipping
 there is nothing to do
```

it also doing that second pacman call, so it's fine

**Comment by CodingKoopa** [comment]
I tried installing another Git package from `chaotic-aur`, that I don't have installed (`dxvk-mingw-git` to be precise), and the issue did occur, leading me to believe that there is a correlation with Git packages.

**Comment by actionless** [comment]
i've just installed and configured manjaro VM

gonna try chaotic aur now

**Comment by actionless** [comment]
still can't reproduce :(

![2019-10-21--1571614699_1387x745_scrot](https://user-images.githubusercontent.com/1655669/67168304-7f271f80-f3a3-11e9-94f0-b74f29fa31ce.png)

**Comment by actionless** [comment]
finally found out the difference which makes to reproduce it!

it works fine in `fish`, but not in `bash`

**Comment by actionless** [comment]
in the meantime i found a way to reproduce it without using third-party repo:

```
echo "mpv" | ./pikaur.py -S --noconfirm - -v
```

**Comment by actionless** [comment]
:fireworks:

**Comment by CodingKoopa** [comment]
Confirmed working on my end. Very nice work, thanks for the quick turnaround!

**Comment by actionless** [comment]
thanks for detailed reporting!

your issue also helped to find and fix another problem: https://github.com/actionless/pikaur/commit/bff744c43434a36b2003fedbe9c222ae3dfe5e0d  (packages with `-git` in the name shouldn't be treated as dev-packages if they're going to be installed from the repo, not from AUR)
