### ISSUE TITLE
pikaur doesn't respect noedit or donteditbydefault configs

### ISSUE THREAD

**Issue by codebling** [actionless/pikaur#415]
My config file contains the following options: 
```
$ cat ~/.config/pikaur.conf | grep -i edit
donteditbydefault = yes
noedit = yes
```
but when I install a package, `pikaur` still asks if I want to edit files
```
$ sudo pikaur -S x
[...]
looking for conflicting AUR packages...
:: warning: Not showing diff for xx package (installing for the first time)
Do you want to edit PKGBUILD for xx package? [Y/n] 
```

I poked around and printed out the variables right before it asks the question
```
noedit=False
self.args.edit=None
self.args.noedit=False
self.args.noconfirm=None
```
so I think that the evaluation [here](https://github.com/actionless/pikaur/blob/e53cbb5870f5ca7b264edfe282e9a2765c736d70/pikaur/install_cli.py#L524-L526) results in `noedit=not None and False`, which is `False`

**Comment by actionless** [comment]
you're using pikaur with sudo, so the config file for is being read from `/root/.config/pikaur`

**Comment by codebling** [comment]
Wow..sorry. I thought `env_keep` was set up to preserve `$HOME` but this is a new system and it is not. Very dumb of me. Thanks, sorry!

**Comment by actionless** [comment]
no problem!
