### ISSUE TITLE
[enhancement] clarify color code

### ISSUE THREAD

**Issue by mattia-b89** [actionless/pikaur#418]
`man pikaur` states:

```
[colors]
     Terminal colors, from 0 to 15:
```

it is not clear at all! 

What colour does number {0,...,15} stand for?
Where does the code come from?
Where can I find a palette?
Can we print a palette somewhere?

**Comment by actionless** [comment]
it's like that in all terminal apps where you could set base terminal color from 0 to 15, like in vim or tmux

if you feel like some extra clarifications are needed feel free to update the readme

**Comment by mattia-b89** [comment]
I have never used tmux nor vim, so I am a bit confused:  
I used to play with gnome-terminal and yes, it has a 16-colors palette, but you can choose between multiple palette: tango, solarized, xterm, rxvt, etc.  
This means there is no AN official palette, thus the a code can be different color!  
This has been confirmed by a google search, because you (see https://terminal.sexy/) will find many 16-colors palette schemes;  
What is most missing is a **correspondence** between color code {0,...,15} and a color {that I represent as hexadecimal code}

Furthermore, if I run `man xrdb` I do not get a color palette or instructions on how to get them.

**Comment by actionless** [comment]
yeah, indeed it seems to lack in xrdb documentation, but according to https://superuser.com/questions/924995/what-do-the-16-definable-colors-in-xresources-do it's still documented in xterm

again, if you think what it's not obvious -- feel free to amend the readme section on that

**Comment by mattia-b89** [comment]
perfect! now it's more clear.  
as soon as I produce something good integration I will post here, before pull code

**Comment by mattia-b89** [comment]
ok, I'd like to included a brief "guide" like the below one:
```
The 8 ANSI colours are:
0 -> gray
1 -> red
2 -> green
3 -> yellow
4 -> light blue
5 -> magenta
6 -> cyan
7 -> white
while remaining 8  colours (from 8 to 15) are the bold and brighter equivalents 
! Disclaimer: there are no standard colours used in terminal emulation; this means final effect varies upon different terminal emulator.
```
1. I explicit the standard (ANSI)
2. I describe the palette
3. I warn about colour chosen and final result

to be "compatible with README style I propose:
```
There are 8 ANSI colours available:
0: gray 1: red 2: green 3: yellow 4: light blue 5: magenta 6: cyan 7: white
the remaining 8 colours (from 8 to 15) are the bold and brighter equivalents

! Disclaimer: there are no standard colours used in terminal emulation; this means final results vary upon different terminal emulator.
```
```

**Comment by actionless** [comment]
alright, looks nice

although having a last sentence as a separate disclaimer feels slightly extra to me

**Comment by mattia-b89** [comment]
yeya, thanks.
I have found a good/proper solution for disclaimer too: move it into the FAQ

> **I set colour **red** for _version_ in the configuration file. Why does terminal paint it **orange**?**
> There are no standard colours used in terminal emulation. This means final results vary upon different terminal emulator.

This solution would make me happy!

**Comment by actionless** [comment]
looks fine, thanks
