### ISSUE TITLE
[Future Request] Make the news more visible.

### ISSUE THREAD

**Issue by Bundy01** [actionless/pikaur#419]
I find the appearance of the news not very visible. Maybe putting them in red for example would be a good idea.

Thanks.

**Comment by Bundy01** [comment]
Hi ,
my suggestion has no success :).
I was just thinking about changing the color of 'There are news from archlinux.org!' and not the whole news.
Regards.

**Comment by Bundy01** [comment]
Yeah, I think that's pretty good.

**Comment by actionless** [comment]
thanks for your feedback, you could try with `pikaur-git`

**Comment by Bundy01** [comment]
Okay, thank you.

I didn't pay attention to your wallpaper, it looks nice ;)

**Comment by actionless** [comment]
yeah, gimp really rules :)

you can grab it here https://github.com/actionless/dotfiles/blob/master/common-theme-assets/images/common-wallpapers/260-2.jpg
