### ISSUE TITLE
Broken by recent Arch upgrades?

### ISSUE THREAD

**Issue by TheReverendHerculesGrytpype-Thynne** [actionless/pikaur#423]
Pikaur fails since recent upgrade of Arch

```
pikaur -Vq


  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
ModuleNotFoundError: No module named 'pikaur'


```

##### Attached log:

```
pikaur -S my-precious-package


```

**Comment by noraj** [comment]
Same here with bleeding edge Arch:

```
$ pikaur --version
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 5, in <module>
    from pikaur.main import main
ModuleNotFoundError: No module named 'pikaur'
```

**Comment by actionless** [comment]
https://aur.archlinux.org/packages/pikaur/#comment-716929

**Comment by noraj** [comment]
Answer:

>  @E3LDDfrK There was a major python update (3.7.x - 3.8), all aur packages that depend on python 3 have to be rebuilt.

I did not read AUR comments as the pinned comment says:

> please report your issue here with attaching the full output: https://github.com/actionless/pikaur/issues
