### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [actionless/pikaur#424]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by actionless** [comment]
but it's not up to AUR helper, users are free to configure it themselves in makepkg.conf

if you feel like it's very important information, feel free to add it to the FAQ section of the readme

**Comment by es20490446e** [comment]
The default is not a good one.

**Comment by actionless** [comment]
that's a default of `makepkg`, not of `pikaur`

**Comment by es20490446e** [comment]
Ideally that should be considered in makepkg, but they won't listen to me if it's me who proposes it.

Alternatively pikaur can choose its own default.

**Comment by actionless** [comment]
also, you probably missed https://www.archlinux.org/news/required-update-to-recent-libarchive/

**Comment by es20490446e** [comment]
I just read that Arch is planning to default to zstd, so no fix will be needed here.

- [Arch thread](https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029520.html)
- [Pacman git log](https://git.archlinux.org/svntogit/packages.git/log/?h=packages/pacman)
