### ISSUE TITLE
sudo run multiple times?

### ISSUE THREAD

**Issue by tblancher** [actionless/pikaur#425]
```
Pikaur v1.5.4
Pacman v5.2.1 - libalpm v12.0.1

```

##### [Optional] Prerequisites:
logwatch

##### Attached log:
This isn't a problem with pikaur, merely a question.  I use logwatch to report on my Arch systems every day, and it emails me various tidbits of data regarding my Arch installations.  Lately I've noticed that the `pam_unix` section of logwatch reports an inordinate number of `sudo` invocations, from my user to root.  Here is an example of logwatch output:

```
                      pam_unix     
    sudo:                                                                  
	Sessions Opened:
		trey -> root: 327 Time(s)
```
This is at least an order of magnitude more times than I'm running sudo manually in a given day.  Recently I've been seeing these reports, and some of the counts are well above 3,000.  Someone on IRC (#archlinux@freenode) suggested this may be a result of my AUR helper (`pikaur` in this case).

So I'm wondering, does `pikaur` invoke `sudo` multiple times during its `-Syu` invocation?  That would explain what I'm seeing if it does.

This is a question, not a bug per se.

**Comment by actionless** [comment]
see https://github.com/actionless/pikaur#sudoloopinterval-default-59

**Comment by tblancher** [comment]
@actionless Thanks, I thought it was that simple.  My sudoloopinterval timeout was set to 1 second, so that explains everything.  I've updated it to be 280 seconds, within the default five minute timeout of sudo.
