### ISSUE TITLE
sudo is used for pikaur -Sca (clean aur build cache)

### ISSUE THREAD

**Issue by jplatte** [actionless/pikaur#430]
```
Pikaur v1.5.4
Pacman v5.2.1 - libalpm v12.0.1
```

pikaur executes sudo for an operation that shouldn't require root permission: cleaning the aur build cache (`pikaur -Sca`). I've set up paccache to clean my system package cache regularily, so only need to clean the build cache with pikaur. I don't see why doing that would require root permission.

Thanks for this great piece of software! :)

##### Attached log:

```
pikaur -Sca
[sudo] Passwort für jplatte:
```

**Comment by actionless** [comment]
thanks for reporting!
please try with `pikaur-git`

**Comment by jplatte** [comment]
Thanks for fixing this so fast, and thanks for pikaur in general! :heart:
