### ISSUE TITLE
Cannot build mat2 from AUR

### ISSUE THREAD

**Issue by eleius** [actionless/pikaur#433]
I tried updating the packages as usual with -Sy and -Su but one of them (aur/mat2) fails.

Error log here: https://pastebin.com/raw/kzVEReas

If I download the pkgbuild and run makepkg manually everything works fine.

pikaur -Vq returns:
Pikaur v1.5.4
Pacman v5.2.1 - libalpm v12.0.1

**Comment by actionless** [comment]
try first running pikaur with adding `-v` flag and next running manually the commands from verbose log

**Comment by eleius** [comment]
If I run pikaur -v mat2, the same 2 tests reported above fail. But it builds fine if I manually run the commands from the log, that is:

> git -C /home/user/.mypc/share/pikaur/aur_repos/mat2 pull origin master
> pacman --color=always --deptest perl-image-exiftool python-mutagen python-cairo python-gobject poppler-glib gdk-pixbuf2 mailcap
> pacman --color=always --deptest python-setuptools git
> pacman --color=always --deptest ffmpeg
> sudo rm -rf /home/user/.cache/pikaur/build/mat2
> mkdir -p /hd/ramdisk/.cache/pikaur/build/mat2
> cp -r /home/user/.mypc/share/pikaur/aur_repos/mat2/PKGBUILD /home/user/.mypc/share/pikaur/aur_repos/mat2/.SRCINFO /hd/ramdisk/.cache/pikaur/build/mat2/
> makepkg --packagelist
> makepkg --force

**Comment by eleius** [comment]
If I run pikaur -v mat2, the same 2 tests reported above fail. But it builds fine if I manually run the commands from the log, that is:

> git -C /home/user/.local/share/pikaur/aur_repos/mat2 pull origin master
> pacman --color=always --deptest perl-image-exiftool python-mutagen python-cairo python-gobject poppler-glib gdk-pixbuf2 mailcap
> pacman --color=always --deptest python-setuptools git
> pacman --color=always --deptest ffmpeg
> sudo rm -rf /home/user/.cache/pikaur/build/mat2
> mkdir -p /hd/ramdisk/.cache/pikaur/build/mat2
> cp -r /home/user/.local/share/pikaur/aur_repos/mat2/PKGBUILD /home/user/.local/share/pikaur/aur_repos/mat2/.SRCINFO /hd/ramdisk/.cache/pikaur/build/mat2/
> makepkg --packagelist
> makepkg --force

**Comment by actionless** [comment]
do you run with sudo, as root or using dynamic_users?

**Comment by actionless** [comment]
> But it builds fine if I manually run the commands from the log

and when building manually, are you also doing it inside `/hd/ramdisk/.cache/pikaur/build/mat2/` directory?

**Comment by eleius** [comment]
I'm running pikaur as my main (non-root) user.

When running manually the commands listed in the verbose log, right before makepkg I changed directory to the one you mentioned.

**Comment by actionless** [comment]
i took a look on the error log

> AssertionError: b' [-v] [-l] [--check-dependencies] [-L | -s]' not found in b"usage: mat2 [-h] [-V] [--unknown-members policy] [--inplace] [--no-sandbox] [-v]\n            [-l] [--check-dependencies] [-L | -s]\n 

the problem is with the testsuite itself. it using some function to linewrap to terminal size and insert newline and for some reason it's assuming it to be 80:

```
$ echo "usage: mat2 [-h] [-V] [--unknown-members policy] [--inplace] [--no-sandbox] [-v]" | wc -c
81
```
