### ISSUE TITLE
Building only one of several packages after editing PKGBUILD

### ISSUE THREAD

**Issue by Drommer** [actionless/pikaur#440]
Pikaur v1.5.8.1
Pacman v5.2.1 - libalpm v12.0.1

I noticed a strangeness that I had not seen before. When installing several packages from AUR after editing PKGBUILD of the first one, only this package is built and installed, and the others are not, the script forgets about it.

For example: I write the command "pikaur -S dolphin-root kate-root", then "edit PKGBUILD for dolphin-root" - "yes", after editing I see the message "Installation info changed (or new deps found) for dolphin-root package ", then a second request to edit PKGBUILD for dolphin-root appears. After selecting "no", dolphin-root is built and installed, and pikaur finished. There are no more references to kate-root.

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by Drommer** [comment]
Everything is working correctly now, thanks for the prompt fix.
