### ISSUE TITLE
Outdated AUR package not displayed during sysupgrade despite `ignoreoutofdateaurupgrades` being set to "no"

### ISSUE THREAD

**Issue by vtnpp** [actionless/pikaur#443]
```
$ pikaur -Vq
Pikaur v1.5.9
Pacman v5.2.1 - libalpm v12.0.1
```

`pikaur.conf`:

![Screenshot_2020-01-14_15-12-43](https://user-images.githubusercontent.com/59181811/72352221-220ce280-36e2-11ea-971e-a8680e30e456.png)

`$ pikaur -Syu`:

![Screenshot_2020-01-14_15-12-17](https://user-images.githubusercontent.com/59181811/72352236-276a2d00-36e2-11ea-843d-d1cf85a3a9ca.png)

Isn't `pikaur` supposed to display a message saying that `qomui`<sup>AUR</sup> is out of date?
Set `ignoreoutofdateaurupgrades` to `yes` doesn't make any difference.

**Comment by actionless** [comment]
show also `pikaur -Qs qomui`

**Comment by vtnpp** [comment]
`$ pikaur -Qs qomui`:

![Screenshot_2020-01-14_15-32-04](https://user-images.githubusercontent.com/59181811/72352739-1968dc00-36e3-11ea-820a-d9b433b906f6.png)

**Comment by actionless** [comment]
it's not upgradeable

**Comment by vtnpp** [comment]
Ok, I thought it would display a message anyway, like `yay` does.

Thanks.

**Comment by actionless** [comment]
option is called ignoreoutofdateaur**upgrades**

**Comment by vtnpp** [comment]
Silly me. Makes sense then.

Sorry!

**Comment by actionless** [comment]
no problem, the motivation behind not showing it in other cases -- if package is already marked out-of-date -- you can't do much unless you're a maintainer of that package; and if you're the maintainer -- you'll receive e-mail notification anyway
