### ISSUE TITLE
Please add support for applying patch

### ISSUE THREAD

**Issue by agguser** [actionless/pikaur#445]
Some AUR packages are outdate (e.g. https://aur.archlinux.org/packages/tome4/);
but comments provide "patches" (e.g. https://git.sr.ht/~stick/aur-tome4/commit/a7b1fa91cb1a721646afd239105aa3884ed2afe2.patch);
so pikaur should provide a convenient way to apply a patch (e.g. `pikaur -S --patch /tmp/tome4.patch tome4`),
instead of doing it manually (e.g. `patch -d ~/.cache/pikaur/build/tome4 -p1 </tmp/tome4.patch`).

Or is there already a better way to do this?

**Comment by actionless** [comment]
better way to convince the maintainer to fix outdated package or if it appears practically abandoned -- to request package orphanage and adopting it yourself
