### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Mauladen** [actionless/pikaur#45]

**Comment by Zopieux** [comment]
Pikaur parses the output of pacman --help for its own help,
* replacing `pacman` with `pikaur`
* replacing `options:` with `common pacman options`

But when running under another locale, the second operation will fail, eg. `options` is `opciones` in Spanish.

Possible solutions:
1. search for `_("options:")` instead, but this means adding `options:` translation to our own catalog for every supported locale.
1. don't try to replace anything (except maybe `pacman` that is more or less guaranteed to be `pacman` in every locale).
1. change nothing: try to replace `options:` but accept that this will only work for English or by accident (ie. target locale translates to `options:` too).
1. run the pacman subprocess with `LANG=C` so the replace works, but then pikaur help will *have* to be in English.

I would advocate 3.

**Comment by actionless** [comment]
@Zopieux  i am up for №1
