### ISSUE TITLE
Unknown distribution option

### ISSUE THREAD

**Issue by j77h** [actionless/pikaur#450]
[200203_pikaur2.log](https://github.com/actionless/pikaur/files/4147520/200203_pikaur2.log)
```
$ pikaur -Vq
Pikaur v1.6
Pacman v5.2.1 - libalpm v12.0.1
```
```pikaur -S pikaur```
got the warning
```/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option:```
for 'long_description_content_type', 'install_requires', and 'entry_points'.

pikaur seems to be working correctly.
I'm reporting this only in case it _might_ cause a problem somehow. 

A stackoverflow answer about [unknown distribution option](https://stackoverflow.com/questions/8295644/pypi-userwarning-unknown-distribution-option-install-requires) mentions setuptools, so I checked if I have it:
```
$ python
Python 3.8.1 ...
>>> import setuptools
>>> setuptools.__version__
'44.0.0'
```
full output attached

**Comment by actionless** [comment]
that's because optional `setuptools` support, which is disabled by default:
https://github.com/actionless/pikaur/blob/master/setup.py#L7-L8

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by j77h** [comment]
Yes, it works OK.

That error must be in the pikaur installer, not in pikaur itself, 
as pikaur did not get the warning when installing pikaur-git.
[200204_pikaur-git.log](https://github.com/actionless/pikaur/files/4151250/200204_pikaur-git.log)

Then I installed mercurial-python3 and tortoisehg with pikaur(-git). 
Got no warnings relating to pikaur, and tortoisehg works fine.
