### ISSUE TITLE
runs out of disk space while building

### ISSUE THREAD

**Issue by RubenKelevra** [actionless/pikaur#453]
```
Pikaur v1.6.4
Pacman v5.2.1 - libalpm v12.0.1
```
### Current behavior
Currently, pikaur seems to not check if it's running low on disk space in its `~/.cache/pikaur/build` as well as `~/.cache/pikaur/pkg` directory.

### Expected behavior
Pikaur should check from time to time how much disk space is left, to avoid filling `/home`, `~/.cache` or `/` completely.

If the disk space runs below a minimum threshold like 1 GB it should abort the build operation.

**Comment by actionless** [comment]
i don't think it's responsibility of build helper to do so -- pacman already does its own checks for packages with known file size, for building packages the size is not known so such check could be annoying and totally useless in a lot of cases

**Comment by RubenKelevra** [comment]
In which cases do you think it's useless to avoid filling `/home` up to 0 bytes left?

The building process will fail in those cases anyway, so why not let it fail before the remaining space is completely used up?

There are many programs (like browsers) writing their databases to `/home` which might lead to data loss if there's no space left.

Additionally a full `/home` directory can lead to failures of any graphical login.

So if the user do not realize that he run out of disk space, he might be unable to login again after a reboot - except on the console or as root (which is usually not enabled for graphical login).

Additionally the I/O to the filesystem will be extremely slow and fragmented, when filling a filesystem to the brim, and filesystems like BTRFS even had trouble to recover from a completely filled filesystem in the past, because of usually rarely occuring bugs.

So there are many reasons why it should be avoided to use up the disk space completely, and since it's an extremely cheap and easy system call (just an `shutil.disk_usage(path)`) I don't see a reason why pikaur should not check for this condition.

**Comment by actionless** [comment]
cause it's not possible to predict the build dir size

if you have a small drive/partition there are thousands other things which could make your partition full -- just find some taskbar widget notifier with disk size or so on

**Comment by RubenKelevra** [comment]
> cause it's not possible to predict the build dir size
> 
> if you have a small drive/partition there are thousands other things which could make your partition full -- just find some taskbar widget notifier with disk size or so on

Sure. But it would be a better user experience if pikaur would be intelligently aware of this fact and stop filling a nearly full partition even more.

It can stop the build, print an "out of disk space (lower than 1 GB of free space in build directory)" message and clean the half finished build to reclaim space.

It isn't complex and I don't see a case where it would hurt checking for remaining disk space.

**Comment by actionless** [comment]
> cause it's not possible to predict the build dir size
