### ISSUE TITLE
Update and packet search very slow over IPv6

### ISSUE THREAD

**Issue by frankenstein91** [actionless/pikaur#457]
```
pikaur -Vq
Pikaur v1.6.6
Pacman v5.2.1 - libalpm v12.0.1

```

##### Prerequisites:
To reproduce this problem, an IPv6 and IPv4 connection is necessary.

##### Error description.
Since the log does not give any information even in the suggested log mode, I prefer to describe the error. I usually use an Internet connection with IPv4 and IPv6 enabled. This allows me to use both protocols. According to Wireshark IPv6 is used to connect pikaur in the initial situation. It takes a very long time until I get a list of packages with updates. For a test I disabled the IPv6 connection in the network manager and reconnected to the WLAN. This solved the speed problem. Activating the IPv6 addresses brought back the problem of the long waiting time.

Since I don't know if it is an error of my internet provider, a problem of the AUR servers, a local problem or a pikaur problem, I would like to ask for help. Would it be possible to include an IPv4/IPv6/both switch in the configuration?

**Comment by actionless** [comment]
1) run pikaur with `-v/--verbose` flag (it will print the commands it executes)
2) run the same commands manually

if you still having the same problem -- then it's nothing pikaur could affect

**Comment by frankenstein91** [comment]
unfortunately no command is displayed at this point. All displayed commands are executed quickly and without problems.
Once it hangs after downloading the repositories and then again when reading the AUR package info.

**Comment by frankenstein91** [comment]
I just did another test. The command "pacman -Suy" is fast and the command "pikaur -Suy" is unfortunately slow in connection with IPv6.

**Comment by actionless** [comment]
please update to the latest `pikaur-git` and try it with `-v` again -- now pikaur should log in verbose mode not only CLI commands but also network requests (so you could try them with `curl`)

**Comment by frankenstein91** [comment]
I was able to fix the problem with my ISP

**Comment by frankenstein91** [comment]
I'm not sure if we shouldn't look at the problem anyway and allow the user to work without IPv6. I was able to find the ISP error through my contacts, but not everyone has this possibility. If here the IPv6 packets are sent into nothing and you have to hope for luck during the timeout that the operating system delivers an IPv4 address to Python, I still see this as a problem. Maybe not necessarily your problem. 
The non-AUR repositories work only with IPv4 in my opinion. Don't get me wrong, I like IPv6 a lot. But I always see problems with it, even though it is an old RFC. But I think it might be enough to replace the domain with the IPv4 address of the AUR in the configuration file, at least for affected users?

**Comment by actionless** [comment]
1) i think what helping to workaround network misconfiguration problems is outside of responibility of aur helper
2) python's urllib require quite a hack to force ipv4 explicitly, ex.: https://stackoverflow.com/a/18007585/1850190
