### ISSUE TITLE
install dependencies before building 

### ISSUE THREAD

**Issue by gjvnq** [actionless/pikaur#462]
```
pikaur -Vq
Pikaur v1.6.8
Pacman v5.2.1 - libalpm v12.0.1
```

Many times I try to install a package only to have it fail because some dependency is scheduled to be built and installed after the current package.

Is there an option to consider all dependencies as build dependencies? This would ensure all dependencies are installed before attempting to build.

**Comment by actionless** [comment]
> Many times I try to install a package only to have it fail because some dependency is scheduled to be built and installed after the current package.

please provide the steps to reproduce it

**Comment by gjvnq** [comment]
Ops, I reported to the wrong repo. The problem was with pacaur, not pikaur. My bad.
