### ISSUE TITLE
[Feature request] Colored repositories names during system upgrade

### ISSUE THREAD

**Issue by vtnpp** [actionless/pikaur#464]
`pikaur -Vq`
```
Pikaur v1.6.8.r1.g71a9390
Pacman v5.2.1 - libalpm v12.0.1
```

I'm using

```
[sync]
alwaysshowpkgorigin = yes
upgradesorting = repo
```

and thought it'd be nice if we could have different colors for repositories when doing a system upgrade, just like when searching for packages (`pikaur <pkg_name>` or `pikaur -Ss <pkg_name>`).

Current behavior:

![2020-03-22_18-57-51](https://user-images.githubusercontent.com/59181811/77257038-215c7380-6c72-11ea-9c96-9ebdfb4e59eb.png)

Any chance it could be implemented?

Cheers

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by vtnpp** [comment]
Thanks, works fine indeed.

Looks like there is an issue when searching for packages now though. Not sure if the commit is the culprit but I don't recall seeing that before:

`pikaur gimp`

![2020-03-22_20-20-00](https://user-images.githubusercontent.com/59181811/77258420-caa76780-6c7a-11ea-86de-e79d30844980.png)

**Comment by actionless** [comment]
oops, that was a debug output, please try with the latest `pikaur-git`

**Comment by vtnpp** [comment]
Fixed, thanks.

Keep up the good work!
