### ISSUE TITLE
aur_repos directory path changes to ~/.local/share/aur_repos instead of ~/.local/share/pikaur/aur_repos when using export XDG_DATA_HOME="$HOME/.local/share" environment variable

### ISSUE THREAD

**Issue by vtnpp** [actionless/pikaur#465]
`pikaur -Vq`:

```
Pikaur v1.6.8.r5.gec8fa99
Pacman v5.2.1 - libalpm v12.0.1
```

`~/.config/pikaur.conf`:

```
[sync]
alwaysshowpkgorigin = yes
develpkgsexpiration = 7
upgradesorting = repo
showdownloadsize = yes
ignoreoutofdateaurupgrades = no

[build]
keepbuilddir = no
keepdevbuilddir = yes
keepbuilddeps = no
skipfailedbuild = no
alwaysusedynamicusers = no

[colors]
version = 10
versiondiffold = 11
versiondiffnew = 9

[ui]
requireenterconfirm = no
printcommands = no
reversesearchsorting = yes

[misc]
sudoloopinterval = 59
pacmanpath = pacman
privilegeescalationtool = sudo

[network]
socks5proxy =
aururl = https://aur.archlinux.org
newsurl = https://www.archlinux.org/feeds/news/

[review]
noedit = no
donteditbydefault = no
nodiff = no
gitdiffargs = --ignore-space-change,--ignore-all-space
diffpager = auto
hidedifffiles = .SRCINFO
```

I was reorganizing my dotfiles lately and have set the following in my `.xinitrc` :

```
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
```

Since then, I noticed that `aur_repos` directory path has changed when updating an AUR package or installing a new one.

- before: `~/.local/share/pikaur/aur_repos`
- now: `~/.local/share/aur_repos`

Is it the intended behavior? should I just move my old `aur_repos` folders in the new path and forget about it?

I couldn't find any relevant information with `man pikaur`:

Cheers

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by vtnpp** [comment]
Can confirm the repositories are now saved to `~/.local/share/pikaur/aur_repos`. Thanks!
