### ISSUE TITLE
[Feature request] Run `pikaur` without argument = `pikaur -Syu`

### ISSUE THREAD

**Issue by vtnpp** [actionless/pikaur#467]
`pikaur -Vq`:

```
Pikaur v1.6.9.1.r0.gffe3dda
Pacman v5.2.1 - libalpm v12.0.1
```

Currently, running `pikaur` returns: `error: no operation specified (use -h for help)`.

How about just using `pikaur` to mimic `pikaur -Syu`, in the same vein than running `yay` actually runs `yay -Syu`?

Using `alias pikaur = pikaur -Syu` isn't possible because any other `pikaur` operation will fail. For example, `pikaur -Qm` will run `pikaur -Syu -Qm`.

Cheers.

**Comment by actionless** [comment]
i personally use `alias syu = pikaur -Syu` and `alias syua = pikaur -Syua`

for your usecase you could define a shell function or script wrapper:
```sh
pikaur() {
if test "$#" -eq 0; then
    pikaur -Syu
else
    pikaur "$@"
fi
}
```
