### ISSUE TITLE
SystemD Dynamic Users: spawned process freezes from time to time

### ISSUE THREAD

**Issue by x3a** [actionless/pikaur#469]
```
pikaur -Vq

Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1
```

For a while, I'm experiencing occasional stagnation of the _makepkg_ process invoked by _pikaur_, the last message that's printed is:

 `:: Starting the build:`

and I can see by running `htop` that the _makepkg_ process has started and is running but remains inactive at some point.

This doesn't affect all packages and occurs only from time to time on two different machines I'm running. Invoking `pikaur -Scc` to clear up the cache doesn't fix this but building the packages manually with _makepkg_ works. Re-Installing _pikaur_ also hasn't changed this behavior.

I want to keep an eye on this issue to provide you with some debugging output when it re-occurs. For this, can you tell me how I can activate propagation of _makepkg_'s output to _pikaur_ just like I'd be running _makepkg_ manually?

**Comment by actionless** [comment]
do you use sudo/dynamic users?

**Comment by actionless** [comment]
also in pikaur.conf you could set `[ui]printcommands = yes` so next time it happens you'll have more debugging info

(running pikaur with `--pikaur-debug`) will produce even more debug info

**Comment by rarjpg** [comment]
```
:: Starting the build:
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/zoom makepkg --force
```

No more output in 5 minutes. Also aurman works.

**Comment by actionless** [comment]
so, as i was expecting in the comment above systemd dynamic users not working properly on your setup, either disable it or try this: https://github.com/actionless/pikaur#pikaur-slow-when-running-it-as-root-user-or-via-sudo

**Comment by rarjpg** [comment]
This was working perfectly a week ago.

**Comment by rarjpg** [comment]
Oh I see, I'll try it.

**Comment by actionless** [comment]
you could also try to monitor systemd journal to see why invocation of `systemd-run` stalled and/or try to execute that command manually

but if you see in htop what systemd-run/nested makepkg are still running -- it's nothing to fix on pikaur's side, as it's just waiting for it to finish

**Comment by rarjpg** [comment]
We might have different issues with OP, I think you closed the issue too early.

**Comment by actionless** [comment]
you just have almost the same autogenerated avatar, so i thought it's the same guy

let's see, if OPs problem is not related to systemd, then it will be another thing to investigate, but so far it looks like it is the same

**Comment by ikrivosheev** [comment]
@actionless how can I help you?

**Comment by actionless** [comment]
@ikrivosheev mb you could try those systemd-run commands manually for few times and see if the same behavior also occurs?

**Comment by actionless** [comment]
and check `sudo journalctl -f` while the problem reproduces

**Comment by ikrivosheev** [comment]
@actionless 
1. `sudo journalctl -f` - is clean, only one record: 
`hp-pavilion systemd[1]: Starting /usr/bin/makepkg --force...`

I guess `strace` shows the problem:
```
strace: Process 24195 attached
write(1</dev/pts/1>, "[ 52%] \33[32mBuilding CXX object "..., 78
```
Maybe /dev/pts1 does not have space in buffer for new data and `write` is waiting?

**Comment by actionless** [comment]
but if the same happens if you run the same command manually several times?

**Comment by ikrivosheev** [comment]
Yes, playable.

**Comment by actionless** [comment]
but with --pty it also happens?

**Comment by ikrivosheev** [comment]
Yes.

**Comment by actionless** [comment]
so if that happens when you just run systemd-run from terminal -- then consider reporting it to systemd

**Comment by ikrivosheev** [comment]
With `--pty`` - never work
Without `--pty`` is ok.

**Comment by ikrivosheev** [comment]
Why do you think this is systemd bug?

**Comment by actionless** [comment]
it happens to you when you just run systemd directly from terminal, right?

**Comment by ikrivosheev** [comment]
Yes

**Comment by rarjpg** [comment]
I've created an issue in systemd tracker: https://github.com/systemd/systemd/issues/15395.

**Comment by MV-SH** [comment]
Looks like this problem could be the same what was already discussed in Arch forums at the end of March (it's marked as _SOLVED_, but I get the feeling that they might have arrived to a wrong conclusion there):

https://bbs.archlinux.org/viewtopic.php?id=254165

For the record, I experience the same problem (I don't use `sudo` on my Arch machines), but unfortunately can't debug it myself further for the next few days, so just leaving it here if someone is looking for more data points, as it will likely draw more people to search for a related ticket by now...

(From my previous tests some time earlier during the last week, there was nothing relevant in systemd journal, various builds usually run for a while with no output and no error in the logs, but they eventually freeze. There is one interesting distinction I've noticed - building `pikaur` and `pikaur-git` never fails, but the output is visibly buffered in entirety until the very end. Only when finished, the build output is then all at once dumped into the terminal.)

**Comment by actionless** [comment]
totally forgot to mention what removing `--pty` from the call will break Ctrl+C handling

so, if you urgently need to use systemd dynamic users -powered build and not gonna use Ctrl+C -- you could work it around by just removing --pty from the call

**Comment by M4tT3d** [comment]
I don't know if it is useful but also with pikaur -Scc the process is too long

**Comment by actionless** [comment]
it would be nice, if someone who have it reproducible on their setup will improve the existing report at https://github.com/systemd/systemd/issues/15395

**Comment by M4tT3d** [comment]
> it would be nice, if someone who have it reproducible on their setup will improve the existing report at [systemd/systemd#15395](https://github.com/systemd/systemd/issues/15395)

can I paste the post data #473 ?

**Comment by actionless** [comment]
@M4tT3d i don't think it will be useful as is.
it will be better if you will just try running directly in your terminal `systemd-run` commands from the log you had there

**Comment by M4tT3d** [comment]
@actionless is this ok? Sorry but I'm not an expert
`systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/snapd makepkg --force`

**Comment by actionless** [comment]
yeah, so it also stuck when you run it directly in the terminal?

**Comment by M4tT3d** [comment]
yes. It stucks

**Comment by actionless** [comment]
yeah, then it looks like fine to report

**Comment by actionless** [comment]
you could also mention what to get the contents of /var/cache/pikaur/build/snapd dir one should clone https://aur.archlinux.org/snapd.git (or any other aur package)

**Comment by M4tT3d** [comment]
@actionless ok. I have updated the post

**Comment by actionless** [comment]
thanks @M4tT3d !

**Comment by M4tT3d** [comment]
you're welcome

**Comment by actionless** [comment]
systemd fix got merged into mainline, now just wait when it got released

**Comment by ivica-k** [comment]
Thank you @actionless for being so involved with this issue. There's a lot of us "suffering" in silence :)

**Comment by M4tT3d** [comment]
I still have the problem. What can I do?

**Comment by ivica-k** [comment]
Hey @M4tT3d, in my case I stopped using `pikaur` with `sudo` and it works well.

**Comment by actionless** [comment]
yup, either this or just waiting for the next systemd release :)

don't think downgrading systemd to a version before it got broken is a good idea at all

**Comment by M4tT3d** [comment]
> Hey @M4tT3d, in my case I stopped using `pikaur` with `sudo` and it works well.

thanks. It works now

**Comment by actionless** [comment]
is still reproducible for anyone? if not i'll unpin this issue from the top
