### ISSUE TITLE
Notifying the date of an outdated package.

### ISSUE THREAD

**Issue by Bundy01** [actionless/pikaur#476]
```
pikaur -Vq
Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1

```

##### [Optional] Prerequisites:
Hi,
Would it be possible to add the date of an outdated package from the official repositories with the command `pikaur -Si package` and `pikaur -Qi package`?

With AUR, the above commands work, but there is no date. It is replaced with a number (e.g., Out of date       : 1587661074).

Regards.

##### Attached log:
ex:

```
pikaur -Si ugrep
URL AUR Git     : https://aur.archlinux.org/ugrep.git
Nom             : ugrep
Base du Paquet  : ugrep
Version         : 2.0.2-1
Description     : Universal grep: ultra fast searcher of file systems, text and binary files, source code, archives, compressed files, documents, and more.
URL             : https://github.com/Genivia/ugrep
Mots-clés       : grep
Licenses        : BSD-3
Groupes         : Aucun
Fournit         : Aucun
Dépend De       : pcre2, zlib, bzip2, xz
Dépendances optionnelles: Aucun
Dépendances de construction: Aucun
Vérifier Deps   : Aucun
Conflits Avec   : Aucun
Remplace        : Aucun
Mainteneur      : swiftscythe
Votes           : 1
Popularité      : 0.813646
Première Soumission: Wed Apr  8 17:39:23 2020
Dernière Mise à jour: Wed Apr 22 03:31:29 2020
Périmé          : 1587661074

```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by Bundy01** [comment]
For AUR, the commit works well. But there is no informations for the packages in the official repositories.
Afterwards, it may not be possible to get this information.

**Comment by actionless** [comment]
for repo packages `pacman -Si` is used

**Comment by Bundy01** [comment]
I opened a Feature Request on archlinux.org. I hope it gets accepted.

**Comment by actionless** [comment]
nice, hope so as well
