### ISSUE TITLE
How to ignore aur package

### ISSUE THREAD

**Issue by jjgalvez** [actionless/pikaur#477]
```
pikaur -Vq
Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1
```
Does pikaur have the ability to ignore am AUR package similar to pacman? I have a package that I need to keep frozen on an older version (at least until it breaks)
thanks in advance

**Comment by actionless** [comment]
you can do it in the pacman config literally the same as for repo packages
or use --ignore arg the same as in pacman

**Comment by jjgalvez** [comment]
now I feel stupid, thank you
