### ISSUE TITLE
Feature Request: git clone protocol:urls in place of names

### ISSUE THREAD

**Issue by DreamingRaven** [actionless/pikaur#480]
I noticed the source for AUR packages uses git clone already to get the desired PKGBUILDS: https://github.com/actionless/pikaur/blob/090d145aa0b5dd7d5aae71a622eb29e7e6d9e24e/pikaur/main.py#L165-L174 
and here
https://github.com/actionless/pikaur/blob/090d145aa0b5dd7d5aae71a622eb29e7e6d9e24e/pikaur/aur.py#L190-L191

However you can not request a package by full protocol and url which is a feature supported by git clone already for us to use interchangeably E.G:

```
git clone git://git@aur.archlinux.org/python-ezdb-git.git
git clone https://git@aur.archlinux.org/python-ezdb-git.git
git clone ssh://git@aur.archlinux.org/python-ezdb-git.git
```

If you attempt to do the same in pikaur this will naturally fail as one would expect as passing in the full url is an unexpected use case:

using pure git:
```
pikaur -S git://git@aur.archlinux.org/python-ezdb-git.git

Reading repository package databases...
Reading local package database...
:: warning: Following package cannot be found in AUR:
    git://git@aur.archlinux.org/python-ezdb-git.git 
```
using https:
```
pikaur -S https://git@aur.archlinux.org/python-ezdb-git.git
```
using ssh:
```
pikaur -S ssh://git@aur.archlinux.org/python-ezdb-git.git
```

The main advantage of this feature would be that it gives the user more control and as a consequence allows us the flexibility to change the URL to our own potentially private repos, and not have to go through the process of cloning, cloning all aur dependencies, and building using mkpkg -si everything.

I dunno what do you think?

**Comment by actionless** [comment]
you can just use `git clone <URL> ./dir && pikaur -Pi ./dir`

i don't see any point in combining those

**Comment by DreamingRaven** [comment]
Okie dokes, was spit-balling anyway, just thought since git clone was already being used that it would be just a matter of letting the url through to where we call it. You are right tho, it does seem trivial when you put it that way since it only saves on a few keystrokes.

Thanks for the quick response as always tho!
