### ISSUE TITLE
[bug] pikaur shows new dependencies even if no more needed

### ISSUE THREAD

**Issue by mattia-b89** [actionless/pikaur#481]
```
$ pikaur -Vq
Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1
```

pikaur continues showing new dependencies to install,  
even if I removed the original package from upgrade list.

I noticed it today, before upgrading `hwinfo` package:  
removing it from the upgrade list, the plethora of _perl_ deps stay

_e.g.:  
package A has a new dep (that's package B);  
I launch `pikaur -Syu` and in the recap it shows the upgrade of package A and package B which will be installed too;  
Now, if I remove package A from upgrade list (press 'm' and edit)  
package B is still shown in the packages recap (prior the confirmation)_

---

**EDIT**
steps to reproduce it:
(this is an example, likely, other applications can reproduce it too)
* install or downgrade to previous release of **gedit** (gedit-3.36.1-1) and **hwinfo** (hwinfo-21.70-1); I downloaded manually it here, [Arch Linux Archive](https://archive.archlinux.org/)
* be sure (remove) you do not have these two packages (`perl-xml-parser` and `perl-xml-writer`) installed on your system
* start to upgrade your system as usual (`pikaur -Syu`); you will notice a plethora of *perl* packages that need to be installed as new dependency of **hwinfo**;  
as *acid test* you can try to upgrade those two packages individually: you will notice *gedit* does not bring any additional package.
* come back to upgrade process: do not continue with it but press **m** to *manually select packages* in order to remove **hwinfo** from the list
* at this point, pikaur shows **again** that plethora of *perl* deps needed by **hwinfo** even if it is no more in the upgrade list
* **NB:** if you continue in the upgrade process, all those *perl* packages even if listed in the upgrade process, will not be upgraded, thus it looks like a cosmetic bug

**Comment by actionless** [comment]
thanks for reporting, please add the minimal steps to reproduce it

**Comment by mattia-b89** [comment]
sure, I add it in OP

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by mattia-b89** [comment]
fixed!
