### ISSUE TITLE
Option to upfront edit PKGBUILD file

### ISSUE THREAD

**Issue by pejobo** [actionless/pikaur#483]
```
pikaur -Vq
Pikaur v1.6.10.r0.gf1b5c43
Pacman v5.2.1 - libalpm v12.0.1
```

##### Attached log:

I migrated from yaourt which as first step provided an option to edit the PKGBUILD file. 
Since many packages are not provided for my arm based platform even so they do build fine on arm I used this to change the arch to 'armv7h'. It's a bit tedious trying to convince maintainers to do so, so this is a workaround to make progress.

Looking at the docs there is no such option for pikaur. Would it be possible to add a configuration option for this?

**Comment by actionless** [comment]
there is a recovery prompt there right now, i think it covers it
