### ISSUE TITLE
asp is "required" for AUR download

### ISSUE THREAD

**Issue by yuyichao** [actionless/pikaur#485]
```
pikaur -Vq
Pikaur v1.6.10.r1.g2501ef6
Pacman v5.2.1 - libalpm v12.0.1
```

The [`optdepends` of `pikcur` states](https://github.com/actionless/pikaur/blob/2501ef608ddea71517e416d39abf0b3e7aed8355/PKGBUILD#L22)

> `asp: for ABS support in -G/--getpkgbuild operation`

However, if `asp` is not installed, an error is raised even if the package to be downloaded is on AUR and not ABS.

Indeed, `cli_gtpkgbuild` [checks the existance of `asp` as the first action](https://github.com/actionless/pikaur/blob/cadb86dd705f93342aa30f9e5f84c0c1afa12a4c/pikaur/main.py#L143)

This is probably a regression caused by https://github.com/actionless/pikaur/commit/4c6abd311ea8f9a909cc5eb796f6cd0cd1035553

I believe a better way to handle this is to only dod the check if there is any repo packages. i.e.

```diff
diff --git a/pikaur/main.py b/pikaur/main.py
index 7828a55..193d8f0 100644
--- a/pikaur/main.py
+++ b/pikaur/main.py
@@ -140,7 +140,6 @@ def cli_pkgbuild() -> None:


 def cli_getpkgbuild() -> None:
-    check_runtime_deps(['asp'])
     args = parse_args()
     pwd = os.path.abspath(os.path.curdir)
     aur_pkg_names = args.positional
@@ -162,6 +161,9 @@ def cli_getpkgbuild() -> None:
     if args.deps:
         aur_pkgs = aur_pkgs + get_aur_deps_list(aur_pkgs)

+    if repo_pkgs:
+        check_runtime_deps(['asp'])
+
     for aur_pkg in aur_pkgs:
         name = aur_pkg.name
         repo_path = os.path.join(pwd, name)
```

A better error message mentioning the feature that requires `asp` would also be nice.

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
