### ISSUE TITLE
Handling w/ Unofficial user repositories

### ISSUE THREAD

**Issue by chiboreache** [actionless/pikaur#492]
Here is the deal

<img width="908" alt="Screenshot_20200617_090059" src="https://user-images.githubusercontent.com/16459251/84861164-1c447000-b079-11ea-8821-645924a30555.png">

so, how can i choose the second one :?

_*repo positioning in the `/etc/pacman.conf/` doesn't affect on a result_
_**aur is just alias for `pikaur -S`_

**Comment by chiboreache** [comment]
it's pacman repo, not aur `~_~`

was misled by [guide](https://community.amd.com/thread/253882)

**Comment by chiboreache** [comment]
i'm sorry, but problem still here

aur helper installed packages from pacman repo

<img width="882" alt="Screenshot_20200617_223120" src="https://user-images.githubusercontent.com/16459251/84945241-b8a95980-b0ef-11ea-932e-f3830bc84935.png">

**Comment by actionless** [comment]
i can't reproduce your issue, it might be some repo configuration issue on your side:

![2020-06-18--1592515260_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/85073155-93355200-b1ba-11ea-9887-b26748a26b3e.png)

**Comment by chiboreache** [comment]
please [Add arch4edu to your Archlinux](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux) and try again

**Comment by actionless** [comment]
i don't need to add that crap on my machine to see what it's broken: 

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocm-dev
https://github.com/arch4edu/arch4edu/blob/master/rocm-dev/PKGBUILD

**Comment by chiboreache** [comment]
rocm-dev yeah..

but rocm-dkms(with llvm-amdgpu) works nice, and binary version in arch4edu, saved me a LOTs of time!
