### ISSUE TITLE
Remove the src and pkg dirs only after build

### ISSUE THREAD

**Issue by roussak** [actionless/pikaur#494]
It would be good to enhance clearing the build directory with an option to remove the `pkg` and `src` dirs only and keep other files.

**Comment by roussak** [comment]
This can be achieved via specifying `--mflags=-c` during install. But it doesn't look like a convenient way...

**Comment by actionless** [comment]
i don't see much of usecase for that (ecpecially since, as mentioned, `mflags` option exists)

 if demand would be higher, i could accept a pull request with patch for such extra option

**Comment by roussak** [comment]
First, this dirs consume a storage space. Second, they are mostly useless. Moreover, they can prevent successful build. But, on the other hand, the of tarballs or repositories kept may optimize a building process for the next time. In other words, there is no need to keep the same things twice.
By the way, this could be said about packages files stored by the `pikaur`. They are stored by the `pacman`. Why should we keep them twice?

**Comment by roussak** [comment]
I even tried to implement this feature. You can find the patch attached. But something went wrong and it doesn't work silently... :o(
[makepkg-clean.patch.zip](https://github.com/actionless/pikaur/files/4803538/makepkg-clean.patch.zip)

**Comment by actionless** [comment]
> First, this dirs consume a storage space. Second, they are mostly useless. Moreover, they can prevent successful build (of the newer package version, for example). But, on the other hand, the tarballs or repositories kept may optimize a building process for the next time. In the other words, there is no need to keep the same things twice.

for that there are already 2 related config options (and cli flags): https://github.com/actionless/pikaur#keepbuilddir-default-no and https://github.com/actionless/pikaur#keepdevbuilddir-default-yes

**Comment by roussak** [comment]
I saw them. But they do not cover all my use-cases. If I chose to keep the build dirs, the subject dirs will waste the storage. If, on the other hand, I chose to delete the build dirs, I will need to download sources on every upgrade. There is, for example, the `qt4` package in the AUR. It is updated rarely and its sources tarball is the same among last upgrades, but it is relatively big. That's why I could to keep the sources but to delete all intermediate stuff.

**Comment by roussak** [comment]
But what about -git packages?

**Comment by roussak** [comment]
I can imagine a (hypothetical) case when I could need the previous version of the source tarball, but I can't do it about the dirs we are discussing.

**Comment by roussak** [comment]
If it's interesting to you, you may take a look at [my repo](https://github.com/roussak/pikaur) to review how I implemented it.

**Comment by actionless** [comment]
> i still not convinced what smth beyond mflags is needed for this case

> If it's interesting to you, you may take a look at my repo to review how I implemented it.

in the repo i see you just added `mflags` as the config property and set it to some value of your liking

i don't mind adding the abiilty to set default makepkg args not only as `mflags` cli arg, but also in the config, so feel free to submit a PR for this
