### ISSUE TITLE
Cant edit PKGBUILD after build fail

### ISSUE THREAD

**Issue by random2324** [actionless/pikaur#499]
Hello,
trying to edit the PKGBUILD after a build fails simply restarts the build process. Editing doesn't work.

make[1]: Verzeichnis „/home/greg/.cache/pikaur/build/lib32-libheif/src/libheif-1.7.0“ wird verlassen
make: *** [Makefile:434: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

Ausführung des Befehls 'makepkg --force' ist fehlgeschlagen.
:: Versuchen, wiederherzustellen?
[R] Build nochmal versuchen
[p] überspringe PGP-Signaturprüfung
[c] überspringe Checksummen-Prüfung
[i] ignoriere Architektur
[d] entferne Build-Verzeichnis und versuche erneut
[e] edit PKGBUILD
------------------------
[u] überspringe Build dieses Pakets
[a] bauen aller Pakete abbrechen
> e

Pikaur v1.6.10.r11.gb0f54b1
Pacman v5.2.1 - libalpm v12.0.1

##### Attached log:

pikaur -S lib32-libheif --verbose --pikaur-debug
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['lib32-libheif']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Lese Repository-Paketdatenbank...
Lese lokale Paketdatenbank...
=> pacman --color=always --sync lib32-libheif --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['lib32-libheif']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'lib32-libheif': <VersionMatcher lib32-libheif['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=lib32-libheif
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "lib32-libheif" 1.6.2-1 -> 1.7.0-1>]
Löse AUR-Abhängigkeiten auf...
=> pacman --color=always --deptest lib32-gdk-pixbuf2 lib32-libde265 lib32-x265 libheif lib32-libjpeg lib32-libpng x265

:: Zu installierendes AUR-Paket:
 lib32-libheif                         1.6.2-1              -> 1.7.0-1

**Comment by actionless** [comment]
can't understand what's going on here

**Comment by random2324** [comment]
Pikaur doesnt take any commands after a build fail occur.
I'm doing pikaur -Syu for a full system upgrade including AUR packages. 

As can seen above, the building of a random package fails. So I want to edit the PKGBUILD, I press "e" as shown in the prompt ( [e] edit PKGBUILD ). But instead of showing me the PKGBUILD, it simply starts rebuilding the package. For me this looks like it cant interpret my keyboard input.

I just tested with LC_ALL=C and there I can press "e" and get into the editor. So its seems like a problem with the locale. Although crashing again after editing the PKGBUILD:

Resolving AUR dependencies...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 822, in build_packages
    pkg_build.build(
  File "/usr/lib/python3.8/site-packages/pikaur/build.py", line 705, in build
    build_succeeded = self.build_with_makepkg()
  File "/usr/lib/python3.8/site-packages/pikaur/build.py", line 674, in build_with_makepkg
    raise PkgbuildChanged()
pikaur.build.PkgbuildChanged

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 437, in main
    cli_entry_point()
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 326, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 987, in install_packages
    self.build_packages()
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 827, in build_packages
    self.handle_pkgbuild_changed(pkg_build)
  File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 792, in handle_pkgbuild_changed
    if old_install_info != self.install_info or old_srcinfo_hash != new_srcinfo_hash:
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 52, in __eq__
    return self_vars == other_vars
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 52, in __eq__
    return self_vars == other_vars
  File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 52, in __eq__
    return self_vars == other_vars
  [Previous line repeated 244 more times]
RecursionError: maximum recursion depth exceeded in comparison

**Comment by random2324** [comment]
Still a problem with Pikaur v1.6.11.r2.g92e6d1f

Reproduce:
Install lib32-ffmpeg 2:4.3.1-1 and lib32-x264 3:0.159.r2999.296494a-3
Do a system update with: `LC_ALL=de_DE.utf8 pikaur -Syu`
Wait till make process fails:
```
/usr/bin/ld: libavcodec/libavcodec.so: undefined reference to `x264_encoder_open_160'
/usr/bin/ld: libavcodec/libavcodec.so: undefined reference to `x264_encoder_open_160'
/usr/bin/ld: libavcodec/libavcodec.so: undefined reference to `x264_encoder_open_160'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [Makefile:114: ffmpeg_g] Fehler 1
make: *** Es wird auf noch nicht beendete Prozesse gewartet....
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [Makefile:114: ffprobe_g] Fehler 1
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [Makefile:114: ffplay_g] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```
Now the menu appears with different options:
```
Ausführung des Befehls 'makepkg --force' ist fehlgeschlagen.
:: Versuchen, wiederherzustellen?
[R] Build nochmal versuchen
[p] überspringe PGP-Signaturprüfung
[c] überspringe Checksummen-Prüfung
[i] ignoriere Architektur
[d] entferne Build-Verzeichnis und versuche erneut
[e] edit PKGBUILD
[u] überspringe Build dieses Pakets
[a] bauen aller Pakete abbrechen
```
If you now press "e" to edit the package build nothing happens. It just goes on with the next package.

But it works with `LC_ALL=en_US.utf8 pikaur -Syu`
Its also interesting that the english menu has different key input options. Skip building package is "s" in english and "u" in german. 

```
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
```

**Comment by actionless** [comment]
this seems like another unrelated issue, related to german locale strings

**Comment by random2324** [comment]
hmm I'm no programmer but if it understand this correctly, the locale file tries to "find" a text string in the other files and substitute it with the translation provided.

So in de.po:759 all code actually expecting "r" now expect an "e"
```
#: pikaur/install_cli.py:523 pikaur/install_cli.py:528 pikaur/build.py:644
#: pikaur/build.py:649
msgid "r"
msgstr "e"
```
which is fine because of de.po:537  
```
#: pikaur/install_cli.py:519
msgid "[r] remove dir and clone again"
msgstr "[e] entferne Verzeichnis und klone erneut"
```
but the "r" stays the same in de.po:491
```
#: pikaur/build.py:631
msgid "[R] retry build"
msgstr "[R] Build nochmal versuchen"
```
and as nothing changes in de.po:614 we have now answer "e" twice.

```
#: pikaur/install_cli.py:212 pikaur/install_cli.py:215 pikaur/build.py:644
#: pikaur/build.py:663
msgid "e"
msgstr ""
```

So when I want to retry a build, it actually expects an "e" from me. As I type "R" it just skips and move on to another build. When I type "e" it doesnt show me the editor and retry building.

**Comment by ikselven** [comment]
> Its also interesting that the english menu has different key input options. Skip building package is "s" in english and "u" in german.

Some of the keys are adapted to the locale, i.e. "u" makes more sense for "überspringe Build des Pakets" than the original key "s". As you already mentioned in your last comment, there is a translation entry that maps English "s" to German "u". However, the limitation here is, that all English strings showing the "s" key require the "u" key in their German translation.

The German locale could use an update anyway, as there are some new untranslated strings, so I'm going to fix this issue with the next translation update.

**Comment by actionless** [comment]
@random2324 please check if `pikaur-git` works for you after @ikselven 's patch got merged

**Comment by random2324** [comment]
Can confirm its working now. Thanks!

**Comment by actionless** [comment]
thanks again, @ikselven !
