### ISSUE TITLE
doas support bug?

### ISSUE THREAD

**Issue by xnegra80** [actionless/pikaur#503]
Hi I can't get it to work. Example: i put `pikaur -S somepackage` I get something like this:

```
doas: invalid option -- 'T'
usage: doas [-ns] [-a style] [-C config] [-u user] command [args]
doas: invalid option -- 'T'
usage: doas [-ns] [-a style] [-C config] [-u user] command [args]
```

Is there something wrong with the placement of the doas command?

_Originally posted by @xnegra80 in https://github.com/actionless/pikaur/pull/455#issuecomment-660664627_

**Comment by actionless** [comment]
cc @NeoTheFox

**Comment by NeoTheFox** [comment]
Can't reproduce this on my machine. How's your `/etc/doas.conf` and `pikaur.conf` look like? Seems like you have an extra "T" somewhere...

**Comment by xnegra80** [comment]
I was using the `doas` package from the aur that's why.
Got it working using `opendoas` from the community repo
