### ISSUE TITLE
Add option to cache aur package names

### ISSUE THREAD

**Issue by AKorezin** [actionless/pikaur#504]
Can you add an option to cache aur package names?
Pikaur always try to check aur for packages and it takes a lot of time. If I use autocompletion it will take some time to resolve every autocompletion request.

So it will be good to create a local cache of all aur packages from `https://aur.archlinux.org/packages.gz`. And update it every time you run `pikaur -Syu`.

##### Pikaur version
```
# pikaur -Vq
Pikaur v1.6.10
Pacman v5.2.2 - libalpm v12.0.2
```

**Comment by actionless** [comment]
> If I use autocompletion it will take some time to resolve every autocompletion request.

it's cached by auto-completion itself:
https://github.com/actionless/pikaur/blob/master/packaging/usr/share/fish/completions/pikaur.fish#L8-L36

**Comment by AKorezin** [comment]
And what about bash?

**Comment by actionless** [comment]
idk, not using them

feel free to contribute it to their completion
