### ISSUE TITLE
Installing AUR packages fails with -q / --quiet

### ISSUE THREAD

**Issue by jplatte** [actionless/pikaur#508]
It seems like pikaur always passes `--quiet` to pacman when it received `-q` / `--quiet` itself. However, pacman only has a quiet flag for query, sync, database and file, **not** upgrade and so installing AUR packages this way fails.

```
pikaur -Vq
Pikaur v1.6.11
Pacman v5.2.2 - libalpm v12.0.2
```

##### Attached log:

```
% pikaur -Sq --noconfirm pikaur
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
looking for conflicting AUR packages...
Not showing diff for pikaur package (--noconfirm)
:: Skipping review of PKGBUILD for pikaur package (--noconfirm)

:: Package pikaur is already built. Pass '--rebuild' flag to force the build.

error: invalid option '--quiet'
Command 'sudo pacman --color=always --upgrade --quiet --noconfirm /home/jplatte/.cache/pikaur/pkg/pikaur-1.6.11-1-any.pkg.tar.zst' failed to execute.
Do you want to retry? [N]o (--noconfirm)
Do you want to proceed? [N]o (--noconfirm)
```

**Comment by actionless** [comment]
```
$ pikaur -Sh | grep quiet
  -q, --quiet          show less information for query and search
```

**Comment by actionless** [comment]
however there exists (hidden) debug flag `--hide-build-log`

**Comment by jplatte** [comment]
You misunderstood this issue. I'm not asking you to add a new flag, I was reporting a bug. Please take a look at the error message in the attached log.

**Comment by actionless** [comment]
it's not a bug

**Comment by jplatte** [comment]
So `pikaur -Syuq` is supposed to fail if there are AUR packages to update?

**Comment by actionless** [comment]
is not related to aur packages, read again the help message for the flag

**Comment by jplatte** [comment]
I see. So (maybe?) `pacman -Syuq` doesn't even hide anything, and as such not having `pikaur -Syuq` work doesn't matter much. Thanks!
