### ISSUE TITLE
prioritize specific packages from AUR

### ISSUE THREAD

**Issue by LouisDK1** [actionless/pikaur#514]
```
pikaur -Vq

Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2

```
I use some patched Firefox package from AUR that require a language package from the main repos.
When an update comes to Firefox pikaur will sugguest to install the normal firefox package to satisfy the language package resulting in my patched Firefox getting uninstalled before I can upgrade the patched version from AUR.

Is there a way to prioritize specific packages in AUR to get updated before the other packages or a way to make specific packages getting upgraded as the last?

**Comment by actionless** [comment]
> I use some patched Firefox package 

change `pkgname`

**Comment by LouisDK1** [comment]
> > I use some patched Firefox package
> 
> change `pkgname`

Package is called "firefox-appmenu-bin" but when I recieve an update to firefox-i18n-da and don't update firefox-appmenu-bin at first it'll replace it with the regular firefox doing the update of firefox-i18n-da.

**Comment by actionless** [comment]
ah, firefox-i18n-da have a versioned dependency on firefox

set versioned dependency on firefox-i18n-da in your firefox forked package and put firefox-i18n-da to ignored packages, that might work

otherwise you can write an update script/etc
