### ISSUE TITLE
Bash tab completion doesn't account AUR

### ISSUE THREAD

**Issue by Meister1593** [actionless/pikaur#519]
```
Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2
bash 5.0.018-1
bash-completion 2.11-1
```

##### Prerequisites:

When doing bash tab completion, it fetches first query from repos and doesn't account AUR.
I've seen #243 issue and it seems that bash should not be an exception too, right? 
`pikaur -S turbo <tab><tab>` gives `turbostat` but not results of AUR with simular name.
`pikaur -S pik <tab><tab>` doesn't give anything at all

**Comment by actionless** [comment]
you can use fish completion as a reference (i myself using fish, so it guarantees what it always in a working state :) )

**Comment by baj0k** [comment]
Pikaur v1.9
Pacman v6.0.1 - libalpm v13.0.1
GNU bash, version 5.1.12(1)-release
bash-completion 2.11-2

Works like a charm

I believe this has been already resolved in #https://github.com/actionless/pikaur/commit/32f5ed26f63fd489c2fb4921476f543d3a5e0dc5

**Comment by actionless** [comment]
thanks for update @baj0k !
