### ISSUE TITLE
Converting from unix time to regular date

### ISSUE THREAD

**Issue by MartinSandfuchs** [actionless/pikaur#52]
Currently when listing package information from aur packages dates are listed in a rather unreadable unix timestamp format. For example when running
`pikaur -Si pikaur-git`
...
`firstsubmitted  : 1517379650`
`lastmodified    : 1519879070`
...

More closely following the format that pacman uses for displaying package information might enhance readability in general

**Comment by actionless** [comment]
fixed in #56
