### ISSUE TITLE
"pikaur -Ss search" results sometimes in a  segmentation fault

### ISSUE THREAD

**Issue by qupfer** [actionless/pikaur#520]
Hi, I found a strange behavior on my system. 

```
pikaur -Vq
Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2

```
##### Attached log:

```
pikaur -Ss python3-tk --verbose --pikaur-debug
Suche... [---][1]    5326 segmentation fault (core dumped)  pikaur -Ss python3-tk --verbose --pikaur-debug

pikaur -Ss python3-tk --verbose --pikaur-debug
Suche... [---]#=> GET https://aur.archlinux.org/rpc/?v=5&type=search&arg=python3-tk&by=name-desc
##

```
It does not depends on the search word and happens not always, but time to time. 

Any ideas? 

Its only on one of my systems, so maybe its related to some dependencies or complete other reasons :-D 

Thanks

**Comment by actionless** [comment]
yeah, python is managed language so it couldn't segfault by itself

**Comment by qupfer** [comment]
any ideas how find out, what (sub) routine/programm cause that error?

**Comment by actionless** [comment]
you could try to to run it with gdb and during the crash to ask for the traceback

**Comment by qupfer** [comment]
I tried, seems to do with libalpm.so.11.
Then I removed pikaur, installed manual pyalpm with pacman, and then re-install pikaur. Now it seems working correct again.
Thanks

**Comment by actionless** [comment]
mb you had version mismatch of pyalpm libalpm

**Comment by actionless** [comment]
glad it resolved anyway :3

**Comment by actionless** [comment]
btw mb good idea to also output pyalpm version in pikaur -V
