### ISSUE TITLE
Is there a way to switch vim to nano for PKGBUILD?

### ISSUE THREAD

**Issue by cgcgcgcgcg** [actionless/pikaur#523]
It's the only reason I'm not currently using pikaur.

**Comment by Morganamilo** [comment]
Set your VISUAL/EDITOR to nano.

**Comment by cgcgcgcgcg** [comment]
Thank you, and sorry for thinking you explicitly linked vi or vim to the editor, should have checked before.
I just added those to my config.fish:
`export EDITOR="nano"
export VISUAL="nano"`
