### ISSUE TITLE
pikaur asks to review pkgbuilds twice, when one is edited

### ISSUE THREAD

**Issue by deathtrip** [actionless/pikaur#525]
```
pikaur -Vq
Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2
```
##### Description:
When installing multiple packages, and after one pkgbuild is edited and saved, pikaur will restart the installation process, and ask to review already accepted pkgbuilds. It should only ask about those that were not previously reviewed.

**Comment by naufik** [comment]
```
~ % pikaur -Vq
Pikaur v1.8
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

Adding extra info that this also happens if you edit your `pkgbuild` due to installation failure. Pikaur will go back to the initial pkgbuild verification.
