### ISSUE TITLE
Installing via multiple pikaur sessions reverts installed packages on error

### ISSUE THREAD

**Issue by eleius** [actionless/pikaur#528]
```
Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2
```

Description:
I usually tend to install packages using multiple terminal tabs when installation takes time (e.g. compiling from AUR). Lately I also noticed packages I was sure I had installed weren't there...

Today, I installed Arch on a new notebook and used pikaur to install openmsx (about 15 minutes compile time), meanwhile I was using a different terminal tab to install many other packages.

At some point openmsx finished compiling but pikaur complained pacman was locked, so it asked me if I wanted to retry installing or abort. I choose retry, and to my horror it uninstalled about 140 packaged I had installed while it was working, and then it happily installed openmsx.

Is this a bug in pikaur or is it normal pacman behavior?

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

as you can see from the diff - it already had `@TODO` marker for adding a lock there :)

**Comment by eleius** [comment]
So I've tried the latest git package:
Pikaur v1.6.12.r16.g8341e0c
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.1

Then after installing several packages without issues, I installed r-stringr from AUR. It took a while, then pikaur said:

Finished making: r-stringr 1.4.0-1 (thu 19 nov 2020, 09:50:27)
:: error: Failed to remove installed dependencies, packages inconsistency: protobuf, imlib2, libdbusmenu-glib, dnssec-anchors, gtk-vnc, serd, soundtouch, libnfs, hwinfo, python2-pycurl, flashrom, recode, lib32-util-linux, leafpad, libdca, dhex, hyphen, libsasl, gnome-font-viewer, gsettings-desktop-schemas, mcomix, libdaemon, nspr, groff, libgxps, liblangtag, libpciaccess, libcanberra, tbb, jhead, libxft, linux-api-headers, perl, sdl, gparted, lib32-libxshmfence, pipewire, libibus, lib32-gettext, speexdsp, gnome-online-accounts, libwpe, gom, xf86-video-vesa, gvfs-goa, libical, openjpeg2, spandsp, libsndfile, progress, python-grip, lib32-libssh2, pinentry, libxdamage, python-mutagen, avidemux-qt, wvstreams, bleachbit, jitterentropy-git, libavtp, hwloc, lapack, xorg-xmessage, gnome-user-docs, gpm, lib32-fontconfig, cpulimit, libcdr, gnome-shell-extensions, python2-idna, bc, libsamplerate, yelp-xsl, libqmi, libofa, libmodplug, python2-ordered-set, glib-perl, xterm, lzo, babl, iso-codes, libedit, baobab, qt5-sensors, upower, libxcomp, python-pyqt5, x264, ffmpegthumbnailer, adwaita-icon-theme, libmnl, automake, python2-cachecontrol, libnl, python-soupsieve, enca, libslirp, rav1e, gnome-boxes, lib32-keyutils, wget, icu, folks, gcr, alsa-lib, gnome-tweaks, python2-cryptography, r, rtmpdump, libtheora, cifs-utils, libnotify, adobe-source-code-pro-fonts, tdb, gtkspell, pangomm, python2-appdirs, libogg, nautilus, paprefs, lib32-libdrm, boost-libs, libsoup, geoclue, go, python-pyopenssl, mpv, nvidia, sudo, python2-importlib-metadata, python-cairo, libvpx, device-mapper, libstemmer, libvdpau, xorg-server, gst-editing-services, python-markdown, libtool, rdesktop, xvidcore, ltrace, s-tui, unace, graphite, libasyncns, python-scapy, opus, libepoxy, scapy, gedit, gcc-libs, python2-distro, python-pyzmq, lib32-libjpeg-turbo, perl-net-ssleay, libunibreak, fontconfig, apr, python-pip, libnice, snappy, fakeroot, avahi, python-pygments, perl-image-exiftool, perl-html-tagset, libgtop, perl-clone, pyalpm, desktop-file-utils, python-requests, lib32-ncurses, libdvdcss, gdk-pixbuf2, gnome-terminal, yelp, ttf-bitstream-vera, perl-libintl-perl, perl-io-socket-ssl, c-ares, pam, vte-common, libgnomekbd, libgrss, libsodium, nautilus-sendto, qt5-location, webrtc-audio-processing, libvisio, systemd-libs, libquicktime, gegl, libbytesize, rygel, libtasn1, libxtst, unbound, python2, libavc1394, trickle, perl-www-robotrules, gnome-music, python2-ipaddress, ttf-carlito, libmpc, lib32-freetype2, blas, python-cryptography, xcb-proto, cabextract, zita-alsa-pcmi, m4, python-werkzeug, zita-resampler, cups, autogen, numactl, downgrade, rar, libguess, hunspell, ppp, usbredir, detox, jsoncpp, libarchive, libdvdread, yajl, php, archlinux-keyring, vino, glib-networking, evolution-data-server, fuse-common, jfsutils, cups-pdf, argon2, gnome-menus, smbclient, gucharmap, gcab, zvbi, minicom, brotli, libexttextcat, findutils, python2-pycparser, ldns, zip, ca-certificates-utils, htop, perl-xml-libxml, retext, hwids, net-tools, perl-dbi, qt5-multimedia, nss-mdns, wine, libatomic_ops, libgee, python-asn1crypto, python2-progress, shared-mime-info, rest, libatasmart, libkate, mypaint-brushes1, xboard, webkit2gtk, taglib, python2-pep517, libunistring, xdg-user-dirs, mtdev, links, nvidia-utils, noto-fonts-cjk, linux-headers, libopenshot, zenity, usbmuxd, hdparm, gtkspell3, l-smash, cmake, mpack, vamp-plugin-sdk, wireless-regdb, mkinitcpio-nfs-utils, putty, lib32-harfbuzz, run-parts, double-conversion, mkvtoolnix-cli, libssh2, clucene, mutter, xf86-video-fbdev, uchardet, diffutils, tracker3-miners, libebur128, gnome-usage, mplayer, python-html5lib, cairo-perl, texinfo, fwupd, vte3, gnome-online-miners, phodav, jre8-openjdk-headless, lib32-glibc, libxaw, tlp, lib32-libxi, rsync, gsfonts, geoip, openexr, libfreehand, alsa-plugins, libmediaart, seahorse, lsb-release, djview, libcap, gvfs-smb, lib32-libpng, python2-webencodings, wildmidi, chromaprint, mpg123, python-markdown-math, gtk2, libxpm, libgusb, lib32-libxcrypt, libmicrohttpd, lpsolve, bzip2, gtkmm3, foomatic-db, xxhash, bind, unshield, accountsservice, qemu, zbar, woff2, dleyna-server, libassuan, qbittorrent, libusbmuxd, vi, alsa-utils, bluez, libdvbpsi, spek-alternative, xcb-util-image, python-distro, perl-xml-parser, mailcap, glslang, autoconf, gnome-books, unarj, json-glib, gpgme, libquvi-scripts, libpaper, elfutils, wayland-protocols, python-beautifulsoup4, libteam, xkeyboard-config, gnome-clocks, wvdial, wxgtk2, sdl2, gimp, cracklib, glances, fmt, libetonyek, liborcus, metis, iptables, libgme, binutils, s-nail, git, java-runtime-common, gptfdisk, graphene, xdg-utils, libosinfo, zlib, pulseaudio-alsa, libcloudproviders, make, gd, gtkhash, libvirt, libmpeg2, foomatic-db-engine, libsmbios, ttf-dejavu, lib32-libffi, ttf-ubuntu-font-family, libao, perl-mailtools, libdazzle, libxklavier, celluloid, pulseaudio-bluetooth, xl2tpd, fdupes, kmod, python-jinja, portaudio, libjpeg-turbo, llvm-libs, libimagequant, pixman, shared-color-targets, python2-retrying, wxgtk3, totem-pl-parser, libidn, hidapi, glu, libxcursor, mpfr, lib32-libxdamage, npth, libappindicator-gtk3, gsm, cups-pk-helper, libnghttp2, libxt, startup-notification, libseccomp, libmng, libcddb, libopenraw, python-retrying, libmypaint, egl-wayland, perl-file-which, guile, gstreamer, perl-capture-tiny, subversion, mat2, parallel, openvpn, lib32-libnl, libsidplayfp, efivar, xdg-user-dirs-gtk, unp, libportal, libxfixes, hiredis, alsa-ucm-conf, python-cffi, vid.stab, python-future, clutter, json-c, perl-try-tiny, python-psutil, lua52-expat, lib32-libldap, libxdmcp, keyutils, perl-lwp-mediatypes, libplist, gnome-desktop, gnome-backgrounds, perl-net-http, transcode, libxnvctrl, lzop, shadow, file-roller, gdm, lib32-libsm, libxfont2, perl-uri, ntfs-3g, gnome-system-monitor, lib32-zlib, wxgtk-common, bison, media-player-info, tar, doxygen, libsecret, ijs, lua52-lpeg, noto-fonts, python2-scandir, python-docopt, python-resolvelib, lua52-socket, psmisc, perl-lwp-protocol-https, mdadm, lrzip, gnome-disk-utility, gvfs-mtp, lib32-libcap, lua52, intltool, openshot, p11-kit, gvfs-afc, lua, curl, solid, lib32-libx11, libbs2b, libpagemaker, python2-pyopenssl, gnome-photos, perl-alien-build, gtksourceview4, librsvg, libmtp, dav1d, lib32-acl, fluidsynth, lirc, sdl2_ttf, liboauth, libxslt, hddtemp, gnome-video-effects, dconf, lib32-libgpg-error, python-itsdangerous, grilo, gst-plugins-bad, nxproxy, perl-timedate, gavl, efibootmgr, ttf-croscore, lib32-icu, xorg-setxkbmap, cups-filters, faudio, stress, libglvnd, libindicator-gtk3, xdg-dbus-proxy, perl-alien-libxml2, usbutils, libxrender, perl-xml-sax, gnome-control-center, libheif, inxi, lensfun, lib32-zstd, lib32-glib2, python-pycups, python-markupsafe, swig, gtk-update-icon-cache, libsrtp, gutenprint, libquvi, strace, alsa-card-profiles, ldb, python2-html5lib, pkcs11-helper, zxing-cpp, djvulibre, lib32-libxxf86vm, libraqm, libspiro, wireshark-cli, lm_sensors, libhandy, js78, soundconverter, pavucontrol, python2-ply, nm-connection-editor, python-html2text, nvidia-settings, gst-plugins-ugly, xf86-video-intel, libpipeline, lib32-libxfixes, sushi, gobject-introspection-runtime, enchant, mencoder, libnumbertext, nano, bubblewrap, patch, fribidi, python-markups, libxi, sbc, virglrenderer, colordiff, faad2, perl-xml-sax-base, libsynctex, wpebackend-fdo, pdfgrep, man-pages, libxrandr, libgpg-error, libxxf86vm, sword, python2-cffi, libmwaw, arptables, gnome-getting-started-docs, lmdb, e2fsprogs, python-cachecontrol, libshout, lib32-krb5, libabw, libuv, tpm2-tss, python-six, opencore-amr, gnome-calculator, lib32-libgcrypt, arc-gtk-theme, libdbusmenu-gtk3, xcb-util-renderutil, clutter-gst, logrotate, fuse3, grilo-plugins, t1lib, foomatic-db-gutenprint-ppds, libpwquality, xcb-util-keysyms, ntpdate, libplacebo, arch-audit, openssl, perl-locale-gettext, libaio, libxinerama, gvfs-gphoto2, python-ply, gnome-characters, gnome-autoar, neofetch, gnome-bluetooth, dialog, qt5-x11extras, lib32-libxml2, python2-zipp, libva, mesa, libjcat, confuse, gnome-calendar, python-setuptools, tslib, libde265, perl-path-tiny, iana-etc, python2-backports, libsoxr, cheese, bcg729, unzip, python-dbus-common, python-pyqt5-sip, redland, rhash, graphicsmagick, lcms2, hicolor-icon-theme, net-snmp, pacman, gnome-color-manager, python-contextlib2, pidgin-otr, rasqal, suitesparse, libimobiledevice, python-pyxdg, cairomm, f2fs-tools, seabios, gmp, winetricks, osinfo-db, libgphoto2, openresolv, speex, libzapojit, python2-pyparsing, libksba, libass, networkmanager-openvpn, gmime3, libdmapsharing, gnome-user-share, gawk, mkinitcpio-busybox, cairo, licenses, gsound, libxcrypt, wine-mono, intel-ucode, frei0r-plugins, mod_dnssd, perl-html-parser, perl-encode-locale, libffi, dbus, hstr-git, gtk3, nvme-cli, gnome-remote-desktop, libgudev, krb5, libpulse, rtkit, nss, python2-setuptools, webp-pixbuf-loader, libxkbcommon, gspell, talloc, librevenge, libmicrodns, xorg-xinput, libproxy, libwebp, pikaur-git, pango, libpurple, lib32-libxcb, nettle, eglexternalplatform, diffuse, libnma, vpnc, reiserfsprogs, libnfnetlink, tcpdump, xorg-fonts-encodings, libomxil-bellagio, libgdm, libdc1394, libunwind, libldap, db, libhandy0, dleyna-core, cantarell-fonts, gnome-screenshot, libcanberra-pulse, x265, portsmf, which, glibmm, srt, python-webencodings, jpegoptim, openssh, liblouis, libgadu, lib32-xz, libxv, gvfs-google, python2-distlib, tracker3, libstaroffice, libbluray, cryptsetup, man-db, python-pycurl, gcolor2, nasm, libspeechd, python-shiboken2, xorg-xauth, libixion, libtorrent-rasterbar, libspectre, pcre, libpsl, xorgproto, audacity, libexif, libgssglue, harfbuzz-icu, fbreader, libgepub, qpdf, python-urllib3, base, ca-certificates-mozilla, gst-plugin-gtk, gssdp, handbrake, tzdata, libnetfilter_conntrack, grep, flex, evince, gnu-free-fonts, xorg-xmodmap, libcaca, exiv2, bluez-libs, libxshmfence, libnftnl, lib32-curl, gtksourceview3, giflib, libvisual, slang, xplc, libiptcdata, perl-xml-writer, python-msgpack, python-pep517, aom, udisks2, v4l-utils, colord-gtk, libusb, less, wpa_supplicant, mujs, xsel, spice, lib32-sdl2, lib32-libice, asunder, xorg-xrandr, python, libxcomposite, libmspub, libgdata, anydesk-bin, fakepkg, audacious-plugins, hardinfo, python-ordered-set, python2-urllib3, ttf-caladea, gnome-weather, openssl-1.0, at-spi2-core, xchm, glibc, clipit, libwpd, pacman-contrib, lib32-glu, pacman-mirrorlist, libepubgen, lib32-libxau, python2-enum34, ruby-irb, python2-chardet, util-linux-libs, networkmanager, twolame, lua52-luajson, wavpack, libxss, gnome-keyring, libnsl, gjs, avidemux-cli, libxau, filesystem, freerdp, libopenshot-audio, reflector, lib32-libxcursor, linux, gnome-nettool, ndisc6, libtar, libnautilus-extension, libmad, lib32-lcms2, gst-plugins-base, dotconf, sord, libdv, modemmanager, libelf, libphonenumber, libutempter, sane, libbsd, hsync, lib32-libidn2, libotr, at-spi2-atk, gnuchess, libmatroska, mjpegtools, ipw2100-fw, popt, p7zip, libebml, cdparanoia, libxmlb, faac, filezilla, libcdio, ttf-liberation, xmlsec, file, lib32-gcc-libs, polkit, orca, lib32-libunwind, wireshark-qt, re2, libcroco, mobile-broadband-provider-info, python-pycparser, glib2, brltty, lib32-libunistring, libgcrypt, lib32-libxext, xorg-xkbcomp, tcl, mtools, tepl, libdvdnav, ndctl, cdrtools, gst-libav, md4c, gnome-logs, mlt, gnome-epub-thumbnailer, apr-util, gupnp, liburing, sound-theme-freedesktop, volume_key, libwacom, jasper, poppler-data, thin-provisioning-tools, systemd-sysvcompat, lib32-bzip2, gnu-netcat, dmraid, xorg-server-xwayland, nodejs, libvirt-glib, gnutls, python2-contextlib2, libpgm, gtkglext, libpeas, libxcb, lib32-libtiff, opencv, gnome-multi-writer, lvm2, poppler-glib, lib32-openssl, libxmu, lib32-llvm-libs, gst-plugins-bad-libs, lib32-pcre, libmfx, pptpclient, lib32-libpsl, mp3gain, foomatic-db-ppds, ccrypt, tracker, libwpg, suil, aalib, sqlite, gtop, arj, perl-error, vbindiff, libusb-compat, shaderc, gvfs, python-progress, ncftp, perl-http-daemon, libdrm, pdfcrack, xcb-util, python2-configparser, alsa-topology-conf, python2-toml, spirv-tools, libxvmc, fuse2, lame, stoken, system-config-printer, vulkan-icd-loader, libnewt, libzmf, xorg-xset, pciutils, dhclient, dbus-glib, bash, pulseaudio, gfbgraph, usb_modeswitch, perl-http-date, libid3tag, xorg-xinit, lib32-e2fsprogs, libidn2, iwd, python-docutils, libcacard, rubberband, foomatic-db-nonfree-ppds, fftw, lib32-expat, sed, a52dec, lib32-attr, libgsf, lib32-libnsl, perl-ffi-checklib, python-chardet, libndp, yad, libupnp, libtommath, qt5-webkit, lrzsz, glew, kbd, perl-io-html, lsof, luajit, libgexiv2, libfontenc, libiec61883, python-pyparsing, gupnp-igd, orc, libgweather, oniguruma, iproute2, xz, libp11-kit, os-prober, libxml2, dos2unix, lib32-wayland, qt5-webengine, apache, lib32-libelf, dmidecode, perl-rename, ethtool, inetutils, gupnp-av, linux-atm, rpmextract, rp-pppoe, xorg-server-common, sratom, xfsprogs, noto-fonts-emoji, chmlib, ncurses, lib32-libglvnd, python-appdirs, qt5-declarative, simple-scan, gst-plugins-good, linux-firmware, libwmf, jdk8-openjdk, gprename, telepathy-glib, wipe, lhasa, qt5-base, qt5-svg, dleyna-connector-dbus, serf, pdf-compress, python2-pip, bolt, ghex, pcsclite, libsigc++, sysfsutils, ffmpeg, libmbim, libsidplay, firefox, lib32-libpciaccess, acl, python2-asn1crypto, openmpi, patchelf, raptor, libsm, luit, lib32-faudio, lib32-pam, python-gobject, xf86-input-libinput, lib32-libxrandr, audacious, meld, libyaml, libnm, readline, pambase, gnome-documents, gettext, lib32-libxdmcp, farstream, libcups, parted, python-urwid, flac, libpcap, lua52-bitop, colord-sane, libdatrie, libwps, cogl, lib32-libxrender, libfilezilla, libcmis, python-toml, b43-fwcutter, python2-resolvelib, svt-hevc, ghostscript, ca-certificates, libthai, libtirpc, gc, xorg-xhost, audit, libmms, libchamplain, libxkbfile, time, python2-pathlib2, gnome-maps, libftdi, gdbm, neon, zeromq, libmusicbrainz5, libcdio-paranoia, liblqr, perl-file-chdir, libxres, libinput, tevent, procps-ng, uget, pidgin, python-flask, jbig2dec, xcb-util-wm, smartmontools, alsa-firmware, libinstpatch, python2-requests, geocode-glib, gtk2-perl, libmaxminddb, libmpcdec, dleyna-renderer, libraw, foomatic-db-nonfree, python-packaging, wayland, ipw2200-fw, gpart, gupnp-dlna, libqxp, lib32-systemd, dosfstools, python2-six, atkmm, ruby-reline, libvncserver, iotop, minizip, java-environment-common, gnome-settings-daemon, perl-http-message, imagemagick, libx11, colord, libraw1394, clutter-gtk, tracker-miners, ruby, libcue, protobuf-c, totem, jre8-openjdk, jansson, python-atspi, lz4, vlc, gnome-contacts, pkgconf, libvorbis, dbus-broker, util-linux, cblas, pcurses, libmm-glib, eog, qt5-webchannel, perl-xml-namespacesupport, libieee1284, python-dbus, btrfs-progs, vde2, mlocate, python-distlib, libpng, edk2-ovmf, mkinitcpio, libssh, freetype2, coreutils, python2-msgpack, libtiff, pango-perl, libevdev, chrome-gnome-shell, perl-http-cookies, gmic, gvfs-nfs, libxkbcommon-x11, gnome-session, speech-dispatcher, gnome-shell, gcc, sharutils, viewnior, xbitmaps, harfbuzz, libice, iputils, perl-http-negotiate, libevent, exempi, grub, python-pillow, wireless_tools, openal, python-idna, spice-gtk, attr, geoip-database, libcap-ng, amtk, fstrm, perl-libwww, jack, rubygems, libxext, thunderbird, gimp-plugin-gmic, python-path-and-address, poppler, libe-book, systemd, python2-packaging, vmaf, zstd, gzip, whois, python-colorama, lilv, streamripper, gnome-themes-extra, lib32-lm_sensors, lib32-mesa, libodfgen, libfdk-aac, lib32-nvidia-utils, xorg-xkill, bash-completion, lib32-libpcap, libx86emu, xorg-xrdb, gpick, lib32-readline, libblockdev, libzip, liblrdf, libreoffice-fresh, expat, libutf8proc, pcre2, lib32-dbus, dnsmasq, httrack, lib32-lz4, powertop, xorg-xprop, gnupg, gst-plugins-base-libs, openconnect, splix, atk, iw, perl-file-listing, lib32-libtirpc, libwnck3, python-click, python2-colorama, netctl
Do you want to proceed? [Y/n]

**Comment by eleius** [comment]
It just happened again with a different package :-/

**Comment by actionless** [comment]
thanks a lot for testing!

i've tried to extend the lock to be put earlier, i hope it finally will fix it

**Comment by eleius** [comment]
Nothing unsual to report at the moment, seems to work.

**Comment by konomikitten** [comment]
I'm rather new to Arch Linux but I tried `pikaur 1.6.14-1` and ran into this issue too where trying to do `pikaur -S crazydiskmark` ended up giving the error of `:: error: Failed to remove installed dependencies, packages inconsistency:`. Switching to `pikaur-git` seems to have fixed the problem specifically I installed `pikaur-git 1.6.14.r1.g17feee7-1` and no longer have this issue when doing `pikaur -S crazydiskmark`. Hope that helps for testing information.

**Comment by actionless** [comment]
@konomikitten unfortunately it's not enough, i need full logs, preferable with `--pikaur-debug` flag

**Comment by actionless** [comment]
btw, to workaround this issue you can press "Y" when it prints this error, and next remove unneedeed deps manually, with `pacman -Rs $(pacman -Qtdq)` command

**Comment by konomikitten** [comment]
@actionless unfortunately it seems the git release has this issue too if I run the command once then get the error and press no then I run the command again the error does not seem to appear. I've attached detailed logs of both pikaur and pikaur-git. Let know if you need additional information.

[pikaur_v1.6.14-1.log](https://github.com/actionless/pikaur/files/5648777/pikaur_v1.6.14-1.log)
[pikaur_v1.6.14.r1.g17feee7.log](https://github.com/actionless/pikaur/files/5648779/pikaur_v1.6.14.r1.g17feee7.log)

**Comment by actionless** [comment]
@konomikitten i've added additional debug logging to `pikaur-git` could you please run it again so i'll have more debug output?

**Comment by konomikitten** [comment]
@actionless I ran the command twice this time to show how it fails the first time and works the second time, I used makepkg -si and got the source directly from your GitHub.

[pikaur_v1.6.14.r2.g92ede58.txt](https://github.com/actionless/pikaur/files/5648831/pikaur_v1.6.14.r2.g92ede58.txt)

**Comment by actionless** [comment]
@konomikitten apparently the issue you discovered is not related to the original one

please try if latest `pikaur-git` fixes it

**Comment by konomikitten** [comment]
@actionless oh sorry for posting in the wrong thread then! When you say `pikaur-git` do you mean https://github.com/actionless/pikaur.git or https://aur.archlinux.org/pikaur-git.git?

**Comment by actionless** [comment]
it's correct thread since the error message is the same, just the rootcause of the issue is different

i mean https://aur.archlinux.org/pikaur-git.git

**Comment by konomikitten** [comment]
@actionless the reason I ask is because https://aur.archlinux.org/pikaur-git.git doesn't seem up to date:

```
bash ~/Downloads/pikaur-git
$ git pull
Already up to date.
bash ~/Downloads/pikaur-git
$ git ls-remote
From https://aur.archlinux.org/pikaur-git.git
9e8171d8f8127eb3c1bc7983d3c92f9ebbc58ef7        HEAD
9e8171d8f8127eb3c1bc7983d3c92f9ebbc58ef7        refs/heads/master
bash ~/Downloads/pikaur-git
$ git log -1
commit 9e8171d8f8127eb3c1bc7983d3c92f9ebbc58ef7 (HEAD -> master, origin/master, origin/HEAD)
Author: actionless <actionless.loveless@gmail.com>
Date:   Fri Dec 4 12:49:22 2020 +0100

    update to 1.6.14
bash ~/Downloads/pikaur-git
$
```

**Comment by actionless** [comment]
it shouldn't, that's the way how `-git` packages work in aur

**Comment by konomikitten** [comment]
@actionless ah okay new to arch and all I think I get it now, attached a new log.

[pikaur_v1.6.14.r3.gf0041a3.txt](https://github.com/actionless/pikaur/files/5648904/pikaur_v1.6.14.r3.gf0041a3.txt)

**Comment by actionless** [comment]
so it works for you now?

**Comment by konomikitten** [comment]
I believe so I don't see any errors, thanks so much for your time.

**Comment by actionless** [comment]
sure, thanks for reporting!
