### ISSUE TITLE
Prompting for edit and diff when set to no in config file

### ISSUE THREAD

**Issue by arivarton** [actionless/pikaur#533]
```
Pikaur v1.6.12.r1.g6a75b12
Pacman v5.2.2 - libalpm v12.0.2
```

##### Description:

Pikaur is prompting for edit of PKGBUILD and showing build diff files even though I have set `noedit = no` and `nodiff = no` in ~/.config/pikaur.conf.

It is not prompting when setting `--nodiff` and `--noedit` as arguments to pikaur.

The command I'm running is `pikaur -Syuu`.

I have no pikaur aliases set.

##### My config:

```
[sync]
alwaysshowpkgorigin = no
develpkgsexpiration = -1
upgradesorting = versiondiff
showdownloadsize = no
ignoreoutofdateaurupgrades = no

[build]
keepbuilddir = no
keepdevbuilddir = yes
keepbuilddeps = no
skipfailedbuild = no
alwaysusedynamicusers = no

[colors]
version = 10
versiondiffold = 11
versiondiffnew = 9

[ui]
requireenterconfirm = yes
printcommands = no
reversesearchsorting = no

[misc]
pacmanpath = pacman
sudoloopinterval = 59
privilegeescalationtool = sudo

[review]
noedit = no
nodiff = no
donteditbydefault = no
gitdiffargs = --ignore-space-change,--ignore-all-space
diffpager = auto
hidedifffiles = .SRCINFO

[network]
aururl = https://aur.archlinux.org
newsurl = https://www.archlinux.org/feeds/news/
socks5proxy = 
aurhttpproxy = 
aurhttpsproxy = 
```

**Comment by arivarton** [comment]
Set `noedit` and `nodiff` to yes...

**Comment by actionless** [comment]
so it works as expected now?

**Comment by arivarton** [comment]
> so it works as expected now?

Yes, working perfectly. Just a premature issue made by me before actually turning on the brain.

**Comment by actionless** [comment]
no worries :)  i was just checking if mb you closed an issue by pressing "Close and comment" instead of "Comment"
