### ISSUE TITLE
No module named 'commonmark'

### ISSUE THREAD

**Issue by tobiasKaminsky** [actionless/pikaur#536]
This also happens with pacaur, or when doing this in git cloned repo:
```
makepkg -fsri
```
…
msgfmt -o locale/ja.mo locale/ja.po
python ./maintenance_scripts/pikaman.py README.md pikaur.1
Traceback (most recent call last):
  File "/home/tobi/.cache/pikaur/build/pikaur/src/pikaur-1.6.15/./maintenance_scripts/pikaman.py", line 17, in <module>
    import commonmark
ModuleNotFoundError: No module named 'commonmark'
make: *** [Makefile:37: pikaur.1] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
…

```
» python --version                                                                                                                                                                            Python 3.9.0
```

**Comment by tobiasKaminsky** [comment]
```
pacaur -Ss python-commonmark                                                                                                                                                                  community/python-commonmark 0.9.1-3 [Installed: 0.9.1-1]
```

**Comment by actionless** [comment]
have no idea what's wrong with your arch installation, that package is in official arch repositories: https://www.archlinux.org/packages/community/any/python-commonmark/

**Comment by actionless** [comment]
also in any way if you need to build pikaur without commonmark,
you could replace in PKGBUILD `make` to `make locale bin` to skip building the manpage and remove the commonmark dep from pkgbuild then

**Comment by tobiasKaminsky** [comment]
Thanks for your quick answer.
I upgraded whole system via regular pacman and then I could build pikaur again.
Not sure why/if python was in an inconsistent state.

**Comment by actionless** [comment]
probably due to fact what python package upgraded before python-commonmark did
