### ISSUE TITLE
clean temporary files after package is built

### ISSUE THREAD

**Issue by deathtrip** [actionless/pikaur#538]
```
pikaur -Vq
Pikaur v1.6.15
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2
```
##### Description:
It seems pikaur doesn't pass the -c argument to makepkg when building packages.
Which leaves the temporary files in `/tmp/makepkg/`, and sometimes that folder can get quite huge.

**Comment by actionless** [comment]
see https://github.com/actionless/pikaur#keepbuilddir-default-no and https://github.com/actionless/pikaur#keepdevbuilddir-default-yes

**Comment by actionless** [comment]
ah, and `pikaur -Sh | grep mflags -A 1`

**Comment by deathtrip** [comment]
Any way to make the flags persistent in the config file?
I tried adding mflags to it, under sync and build sections, but with no luck

**Comment by actionless** [comment]
no, feel free adding a PR for exposing it into config file
