### ISSUE TITLE
if package available in both AUR and repo installation always defaults to repo even if AUR package is selected

### ISSUE THREAD

**Issue by jjgalvez** [actionless/pikaur#542]
```
pikaur -Vq
Pikaur v1.6.15
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2

```

##### [Optional] Prerequisites:
use pikaur to search for a package for example nomachine
`pikaur nomachine`

##### Description:
when using pikaur to search for a package, if the package exists in both the AUR and a repo (obviously an unsupported repo), you can not selet the AUR over the repo package. This is different from the expected behavior which would install the package from the selected option.

**Comment by actionless** [comment]
i can confirm that's the planned behavior

although if somebody would like to implement support for that (or at least to write a comprehensive spec/acceptance criterias) that would be appreciated

**Comment by actionless** [comment]
![2024-06-15--1718476444_1252x2062_scrot](https://github.com/actionless/pikaur/assets/1655669/eb5f7747-09e2-4da2-ad42-ca2767d90a83)
