### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by superiums** [actionless/pikaur#543]
```
can't see any thing in editor

```

##### Description: when  Review PKGBUILDs, can't see anything in the editor. all packages  act like this. only ":" was shown on the bottom was shown, type q will exit. but in the editor ,always shows nothing.

am i missing any dependencies ?
vi is correct while i manaually edit text files.

**Comment by actionless** [comment]
run pikaur with --pikaur-debug flag as it's asked in issue template

**Comment by superiums** [comment]
thanks ! after debug, i found that pikaur lanch /usr/bin/edit ,which was lnk to /usr/bin/ex. this editor shows nothing for any file. if i use vi instead of ex, file content was shown.

**Comment by superiums** [comment]
After change the link:

[shar@MagicA ~]$ ls /usr/bin/edit -l
lrwxrwxrwx 1 root root 2 12月 26 12:12 /usr/bin/edit -> vi
[shar@MagicA ~]$ vi .bashrc     #this shows the file.
[shar@MagicA ~]$ ex .bashrc    #this NOT shows the file.
[shar@MagicA ~]$ edit .bashrc  #this NOT shows the file.

**Comment by actionless** [comment]
what you trying to say, offering to remove `ex` and `edit` from fallback editors?

**Comment by superiums** [comment]
i am trying to say the vi works,but pikaur use /usr/bin/editor, which not work. even if i change the link to vi, still not work.
i am puzzled.

**Comment by actionless** [comment]
those are historical reasons, and obviously notthing to do about pikaur

**Comment by superiums** [comment]
hi, dear @actionless 
I got it. i think you may change '/usr/bin/edit BUILDFILE' to '/usr/bin/edit -v BUILDFILE'. this will show all the content of the file.
otherwise, users have to type 'vi'  to see the content after file open. and infact many people including me don't know this before.
