### ISSUE TITLE
pikaur's autocompletion for the zsh considers command-line parameters of the -S as the packages names 

### ISSUE THREAD

**Issue by roussak** [actionless/pikaur#545]
```
pikaur -Vq
Pikaur v1.6.15.r15.g7317ea0
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2
```
##### Description:
I use the zsh. And if I type the following
```
pikaur -S --asd
```
and press the `Tab` key, the autocompletion hangs for some time. As I can understand, it performs a searching of packages which names contain the '--asd' in the AUR during this time. And finally, it completes the `--asdeps` command-line argument, what actually is expected to be done.

I understand that it is a fine line, but I know that there was no such hangs in the `yaourt`, for example.

**Comment by roussak** [comment]
So, which help is wanted?

**Comment by actionless** [comment]
it's described in the first message
