### ISSUE TITLE
⌨️ No stdin after stdout redirection

### ISSUE THREAD

**Issue by es20490446e** [actionless/pikaur#547]
1. sudo pikaur --sync --refresh --noconfirm youtube-dl 1> "/dev/null"
2. Type something

Result: What you type is invisible.

**Comment by actionless** [comment]
i repeated exactly the same steps but can't reproduce it

**Comment by actionless** [comment]
the change which you reverting in your PR was introduced to avoid the problems when running pikaur piped (https://github.com/actionless/pikaur/commit/4b979aba5d9bf3c33577d6bcb6b4d1164ff3af9f), however that i can't reproduce neither

**Comment by es20490446e** [comment]
So lets find out where the magic behind the scenes is taking place. Let me know how your system is like, mine is:

- Distro: Manjaro
- Branch: Stable
- Terminal: Bash
- Bashrc: [link](https://bin.privacytools.io/?a80cb99097b1c5b1#8c3YuXK1wyBh5Caw3k25m3bGDp3mCHCkbHDVDNDVQvSo)
- Terminal emulator: qterminal
- Desktop: plasma
- Python version: 3.9.1

**Comment by actionless** [comment]
thanks a lot for investigating, i indeed can reproduce it with bash

**Comment by es20490446e** [comment]
Thanks. Perhaps it is a good time to bump version.

**Comment by actionless** [comment]
if you wanna that happen sooner you could fix the unit tests, otherwise tag release won't happen earlier than i'll have time for doing that

(2 packages used in the tests are not building anymore, so other packages with similar dependency-chains should be picked instead of them)

**Comment by es20490446e** [comment]
I think I won't do that, at it looks more interesting to me just building from master.

**Comment by actionless** [comment]
in that case you could simpler use `pikaur-git` AUR package

**Comment by es20490446e** [comment]
It's already solved for me. It's a long story 😌
