### ISSUE TITLE
Repository's priority is ignored.

### ISSUE THREAD

**Issue by naqern** [actionless/pikaur#55]
Repositories listed on pacman.conf have priorities (see: [archwiki](https://wiki.archlinux.org/index.php/Pacman#Repositories_and_mirrors))

> repositories listed first will take precedence over those listed later in the file when packages in two repositories have identical names, regardless of version number.

I have [testing], [community-testing], [multilib-testing] enabled (but only specific packages are explicitly installed from them). Yet, "pikaur -Syu" for example suggests the very dangerous list of updates (all of them from testing!):

`linux                                 4.15.6-1            -> 4.15.7-1`
`linux-headers                         4.15.6-1            -> 4.15.7-1`
`linux-zen                             4.15.6-1            -> 4.15.7-1`
`linux-zen-headers                     4.15.6-1            -> 4.15.7-1`

Different helpers (pacaur, yay, trizen…) are correctly implementing repository priority.

**Comment by actionless** [comment]
should priority apply only to `-Syu` or to just `-S` as well?

**Comment by naqern** [comment]
Priority is always applied. To install a package from a low priority repository you need to prepend the repository's name: 

Install explicitly from a repository: `pacman -S testing/linux`
Install the "official" package: `pacman -S linux`

**Comment by actionless** [comment]
thanks, in that case fix should be quite easy, i'll try to address it tonight or so

**Comment by actionless** [comment]
should be fine now:


```
$ ./pikaur.py -Ss core/archlinux-keyring
Searching... [###]
core/archlinux-keyring 20180108-1 [installed]
    Arch Linux PGP keyring

$ ./pikaur.py -Ss testing/archlinux-keyring
Searching... [###]
testing/archlinux-keyring 20180302-1 [installed: 20180108-1]
    Arch Linux PGP keyring

$ ./pikaur.py -Ss archlinux-keyring
Searching... [###]
testing/archlinux-keyring 20180302-1 [installed: 20180108-1]
    Arch Linux PGP keyring
```
