### ISSUE TITLE
Running without an attached terminal hangs pikaur

### ISSUE THREAD

**Issue by es20490446e** [actionless/pikaur#556]
Launching pikaur as a background process, like:
sudo -v && sudo pikaur --sync --noconfirm bash &

Will result in it getting the "stopped" status forever.

This is relevant because otherwise [pacman-auto-update](https://github.com/cmuench/pacman-auto-update) could use pikaur for keeping all the AUR packages automatically updated.

**Comment by actionless** [comment]
what happens if you redirect output to file?

**Comment by es20490446e** [comment]
The same. Also there's also a parent process "bash" with the status "stopped" different than the one used by the terminal emulator (there are two, one normal and one stopped).

**Comment by actionless** [comment]
on what's inside the file, any output?

**Comment by es20490446e** [comment]
The file isn't created, as the parent "bash" and all its sub-processes hang intermediately.

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by es20490446e** [comment]
I will have a look 👍

**Comment by es20490446e** [comment]
Fixed. Thank you! 👏🙈🥳🎉
