### ISSUE TITLE
Add option to keep package sources after successful build

### ISSUE THREAD

**Issue by Yardanico** [actionless/pikaur#57]
Some packages like wine require users to clone a big git repository for building, and cloning it every time you build wine can be very slow. I think it would be useful to add an option to keep all source files in user-specified directory (because .cache folder isn't really made for persistent storage)

**Comment by AladW** [comment]
One option would be the `AURDEST` environment variable (which is used by at least two other projects, being pacaur and aurutils)

**Comment by parkerlreed** [comment]
I thought the point of .cache was for keeping files you may need later at runtime (hence sources). A lot faster to keep the source tree and git pull the changes (isn't that required for the --needed parameter anyways? (Was in pacaur at least))

**Comment by actionless** [comment]
so far i am thinking about implementing it as option `RemoveBuildDir` in upcoming config file

**Comment by actionless** [comment]
better `KeepBuildDirBetweenBuild` or just `KeepBuildDir`

**Comment by actionless** [comment]
if you also want command line argument for that feel free to propose the name, it should go to the next release

**Comment by actionless** [comment]
what about `-k, --keepbuild`?

**Comment by alegru** [comment]
It would be nice to have the sources of packages in aur_repos/ or have a option `AURDEST` / `SRCDEST` as in pacaur
For now, setting `KeepBuildDir` leads to having:
PKGBUILD, .SRCINFO in aur_repos/
PKGBUILD, .SRCINFO and sources in build/ (and build stuff depending on `BUILDDIR`)

**Comment by actionless** [comment]
i purposely splitted build dir from aur clone dir to make it easier to clean-up

**Comment by actionless** [comment]
if it's set -- it will be used

**Comment by AladW** [comment]
>UPD2: isn't it BUILDIR, not BUILDDEST?

Yep. https://www.archlinux.org/pacman/makepkg.conf.5.html#_options

**Comment by actionless** [comment]
i've checked -- if it's set that dir will be used, so keepbuild option will make no effect in that case
