### ISSUE TITLE
Segfault when searching for package names containing 0xc3 as character

### ISSUE THREAD

**Issue by adlerweb** [actionless/pikaur#570]
```
Pikaur v1.6.17
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2
Python 3.9.5
```

##### Description:
While searching for a package I accidently hit a wrong key causing the character byte 0xc3 to appear in the package name. Instead of returning an empty search result a segfault occured.

##### Attached log:
```
$ pikaur --verbose -Ss letsencÃpypt
Searching... [Segmentation fault (core dumped)
```

Note: `0x3C` is a valid extended ascii character (`Ã`), but is also used as a UTF-8 start byte. Copy/Pasting will probably not work as most shells will convert the input to 0xc383 (UTF-8 Ã). Hex representation of command

```
00000000: 7069 6b61 7572 202d 5373 202d 2d76 6572  pikaur -Ss --ver
00000010: 626f 7365 206c 6574 7365 6e63 7279 c370  bose letsencry.p
00000020: 740a                                     t.
```

**Comment by Morganamilo** [comment]
The bug would be it pyalpm. Given how the db search function has changed in alpm 13, this bug may end up being fixed there.

**Comment by actionless** [comment]
yes, because obviously python is managed code so couldnt segfauly directly
