### ISSUE TITLE
Use `--ignore` to resolve update version conflict skips update verification.

### ISSUE THREAD

**Issue by yuyichao** [actionless/pikaur#577]
```
pikaur -Vq
Pikaur v1.7.r11.g7700162
Pacman v6.0.0 - libalpm v13.0.0 - pyalpm v0.10.6
```

##### Description:
When an upgrade isn't possible (when using 3rd party repo that lacks behind the official one for a few hours) due to a unsatisfied version requirement (package B requiring version x of package A but A has a new verion y in repo), pikaur normally would report an error and quit. This error, however, can be fixed by ignoring the packages that break the version requirement (`--ignore A` in the case above) on the command line. However, when doing this with `pikaur` (AFAICT `pacman` itself is fine), both the pikaur confirmation screen and the pacman one are skipped causing the upgrade to start immediately.

**Comment by actionless** [comment]
you forgot to attach the log

**Comment by yuyichao** [comment]
I know but I don’t really have the log.

**Comment by actionless** [comment]
then i can't really help with it

**Comment by yuyichao** [comment]
Well that’s why I provided a detailed description.
