### ISSUE TITLE
Prepare all AUR package to update

### ISSUE THREAD

**Issue by TommyJerryMairo** [actionless/pikaur#578]
```
[tjm@ArchPad ~]$ pikaur -Vq
Pikaur v1.6.17
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2
[tjm@ArchPad ~]$ 

```

##### Description:
It is not common when people use Arch without stable 24/7 Internet access. However, I'm one of those few lucky dogs who have limited time access to the Internet. Without interference from high CPU, low memory or heavy disk IO, I could utilize the limited time to perform heavy network jobs first. Therefore, I will appreciate it if there is an option in `pikaur`, which will download and get the source prepared(`makepkg -o`) for AUR packages to update. I noticed there is `pacman -Sw`, a download-only option in `pacman`. Unfortunatically, `pikaur -Sw` overrides it with download and build. There is plenty of time for my computer to build the packages in an Internet-free environment. It would be helpful to separate the download, prepare, build and install phases of `pikaur`.

**Comment by actionless** [comment]
for a lot of packages which are using rust, npm your idea wouldnt work

and, considering what such a usecase very limited - i recommend you writing bash script
