### ISSUE TITLE
Add support for -w, --downloadonly flag

### ISSUE THREAD

**Issue by alecdwm** [actionless/pikaur#58]
When provided, pikaur would only clone the provided packages from the AUR, but not install them.

E.g. `pikaur -Sw openarena`

**Comment by actionless** [comment]
should it also build the package?

**Comment by AlmightyFrog** [comment]
If it would also build then all aur packages which were approved before that would be perfect. That is a feature which i always missed at yaourt. But of cause then there would need to be the check added to use it from that local build cache and not to build it automatically new at next issue.

**Comment by alecdwm** [comment]
Good Q!
I'd say so. `pacaur` also has this feature and over there they build but don't install the specified packages.

**Comment by rmarquis** [comment]
@actionless Yes. See [pacaur man page](https://github.com/rmarquis/pacaur#aur-specific-operations):

> buildonly (same as -Sw --aur)
Clone build files and build target(s). Missing dependencies will be installed as needed for the build process, and removed automatically afterwards.
