### ISSUE TITLE
How to tell pikaur to consider llvm-git as llvm

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [actionless/pikaur#586]
Problem:
Install `llvm-git` and `kdevelop-git`. Try to update `pikaur -Syu --devel`

```
New packages 'llvm' and 'llvm-git' are in conflict.
```
Can I tell pikaur/pacman somehow to consider `llvm-git` as `llvm`?

**Comment by Morganamilo** [comment]
Looks like llvm-git is missing a provide on llvm,

**Comment by actionless** [comment]
@T35R6braPwgDJKq show the output of `pacman -Qi llvm-git`

**Comment by T35R6braPwgDJKq** [comment]
@Morganamilo right, thx
