### ISSUE TITLE
pikaur doesn't "see" all available updates

### ISSUE THREAD

**Issue by pjhalsli** [actionless/pikaur#597]
Pikaur v1.8
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6

##### Description:
Sometimes pikaur don't see available updates. Just now I updated and when finished I tried with yay and dunst-git was available - tried again with pikaur and it doesn't seem to "see" it

![2021-10-31-183318_2880x1620_scrot](https://user-images.githubusercontent.com/12110311/139595215-5f35999a-c53e-428c-9e86-fbcab3cbf436.png)

**Comment by actionless** [comment]
see 

https://github.com/actionless/pikaur#develpkgsexpiration-default--1

and

https://github.com/actionless/pikaur#how-to-upgrade-all-the-dev--git-packages-at-once

for two different approaches
