### ISSUE TITLE
Clone remaining devel packages while one is being built

### ISSUE THREAD

**Issue by LordRishav** [actionless/pikaur#616]
```
pikaur -Vq
Pikaur v1.9.r6.gab8fc9e
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

It would be good if pikaur clones remaining devel packages (if any) in the background while one is being built, instead of doing it all sequentially, because building a package can take a long time.

I am not sure if any other AUR helper does that already, but I remember Gentoo's portage package manager does it already (that is, downloads the source of packages to be installed while one is building in the background).

**Comment by actionless** [comment]
devel packages all cloned in multiple processes before the build
