### ISSUE TITLE
Confirm reading Arch news

### ISSUE THREAD

**Issue by mattia-b89** [actionless/pikaur#618]
```
$ pikaur -Vq
Pikaur v1.9
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:

I had updated a system with very old packages, that's many (almost all) of them have been upgraded, resulting in a very long list, before proceed with the upgrade.

This led me to missing the Arch news, just because terminal automatically scroll down...

I'd like to have a discussion about this issue: for example, adding a confirmation message e.g. "Press Enter to continue" message would be enough IMO
or another solution could be placing Arch news at the bottom of the package list

**Comment by actionless** [comment]
> adding a confirmation message e.g. "Press Enter to continue" message would be enough IMO

such prompt also would require thinking of default choice for both manual and --noconfirm modes

**Comment by mattia-b89** [comment]
I think:

- with `--noconfirm` it skips the prompt, that's no changes compared with today's behaviour
- for `manual` there isn't a _default_ choice because there is no choice; it is different to `edit (Y/n)` question, where user is able to _edit_ or _not to edit_. Here the user can go only "forward" by acknowledging the presence of news

**Comment by actionless** [comment]
> with --noconfirm it skips the prompt, that's no changes compared with today's behaviour

in this case should the news be marked as read (as now) or not?

**Comment by mattia-b89** [comment]
Good point!
In this case, there is no true objective/definitive action: `--no-confirm` means no user interactions, so it skips the prompt; but the point is: next time should we show the former news again?

I think **no**, the news should be marked as read, because: 

1. news is anyway shown (the prompt just helps you to not miss it), so user can _always_ read it
2. `--no-confirm` is a voluntary option, so user is _aware_

**Comment by actionless** [comment]
i've got a nice idea for UI finally:


```
There is news from archlinux.org!
<Some news goes here>

:: AUR package will be installed:
 pikaur-git                            1.18.3.r13.g70000af-1  -> 1.18.4-1

:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
:: [m]ark Arch news as read
>> 
```
