### ISSUE TITLE
"Manually select packages" option doesn't allow reselection

### ISSUE THREAD

**Issue by ym1234** [actionless/pikaur#62]
Example: 
```
:: Repository packages will be installed:
 iana-etc                              20180131-1          -> 20180221-1
 python2-hyperlink                     17.3.1-1            -> 18.0.0-1
 reflector                             2017.11-1           -> 2018-1
```
After I press `m`  then delete python2-hyperlink and reflector in vim:
```
:: Repository packages will be installed:
 iana-etc                              20180131-1          -> 20180221-1
```
If I press ``m`` again, I cannot reselect python2-hyperlink and reflector.

**Comment by ym1234** [comment]
Actually, sorry, i'm just dumb.

**Comment by actionless** [comment]
that was done purposely, to avoid removing packages from the list again in case if you want to remove one more package before starting the installation
