### ISSUE TITLE
bug: /etc/pacman.conf is read even if --config swtiches to another file

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [actionless/pikaur#624]
```
class PacmanConfig(PycmanConfig):

    def __init__(self) -> None:
        print('pacmanconfig')
        super().__init__(conf='/etc/pacman.conf')
```

`pikaur -S --config not/etc/pacman.conf ` does not work.
Hardcoding the new path in there worked altough

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
