### ISSUE TITLE
Package completition + Package list pager

### ISSUE THREAD

**Issue by Topper30** [actionless/pikaur#640]
```
Pikaur v1.10.1
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6

```

Hi !

In the README is mentionned Package name completition in bash, how does it work ? I'm hitting the TAB key but nothing happens with the command line.

Also, could it be possible to have a pager feature for long package lists ?

Thank you !

**Comment by actionless** [comment]
1) it works:
![2022-03-23--1648069227_491x509_scrot](https://user-images.githubusercontent.com/1655669/159794862-a4d2a4ab-43e6-48eb-9937-1cc3ee110b3b.png)



2) no, use `less` or whatever you prefer

**Comment by Topper30** [comment]
Thanks for your answers actionless.

But I confirm : 
`[olivier@laptop ~]$ pikaur -S themix-[TABKEY]
`
Doesn't do anything in my bash console. Completition works fine for directories still.
I'll provide any details you need, if ever.

**Comment by actionless** [comment]
idk - try asking help on forums for bash users or so
