### ISSUE TITLE
Add Flatpak

### ISSUE THREAD

**Issue by KirMozor** [actionless/pikaur#641]
I have an idea for your program. Please add support for FlatPak so that programs are searched for and installed from FlatPak at the same time, and Pikaur checks for updates in FlatPak

**Comment by btwe** [comment]
Just curious.. Isn't there a flatpak manager already?

**Comment by KirMozor** [comment]
I don't know if there is or not, but it's much more convenient when you can update everything through one console utility (in this case pikaur)

**Comment by btwe** [comment]
Sure. No need to defend your request. Still, I would not like it.

**Comment by Locutus64** [comment]
Install topgrade and edit it to use pikaur instead of paru or yay or whatever it's set to on your system. Topgrade will update EVERYTHING on a Arch based distro.

**Comment by keilmillerjr** [comment]
> 

Topgrade only mentions upgrading, not installing or removing. If it can, I wouldn't know. Readme points to their documentation platform for usage. Their documentation platform is setup, but lacks content.

While I do not use flatpaks, including it would cover usage for a lot of people.

I am currently using [Arch Linux Updates Indicator](https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/) with [checkupdates-with-aur](https://aur.archlinux.org/packages/checkupdates-with-aur). I have a very cohesive environment. If flatpak were to be added, the latter utility should also be updated to include support.

**Comment by ShapeShifter499** [comment]
> Sure. No need to defend your request. Still, I would not like it

@btwe I'm kind of curious of what your reason is. 

If it introduces some sort of major complexity to support Flatpaks then okay fine. But it sure would be nice to have one utility for a bunch of different ways to install programs on Arch Linux.

**Comment by actionless** [comment]
> If it introduces some sort of major complexity to support Flatpaks then okay fine

lol, obviously adding one more type of packages to package manager which supports only one format/source of packages would literally increase complexity ~twice

also see https://github.com/actionless/pikaur/issues/641#issuecomment-1382019238
