### ISSUE TITLE
Git diff error for AUR packages

### ISSUE THREAD

**Issue by felixwiemuth** [actionless/pikaur#645]
```
pikaur -Vq
Pikaur v1.10.1
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:
When doing a system update (I use `pikaur -Syu --needed`) and I am asked whether I want to see the diff for an AUR package and select "y", I get the following output (the git usage output is shortened):

```
Do you want to see build files diff for android-studio package? [Y/n] 
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --function-context

...

Do you want to edit PKGBUILD for android-emulator package? [y/N]
```
It seems to happen for any AUR package.

The git repositories are there in `/var/cache/pikaur/aur_repos/`.
However, with the example of the android-studio package in `/var/cache/pikaur/aur_repos/android-studio`, I get the following output for `git status`:
```
fatal: unsafe repository ('/var/cache/private/pikaur/aur_repos/android-studio' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /var/cache/private/pikaur/aur_repos/android-studio
```
Could this have sth. to do with the dynamic users option (`alwaysusedynamicusers = yes` is set in `pikaur.conf`)?
The premissions on the repository directories in `/var/cache/pikaur/aur_repos/` are `drwxr-xr-x` or `drwx------` (the error occurs for both variants). The owner and group are all the same userid which is neither root nor the user I call pikaur from. The same user owns the files and directories within the repository directory.

##### Attached log:

```
pikaur -S my-precious-package --verbose --pikaur-debug
```
(Not executed yet, would do if needed.)

**Comment by actionless** [comment]
feel free to update it if you'll figure it out (i personally dont believe into dynamic users as helpful measure here, it's like wearing 5x5 cm armored west - there is a small chance it will catch a bullet, but...)
