### ISSUE TITLE
AUR package ends up using not system python

### ISSUE THREAD

**Issue by Randomneo** [actionless/pikaur#649]
##### [Optional] Prerequisites:

I do have in my `.zshrc`
```
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh
workon default
``` 

##### Description:

Unable to install pikaur. I assume there is some way that PKGBUILD ends up using shell `python`. I got `import commonmark` error.

After installing `commonmark` with `pip` in my local env everything works.

##### Attached log:

```
$ makepgk -sri
.........
/home/randomneo/.virtualenvs/default/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
Traceback (most recent call last):
  File "/tmp/pikaur/src/pikaur-1.10.1/./maintenance_scripts/pikaman.py", line 17, in <module>
    import commonmark
ModuleNotFoundError: No module named 'commonmark'
make: *** [Makefile:41: pikaur.1] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by actionless** [comment]
this happens before pikaur is installed, please look for help on archlinux forums
