### ISSUE TITLE
packages Replaces priority

### ISSUE THREAD

**Issue by GFdevelop** [actionless/pikaur#65]
I'm new with pikaur (before i have used pacaur), when I install a package I have a problem, it would change my packages, for example if I install lastpkgs :

```
~> pikaur -S lastpkgs
resolving dependencies...
Reading local package database...

:: AUR package will be installed:
 lastpkgs                                                  -> 0.9.4-1

:: Proceed with installation? [Y/n]
:: [v]iew package detail   [m]anually select packages
> y
looking for conflicting packages...
Reading repository package databases...
:: New package 'create_ap-git' replaces installed 'create_ap' Proceed? [Y/n] n
:: New package 'cupp-git' replaces installed 'cupp' Proceed? [Y/n] n
:: New package 'reaver-wps-fork-t6x-git' replaces installed 'reaver' Proceed? [Y/n] n
:: New package 'reaver-wps-fork-t6x' replaces installed 'reaver' Proceed? [Y/n] n
Do you want to edit PKGBUILD for lastpkgs package? [y/N] n
```

and here _pikaur -Ss_ :
```
~> pikaur -Ss create_ap
Searching... [###]
archstrike/create_ap-git r250.f906559-1 (archstrike archstrike-wireless) 
    A shell script to create a NATed/Bridged Software Access Point(aka WiFi)    
community/create_ap 0.4.6-1 [installed] 
    A shell script to create a NATed/Bridged Software Access Point    
aur/create_ap-gui 1.3.1-1 [installed] (12, 1.49)
    Gui application for easy creating access points. Application allows save configuration for quickly create AP.    
aur/create_ap-git r227.fc28805-2 (3, 0.00)
    A shell script to create a NATed/Bridged Software Access Point    
```
it search for different packages that are not same, for example _create_ap_ are not equal to _create_ap-git_

How to solve this?

**Comment by actionless** [comment]
could you show `pikaur -Si create_ap-git`?

**Comment by actionless** [comment]
mb Replaces logic should fire only if repository priority is the same or higher

**Comment by AladW** [comment]
This is the second issue I saw about repo priority. Is there a real need to implement these things yourself (i.e. can't you refer to what `pacman` does in this case?)

**Comment by GFdevelop** [comment]
Pacman ignore if packages are not equals ("name"=="name")...i have
uninstalled pikaur because is more instable, it don't ask me for choose and
it install dependency packages as explic...

On Mar 8, 2018 14:40, "Alad Wenter" <notifications@github.com> wrote:

This is the second issue I saw about repo priority. Is there a real need to
implement these things yourself (i.e. can't you refer to what pacman does
in this case?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/actionless/pikaur/issues/65#issuecomment-371489048>,
or mute
the thread

**Comment by actionless** [comment]
with which package can i reproduce the problem with installing deps as explicit?

@AladW it's implemented like that:
https://github.com/actionless/pikaur/blob/master/pikaur/package_update.py#L23

i think i should use `pyalpm.sync_newversion` like here:
https://github.com/jelly/pyalpm/blob/master/pycman/action_query.py#L51

**Comment by GFdevelop** [comment]
I don't known, command was an update
