### ISSUE TITLE
Completion when aliases of `mv`, `mkdir` or `rm` declared in shell

### ISSUE THREAD

**Issue by audeoudh** [actionless/pikaur#651]
Hi all,

Having `alias mv='mv -i'` produces a completion that prints on the terminal, which is not expected.  Same for `rm`, `mkdir`.

https://github.com/actionless/pikaur/blob/c48c41b815648a1688de82bc484733114ceb7e54/packaging/usr/share/bash-completion/completions/pikaur#L61
https://github.com/actionless/pikaur/blob/c48c41b815648a1688de82bc484733114ceb7e54/packaging/usr/share/bash-completion/completions/pikaur#L63
https://github.com/actionless/pikaur/blob/c48c41b815648a1688de82bc484733114ceb7e54/packaging/usr/share/bash-completion/completions/pikaur#L72

I'm not sure however if, instead of using directly `mv`, we should use:

1. `command mv` (force executing a command, not an alias or a shell function)
2. `command -p mv ...` (force executing a command with default value for path)
3. `\mv` (disable any alias, but still uses a shell function if exists)

Even if pacman uses 3., I would prefer 1., recommended by scop/bash-completion/CONTRIBUTING.md.

> Use `printf(1)` instead of `echo(1)` for portability reasons, and be sure to invoke commands that are often found aliased (such as `ls` or `grep` etc) using the `command` (or `builtin`) command as appropriate.

**Comment by actionless** [comment]
in fish it should be solved when creating a function by `--wraps` flag:

https://fishshell.com/docs/current/cmds/function.html

i hope people on bash forum will help you to find some similar solution for your shell as well

**Comment by actionless** [comment]
and for completion - i'll prefer to stick with pacman stuff for logical compatibility (all users of pikaur are already users of pacman)

**Comment by audeoudh** [comment]
It makes sense to stick to pacman-style completion.

I just pushed some modifications in 0b91a87.  Note that `chmod` may also be aliased to verbose, so I included it in the commit, even if it should not be as common as `mv` or `rm`.

**Comment by actionless** [comment]
as a fish shell user i fully trust your experience on this - i'll just do a final look before merging

**Comment by audeoudh** [comment]
> what user-customizations of the shell couldn't affect the same shell which used for scripting

A good point IMO.
