### ISSUE TITLE
pikaur -G don’t work if there is a dependency problem

### ISSUE THREAD

**Issue by Br31zh** [actionless/pikaur#656]
```
Pikaur v1.11
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:

I’m trying to get the source files of the mumble/murmur package:

On x86_64:

```
pikaur -G mumble --verbose --pikaur-debug
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-G', 'mumble', '--verbose', '--pikaur-debug']: cli_getpkgbuild
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=mumble
Reading repository package databases...
=> pacman --color=always --sync mumble --print-format %r/%n

Package 'mumble' going to be cloned into '/tmp/mumble'...
=> asp checkout mumble
Cloning into 'mumble'...
done.

```

On aarch64 (Arch Linux ARM):
```
pikaur -G mumble --verbose --pikaur-debug
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-G', 'mumble', '--verbose', '--pikaur-debug']: cli_getpkgbuild
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=mumble
Reading repository package databases...
=> pacman --color=always --sync mumble --print-format %r/%n
:: warning: Following package cannot be found in AUR:
    mumble  
```

So I tried the pacman command on the aarch64:

```
pacman --color=always --sync mumble --print-format %r/%n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'libprotobuf.so=31-64' required by mumble
```

Since I’m using the `-G` to get the PKGBUILD so I can fix the dependency problem, it’s a bit annoying :sweat_smile:. Is it possible to add `--nodeps` on the pacman command used by the -G option? Or can it create others problems?

Thanks.

**Comment by actionless** [comment]
i think it would rather make sense to bypass `--nodeps` option from pikaur -G to underlaying pacman command which causing the error in this case

**Comment by Br31zh** [comment]
This is a good idea, but in this case you have to display the dependency error, so that you know how to fix it. Without the verbose and debug tags, it fails without detailing why.
