### ISSUE TITLE
Systemd-less support?

### ISSUE THREAD

**Issue by pog5** [actionless/pikaur#658]
```
Pikaur v1.11
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

Could we have another version of pikaur, possibly another branch, which would use sudo, fakeroot and/or su to elevate to root instead of systemd? 
This could be very useful for Arch-based distros that do not use systemd, such as Artix Linux.

**Comment by pog5** [comment]
Sorry, did not notice the `alwaysusedynamicusers` option in pikaur.conf

**Comment by actionless** [comment]
you may also need: https://github.com/actionless/pikaur#privilegeescalationtool-default-sudo
