### ISSUE TITLE
man page ?

### ISSUE THREAD

**Issue by jerome-diver** [actionless/pikaur#68]
no man page.

**Comment by AladW** [comment]
`groff` is a set of simple macros so it should be easy enough to write a man page. The syntax is described in `man groff_man`, the guidelines in `man man-pages`. [Example](https://raw.githubusercontent.com/AladW/aurutils/master/man1/aur-sync.1)

**Comment by Morganamilo** [comment]
Did you forget to actually git add the man page?

Also makepkg automatically gzips man pages, no need for you to do it yourself.

**Comment by actionless** [comment]
@Morganamilo  thanks, removed gzip command
