### ISSUE TITLE
Missing dependencies `setuptools` during manual build with `makepkg`

### ISSUE THREAD

**Issue by floesche** [actionless/pikaur#686]
I am trying to follow the manual installation procedure in the [README.md](https://github.com/actionless/pikaur#installation).

```
% makepkg --version
makepage: discount 2.2.7b GITHUB_CHECKBOX
```
I uninstalled pikaur before:
```
% pikaur -Vq
zsh: command not found: pikaur
```

I recently updated my system with `sudo pacman -Syu` and I have the dependencies installed that will show up later as a missing:

setuptools
```
% pacman -Ss python-setuptools
extra/python-setuptools 1:65.6.2-1 [installed]
    Easily download, build, install, upgrade, and uninstall Python packages
```
and pydantic:
```
% pacman -Ss python-pydantic
community/python-pydantic 1.10.2-1 [installed]
    Data parsing and validation using Python type hints
```

If I now run a `makepkg -fsri -L` (`-L` for keeping the log), it ends with this error message ([full log](https://github.com/actionless/pikaur/files/10106586/pikaur-1.14.4-1-x86_64-build.log)): 

```
sed \
        -e "s/%PYTHON_BUILD_VERSION%/$(python -c 'import sys ; print(f"{sys.version_info.major}.{sys.version_info.minor}")')/g" \
        packaging/usr/bin/pikaur > dist/usr/bin/pikaur
chmod +x dist/usr/bin/pikaur
* Getting build dependencies for wheel...

ERROR Missing dependencies:
        setuptools>=40.8.0
        jaraco.text -> inflect -> pydantic>=1.9.1
==> ERROR: A failure occurred in build().
    Aborting...
```

I looked through the other recent issues, but couldn't find a solution. Any idea what I could try?

**Comment by actionless** [comment]
aparently you have some funny env vars set or so, or mb running inside virtual env

**Comment by s-bernard** [comment]
I do have the exact same issue. I cannot install pikaur / update because of this. On just a normal Arch / normal env.

**Comment by floesche** [comment]
Once I remove the `--no-isolation` from the python build command (line 41 in the PKGBUILD), I can build and install pikaur. Line 41 now looks like this:
```sh
/usr/bin/python3 -m build --wheel
```
… just in case this is useful for you, @s-bernard 

Afterwards I still can't run `pikaur -S pikaur` (same dependency problem), but at least I have my pikaur back :-)

**Comment by s-bernard** [comment]
@floesche Thanks! It worked for me as well.

@actionless any clue on why the `--no-isolation` flag makes it fail for us?

**Comment by actionless** [comment]
`--no-isolation` flag was mentioned in Python packaging guideline:

https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)

@s-bernard what exact log message have you got, does it also contain `jaraco.text -> inflect -> pydantic>=1.9.1` line?

**Comment by s-bernard** [comment]
Yes, exactly the same as @floesche log. And I do have `python-setuptools` & `python-pydantic` installed. It was working fine for previous versions (last one installed on my machine was `1.13.2-1`).

**Comment by floesche** [comment]
Just to confirm: Everything was working fine for me up until 1.13.2-1.

With the dynamic users isolation, I can build pikaur through pikaur. The following works (not sure what it means, though):
```sh
pikaur -S --dynamic-users pikaur
```

**Comment by actionless** [comment]
apparently that library (pydantic) doing smth funny with python environment - try reporting it there

**Comment by actionless** [comment]
(with pikaur that problem wasn't reproducing before because pikaur was using legacy build system, which became deprecated couple of days ago, so it was time to migrate to python-build and python-installer)

**Comment by actionless** [comment]
does it work for you if you remove that `python-pydantic` package?

**Comment by s-bernard** [comment]
Do you mean by `pacman -R python-pydantic`? I tried and it’s exactly the same error.
I also try the fix suggested in #691 and it works perfectly.

**Comment by s-bernard** [comment]
Actually, if you want to avoid the redundancy, you can write the `pyproject.toml` in the PKGBUILD so you have access to `makedepends`. My quick&dirty patch to test #691 was:

```
diff --git a/PKGBUILD b/PKGBUILD
index 1e19995..6a9f89d 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -37,6 +37,15 @@ build() {
 	if test -d ./dist ; then
 		rm -r ./dist
 	fi
+        cp pyproject.toml pyproject.toml.old
+echo '[build-system]
+requires = [
+  "wheel",
+  "build",
+  "installer",
+  "markdown-it-py"]' > pyproject.toml
+        cat pyproject.toml.old >> pyproject.toml
+        rm pyproject.toml.old
 	make
 	/usr/bin/python3 -m build --wheel --no-isolation
 }

**Comment by actionless** [comment]
then try creating a totally empty user and run pikaur with it

**Comment by s-bernard** [comment]
With a completely new user, it works.

**Comment by actionless** [comment]
obviously something regarding your local python env is so much broken that it makes `wheel` thing it lost the dep on pydantic or jaraco - since it works with new user - it should be obvious for everyone here

**Comment by BonusPlay** [comment]
I also had the same problem, however I diagnosed it to be a local `pip` install with incorrect version.

Example:
```
ERROR Missing dependencies:
    setuptools>=40.8.0
    jaraco.text -> inflect -> pydantic>=1.9.1
==> ERROR: A failure occurred in build().
    Aborting...

$ pacman -Ss python-pydantic
community/python-pydantic 1.10.2-1 [installed]
    Data parsing and validation using Python type hints
    
$ python3 -c "import pydantic; print(pydantic.version.VERSION); print(pydantic.__path__)"
1.8.2
['/home/bonus/.local/lib/python3.10/site-packages/pydantic']
```

Command below solved the issue :)
```
pip uninstall pydantic
````

**Comment by s-bernard** [comment]
Indeed, `pip uninstall pydantic` solve the issue for me! Thanks a lot @BonusPlay ! Thanks @actionless for taking the time helping us debugging a local issue and @floesche for your debugging. :smiley:

**Comment by actionless** [comment]
that's not normal at first place, as i mentioned probably due to editing PYTHONPATH env var:

```console
$ python3 -c "import sys ; print(sys.path)"
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages/linkgrammar']
```

**Comment by s-bernard** [comment]
I do have my user local `site-package` before my system-wide `site-package`. Which make sense, a user preference overrides a system preference.

**Comment by floesche** [comment]
I also found the same old pydantic in the user's `site-package`, removing it solved the problem for me too. No idea why that wasn't in a virtual env…

Thanks so much to all of you for finding the cause of the issue.
