### ISSUE TITLE
issue with building the new version of pikaur 

### ISSUE THREAD

**Issue by rezad1393** [actionless/pikaur#688]
```
pikaur -Vq
 pikaur -Vq
=> pacman --version
Pikaur v1.13.2
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6

```

I am trying to update from v1.13.2 to the new version 1.14.5 

but I get this error.

```


==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
make: which: No such file or directory
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
        #
./maintenance_scripts/pikaman.py README.md pikaur.1
make: ./maintenance_scripts/pikaman.py: Permission denied
make: *** [Makefile:41: pikaur.1] Error 127
make: *** Waiting for unfinished jobs....
find pikaur -type f -name '*.py' \
        | xargs xgettext --language=python --add-comments --sort-output \
                --default-domain=pikaur --from-code=UTF-8 \
                --keyword='translate' --keyword='translate_many:1,2' \
                --output=locale/pikaur.pot
==> ERROR: A failure occurred in build().
    Aborting...

```

I get this error on my x64 laptop but not on my arm32 device.

I get this error even with downloading the source zip and trying it with make command.

**Comment by freemyminde** [comment]
https://github.com/actionless/pikaur/issues/682
Seems to be the same issue.
But anyways you need to
```
git clone https://github.com/actionless/pikaur.git
cd pikaur
makepkg
pacman -U <package_file>
```

Since the update before the weekend requieres it as mentioned on the aur page: 
https://aur.archlinux.org/packages/pikaur

**Comment by rezad1393** [comment]
I did that and I get the same error.


> I get this error even with downloading the source zip and trying it with make command.

**Comment by actionless** [comment]
this is not normal:

> ==> Starting build()...
> make: which: No such file or directory

**Comment by rezad1393** [comment]
why is this closed?
is it dup of https://github.com/actionless/pikaur/issues/682

**Comment by actionless** [comment]
yes
