### ISSUE TITLE
Install package from list

### ISSUE THREAD

**Issue by ralpheeee88** [actionless/pikaur#69]
Would this be possible...? 

[Install package from list](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#List_of_installed_packages)

**Comment by actionless** [comment]
```sh
xargs pikaur -S --noconfirm < packages.txt
```

**Comment by actionless** [comment]
@ralpheeee88 command in your log is different from the command in my comment

**Comment by actionless** [comment]
mb i could catch that exception and write some kind of message what where is no tty

**Comment by ralpheeee88** [comment]
@actionless  left the --noconfirm out cuz i wanted to test the package conflict with bitlbee / bitlbee-libpurple

**Comment by actionless** [comment]
in that case do smth like:

```bash
pikaur -S $(cat storage/linux/pkglist_aur.txt | xargs)
```

**Comment by ralpheeee88** [comment]
@actionless 

==> Finished making: bitlbee-libpurple 3.5.1-1 (Fri Mar 16 18:36:44 CET 2018)
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 8, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 276, in main
    cli_entry_point()
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 227, in cli_entry_point
    cli_install_packages(args)
  File "/usr/lib/python3.6/site-packages/pikaur/main.py", line 69, in cli_install_packages
    InstallPackagesCLI(args=args, packages=packages)
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 95, in __init__
    self.build_packages()
  File "/usr/lib/python3.6/site-packages/pikaur/install_cli.py", line 511, in build_packages
    repo_status.build(self.args, self.package_builds)
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 374, in build
    self._set_built_package_path()
  File "/usr/lib/python3.6/site-packages/pikaur/build.py", line 302, in _set_built_package_path
    config_path=os.path.join(self.build_dir, 'PKGBUILD')
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 97, in get
    value = cls.get_config(config_path=config_path).get(key)
  File "/usr/lib/python3.6/site-packages/pikaur/core.py", line 88, in get_config
    line for line in config_file.readlines()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128)
~  >>

**Comment by actionless** [comment]
does the same happen when you do just `pikaur -S bitlbee-libpurple`? (that worked from my machine)

**Comment by actionless** [comment]
i guess that's happening because of `# Contributor: Fernando Jiménez Solano (fjim) <fjim@sdfeu.org>` line in the PKGBUILD however on my machine it works so i guess i need to force set some locale before reading config

could you please show your `locale` command output?

**Comment by ralpheeee88** [comment]
@actionless 
locale http://ix.io/403

**Comment by actionless** [comment]
@ralpheeee88 i've tried to address the encoding, please see if that helps

**Comment by ralpheeee88** [comment]
@actionless 
removing the following packages from the list:
bitlbee-libpurple, bleachbit-cli, laptop-mode-tools
at it works...

**Comment by actionless** [comment]
but if `bitlbee-libpurple` is working after the last fix for non-unicode locales?

**Comment by ralpheeee88** [comment]
@actionless  on the dev branch the packages built albeit dependencies of packages were not checked

**Comment by actionless** [comment]
dev branch is out-of-date right now

try either latest master or just install it from AUR (it fetching latest master)

**Comment by actionless** [comment]
i've tagged 0.9 yesterday, could you check if it's working as expected?

**Comment by ralpheeee88** [comment]
@actionless  just tested with one package (bleachbit-cli)...no issues!

**Comment by actionless** [comment]
thanks for testing!
