### ISSUE TITLE
Missing fakeroot dependency

### ISSUE THREAD

**Issue by antonbutanaev** [actionless/pikaur#690]
```
pikaur -Vq
Pikaur v1.14.5
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```
Installing and running on fresh system, fakeroot executable not found

**Comment by alkazar** [comment]
This is still an issue. Can you provide rationale for not making `fakeroot` a dependency in the pikaur PKGBUILD?

**Comment by actionless** [comment]
https://wiki.archlinux.org/title/Arch_User_Repository

**Comment by alkazar** [comment]
Ah right, thank you. For future reference, this is the key bit:
"Note: Packages in the AUR assume that [base-devel](https://archlinux.org/packages/?name=base-devel) is installed in the build environment."

And `base-devel` requires `fakeroot`.
