### ISSUE TITLE
Building only some pkgs from the split package

### ISSUE THREAD

**Issue by DrownedAxolotl** [actionless/pikaur#694]
pikaur -S sk1

##### [Optional] Prerequisites:
Installing a package that has a split package as a dependency

##### Description:
When trying to run the command above pikaur will report that it failed to handle aur dependencies. On the other hand, something like paru will display the following:

```
:: There are 2 providers available for python2-wxpython3:
:: Repository AUR:
    1) python2-wxpython3-gtk2  2) python2-wxpython3-gtk3  
Enter a number (default=1):
```
Meanwhile pikaur displays the following:
```
:: error: Can't resolve dependencies for AUR package 'sk1':
:: error: Dependencies missing for sk1
:: warning: Following package cannot be found in AUR:
    python2-wxpython3    
:: Try recovering sk1?
[e] edit PKGBUILD
[s] skip this package
[A] abort
```

**Comment by actionless** [comment]
i checked arch's makepkg, i don't see such option there:

```console
$ makepkg --help
makepkg (pacman) 6.1.0

Make packages compatible for use with pacman

Usage: /usr/sbin/makepkg [options]

Options:
  -A, --ignorearch Ignore incomplete arch field in PKGBUILD
  -c, --clean      Clean up work files after build
  -C, --cleanbuild Remove $srcdir/ dir before building the package
  -d, --nodeps     Skip all dependency checks
  -e, --noextract  Do not extract source files (use existing $srcdir/ dir)
  -f, --force      Overwrite existing package
  -g, --geninteg   Generate integrity checks for source files
  -h, --help       Show this help message and exit
  -i, --install    Install package after successful build
  -L, --log        Log package build process
  -m, --nocolor    Disable colorized output messages
  -o, --nobuild    Download and extract files only
  -p <file>        Use an alternate build script (instead of 'PKGBUILD')
  -r, --rmdeps     Remove installed dependencies after a successful build
  -R, --repackage  Repackage contents of the package without rebuilding
  -s, --syncdeps   Install missing dependencies with pacman
  -S, --source     Generate a source-only tarball without downloaded sources
  -V, --version    Show version information and exit
  --allsource      Generate a source-only tarball including downloaded sources
  --check          Run the check() function in the PKGBUILD
  --config <file>  Use an alternate config file (instead of '/etc/makepkg.conf')
  --holdver        Do not update VCS sources
  --key <key>      Specify a key to use for gpg signing instead of the default
  --noarchive      Do not create package archive
  --nocheck        Do not run the check() function in the PKGBUILD
  --noprepare      Do not run the prepare() function in the PKGBUILD
  --nosign         Do not create a signature for the package
  --packagelist    Only list package filepaths that would be produced
  --printsrcinfo   Print the generated SRCINFO and exit
  --sign           Sign the resulting package with gpg
  --skipchecksums  Do not verify checksums of the source files
  --skipinteg      Do not perform any verification checks on source files
  --skippgpcheck   Do not verify source files with PGP signatures
  --verifysource   Download source files (if needed) and perform integrity checks

These options can be passed to pacman:

  --asdeps         Install packages as non-explicitly installed
  --needed         Do not reinstall the targets that are already up to date
  --noconfirm      Do not ask for confirmation when resolving dependencies
  --noprogressbar  Do not show a progress bar when downloading files

If -p is not specified, makepkg will look for 'PKGBUILD'
```

**Comment by actionless** [comment]
so, closing this ticket, unless this will became implemented in makepkg itself

for now i recommend to use pikaur's feature to edit pkgbuild before the build, in order to comment out unneeded parts of the split package

apparently arch forums are on the same page on that: https://bbs.archlinux.org/viewtopic.php?id=210591

**Comment by actionless** [comment]
also stumbled upon a perfect example of why it won't be possible at all unless PKGBUILD spec itself would change first:


https://gitlab.archlinux.org/archlinux/packaging/packages/python-pytorch/-/blob/main/PKGBUILD?ref_type=heads#L251-319


build of all subpackages is defined in the same function, so there is literally no other way to split out the package build, other than commenting out the parts of PKGBUILD code:


"""bash
build() {
  cd "${srcdir}/${_pkgname}"
  echo "Building without cuda or rocm and without non-x86-64 optimizations"
  _prepare
  export USE_CUDA=0
  export USE_CUDNN=0
  export USE_ROCM=0
  echo "add_definitions(-march=x86-64)" >> cmake/MiscCheck.cmake
  python setup.py build

  cd "${srcdir}/${_pkgname}-opt"
  echo "Building without cuda or rocm and with non-x86-64 optimizations"
  _prepare
  export USE_CUDA=0
  export USE_CUDNN=0
  export USE_ROCM=0
  echo "add_definitions(-march=x86-64-v3)" >> cmake/MiscCheck.cmake
  python setup.py build

  cd "${srcdir}/${_pkgname}-cuda"
  echo "Building with cuda and without non-x86-64 optimizations"
  _prepare
  export USE_CUDA=1
  export USE_CUDNN=1
  export USE_ROCM=0
  export MAGMA_HOME=/opt/cuda/targets/x86_64-linux
  cd "${srcdir}/${_pkgname}-cuda"
  echo "add_definitions(-march=x86-64)" >> cmake/MiscCheck.cmake
  python setup.py build

  cd "${srcdir}/${_pkgname}-opt-cuda"
  echo "Building with cuda and with non-x86-64 optimizations"
  export USE_CUDA=1
  export USE_CUDNN=1
  export USE_ROCM=0
  export MAGMA_HOME=/opt/cuda/targets/x86_64-linux
  _prepare
  echo "add_definitions(-march=x86-64-v3)" >> cmake/MiscCheck.cmake
  python setup.py build

  cd "${srcdir}/${_pkgname}-rocm"
  echo "Building with rocm and without non-x86-64 optimizations"
  # -fcf-protection is not supported by HIP, see
  # https://rocm.docs.amd.com/projects/llvm-project/en/latest/reference/rocmcc.html#support-status-of-other-clang-options
  CXXFLAGS+=" -fcf-protection=none"
  _prepare
  export USE_CUDA=0
  export USE_CUDNN=0
  export USE_ROCM=1
  export MAGMA_HOME=/opt/rocm
  echo "add_definitions(-march=x86-64)" >> cmake/MiscCheck.cmake
  # Conversion of CUDA to ROCm source files
  python tools/amd_build/build_amd.py
  patch -Np1 -i "$srcdir/pytorch-rocm-jit.patch"
  python setup.py build

  cd "${srcdir}/${_pkgname}-opt-rocm"
  echo "Building with rocm and with non-x86-64 optimizations"
  _prepare
  export USE_CUDA=0
  export USE_CUDNN=0
  export USE_ROCM=1
  export MAGMA_HOME=/opt/rocm
  echo "add_definitions(-march=x86-64-v3)" >> cmake/MiscCheck.cmake
  # Conversion of CUDA to ROCm source files
  python tools/amd_build/build_amd.py
  patch -Np1 -i "$srcdir/pytorch-rocm-jit.patch"
  python setup.py build
}
"""
