### ISSUE TITLE
Missing which as makedepend

### ISSUE THREAD

**Issue by k8ieone** [actionless/pikaur#695]
```
pikaur -Vq

Pikaur v1.14.5
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### [Optional] Prerequisites:
 - The `which` package not installed prior to installing pikaur.

##### Description:
The package should have `which` listed as a build-time dependency. It does not build without it.

##### Attached log:

```
makepkg -si

==> Starting build()...
make: which: No such file or directory
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
find pikaur -type f -name '*.py' \
	| xargs xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
./maintenance_scripts/pikaman.py README.md pikaur.1
make: ./maintenance_scripts/pikaman.py: Permission denied
make: *** [Makefile:41: pikaur.1] Error 127
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by moormaster** [comment]
"which" comes with the base-devel group that should be installed before building any AUR package - see wiki entry [Arch_User_Repository#Getting_started](https://wiki.archlinux.org/title/Arch_User_Repository#Getting_started)

**Comment by actionless** [comment]
```
==> Starting build()...
make: which: No such file or directory
```

that's actually a bug in Makefile though, that installation didn't stopped right after this line - aparently make is not checking by default exit code of subshells used for variable substitution
