### ISSUE TITLE
BUG. Environment EDITOR=set not exist software

### ISSUE THREAD

**Issue by badcast** [actionless/pikaur#696]
BUG!!! Env EDITOR=<set not exist editor>, Any name 
### 
Edit PKGBUILD <pikaur>? [y/N] y File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 369, in main cli_entry_point() File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 272, in cli_entry_point run_with_sudo_loop(pikaur_operation) File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 404, in run_with_sudo_loop raise catched_exc File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 398, in run_with_sudo_loop result = main_thread.get() File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get raise self._value File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker result = (True, func(args, *kwds)) File "/usr/lib/python3.10/site-packages/pikaur/main.py", line 136, in cli_install_packages InstallPackagesCLI() File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 185, in init self.main_sequence() File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 202, in main_sequence self.review_build_files() File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 835, in review_build_files if self.ask_to_edit_file( File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 707, in ask_to_edit_file return edit_file(full_filename) File "/usr/lib/python3.10/site-packages/pikaur/install_cli.py", line 93, in edit_file interactive_spawn( File "/usr/lib/python3.10/site-packages/pikaur/core.py", line 222, in interactive_spawn process = InteractiveSpawn( File "/usr/lib/python3.10/subprocess.py", line 971, in init self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'nan'

**Comment by actionless** [comment]
where is a bug though?
1) you setting editor to wrong filename `nan`  instead of `nano`
2) pikaur says you: No such file or directory: 'nan'

**Comment by badcast** [comment]
> 

I understand that I typed 'nan' instead of '
nano', but this happened completely by accident, and I decided to check how it could harm me when I want to compile a large project like 'beignet'. Instead of outputting "stack heap", recommend entering your own editor in the field if it is not correct,

**Comment by actionless** [comment]
feel free filing a PR if you convinced that such approach wouldn't be an over-engineering

**Comment by badcast** [comment]
`I don't know python enough to fix the code block. But the stack pointed roughly here.`

https://github.com/actionless/pikaur/blob/2d2b5cf462afe30dca05d2cd6c02fd45ea3225da/pikaur/prompt.py#L251

**Comment by badcast** [comment]
I do not know what PR is, please help me how to do it/submit

**Comment by actionless** [comment]
idk which way of information suits you better, text or audio - so find an article or youtube video according to your preference

**Comment by badcast** [comment]
I am glad enough that there is such a tool as 'pikaur'. I cannot make him my ideal, but I am ready to do everything that is required of me.

> feel free filing a PR if you convinced that such approach wouldn't be an over-engineering

**Comment by badcast** [comment]
ok. thank's
