### ISSUE TITLE
`-Sy` -> `-Sy archlinux-keyring --needed` in sysupgrade

### ISSUE THREAD

**Issue by Froggo8311** [actionless/pikaur#698]
##### Description:
Perhaps change the `-Syu` command to instead of `-Sy` and `-Su` to `-Sy archlinux-keyring --needed` and `-Su`? I find that if I don't update the keyring, and I try to install anything in a few months, things start breaking on my arch system.

**Comment by actionless** [comment]
managing keyring, pgp keys or other stuff like that was never planned to be in scope of pikaur
