### ISSUE TITLE
How to remove pikaur?

### ISSUE THREAD

**Issue by Mauladen** [actionless/pikaur#71]
It would be cool if in the README added the instructions for removal

pacman -Rs pikaur --> pikaur not found

**Comment by Yardanico** [comment]
@Mauladen what do you mean?
pikaur is available in AUR as latest dev version, so package name is `pikaur-git`

**Comment by Mauladen** [comment]
@Yardanico I installed pikaur using PKGBUILD from the repository, then decided to remove it but pacman did not find such a package

**Comment by IgnusG** [comment]
It doesn't matter, the PKGBUILD specifies the name and the name is `pikaur-git`.
Uninstall with `pacman -Rs pikaur-git`

**Comment by Yardanico** [comment]
@Mauladen as @IgnusG said, it doesn't matter, because package name in pikaur's `PKGBUILD` is `pikaur-git`: https://github.com/actionless/pikaur/blob/master/PKGBUILD#L4
