### ISSUE TITLE
Entry Point Not Created and Dependency Not Installed

### ISSUE THREAD

**Issue by CurtisLeeBolin** [actionless/pikaur#711]
# Using pip to install from source

```
$ git clone https://github.com/actionless/pikaur.git
$ cd pikaur
$ python -m pip install .
```

Or

```
$ python -m pip install git+https://github.com/actionless/pikaur.git
```

```
...
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pikaur
  Building wheel for pikaur (pyproject.toml) ... done
  Created wheel for pikaur: filename=pikaur-1.14.7-py3-none-any.whl size=113681 sha256=ba689a6e5ff081ca7473ce98b0bdc1b4ce2c3ced18c9c778d3d0444b1a86b48b
  Stored in directory: /tmp/pip-ephem-wheel-cache-xxe6o0ug/wheels/70/2e/dd/63151bf7fd1b19ed66fc3f143505b6ff509697527f575bcb2b
Successfully built pikaur
Installing collected packages: pikaur
Successfully installed pikaur-1.14.7
```

# The Problem

```
$ pikaur
-bash: pikaur: command not found
```

I looked in the `bin/` of my venv; no entry point was created.  

I see it is building from `pyproject.toml`.  I tried adding an entry point to 'pyproject.toml`.  I opened a can of worms.  It kept requiring more and more.

I ended up adding the minimum shown below to `pyproject.toml` to get it to install with the entry point and install the dependency, `pyalpm`:

```
[project]
name = "pikaur"
version = '1.14.7'
dependencies = [
  "pyalpm"
]

[project.scripts]
pikaur = "pikaur.main:main"
```

We would obviously want all of the attributes from the `setup.py`.  I didn't create a pull request because this will affect the steps for creating a release.  

If you would like, I'll add all the attributes from the `setup.py` and create a pull request.

**Comment by actionless** [comment]
if you familiar with pyproject feel free to PR the move from the setup.py workflow 😺👍
