### ISSUE TITLE
Error when calling retrieving PKBUILD with `pikaur -G`

### ISSUE THREAD

**Issue by AKorezin** [actionless/pikaur#721]
```
Pikaur v1.15.2
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

*devtools*: *1.0.0*, *1.0.1*

##### Description:

`pikaur -G` triggers error message `==> ERROR: invalid argument: --unprivileged`.

https://github.com/actionless/pikaur/blob/1519cdcacb1e3cc109b236eebe4704e230699ec7/pikaur/getpkgbuild_cli.py#L61-L67

The script calls `pkgctl repo clone --unprivileged`.
But *pkgctl* can't handle it.

##### Attached log:

```
pikaur -G devtools
Reading repository package databases...

Package 'devtools' going to be cloned into '/tmp/devtools'...
==> ERROR: invalid argument: --unprivileged
```

**Comment by actionless** [comment]
yup, that's due to new devtools release, i'll bump pikaur update with the renamed pkgctl flag
