### ISSUE TITLE
Support for doas without permit

### ISSUE THREAD

**Issue by avalanchemarramrat** [actionless/pikaur#725]
Using doas `permit` on non-OpenBSD operating systems may result in a security hole.
Could you please support doas with `permit` disabled?
By the way, [paru](https://github.com/Morganamilo/paru) supports doas without permit.

**Comment by actionless** [comment]
idk, mb it works in the current `pikaur-git`? (it have new permission-elevating system)

**Comment by GambitVKM** [comment]
Last pikaur update (1.17-1) broke doas work.

```
pikaur -Suuy --noconfirm
doas: invalid option -- '-'
usage: doas [-Lns] [-C config] [-u user] command [args]
```

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
