### ISSUE TITLE
pikaur hands over `--preserve-env` to non-sudo tool

### ISSUE THREAD

**Issue by Baerbeisser** [actionless/pikaur#734]
##### Prerequisites:
pikaur.conf:
`privilegeescalationtool = rdo` or everything not sudo

##### Description:
Updated pikaur from 1.16.1-1 -> 1.17-1, after that i get
```
pikaur -Sv caja
=> rdo --preserve-env /usr/bin/pikaur -Sv caja --pikaur-config=/home/dani/.config/pikaur.conf --user-id=1000
(rdo) Password: 
rdo: --preserve-env: No such file or directory
```
`--preserve-env` is a parameter of sudo.
It appears in `pikaur/core.py:175` and `pikaur/privilege.py:61`.

**Comment by actionless** [comment]
but only sudo and doas supported (they all decided to invent different CLI flags for doing same thing 🙄), feel free to add support for your custom tool as well

**Comment by Baerbeisser** [comment]
That's a feature of such tools, that they don't do much except running stuff as root. ;-)

Feature Request: adding support for [ssu](https://github.com/illiliti/ssu)
Because yay works fine with ssu and never asks for passwords anymore. Or something like
```
privilegeescalationtool = ssu
privilegeescalationflags = '--'
```

**Comment by actionless** [comment]
it's not as easy as just passing hardcoded list of args from the config - beacuse the value of preserve-env depends on actual envs, see https://github.com/actionless/pikaur/blob/075e7eb2d240e8ccbfdb3e5deb24a6872cc828b7/pikaur/privilege.py#L90

**Comment by Baerbeisser** [comment]
I see it would need some rework.
But could you not just add --preserve-env + args only to the command *if* dynamicusers is true?

**Comment by actionless** [comment]
no, it's needed not only for DynamicUsers

if you want to implement support for your favorite tool, check as an example:

```console
$ grep -R doas pikaur
pikaur/privilege.py:    if PikaurConfig().misc.PrivilegeEscalationTool.get_str() == "doas":
pikaur/privilege.py:        if PikaurConfig().misc.PrivilegeEscalationTool.get_str() == "doas":
```
