### ISSUE TITLE
Unconditional `sudo --preserve-env` breaks preinst/postinst hooks

### ISSUE THREAD

**Issue by NeoRaider** [actionless/pikaur#735]
```
pikaur -Vq
Pikaur v1.17
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:

Since one of the last updates, Pikaur preserves certain environment variables when `sudo`ing, in particular `$HOME`, which has a number of weird effects on hooks run by pacman. Two issues I've noticed (but there may be more):

1. When updating a texlive package:
```
% pikaur -S texlive-latexextra                         
[...]
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating TeXLive filename database...
(3/4) Updating TeXLive format files...
fmtutil [WARNING]: resetting $HOME value (was /home/neoraider) to root's actual home (/root).
(4/4) Updating TeXLive font maps...
updmap [WARNING]: resetting $HOME value (was /home/neoraider) to root's actual home (/root).
```
As far as I can tell, this warning is only cosmetic and doesn't cause actual problems.

2. When updating any package that triggers an etckeeper commit (needs etckeeper configured to commit automatically on pacman updates):
```
% pikaur -S dhcp
[...]
:: Running pre-transaction hooks...
(1/1) etckeeper: pre-transaction commit
error: gpg failed to sign the data:
gpg: WARNING: unsafe ownership on homedir '/home/neoraider/.gnupg'
[GNUPG:] KEY_CONSIDERED 6664E7BDA6B669881EC52E7516EF3F64CB201D9C 2
[GNUPG:] BEGIN_SIGNING H10
[GNUPG:] PINENTRY_LAUNCHED 264215 gnome3:curses 1.2.1 - xterm-256color :0 - 0/0 0
gpg: signing failed: Inappropriate ioctl for device
[GNUPG:] FAILURE sign 83918950
gpg: signing failed: Inappropriate ioctl for device

fatal: failed to write commit object
warning: etckeeper failed to commit changes in /etc using git
:: Processing package changes...
(1/1) reinstalling dhcp                                                                                            [#####################################################################] 100%
:: Running post-transaction hooks...
(1/5) Creating system user accounts...
(2/5) Reloading system manager configuration...
(3/5) Creating temporary files...
(4/5) Arming ConditionNeedsUpdate...
(5/5) etckeeper: post-transaction commit
error: gpg failed to sign the data:
gpg: WARNING: unsafe ownership on homedir '/home/neoraider/.gnupg'
[GNUPG:] KEY_CONSIDERED 6664E7BDA6B669881EC52E7516EF3F64CB201D9C 2
[GNUPG:] BEGIN_SIGNING H10
[GNUPG:] PINENTRY_LAUNCHED 264411 gnome3:curses 1.2.1 - xterm-256color :0 - 0/0 0
gpg: signing failed: Inappropriate ioctl for device
[GNUPG:] FAILURE sign 83918950
gpg: signing failed: Inappropriate ioctl for device

fatal: failed to write commit object
warning: etckeeper failed to commit changes in /etc using git
```
Here, git incorrectly picks up my user's `.gitconfig` instead of root's, which breaks due to commit signing being configured for my user.

**Comment by actionless** [comment]
--preserve-env is intended, so you can do stuff like `MY_ENV=foo pikaur -S some-pkg`, so i guess when running cmds as root some of the env vars should be excluded

**Comment by NeoRaider** [comment]
Do you have examples for variables that are useful to pass to pacman at all? Or are there other commands besides pacman that pikaur runs as root?

I'd rather opt-in than opt-out passing variables. Maybe something like `pikaur --env MY_ENV=foo -S some-pkg`, or a list of allowed variables in `pikaur.conf`?

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by actionless** [comment]
i've just made the allow-list hardcoded by now: https://github.com/actionless/pikaur/commit/f457b7e596c8ef6445e84b6c1aa1f768f92199d4#diff-3ea9f507b011ec8e3424ba3685ee193011e370fedd5ea290d5643d1aa49d10aeR18

if people would need more env vars - i'll make it configurable via the config file

**Comment by NeoRaider** [comment]
Thanks for the quick fix. No further issues with `pikaur-git` :+1:
