### ISSUE TITLE
Request for info: how to deal with "cannot be found in AUR"?

### ISSUE THREAD

**Issue by j77h** [actionless/pikaur#737]
Thanks for pikaur. 
I've been using it for years and it works well. 

The list of "packages cannot be found in AUR" puzzles me.
It appears after `pikaur -Sua`, and grows longer as time goes by.

What can I do about those packages?
Have some moved to Arch repos?
Are some from dead projects? (I think w_scan is dead)

Most of them I don't need (I think I have uninstalled some);
how can I tell pikaur not to list these?

`pikaur -Sua --verbose --pikaur-debug` reveals a list named `not_found_aur_pkgs`,
but I don't have time to analyse the code, find out where the list comes from,
then hopefully understand what to do.

After an hour of searching the web I've seen no sign of a clear answer.

This is the list I get now:

```
:: warning: Following packages cannot be found in AUR:
daala
edid-decode
gtk-theme-breath
ipw2100-fw
ipw2200-fw
js78
libnm-glib
libopenaptx
libsidplay
manjaro-documentation-en
manjaro-firmware
manjaro-tools-base
noto-fonts-compat
w_scan
```

**Comment by actionless** [comment]
try running `pikaur -Ss <PKG_NAME>` for those packages
