### ISSUE TITLE
Certain messages are unexpectedly indented

### ISSUE THREAD

**Issue by jmcantrell** [actionless/pikaur#739]
```
pikaur -Vq
Pikaur v1.18.r0.gc650ec9
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### [Optional] Prerequisites:

Possibly have some dev package installed? It seems to only happen (for me) with dev packages.

##### Description:

When upgrading dev packages, some messages are indented when they shouldn't be.

![Screen Shot 2023-07-30 at 2 01 27 PM](https://github.com/actionless/pikaur/assets/33200/9b7447d2-e0ca-49ed-b5bd-c4a02a849358)

I thought it might be an issue with the TERM setting, but this happens on the desktop (TERM=foot), over ssh (TERM=xterm) and ssh with tmux (TERM=tmux).

I then thought it might be the shell, but it also happens with zsh and bash (with and without shell customizations).

##### Attached log:

```
pikaur -Syu --aur --devel --noconfirm --needed --verbose --pikaur-debug
```

[pikaur-debug.txt](https://github.com/actionless/pikaur/files/12209909/pikaur-debug.txt)

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by jmcantrell** [comment]
Works for me! Thank you
