### ISSUE TITLE
Pikaur just hangs when synchronizing packages

### ISSUE THREAD

**Issue by jibarofoss** [actionless/pikaur#744]
```
pikaur -Vq
Pikaur v1.18.2.r8.gb975562
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:
Pikaur just hangs during the synchronizing packages stage. Not a network or mirror issue, since pacman works just fine.

##### Attached log:

```
pikaur -S my-precious-package --verbose --pikaur-debug
pikaur -Syu --verbose --pikaur-debug
:: debug: main_1000: Setting stdout to utf-8...
:: debug: main_1000: already set - nothing to do
:: debug: main_1000: Setting stderr to utf-8...
:: debug: main_1000: already set - nothing to do
:: debug: main_1000: Pikaur operation found for args ['/usr/bin/pikaur', '-Syu', '--verbose', '--pikaur-debug']: cli_install_packages
=> sudo --preserve-env=EDITOR -- /usr/bin/pikaur -Syu --verbose --pikaur-debug --pikaur-config=/home/jibarofoss/.config/pikaur.conf --user-id=1000 --home-dir=/home/jibarofoss
:: debug: main_0: Setting stdout to utf-8...
:: debug: main_0: already set - nothing to do
:: debug: main_0: Setting stderr to utf-8...
:: debug: main_0: already set - nothing to do
:: debug: main_0: Pikaur operation found for args ['/usr/bin/pikaur', '-Syu', '--verbose', '--pikaur-debug', '--pikaur-config=/home/jibarofoss/.config/pikaur.conf', '--user-id=1000', '--home-dir=/home/jibarofoss']: cli_install_packages
:: debug: news: init
:: debug: news: fetch_latest
=> pacman --color=always --sync --refresh
=> GET https://www.archlinux.org/feeds/news/
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
```

**Comment by jibarofoss** [comment]
So it eventually completed. So I decided to execute a simple `time pikaur -Syu`, which resulted in 
```
real    6m34.497s
user    0m0.080s
sys     0m0.031s
```
My CPU was basically idle during this time.

**Comment by actionless** [comment]
on which exact line it's waiting for 6 minutes?

is reproducible every time or happens occasionally?

**Comment by jibarofoss** [comment]
It hangs on `multilib is up to date`. It happens every time I run pikaur since yesterday. I've rebooted twice to rule out transient shenanigans.

**Comment by actionless** [comment]
upload the full log then and insert `>_____________` at the moment it freezes

**Comment by jibarofoss** [comment]
> upload the full log then and insert `>_____________` at the moment it freezes

Where is the log stored?

**Comment by actionless** [comment]
in terminal when you run pikaur with  --pikaur-debug flag

**Comment by jibarofoss** [comment]
Got an email from my ISP today that they were having some network issues that affected some services. Issues with pikaur are gone today so I guess it was being affected by it. Sorry for bothering you.

**Comment by actionless** [comment]
that makes sense, since the hang was happening while waiting for network request reply from AUR RPC
