### ISSUE TITLE
Compilation error with the version 1.18.3-1

### ISSUE THREAD

**Issue by plague-doctor** [actionless/pikaur#747]
This issue has been closed too soon: https://github.com/actionless/pikaur/issues/746

Fully updated Arch Linux. Still cannot compile pikaur:

```
msgfmt -o locale/uk.mo locale/uk.po
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
Traceback (most recent call last):
  File "/var/cache/private/pikaur/build/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
make: *** [Makefile:48: pikaur.1] Error 1
==> ERROR: A failure occurred in build().
```

**Comment by actionless** [comment]
what version of markdown-it do you have installed?

apparently you're using either a mixture of different repositories or using a mirror which have troubles syncing to upsteram arch repos

**Comment by HennoHimself** [comment]
I have the same issue and am running python-markdown-it-py-2.2.0-3

**Comment by actionless** [comment]
https://archlinux.org/packages/extra/any/python-markdown-it-py/
