### ISSUE TITLE
unexpected build failed after try  to update  to aur/pikaur  1.18.3-1

### ISSUE THREAD

**Issue by maclinuxG4** [actionless/pikaur#748]
```
pikaur -Vq

```
Pikaur v1.18.2
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6

##### [Optional] Prerequisites:

yay -Syyu

##### Description:
1 pikaur                           (Installé)(Les fichiers de compilation existent)
==> Paquets à nettoyer avant compilation (cleanBuild) ?
==> [N]Aucun [A]Tous [Ab]Annuler [I]nstallés [No]nInstallés ou (1 2 3, 1-3, ^4)
==> A
:: Suppression (1/1) : /home/user/.cache/yay/pikaur
HEAD est maintenant à 262ced7 update to 1.18.3
avertissement : impossible d'ouvrir le répertoire 'pkg/': Permission non accordée
Suppression de pikaur-1.18.3.tar.gz
Suppression de pkg/
Suppression de src/
  1 pikaur                           (Installé)(Les fichiers de compilation existent)
==> Afficher les diffs ?
==> [N]Aucun [A]Tous [Ab]Annuler [I]nstallés [No]nInstallés ou (1 2 3, 1-3, ^4)
==> N
==> Création du paquet pikaur 1.18.3-1 (sam. 19 août 2023 09:48:34)
==> Récupération des sources…
  -> Téléchargement de pikaur-1.18.3.tar.gz…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2159k  100 2159k    0     0  5264k      0 --:--:-- --:--:-- --:--:-- 5264k
==> ATTENTION : Ignore la vérification des signatures PGP des fichiers sources.
==> Validation des fichiers source avec b2sums…
    pikaur-1.18.3.tar.gz ... Réussite
:: (1/1) Lecture de SRCINFO : pikaur
==> Création du paquet pikaur 1.18.3-1 (sam. 19 août 2023 09:48:35)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> pikaur-1.18.3.tar.gz trouvé
==> Validation des fichiers source avec b2sums…
    pikaur-1.18.3.tar.gz ... Réussite
==> Suppression du répertoire $srcdir/ existant…
==> Extraction des sources…
  -> Extraction de pikaur-1.18.3.tar.gz avec bsdtar
==> Les sources sont prêtes.
==> Création du paquet pikaur 1.18.3-1 (sam. 19 août 2023 09:48:36)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> ATTENTION : Utilisation de l’arbre $srcdir/ existant
==> Lancement de build()…
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
........................................................ terminé.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
..................................................... terminé.
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
..................................................... terminé.
test -f locale/pt_BR.po || msginit --locale=pt_BR --no-translator --input=locale/pikaur.pot --output=locale/pt_BR.po
msgmerge --update locale/pt_BR.po locale/pikaur.pot
Traceback (most recent call last):
  File "/home/mike/.cache/yay/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
make: *** [Makefile:48: pikaur.1] Error 1
make: *** Attente des tâches non terminées....

##### Attached log:

```
pikaur -S my-precious-package --verbose --pikaur-debug


```
pikaur -S my-precious-package --verbose --pikaur-debug
:: déboguer : main_1000: Setting stdout to utf-8...
:: déboguer : main_1000: already set - nothing to do
:: déboguer : main_1000: Setting stderr to utf-8...
:: déboguer : main_1000: already set - nothing to do
:: déboguer : main_1000: Pikaur operation found for args ['/usr/bin/pikaur', '-S', 'my-precious-package', '--verbose', '--pikaur-debug']: cli_install_packages
=> sudo --preserve-env=EDITOR -- /usr/bin/pikaur -S my-precious-package --verbose --pikaur-debug --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user
[sudo] Mot de passe de mike : 
:: déboguer : main_0: Setting stdout to utf-8...
:: déboguer : main_0: already set - nothing to do
:: déboguer : main_0: Setting stderr to utf-8...
:: déboguer : main_0: already set - nothing to do
:: déboguer : main_0: Pikaur operation found for args ['/usr/bin/pikaur', '-S', 'my-precious-package', '--verbose', '--pikaur-debug', '--pikaur-config=/home/user/.config/pikaur.conf', '--user-id=1000', '--home-dir=/home/user']: cli_install_packages
:: déboguer : install_info_fetcher: 
Gonna fetch install info for:
    install_package_names=['my-precious-package']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: déboguer : install_info_fetcher: Gonna get repo pkgs install info...
Lecture des bases de données du paquet…
Lecture de la base locale du paquet…
:: déboguer : install_info_fetcher: Checking if '['my-precious-package']' is installable:
=> pacman --color=always --sync my-precious-package --print-format %r/%n
:: déboguer : install_info_fetcher: Check failed - gonna check it separately:
:: déboguer : install_info_fetcher: Checking if 'my-precious-package' exists in the repo:
=> pacman --color=always --sync my-precious-package --print-format %r/%n --nodeps --nodeps
:: déboguer : install_info_fetcher:   'my-precious-package' is NOT found in the repo.
:: déboguer : install_info_fetcher: Check partially passed - gonna get install infos:
:: déboguer : install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['my-precious-package']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'my-precious-package': <VersionMatcher my-precious-package['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=my-precious-package
:: déboguer : install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[]
not found AUR pkgs:
    not_found_aur_pkgs=['my-precious-package']
:: avertissement : Le paquet suivant ne se trouve pas dans l'AUR :
    my-precious-package    
:: déboguer : main_0: Restoring stdout...
:: déboguer : main_0: nothing to do
:: déboguer : main_0: Restoring stderr...
:: déboguer : main_0: nothing to do
:: déboguer : main_1000: Restoring stdout...
:: déboguer : main_1000: nothing to do
:: déboguer : main_1000: Restoring stderr...
:: déboguer : main_1000: nothing to do

**Comment by darkbaboon** [comment]
Try pikaur -S pikaur --verbose --pikaur-debug instead of _my-precious-package_ which is a nickname for the package you try to build.

**Comment by maclinuxG4** [comment]
pikaur -S pikaur --verbose --pikaur-debug
:: déboguer : main_1000: Setting stdout to utf-8...
:: déboguer : main_1000: already set - nothing to do
:: déboguer : main_1000: Setting stderr to utf-8...
:: déboguer : main_1000: already set - nothing to do
:: déboguer : main_1000: Pikaur operation found for args ['/usr/bin/pikaur', '-S', 'pikaur', '--verbose', '--pikaur-debug']: cli_install_packages
=> sudo --preserve-env=EDITOR -- /usr/bin/pikaur -S pikaur --verbose --pikaur-debug --pikaur-config=/home/user/.config/pikaur.conf --user-id=1000 --home-dir=/home/user
[sudo] Mot de passe de user : 
:: déboguer : main_0: Setting stdout to utf-8...
:: déboguer : main_0: already set - nothing to do
:: déboguer : main_0: Setting stderr to utf-8...
:: déboguer : main_0: already set - nothing to do
:: déboguer : main_0: Pikaur operation found for args ['/usr/bin/pikaur', '-S', 'pikaur', '--verbose', '--pikaur-debug', '--pikaur-config=/home/mike/.config/pikaur.conf', '--user-id=1000', '--home-dir=/home/user']: cli_install_packages
:: déboguer : install_info_fetcher: 
Gonna fetch install info for:
    install_package_names=['pikaur']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: déboguer : install_info_fetcher: Gonna get repo pkgs install info...
Lecture des bases de données du paquet…
Lecture de la base locale du paquet…
:: déboguer : install_info_fetcher: Checking if '['pikaur']' is installable:
=> pacman --color=always --sync pikaur --print-format %r/%n
:: déboguer : install_info_fetcher: Check failed - gonna check it separately:
:: déboguer : install_info_fetcher: Checking if 'pikaur' exists in the repo:
=> pacman --color=always --sync pikaur --print-format %r/%n --nodeps --nodeps
:: déboguer : install_info_fetcher:   'pikaur' is NOT found in the repo.
:: déboguer : install_info_fetcher: Check partially passed - gonna get install infos:
:: déboguer : install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['pikaur']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'pikaur': <VersionMatcher pikaur['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pikaur
:: déboguer : install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "pikaur" 1.18.3-1>]
not found AUR pkgs:
    not_found_aur_pkgs=[]
:: déboguer : install_info_fetcher: got AUR pkgs install info: [<AURInstallInfo "pikaur" 1.18.2-1 -> 1.18.3-1>]
Résolution des dépendances de l'AUR…
=> pacman --color=always --deptest pyalpm git python-wheel python-hatchling python-build python-installer python-setuptools python-markdown-it-py
:: déboguer : install_cli: self.install_info.all_install_info_containers=([], [], [], [], [], [], [<AURInstallInfo "pikaur" 1.18.2-1 -> 1.18.3-1>], [])

:: Le paquet de l'AUR sera installé :
 pikaur                                1.18.2-1             -> 1.18.3-1

:: déboguer : prompt: Gonna get input from user...
:: déboguer : FileLock: Acquiring /tmp/pikaur_prompt_296433.lock...
:: déboguer : FileLock: Acquired /tmp/pikaur_prompt_296433.lock
:: déboguer : prompt_nolock: Restoring TTY...
:: déboguer : prompt_nolock: Using standard input reader...
:: Commencer l'installation ? [O/n]
:: [v]oir les détails du paquet   sélectionner [m]anuellement les paquets
>> O
:: déboguer : FileLock: Releasing /tmp/pikaur_prompt_296433.lock
:: déboguer : FileLock: Released /tmp/pikaur_prompt_296433.lock
:: déboguer : prompt: Got answer: 'o'
:: déboguer : build: Build dir: /home/user/.cache/pikaur/build/pikaur
=> sudo --user=#1000 --preserve-env=EDITOR -- git -C /home/mike/.local/share/pikaur/aur_repos/pikaur pull origin master
:: déboguer : build: Build dir: /home/mike/.cache/pikaur/build/pikaur
=> pacman --color=always --deptest pyalpm git
=> pacman --color=always --deptest python-wheel python-hatchling python-build python-installer python-setuptools python-markdown-it-py
recherche des paquets de l'AUR en conflit…
:: avertissement : Ne pas montrer de différence pour le paquet pikaur (déjà examiné)
:: déboguer : prompt: Gonna get input from user...
:: déboguer : FileLock: Acquiring /tmp/pikaur_prompt_147565.lock...
:: déboguer : FileLock: Acquired /tmp/pikaur_prompt_147565.lock
:: déboguer : prompt_nolock: Restoring TTY...
:: déboguer : prompt_nolock: Using standard input reader...
Voulez-vous éditer PKGBUILD pour le paquet pikaur ? [o/N] o
:: déboguer : FileLock: Releasing /tmp/pikaur_prompt_147565.lock
:: déboguer : FileLock: Released /tmp/pikaur_prompt_147565.lock
:: déboguer : prompt: Got answer: 'o'
=> sudo --user=#1000 --preserve-env=EDITOR -- /usr/bin/nano /home/user/.local/share/pikaur/aur_repos/pikaur/PKGBUILD

:: déboguer : install_cli: Gonna build PKGBUILDS: {'pikaur': <PackageBuild "pikaur" ['pikaur']>}
:: déboguer : install_cli: Gonna build pkgnames: ['pikaur']
=> sudo --user=#1000 --preserve-env=EDITOR -- mkdir -p /home/user/.cache/pikaur/build/pikaur
=> sudo --user=#1000 --preserve-env=EDITOR -- cp -r /home/mike/.local/share/pikaur/aur_repos/pikaur/PKGBUILD /home/user/.local/share/pikaur/aur_repos/pikaur/CHANGELOG /home/user/.local/share/pikaur/aur_repos/pikaur/last_installed.txt /home/user/.local/share/pikaur/aur_repos/pikaur/.SRCINFO /home/user/.cache/pikaur/build/pikaur
:: déboguer : FileLock: Acquiring /tmp/pikaur_build_deps.lock...
:: déboguer : FileLock: Acquired /tmp/pikaur_build_deps.lock
:: déboguer : FileLock: Releasing /tmp/pikaur_build_deps.lock
:: déboguer : FileLock: Released /tmp/pikaur_build_deps.lock
=> sudo --user=#1000 --preserve-env=EDITOR -- makepkg --packagelist
:: déboguer : build: Package names: InteractiveSpawn returned 0:
STDOUT:
/home/user/.cache/pikaur/build/pikaur/pikaur-1.18.3-1-any.pkg.tar.zst


STDERR:

:: déboguer : build: PKGDEST: None
:: déboguer : build: Full path: /home/user/.cache/pikaur/build/pikaur/pikaur-1.18.3-1-any.pkg.tar.zst, base path: pikaur-1.18.3-1-any.pkg.tar.zst
:: déboguer : build: New package path: /home/user/.cache/pikaur/pkg/pikaur-1.18.3-1-any.pkg.tar.zst

:: Démarrer la compilation:
=> sudo --user=#1000 --preserve-env=EDITOR -- makepkg --force
==> Création du paquet pikaur 1.18.3-1 (sam. 19 août 2023 19:42:34)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> Téléchargement de pikaur-1.18.3.tar.gz…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2159k    0 2159k    0     0  2023k      0 --:--:--  0:00:01 --:--:-- 5636k
==> Validation des fichiers source avec b2sums…
    pikaur-1.18.3.tar.gz ... Réussite
==> Extraction des sources…
  -> Extraction de pikaur-1.18.3.tar.gz avec bsdtar
==> Lancement de build()…
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
........................................................ terminé.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
Traceback (most recent call last):
  File "/home/user/.cache/pikaur/build/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
.......make: *** [Makefile:48: pikaur.1] Error 1
..............................................make: *** Attente des tâches non terminées....
... terminé.
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

La commande 'sudo --user=#1000 --preserve-env=EDITOR -- makepkg --force' a échoué.
:: déboguer : prompt: Gonna get input from user...
:: déboguer : FileLock: Acquiring /tmp/pikaur_prompt_548314.lock...
:: déboguer : FileLock: Acquired /tmp/pikaur_prompt_548314.lock
:: déboguer : prompt_nolock: Restoring TTY...
:: déboguer : prompt_nolock: Using standard input reader...
:: Essayer de récupérer ?
[R] réessayer de compiler
[p] ignorer le contrôle PGP
[c] ignorer les sommes de contrôle
[f] ignorer la fonction 'check()' du PKGBUILD
[n] ignorer la fonction 'prepare()' du PKGBUILD
[i] ignorer l'architecture
[d] effacer le répertoire de compilation et réessayer
[e] éditer le PKGBUILD
------------------------
[s] ignorer la compilation de ce paquet
[a] abandonner la compilation de tous les paquets
> R
:: déboguer : FileLock: Releasing /tmp/pikaur_prompt_548314.lock
:: déboguer : FileLock: Released /tmp/pikaur_prompt_548314.lock
:: déboguer : prompt: Got answer: 'r'
=> sudo --user=#1000 --preserve-env=EDITOR -- makepkg --force
==> Création du paquet pikaur 1.18.3-1 (sam. 19 août 2023 19:42:48)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> pikaur-1.18.3.tar.gz trouvé
==> Validation des fichiers source avec b2sums…
    pikaur-1.18.3.tar.gz ... Réussite
==> Extraction des sources…
  -> Extraction de pikaur-1.18.3.tar.gz avec bsdtar
==> Suppression du répertoire $pkgdir/ existant…
==> Lancement de build()…
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
...................................................... terminé.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
Traceback (most recent call last):
  File "/home/user/.cache/pikaur/build/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
.make: *** [Makefile:48: pikaur.1] Error 1
.................................................make: *** Attente des tâches non terminées....
... terminé.
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

La commande 'sudo --user=#1000 --preserve-env=EDITOR -- makepkg --force' a échoué.
:: déboguer : prompt: Gonna get input from user...
:: déboguer : FileLock: Acquiring /tmp/pikaur_prompt_317943.lock...
:: déboguer : FileLock: Acquired /tmp/pikaur_prompt_317943.lock
:: déboguer : prompt_nolock: Restoring TTY...
:: déboguer : prompt_nolock: Using standard input reader...
:: Essayer de récupérer ?
[R] réessayer de compiler
[p] ignorer le contrôle PGP
[c] ignorer les sommes de contrôle
[f] ignorer la fonction 'check()' du PKGBUILD
[n] ignorer la fonction 'prepare()' du PKGBUILD
[i] ignorer l'architecture
[d] effacer le répertoire de compilation et réessayer
[e] éditer le PKGBUILD
------------------------
[s] ignorer la compilation de ce paquet
[a] abandonner la compilation de tous les paquets
> d
:: déboguer : FileLock: Releasing /tmp/pikaur_prompt_317943.lock
:: déboguer : FileLock: Released /tmp/pikaur_prompt_317943.lock
:: déboguer : prompt: Got answer: 'd'
=> sudo --user=#1000 --preserve-env=EDITOR -- mkdir -p /home/mike/.cache/pikaur/build/pikaur
=> sudo --user=#1000 --preserve-env=EDITOR -- cp -r /home/mike/.local/share/pikaur/aur_repos/pikaur/PKGBUILD /home/user/.local/share/pikaur/aur_repos/pikaur/CHANGELOG /home/mike/.local/share/pikaur/aur_repos/pikaur/last_installed.txt /home/user/.local/share/pikaur/aur_repos/pikaur/.SRCINFO /home/user/.cache/pikaur/build/pikaur
=> sudo --user=#1000 --preserve-env=EDITOR -- makepkg --force
==> Création du paquet pikaur 1.18.3-1 (sam. 19 août 2023 19:42:57)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> Téléchargement de pikaur-1.18.3.tar.gz…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2159k    0 2159k    0     0  4218k      0 --:--:-- --:--:-- --:--:-- 4218k
==> Validation des fichiers source avec b2sums…
    pikaur-1.18.3.tar.gz ... Réussite
==> Extraction des sources…
  -> Extraction de pikaur-1.18.3.tar.gz avec bsdtar
==> Lancement de build()…
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
	#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
	| xargs --null xgettext --language=python --add-comments --sort-output \
		--default-domain=pikaur --from-code=UTF-8 \
		--keyword='translate' --keyword='translate_many:1,2' \
		--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
........................................................ terminé.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
Traceback (most recent call last):
  File "/home/user/.cache/pikaur/build/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
    OptionsType = markdown_it.utils.OptionsType
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
make: *** [Makefile:48: pikaur.1] Error 1
make: *** Attente des tâches non terminées....
...................................................... terminé.
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

La commande 'sudo --user=#1000 --preserve-env=EDITOR -- makepkg --force' a échoué.
:: déboguer : prompt: Gonna get input from user...
:: déboguer : FileLock: Acquiring /tmp/pikaur_prompt_814110.lock...
:: déboguer : FileLock: Acquired /tmp/pikaur_prompt_814110.lock
:: déboguer : prompt_nolock: Restoring TTY...
:: déboguer : prompt_nolock: Using standard input reader...
:: Essayer de récupérer ?
[R] réessayer de compiler
[p] ignorer le contrôle PGP
[c] ignorer les sommes de contrôle
[f] ignorer la fonction 'check()' du PKGBUILD
[n] ignorer la fonction 'prepare()' du PKGBUILD
[i] ignorer l'architecture
[d] effacer le répertoire de compilation et réessayer
[e] éditer le PKGBUILD
------------------------
[s] ignorer la compilation de ce paquet
[a] abandonner la compilation de tous les paquets
> a
:: déboguer : FileLock: Releasing /tmp/pikaur_prompt_814110.lock
:: déboguer : FileLock: Released /tmp/pikaur_prompt_814110.lock
:: déboguer : prompt: Got answer: 'a'
:: déboguer : main_0: Restoring stdout...
:: déboguer : main_0: nothing to do
:: déboguer : main_0: Restoring stderr...
:: déboguer : main_0: nothing to do
:: déboguer : main_1000: Restoring stdout...
:: déboguer : main_1000: nothing to do
:: déboguer : main_1000: Restoring stderr...
:: déboguer : main_1000: nothing to do

**Comment by tdtooke** [comment]
I have nothing to add that has not already been said but I too have this exact issue so it's not something specific to one person.

**Comment by maclinuxG4** [comment]
locale seems  be change and pikaur doesn't manage something. 
i try to  use previous  rekease pikaur, not sur how to process

**Comment by actionless** [comment]
if you'll continue creating the same duplicate issue over and over i'll have to block your access to repository

https://github.com/actionless/pikaur/issues/747#issuecomment-1685345446
