### ISSUE TITLE
pikaur -U /path/to/PKGBUILD

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#75]
the same as `makepkg -fsri` but fetching deps from AUR

**Comment by actionless** [comment]
that also mean what `pikaur -Uw` should behave like `makepkg -fsr`, right?

**Comment by AladW** [comment]
`-U PKGBUILD` is a completely different meaning than `pacman`'s `-U uri://.pkg.tar.xz` though.

**Comment by actionless** [comment]
or mb to make it like in `yaourt`:

` yaourt {-P --pkgbuild}    [-i --install] <directory>`
