### ISSUE TITLE
Package Conflicts

### ISSUE THREAD

**Issue by ralpheeee88** [actionless/pikaur#76]
am not getting the chance / option to answer `:: bitlbee-libpurple and bitlbee are in conflict. Remove bitlbee? [y/N]`

`loading packages...
resolving dependencies...
looking for conflicting packages...
:: bitlbee-libpurple and bitlbee are in conflict. Remove bitlbee? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: bitlbee-libpurple and bitlbee are in conflict
Command 'sudo pacman --upgrade --ask=no /home/ralphe/.cache/pikaur/pkg/bitlbee-libpurple-3.5.1-1-x86_64.pkg.tar.xz' failed to execute.
Do you want to retry? [Y/n]
`

**Comment by actionless** [comment]
that conflict unresolvable automatically[1] so pikaur giving you an opportunity to resolve it manually and restart the operation without interrupting


[1] @AladW @rmarquis Am i right?

**Comment by rmarquis** [comment]
I don't think so, this seems to be a trivial conflict situation.

Also, you don not seem to be using the `--ask` parameter correctly. It requires a bitwise value, not a no/yes value.

**Comment by actionless** [comment]
i've just reread the log again, first i've got an impression what pikaur halted instead of trying to resolve deps, but now i think i know what the problem -- pikaur seems to be started without tty (ie like through `xargs`), so i think that's still a correct behavior

@ralpheeee88 what was the pikaur command which lead to this log?

**Comment by ralpheeee88** [comment]
@actionless  just ran pikaur -S  <package>

**Comment by Morganamilo** [comment]
If you're confused about `--ask` here's a little explanation.

It allows you to set the default answers for each question type, it also implies `--noconfirm`.

here's the values for each question type:
```c
typedef enum _alpm_question_type_t {
		ALPM_QUESTION_INSTALL_IGNOREPKG = (1 << 0),
		ALPM_QUESTION_REPLACE_PKG = (1 << 1),
		ALPM_QUESTION_CONFLICT_PKG = (1 << 2),
		ALPM_QUESTION_CORRUPTED_PKG = (1 << 3),
		ALPM_QUESTION_REMOVE_PKGS = (1 << 4),
		ALPM_QUESTION_SELECT_PROVIDER = (1 << 5),
		ALPM_QUESTION_IMPORT_KEY = (1 << 6)
	} alpm_question_type_t;
```

like @rmarquis said it's bitwise so to set multiple you just and them together.

**Comment by actionless** [comment]
i've tried to play a bit with that:
https://github.com/actionless/pikaur/commit/55851083722996cf1d929a842a7fe1d2006379f0
https://github.com/actionless/pikaur/commit/874a7f20e446b8b1ef22853c8ffbbfee716604ac

@ralpheeee88 please try now

**Comment by actionless** [comment]
@rmarquis @Morganamilo mb you also now if it's possible in some way to pass that option to pacman when it's invoked by `makepkg`?

**Comment by actionless** [comment]
@ralpheeee88 can you still reproduce this?

**Comment by ralpheeee88** [comment]
@actionless working as well... Thxs for all your work chief!!!
