### ISSUE TITLE
Install PKGBUILD from remote git repository

### ISSUE THREAD

**Issue by noraj** [actionless/pikaur#761]
```
$ pikaur -Vq
Pikaur v1.18.3
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:

This option is interesting to install package out of a user repository.

* build local PKGBUILDs with AUR deps (`-P`/`--pkgbuild`)

But what would be nice, would be to add an option to install from a git URL a bit like go or pip can do.

It could be an update to the `--pkgbuild` option so that it can fetch remote files too.

The goal is to be able to do that:

```
$ pikaur -P https://github.com/actionless/pikaur 
```

It would do a `git clone --depth 1 https://github.com/actionless/pikaur  "$(mktemp -d)/pikaur"` or something like that then try to find `PKGBUILD` at the root.

Maybe in case of a multi-repo, it could be useful to specify a folder to know where to look for the PKGBUILD.

```
$ pikaur -P https://github.com/BlackArch/blackarch:packages/haiti
```

**Comment by actionless** [comment]
sorry, but i don't like this idea, so even if PR would arrive - it won't be merged

it's a very corner case and could be solved with a 10-character shell alias

**Comment by actionless** [comment]
i recommend submitting package to AUR, or creating your own AUR index, if the package can't be approved to AUR for some reasons

PR for adding support for using 2 or more AUR indexes at the same time - i wouldn't mind merging
