### ISSUE TITLE
pikaur on arm arch64 pauses for "yes" at second confirmation

### ISSUE THREAD

**Issue by switit** [actionless/pikaur#766]
```
pikaur -Vq
'Pikaur v1.18.3
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6'
```

##### [Optional] Prerequisites:
aarch64 machine

##### Description:
pikaur -Syu pauses for "enter" key at the second "Proceed for installation" as shown by the blank line under the line:
':: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>>

:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) fontconfig-2:2.15.0-2

Total Download Size:   0.34 MiB
Total Installed Size:  1.07 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y

:: Retrieving packages...
 fontconfig-2:2.15.0-2-aarch64               349.1 KiB   631 KiB/s 00:01 [########################################] 100%(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
(1/1) checking available disk space                                      [########################################] 100%
:: Processing package changes...
(1/1) upgrading fontconfig                                               [########################################] 100%
Rebuilding fontconfig cache...
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating fontconfig cache...'

This is not the case with my other arch x86-64 machines 

##### Attached log:

```
pikaur -S sudo --verbose --pikaur-debug
:: debug: main_1001: Setting stdout to utf-8...
:: debug: main_1001: already set - nothing to do
:: debug: main_1001: Setting stderr to utf-8...
:: debug: main_1001: already set - nothing to do
:: debug: main_1001: Pikaur operation found for args ['/usr/bin/pikaur', '-S', 'sudo', '--verbose', '--pikaur-debug']: cli_install_packages
=> sudo -- /usr/bin/pikaur -S sudo --verbose --pikaur-debug --pikaur-config=/home/ws/.config/pikaur.conf --user-id=1001 --home-dir=/home/ws
:: debug: main_0: Setting stdout to utf-8...
:: debug: main_0: already set - nothing to do
:: debug: main_0: Setting stderr to utf-8...
:: debug: main_0: already set - nothing to do
:: debug: main_0: Pikaur operation found for args ['/usr/bin/pikaur', '-S', 'sudo', '--verbose', '--pikaur-debug', '--pikaur-config=/home/ws/.config/pikaur.conf', '--user-id=1001', '--home-dir=/home/ws']: cli_install_packages
:: debug: install_info_fetcher:
Gonna fetch install info for:
    install_package_names=['sudo']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
:: debug: install_info_fetcher: Checking if '['sudo']' is installable:
=> pacman --color=always --sync sudo --print-format %r/%n
:: debug: install_info_fetcher: Check passed - gonna get install infos:
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=[]
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={}
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[]
not found AUR pkgs:
    not_found_aur_pkgs=[]
:: debug: install_info_fetcher: got AUR pkgs install info: []
:: debug: install_cli: self.install_info.all_install_info_containers=([<RepoInstallInfo "sudo" 1.9.15.p4-1 -> 1.9.15.p4-1>], [], [], [], [], [], [], [])

:: Repository package will be installed:
 sudo                                  1.9.15.p4-1          -> 1.9.15.p4-1

:: debug: prompt: Gonna get input from user...
:: debug: FileLock: Acquiring /tmp/pikaur_prompt_288683.lock...
:: debug: FileLock: Acquired /tmp/pikaur_prompt_288683.lock
:: debug: prompt_nolock: Restoring TTY...
:: debug: prompt_nolock: Using standard input reader...
:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>>
:: debug: FileLock: Releasing /tmp/pikaur_prompt_288683.lock
:: debug: FileLock: Released /tmp/pikaur_prompt_288683.lock
:: debug: prompt: No answer provided - using "Y".

pikspect => pacman --color=always --sync --verbose sudo
:: debug: pikspect: Opening virtual terminal...
:: debug: pikspect: fd: 5, pid: 61851
                                     Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : sudo
warning: sudo-1.9.15.p4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) sudo-1.9.15.p4-1

Total Installed Size:  8.04 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation?:: debug: pikspect: Found right answer to `Proceed with installation? [Y/n]`: `Y`
                                                                                                               [Y/n] Y

(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
(1/1) checking available disk space                                      [########################################] 100%
:: Processing package changes...
(1/1) reinstalling sudo                                                  [########################################] 100%
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
(2/3) Creating temporary files...
(3/3) Arming ConditionNeedsUpdate...
:: debug: pikspect: pid 61851 finished with return code: 0
:: debug: pikspect: Exit details: (None, None, None)
:: debug: pacman: Discarding local cache...
:: debug: main_0: Restoring stdout...
:: debug: main_0: nothing to do
:: debug: main_0: Restoring stderr...
:: debug: main_0: nothing to do
:: debug: main_1001: Restoring stdout...
:: debug: main_1001: nothing to do
:: debug: main_1001: Restoring stderr...
:: debug: main_1001: nothing to do
```

**Comment by actionless** [comment]
> pikaur -S my-precious-package --verbose --pikaur-debug

you have to replace `-S my-precious-package` with your actual example though.

**Comment by switit** [comment]
> > pikaur -S my-precious-package --verbose --pikaur-debug
> 
> you have to replace `-S my-precious-package` with your actual example though.

Updated with package "sudo".

**Comment by actionless** [comment]
so, on the line:

> :: Proceed with installation?:: debug: pikspect: Found right answer to `Proceed with installation? [Y/n]`: `Y`
  
 it's waiting for your input instead of proceeding?

**Comment by switit** [comment]
Since it offers "Y" as the answer, it waits for my "enrter" key. After that it will proceed to the end. There's no issue with the overall functionality. Just a little annoying.

**Comment by actionless** [comment]
that's weird

are you sure you don't have any other differences from your normal setup, except for aarch64?

**Comment by switit** [comment]
pacman.conf has architecture set to aach64 instead of auto
[alarm] and [aur] are added to repositories. I tried changing everything to match the x96_64 one but same result.

I suspect it may have something to do with my workaround suggested by someone during the time when there was some problems with new sudo upgrade (pikaur v1.6,). I looked into the sudoer file (specifically the line "Defaults !use_pty" and found it to match the x86_64 one. Cannot dig into the issue report during that time since they are no longer available. So, really don't know what else I did.

**Comment by switit** [comment]
Ok, I may have found the likely culprit. Somehow pikaur got installed also under /home/alarm with pikaur files/folders in .config .cache and .local. It might have been installed during the first system installation. Now even I removed those files/folders, they got recreated when I ran pikaur. Any suggestion?

**Comment by actionless** [comment]
if you have any workarounds applied there - first reset those configs to default and try over

**Comment by switit** [comment]
The only thing I did was un-comment the lind "Defaults !use_pty" in /etc/sudoers. It has been commented back but still same result.
I see that pacman or other aur helpers like paru or yay don't need the second confirmation question "Proceed with installation? [Y/n]". So if pikaur follows suit, my problem should go away.

**Comment by actionless** [comment]
i really can't help much with this as 1) i can't reproduce it 2) in the log i see that everything worked as expected, and pikspect detected an answer and chosen a right answer to it

**Comment by switit** [comment]
Of course I can live with this small glitch.
Thank you.

**Comment by actionless** [comment]
i'll leave it open to see if anyone else on aarch64 would be able to reproduce it or not

**Comment by switit** [comment]
The problem has gone. No pause at the second confirmation any more. The only change that happened before this was the upgrade of some packages as below:
`[2024-02-21T07:14:14+0700] [ALPM] upgraded dav1d (1.3.0-1 -> 1.4.0-1)
[2024-02-21T07:14:14+0700] [ALPM] upgraded giflib (5.2.1-2 -> 5.2.2-1)
[2024-02-21T07:14:14+0700] [ALPM] upgraded libffi (3.4.5-1 -> 3.4.6-1)
[2024-02-21T07:14:14+0700] [ALPM] upgraded openssh (9.6p1-1 -> 9.6p1-3)`

**Comment by actionless** [comment]
unless you running pikaur via ssh session - these 4 packages shouldn't be affecting this - but the problem at first place seemed quite random so i've sorta not surprised it got fixed somehow randomly as well 😸

**Comment by switit** [comment]
I normally run pikaur via ssh to my vps. It's now consistently proceeding without a pause, jsut the same as when run on my x86-64 boxes.

**Comment by actionless** [comment]
then looks like a bug in tty/pty handling got fixed in openssh lib 👍
