### ISSUE TITLE
Pikaur does not work with socks5 proxy set via environment variable

### ISSUE THREAD

**Issue by Bryan2333** [actionless/pikaur#769]
```
pikaur -Vq

Pikaur v1.18.3
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:
Pikaur does not work with socks5 proxy set via http_proxy and https_proxy environment variable.

##### Attached log:

Here is the screenshot of the situation.

![图片](https://github.com/actionless/pikaur/assets/31512600/7a6b9e9e-f476-4427-bedf-794518567f12)

**Comment by actionless** [comment]
did you installed pikaur's optional dependencies for this feature?

**Comment by Bryan2333** [comment]
Yes, I have installed `python-pysocks`. But both socks5 and socks5h failed to work.

**Comment by actionless** [comment]
idk then, i don't have any socks-proxies to test it, neither i am using them - so i recommend you to investigate it yourself or wait for another user with the same problem

**Comment by actionless** [comment]
btw, according to pikaur doc what should be the format of the socks proxy?

and what format other apps using?

https://github.com/actionless/pikaur/pull/362/files#diff-5c5dc7f52a435c4c22ba7165b7ff58277aa7e2ef7b71bced714cac3f6bc28350R92
