### ISSUE TITLE
The multiple AUR packages building is not optimal if the dependencies are being changed on the go

### ISSUE THREAD

**Issue by roussak** [actionless/pikaur#770]
```
pikaur -Vq
Pikaur v1.18.4.r0.g4443da1
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### [Optional] Prerequisites:

Not all potentially-needed development packages are installed on the system. For example, the `autoconf` package is absent.

##### Description:

The AUR package maintainers may omit some of the build-time dependencies needed to build theirs packages. If we are going to build several AUR packages with `pikaur` at one run, we may get the corresponding error message somewhere in the middle of the process. And here we may to use an option to edit the `PKGBUILD` file and add the absent packages into the `makedepends` array. But, in such a case the `pikaur` restarts the building process for all the packages. As a result, it tries to build all the packages which already has been built (and during this process it installs the corresponding dependencies, performs checks, tries to build a current package, sees that it has already been built and does another mainly unneeded actions). As a result, it returns to the "problematic" package and... may fail again because there is no another development package in the system. We may edit the `PKGBUILD` again and the process will be repeated again.

Probably, it would more optimal to restart the current package building (and continue with the rest of packages, of course).

**Comment by actionless** [comment]
more on this topic - i'd rather consider checking `base-devel` and printing a warning if it's not installed (if that's not yet implemented in makepkg itself?) - if not feel free to file a PR to add that

**Comment by roussak** [comment]
It seems like you didn't read the issue description completely... :(

It was _not_ about fixing all the "broken" packages (just in case, nor about saving the World too), but about the strange (in my opinion) behaviour of the `pikaur` utility. It tries to rebuild _all_ packages instead of the _current_ package rebuilding after that its `PKGBUILD` was edited. Furthermore, the reason of this editing is the secondary here. So, the checking on the `base-devel` presence doesn't matter here.

But, of course, if you don't want to make your software better, I can't enforce you...

**Comment by roussak** [comment]
I see. But, how these new dependencies can influence on the packages that already built?

Let's imagine, we are trying to install 20 packages and the described case is "fired" on the 20th one. We has edited the `PKGBUILD` and are going to see the movie... Probably, not the last episode.

**Comment by actionless** [comment]
> and during this process it installs the corresponding dependencies, performs checks, tries to build a current package, sees that it has already been built and does another mainly unneeded actions

and this is also by design - because some AUR packages require dependencies installed for executing pkgver

so only one potential improvement i see is to do smth like this, (75a3380) to mark already built packages, thus avoid need to call pkgver() of pkgbuild of verifying if that version is already installed
