### ISSUE TITLE
Does pikaur support `pacman -Syudd`

### ISSUE THREAD

**Issue by baseplate-admin** [actionless/pikaur#771]
```
=> pacman --version
Pikaur v1.18.4
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:

Hi i am using the [testing repositories of arch linux](https://wiki.archlinux.org/title/official_repositories#Testing_repositories).
But this often results in things like
```
Installing expat (2.6.0-1) breaks dependency 'expat=2.5.0' required by lib32-expat
```

Which can be resolved when i use `pacman -Syudd`. ( this advice is what i got from this [reddit post](https://www.reddit.com/r/archlinux/comments/14kng1w/how_do_you_deal_with_updates_that_break/) )
But when i do `pikaur -Syudd`, it is not doing the same magic as `pacman -Syudd`.

I recon it might has to do something with the options that `pikaur` passes to `pacman` 

##### Attached log:

Currently not possible due to me upgrading my system. But will update it soon.

**Comment by actionless** [comment]
> Attached log:

> Currently not possible due to me upgrading my system. But will update it soon.

yup, i would need it

mb you could use VM/chroot/docker + `downgrade` util to create a reproducion environment without danger to your "main" setup

**Comment by baseplate-admin** [comment]
Hi, i am extremely sorry that i cant re-produce this issue, even when i rolled my `btrfs` backup to 7 days ago, the issue was not reproducible. 

If i encounter this issue again, i will add additional logs.

Sorry for noise.
