### ISSUE TITLE
Create stable AUR package

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#78]

**Comment by AladW** [comment]
Simple, you just leave out the `pkgver()` function and replace
```
"$pkgname::git+https://github.com/actionless/pikaur.git#branch=master"
```
with
```
"$pkgname-$pkgver.tar.gz"::https://github.com/actionless/pikaur/archive/"$pkgver".tar.gz
```
NB. `make` belongs in the `build()` function

**Comment by AladW** [comment]
Do note that if the next release is `0.10` you'll need an `epoch` value, since `0.10 < 0.9` according to pacman.

**Comment by Morganamilo** [comment]
Are you sure?

```sh
morganamilo@Vinyl ~ % vercmp 0.10 0.9
1
```

**Comment by AladW** [comment]
cf. https://www.archlinux.org/packages/community/x86_64/mpv/

**Comment by Morganamilo** [comment]
It's my understanding that vercmp understands decimals as whole numbers not just individual digits:
`10` > `9` > `1` so `0.10` > `0.9` > `0.1` sure its not the way real numbers work but its a common thing in versioning.

I think vercmp is pretty trustworthy, I could hookup a test using Pacman itself if you like.

**Comment by AladW** [comment]
Well both `pacman` and `vercmp` use the logic so your argument sounds fair to me.

**Comment by actionless** [comment]
so i've actually decided what storing the aur credentials even encrypted in travis is not good idea so i just made extended a script which i am using to tag a new release to also push it to AUR with the interactive confirmation

**Comment by actionless** [comment]
@AladW also resolved your find regarding build/package section and few other small problems

**Comment by AladW** [comment]
:+1:
