### ISSUE TITLE
Can't install package. (pacman error)

### ISSUE THREAD

**Issue by baptistemeunier** [actionless/pikaur#79]
Like this issue #54 i can't install a package with pikaur because pacman report that -a option doesn't exist.

I got this error : Command: sudo pacman --upgrade --noconfirm -a **packages** " failed to execute. 

![Image](https://image.ibb.co/eedYnx/Deepin_Capture_cran_zone_de_s_lection_20180319112544.png)
Sorry it's french but it's can be understand

**Comment by actionless** [comment]
i think you did `pikaur -Syua` intead of `pikaur -Syu`

**Comment by actionless** [comment]
seems to be related to https://github.com/actionless/pikaur/issues/26

**Comment by actionless** [comment]
@baptistemeunier ?
