### ISSUE TITLE
new version  Pikaur v1.20 asks for root for operations that didn't ask before

### ISSUE THREAD

**Issue by rezad1393** [actionless/pikaur#790]
```
pikaur -Vq
=> pacman --version
Pikaur v1.20
Pacman v6.1.0 - libalpm v14.0.0 - pyalpm v0.10.6

```

##### Description:
when I run "pikaur anything" to search for stuff, it asks for root password.

**Comment by actionless** [comment]
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
