### ISSUE TITLE
XDG variables / config-settings confusion

### ISSUE THREAD

**Issue by Baerbeisser** [actionless/pikaur#801]
```
pikaur -Sy

```

##### Prerequisites:
environment set to:  
XDG_CACHE_HOME=$HOME/.local/tmp  
XDG_DATA_HOME=$HOME/.local/data

##### Description:
every time you run pikaur, 
```
cachepath = $HOME/.cache
datapath = $HOME/.local/share
```
gets addded to pikaur.conf independ of your XDG variables and it then uses cachepath for cache.  
Curiously, it then still uses `~/.local/data/pikaur` for aur_repos.

So, in summary:
- XDG_CACHE_HOME gets ignored for config
- - cachepath in config gets used
- XDG_DATA_HOME gets ignored for config
- - but used for repo backups

**Comment by actionless** [comment]
@samuel-jimenez , please communicate with @Baerbeisser how to fix that, otherwise i'll have to unmerge your PR (https://github.com/actionless/pikaur/pull/796)

**Comment by samuel-jimenez** [comment]
The order of resolution is:

1. Command line options (`--xdg-cache-home`)
2. Environment variables (`XDG_CACHE_HOME`)
3. Config setting (`cachepath = ..`)

So the config setting should not matter if an environment variable is set.

Part of the pikaur operation is to call itself with sudo and command line options. In this step, the incorrect cachepath is used.

I will look around to find a fix.
