### ISSUE TITLE
refactor: don't split `pacman -Su` into retrieving upgradeable packages and doing `pacman -S` after

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#81]
if user is altering interactively the list of packages to be upgraded — just do:
`pacman -Su --ignore exluded_pkg_name additional_pkg_name`

**Comment by AladW** [comment]
So is the only aspect about the "pacman wrap"? I'm thinking #80, #65, etc. 

IOW I'm not sure in what places pikaur uses pacman at all and in which others it reimplements it.

**Comment by actionless** [comment]
i am not sure it's possible to avoid those things which you gave in the links

1) basically the problem with groups -- because i am looking up the package before passing it to pacman. why i am looking it up? because i need to determine if it's presented in repo, so otherwise iu can search it in AUR
2) regarding the replacements -- after this (#81) refactoring that code can be dropped (if I understood right how `pacman -Su` is working)

**Comment by actionless** [comment]
also important note what libalpm is used only for querying info but not for manipulating the database

so i think the current 2 open bugs are the only issues on the topic of pacman wrapping

**Comment by actionless** [comment]
@AladW why do you think it's still not complete?

**Comment by AladW** [comment]
The only complete thing is exactly what's discussed on the wiki: do pacman -Syu when you give it -Syu. Helpers that put in the extra effort to make it work that way should be rewarded accordingly.

**Comment by actionless** [comment]
but according to discussion in arch wiki the difference between `pacman -Syu` and `pacman -Sy ; pacman -Su` doesn't matter unless it's -Syy or some other deviation

**Comment by actionless** [comment]
for example, pacman log, from `pikaur -Syu`:

```log
[2018-03-24 09:01] [PACMAN] Running 'pacman --sync --refresh'
[2018-03-24 09:01] [PACMAN] synchronizing package lists
[2018-03-24 09:01] [PACMAN] Running 'pacman --sync --ask=20 --sysupgrade'
[2018-03-24 09:01] [PACMAN] starting full system upgrade
[2018-03-24 09:01] [ALPM] transaction started
[2018-03-24 09:01] [ALPM] upgraded vte3 (0.48.3-1 -> 0.50.2+6+g7fe155b9-1)
[2018-03-24 09:01] [ALPM] transaction completed
[2018-03-24 09:01] [ALPM] running 'systemd-update.hook'...
```

**Comment by Morganamilo** [comment]
Pacman itself does `-Sy` then `-Su` internally if you read the code. Because `y` is allowed on every `-S` operation, when pacman gets `-S` it checks for `-Sy` if so it syncs the DBs. Then is performs whatever else it should.

You can do `-Syu` hit no when it asks to update and you've got the databases synced but no upgrade. Pacman could error during the `-Syu` due to free space or any other reason and as long as that failure occurs after the `y` completes you're left in the same situation.

**Comment by AladW** [comment]
Since we all seem to be on the same page apart from some details, I propose to continue this discussion on the wiki. Worst case, those who engaged in the discussion can cast a vote on their preferred option.

**Comment by AladW** [comment]
@actionless @Morganamilo https://wiki.archlinux.org/index.php/Talk:AUR_helpers#Summary_of_possible_options

**Comment by AlexWayfer** [comment]
OK, guys.

Before I used `pacaur` and saw something like this:

```
$ pacaur -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
:: Replace gnome-themes-standard with extra/gnome-themes-extra? [Y/n] 
:: Replace gnome-tweak-tool with extra/gnome-tweaks? [Y/n] 
resolving dependencies...
looking for conflicting packages...
```

Now I'm using `pikaur` and seeing this:

```
$ pikaur -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    gnome-themes-standard    
    gnome-tweak-tool    
Resolving AUR dependencies...

:: Repository packages will be installed:
```

`Following packages cannot be found in AUR` — yes, but what should I do? Uninstall these packages? I don't want uninstall `gnome-tweak-tool` or `gnome-themes-standard`. Left them outdated? It can be dangerous with GNOME 3.26 → 3.28 update, for example. I even don't know if there are replacements in `extra/` or anywhere else only with `pikaur`, I should use another tool for this. And yes, I didn't see `extra/gnome-tweaks` package in the list.

I don't like approach where CLI becomes less user-friendly.

**Comment by actionless** [comment]
@AlexWayfer but if you run `pikaur -Syu` and choose `y` if pacman asks to replace the packages after? (by my assumption it should)

**Comment by AlexWayfer** [comment]
Oh.

I've downgraded package:

```
$ sudo pacman -U /var/cache/pacman/pkg/gnome-tweak-tool-3.26.4-1-any.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...
:: gnome-tweak-tool and gnome-tweaks are in conflict. Remove gnome-tweaks? [y/N] y

Package (2)       Old Version  New Version  Net Change

gnome-tweaks      3.28.0-1                   -1.12 MiB
gnome-tweak-tool               3.26.4-1       1.10 MiB

Total Installed Size:   1.10 MiB
Net Upgrade Size:      -0.01 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                 [############################################] 100%
(1/1) checking package integrity                                               [############################################] 100%
(1/1) loading package files                                                    [############################################] 100%
(1/1) checking for file conflicts                                              [############################################] 100%
(2/2) checking available disk space                                            [############################################] 100%
:: Processing package changes...
(1/1) removing gnome-tweaks                                                    [############################################] 100%
(1/1) installing gnome-tweak-tool                                              [############################################] 100%
:: Running post-transaction hooks...
(1/3) Updating icon theme caches...
(2/3) Arming ConditionNeedsUpdate...
(3/3) Updating the desktop file MIME type cache...
```

Now when I'm entering `pikaur -Syu`, it doesn't ask confirmation, just make all work. Look, there is no `y` near `[Y/n]`:

```
$ pikaur -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    gnome-tweak-tool    
:: Starting full system upgrade...
:: Replace gnome-tweak-tool with extra/gnome-tweaks? [Y/n] 
resolving dependencies...
looking for conflicting packages...

Package (2)         Old Version  New Version  Net Change

gnome-tweak-tool    3.26.4-1                   -1.10 MiB
extra/gnome-tweaks               3.28.0-1       1.12 MiB

Total Installed Size:  1.12 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                 [############################################] 100%
(1/1) checking package integrity                                               [############################################] 100%
(1/1) loading package files                                                    [############################################] 100%
(1/1) checking for file conflicts                                              [############################################] 100%
(2/2) checking available disk space                                            [############################################] 100%
:: Processing package changes...
(1/1) removing gnome-tweak-tool                                                [############################################] 100%
(1/1) installing gnome-tweaks                                                  [############################################] 100%
:: Running post-transaction hooks...
(1/3) Updating icon theme caches...
(2/3) Arming ConditionNeedsUpdate...
(3/3) Updating the desktop file MIME type cache...
:: Already up-to-date.
```

When I'm running `sudo pacman -Syu` — it waits confirmation:

```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
:: Replace gnome-tweak-tool with extra/gnome-tweaks? [Y/n] y
resolving dependencies...
looking for conflicting packages...

Package (2)         Old Version  New Version  Net Change

gnome-tweak-tool    3.26.4-1                   -1.10 MiB
extra/gnome-tweaks               3.28.0-1       1.12 MiB

Total Installed Size:  1.12 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                 [############################################] 100%
(1/1) checking package integrity                                               [############################################] 100%
(1/1) loading package files                                                    [############################################] 100%
(1/1) checking for file conflicts                                              [############################################] 100%
(2/2) checking available disk space                                            [############################################] 100%
:: Processing package changes...
(1/1) removing gnome-tweak-tool                                                [############################################] 100%
(1/1) installing gnome-tweaks                                                  [############################################] 100%
:: Running post-transaction hooks...
(1/3) Updating icon theme caches...
(2/3) Arming ConditionNeedsUpdate...
(3/3) Updating the desktop file MIME type cache...
```

I suppose it's another bug.

OK, let's move on. 

Downgrade `gnome-tweaks` to `gnome-tweak-tool` and some package from `pacman` repos, `wine` for example:

```
$ sudo pacman -U /var/cache/pacman/pkg/wine-3.4-1-x86_64.pkg.tar.xz
loading packages...
warning: downgrading package wine (3.4-2 => 3.4-1)
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change

wine         3.4-2        3.4-1          1.88 MiB

Total Installed Size:  403.22 MiB
Net Upgrade Size:        1.88 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                 [############################################] 100%
(1/1) checking package integrity                                               [############################################] 100%
(1/1) loading package files                                                    [############################################] 100%
(1/1) checking for file conflicts                                              [############################################] 100%
(1/1) checking available disk space                                            [############################################] 100%
:: Processing package changes...
(1/1) downgrading wine                                                         [############################################] 100%
:: Running post-transaction hooks...
(1/3) Registering binary formats...
(2/3) Arming ConditionNeedsUpdate...
(3/3) Updating the desktop file MIME type cache...
```

Everything is OK. 

Upgrading:

```
$ pikaur -Syu                                                                                                   27 Mar 23:28:44 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...
:: warning: Following packages cannot be found in AUR:
    gnome-tweak-tool    

:: Repository package will be installed:
 wine                                  3.4-1               -> 3.4-2

:: Proceed with installation? [Y/n]
:: [v]iew package detail   [m]anually select packages
> y
looking for conflicting packages...
:: Starting full system upgrade...
:: Replace gnome-tweak-tool with extra/gnome-tweaks? [Y/n] 
resolving dependencies...
looking for conflicting packages...

Package (3)         Old Version  New Version  Net Change

gnome-tweak-tool    3.26.4-1                   -1.10 MiB
extra/gnome-tweaks               3.28.0-1       1.12 MiB
community/wine      3.4-1        3.4-2         -1.88 MiB

Total Installed Size:  402.46 MiB
Net Upgrade Size:       -1.86 MiB

:: Proceed with installation? [Y/n] 
(2/2) checking keys in keyring                                                 [############################################] 100%
(2/2) checking package integrity                                               [############################################] 100%
(2/2) loading package files                                                    [############################################] 100%
(2/2) checking for file conflicts                                              [############################################] 100%
(3/3) checking available disk space                                            [############################################] 100%
:: Processing package changes...
(1/1) removing gnome-tweak-tool                                                [############################################] 100%
(1/2) installing gnome-tweaks                                                  [############################################] 100%
(2/2) upgrading wine                                                           [############################################] 100%
:: Running post-transaction hooks...
(1/4) Updating icon theme caches...
(2/4) Registering binary formats...
(3/4) Arming ConditionNeedsUpdate...
(4/4) Updating the desktop file MIME type cache...
```

Oh yes, there is was confirmation (once) and replacement.

@actionless, please help with creation a bug about no-confirmation. I don't sure that it's a bug, but…

**Comment by AlexWayfer** [comment]
> Oh yes, there is was confirmation (once) and replacement.

And yes, there is no confirmation at moment `:: Replace gnome-tweak-tool with extra/gnome-tweaks? [Y/n] `, as with `pacman`.

**Comment by actionless** [comment]
thanks for the very detailed report! i'll start investigating why pacman ask-flags are not working here as expected here

**Comment by actionless** [comment]
@AladW that's weird i was trying different combination of ask bits and in every combination of them replacements was installed without confirmation. Does it looks like a pacman bug which should be reported or am I doing smth wrong?

**Comment by Morganamilo** [comment]
Are you sure its actually installing? Pacman does not fail if you select no so it's probably just continuing with the install but skipping that one replace.

Using `--ask 2` should set replace to no.

**Comment by actionless** [comment]
@Morganamilo thanks a lot! it seems i need to inverse the flags

**Comment by Morganamilo** [comment]
Yeah the `--ask` flag actually means "flip the answer" not "set to yes" as you may assume. It's sad that there's no documentation for this. Maybe in the next Pacman release?

**Comment by actionless** [comment]
@Morganamilo 
also i can't understand how SELECT_PROVIDER flags assumed to work, i've tried with it and without and in both cases it was the same behavior:

```
$ sudo pacman -S --ask=32 cargo --needed
warning: rust-1:1.24.1-1 is up to date -- skipping
 there is nothing to do

$ sudo pacman -S --ask=0 cargo --needed
warning: rust-1:1.24.1-1 is up to date -- skipping
 there is nothing to do
```

**Comment by actionless** [comment]
oh, that was when rust is installed, when it's not the behavior even more weird:

```
$ sudo pacman -S cargo --needed --ask=32
:: There are 2 providers available for cargo:
:: Repository community
   1) rust  2) rustup

Enter a number (default=1):
resolving dependencies...
looking for conflicting packages...

Package (1)       New Version  Net Change  Download Size

community/rustup  1.11.0-2       5.66 MiB       1.44 MiB

$ sudo pacman -S cargo --needed --ask=0
:: There are 2 providers available for cargo:
:: Repository community
   1) rust  2) rustup

Enter a number (default=1):
resolving dependencies...
looking for conflicting packages...

Package (1)     New Version  Net Change

community/rust  1:1.24.1-1   210.54 MiB
```

**Comment by Morganamilo** [comment]
I think maybe ask is just not meant to be used with the provider question?

`--ask` Literally just flips the answer so all it does is `answer = !answer` Most questions are boolean so it just swaps between 1 and 0. The providers question is an int (the number you see is 1-2 but internally it's 0-1) So like like before it changes it between the default of 0 to 1.

**Comment by actionless** [comment]
i think much better will be if pacman would have just a single flag to skip first Y/n confirmation but to handle all others normally in interactive mode

**Comment by actionless** [comment]
since it not have it i think it would be better just to remove --ask flag at all for now

**Comment by AladW** [comment]
>It's sad that there's no documentation for this. Maybe in the next Pacman release?

There's no documentation (albeit a description in the pacman git log) because it's a deliberately undocumented feature that's only used in the `pacman` test suite.

**Comment by Morganamilo** [comment]
>i think much better will be if pacman would have just a single flag to skip first Y/n confirmation but to handle all others normally in interactive mode

I've always though `--ask` should just not imply `--noconfirm`

**Comment by Morganamilo** [comment]
I didn't know it was just meant for testing but that does make sense now thinking about it.

Still thought, it's available to the users so I think it deserves some documentation.

**Comment by AladW** [comment]
It is deemed "non-user friendly" https://git.archlinux.org/pacman.git/commit/?id=90e3e026d1236ad89c142b427d7eeb842bbb7ff4

**Comment by Morganamilo** [comment]
Why not `#fidef` it for debug builds then.

**Comment by actionless** [comment]
i did the planned changes (linked commit above)

users who choose pikaur for containers/scripts shouldn't be affected since --noconfirm and so still bypassed correctly to pacman

**Comment by AladW** [comment]
Can you add some commit to the wiki table that demonstrates pikaur does exactly `pacman -Syu` and nothing else.

**Comment by actionless** [comment]
@AladW  but that requirement was removed for `Pacman wrapper` criteria in the wiki as far as i see

**Comment by actionless** [comment]
now it's only only required not to split `-Syu` to `-Sy` and `-S <packages>`, while i am splitting `-Syu` to `-Sy` and `-Su`

i can split `-Syu` to `-Sy` and `-Syu` but it was discussed quite objectively what for pacman itself splitting `y` and `u` is not sensible

**Comment by AladW** [comment]
>@AladW but that requirement was removed for Pacman wrapper criteria in the wiki as far as i see

No it was not. I just added a note explaining what Partial is.

**Comment by actionless** [comment]
then it should be stated clearly what even separation of `-Syu` to `-Sy` and `-Su` is counted like that, because right now it looks like that Partial is a sign of some real problem, like -Rdd and so

**Comment by actionless** [comment]
```
 Partial means that a feature is not fully implemented, or that it deviates from the given criteria in a minor way.
```

```
     Native pacman: when used as replacement for pacman(8) commands such as pacman -Syu, the following are obeyed by default:

    – do not separate commands, for example pacman -Syu is not split to pacman -Sy and pacman -S packages;
    – use pacman directly instead of manual database manipulation or usage of libalpm(3).
    In addition, unsupported commands such as pacman -Ud, pacman -Rdd or pacman --force are not used.
```

**Comment by AladW** [comment]
Yes, "in a __minor way__". I disliked adding this but it seems a reasonable compromise to prevent people from constantly changing the table or otherwise making complaints.

**Comment by actionless** [comment]
@AladW now it all fully bypassed

**Comment by actionless** [comment]
also, it should legal to add config option "RemoveDBkiller"

**Comment by AladW** [comment]
I have no idea what you mean or what that commit does.

**Comment by actionless** [comment]
what --refresh/-y option which wasn't bypassed to pacman before is bypassed now
