### ISSUE TITLE
Change warning for base-devel if doas is used instead of sudo

### ISSUE THREAD

**Issue by Baerbeisser** [actionless/pikaur#810]
I see the not-yet-an-issue with pikaur printing an error if package group `base-devel` not existing got already a [commit](https://github.com/actionless/pikaur/commit/d06977b6bc3c3cda03fd850d763d0161aded6d07), changing it to a warning.  

Though still, since arch made sudo part of the group, removing sudo (since you're using doas, despite sudo being default) removes base-devel too. A workaround is to install the individual tools separately, without sudo. But then you get the ambiguous warning that you borked your computer.

I get that this is an arch repo issue and pikaur does basically the right thing. But can't you look for the most important packages like `make` instead?

**Comment by actionless** [comment]
just create a pkgbuild with your own base-devel which would depend on those dev tools which you are using instead of arch defaults

**Comment by actionless** [comment]
also, preceding the question about why message is ambiguous - because its goal to force user into finding the answer in the wiki page, thus forcing to read it, instead of just blindly installing the missing deps

**Comment by actionless** [comment]
i came with the idea, that i could check for this config setting, https://github.com/actionless/pikaur?tab=readme-ov-file#privilegeescalationtool-default-sudo
and if it's set to `doas`, to show a different warning, like "doas is not part of minimal arch default setup, be aware that you could run into potential problems" and make that warning (unlike the current warning message) possible to turn off

**Comment by Baerbeisser** [comment]
Yeah, that sounds more helpful.

**Comment by actionless** [comment]
> although pikaur currently only supports sudo or doas, i think?

in theory you could put there any executable name, but it must have the same arguments as sudo, and doas is handled separately, as it have slightly different args than sudo
