### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by pezz** [actionless/pikaur#812]
```
pikaur -Vq

Pikaur v1.22
Pacman v6.1.0 - libalpm v14.0.0 - pyalpm v0.10.6
```

##### Description:

The latest version of pikaur started telling me this:

```
:: warning: 
Read damn arch-wiki before borking your computer
https://wiki.archlinux.org/title/Arch_User_Repository
```

Being a user of the AUR for about 15 years I found this very unhelpful. After looking for the message in the code it turns out you get this nice message if the base-devel meta package is not installed (regardless if you have all the tooling needed to build packages).

You could at least hint at why this very unhelpful message is being produced.

Also, if you're going to be heavy-handed like this, at least write the sentence properly ("Read the damn Arch Wiki" not "Read damn").

**Comment by actionless** [comment]
https://tr.wikipedia.org/wiki/Lolcat#/media/Dosya:Lolcat_in_folder.jpg

**Comment by pezz** [comment]
Appreciate the childish response. Good work.

**Comment by actionless** [comment]
learn how to use search on github issues, and don't create duplicate ones, adult 👴

**Comment by xPMo** [comment]
No duplicate issue exists. It was in a PR (#806), which is why you didn't find it.

I ran into it as well, it'll happen if you never [converted from the `base-devel` package group to the new meta package](https://archlinux.org/news/switch-to-the-base-devel-meta-package-requires-manual-intervention/).

**Comment by actionless** [comment]
yup, i mean #810 

> because never [converted from the base-devel package group to the new meta package](https://archlinux.org/news/switch-to-the-base-devel-meta-package-requires-manual-intervention/).

yup, that change happened not yesterday, and not even a year ago, so i expect everyone to catch up with this
