### ISSUE TITLE
Error message "Read damn arch-wiki before borking your computer"

### ISSUE THREAD

**Issue by j0hannes** [actionless/pikaur#816]
Hi,

I'm seeing this message for a couple of days now and I have no clue what it is about.

I've searched the code and found (before it got obfuscated) that it is raised by `if not PackageDB.get_local_pkg_uncached("base-devel")`, which translates to the class method `get_alpm_handle`, which, in turn, is the result of the function call to `initialize_alpm`, which has to do with reading in the pacman config. Unfortunately, I still can't figure out what's causing this (somewhat cryptic) message. Can you elaborate?

**Comment by patrick-g** [comment]
It seems obfuscated code to me :
![Capture d’écran_2024-06-24_17-20-20](https://github.com/actionless/pikaur/assets/396194/260c7fb0-c653-4e3e-8dc2-1b9e34b52ea1)

**Comment by actionless** [comment]
message clearly stating NOT to report to pikaur if you're seeing it
