### ISSUE TITLE
Do not require enter on yes/no questions

### ISSUE THREAD

**Issue by JakeStanger** [actionless/pikaur#83]
It's a little detail, but it's something pacaur does I quite like. When asking questions about pkgbuilds, etc, pacaur only requires you to press y/n and moves on immediately. Pikaur currently requires you to type your input and then press the enter key, which just feels slower than it should be.

**Comment by actionless** [comment]
it's very subjective (and objectively not following pacman style)

there were already a PR implementing this feature, but it can be accepted only if it will be implemented optionally (ie configured via the config file)

**Comment by JakeStanger** [comment]
Should just need to bind either `input` or `get_answer` depending on the config value to a variable, and call that instead of `input(). I'll have a look into it.

**Comment by actionless** [comment]
you can take it up from here: https://github.com/actionless/pikaur/pull/28

**Comment by JakeStanger** [comment]
Created #84. It isn't integrated with the config file but it should be easy enough to do. I'll be honest I haven't really looked because it's some stupid hour in the morning; I'll let you decide what happens with that.
