### ISSUE TITLE
pikasay is a pain in the autocompletion butt

### ISSUE THREAD

**Issue by kubrickfr** [actionless/pikaur#837]
```
pikaur -Vq
Pikaur v1.26.1
Pacman v6.1.0 - libalpm v14.0.0 - pyalpm v0.10.6
```
I find it very annoying that pikasay forces me to type 5 characters before I can tab-autocomplete the pikaur command vs 3 before (years of habit).

I know it sounds silly, but it's actually annoying. Feel free to close and ignore, I'll move on, but I really think pikasay has a too frivolous purpose to justify this.

**Comment by kyak** [comment]
This is exact reason why I came here today.

pika-Tab is muscle memory now, please don't break it.

@actionless

**Comment by kubrickfr** [comment]
On Zsh, you can add this line to your `.zshrc`:
```shell
zstyle ':completion:*' ignored-patterns 'pikasay'
```
On bash, it seems like this should do the trick although I have not tested it:
```shell
EXECIGNORE=$(which pikasay)
```

**Comment by actionless** [comment]
see also the original ticket: https://github.com/actionless/pikaur/discussions/828#discussioncomment-10455050
