### ISSUE TITLE
Feature request: Recompile aur packages that depend on updated packages (dependent recompilation)

### ISSUE THREAD

**Issue by TheK0tYaRa** [actionless/pikaur#840]
```
$ pikaur -Vq
Pikaur v1.27
Pacman v6.1.0 - libalpm v14.0.0 - pyalpm v0.10.6
```

##### Description:
For example recently `hyprland-git` had a dependency update, `aquamarine-git`, which required the recompilation of `hyprland-git` for hyprland to run. That is one of many examples why it is needed. I just don't have many personally.

**Comment by actionless** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/qt5-styleplugins.hook?h=qt5-styleplugins

**Comment by TheK0tYaRa** [comment]
It seems that a hook can't run pacman or something that runs pacman as it runs into the lockfile. Unfortunate.

**Comment by actionless** [comment]
yeah, that's the expected behavior
