### ISSUE TITLE
Stable versions of the following devel packages have newer versions

### ISSUE THREAD

**Issue by poslat-pismo** [actionless/pikaur#844]
Hello, my problem is that I'm getting this warning:
```
Stable versions of the following devel packages have newer versions
```
but these packages are not different versions, but they are different packages

https://github.com/TheCactusVert/mpv-sponsorblock
https://github.com/po5/mpv_sponsorblock

Is there a way to disable this warning?
Any way to block/ignore that rusty crap?

**Comment by actionless** [comment]
> Any way to block/ignore that rusty crap?

bro, learn how to talk
