### ISSUE TITLE
Error downloading Arch Linux News

### ISSUE THREAD

**Issue by tblancher** [actionless/pikaur#848]
```
% pikaur -Vq
Pikaur v1.30.2
Pacman v7.0.0 - libalpm v15.0.0 - pyalpm v0.10.6

```

##### Description:
Getting an error trying to download Arch Linux News:

```
△  error: GET https://archlinux.org/feeds/news/
△  error: urllib: Too Many Requests
```
I've seen this for several iterations of pikaur, ever since the feed URL changes (dropped the leading `www.` from the FQDN, from what I can remember).  Sometimes it has worked for me in the past few months, but I frequently get this error.  If this has been reported before I wasn't able to find anything about it.

I use pikaur on all of my Arch Linux systems, and I've seen it on all of them today.  I love it as a drop-in replacement for pacman.  Keep up the good work!

##### Attached log:

```
% pikaur -Syu --verbose --pikaur-debug |& tee /dev/tty | xclip -selection clipboard
△  debug: main_60147: Setting stdout to utf-8...
△  debug: main_60147: already set - nothing to do
△  debug: main_60147: Setting stderr to utf-8...
△  debug: main_60147: already set - nothing to do
△  debug: main_60147: Pikaur operation found for args ['/usr/bin/pikaur', '-Syu', '--verbose', '--pikaur-debug']: cli_install_packages
=> sudo --preserve-env=VISUAL,EDITOR -- /usr/bin/pikaur -Syu --verbose --pikaur-debug --pikaur-config=/home/trey/.config/pikaur.conf --user-id=60147 --home-dir=/home/trey --xdg-cache-home=/home/trey/.cache --xdg-data-home=/home/trey/.local/share
△  debug: main_0: Setting stdout to utf-8...
△  debug: main_0: already set - nothing to do
△  debug: main_0: Setting stderr to utf-8...
△  debug: main_0: already set - nothing to do
△  debug: main_0: Pikaur operation found for args ['/usr/bin/pikaur', '-Syu', '--verbose', '--pikaur-debug', '--pikaur-config=/home/trey/.config/pikaur.conf', '--user-id=60147', '--home-dir=/home/trey', '--xdg-cache-home=/home/trey/.cache', '--xdg-data-home=/home/trey/.local/share']: cli_install_packages
△  debug: news: init
△  debug: news: fetch_latest
=> GET https://archlinux.org/feeds/news/
=> pacman --color=never --sync --refresh
:: Synchronizing package databases...
 core downloading...
 extra downloading...
△  error: GET https://archlinux.org/feeds/news/
△  error: urllib: Too Many Requests
△  debug: prompt: Gonna get input from user...
△  debug: FileLock: Acquiring /tmp/pikaur_prompt_103451.lock...
△  debug: FileLock: Acquired /tmp/pikaur_prompt_103451.lock
△  debug: prompt_nolock: Restoring TTY...
△  debug: prompt_nolock: Using standard input reader...
Do you want to retry? [Y/n] △  debug: main_0: 

Canceling by user (SIGINT)...
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 537, in main
    cli_entry_point()
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 363, in cli_entry_point
    execute_pikaur_operation(pikaur_operation=pikaur_operation, require_sudo=require_sudo)
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 285, in execute_pikaur_operation
    pikaur_operation()
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 175, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.12/site-packages/pikaur/install_cli.py", line 222, in __init__
    self._handle_refresh()
  File "/usr/lib/python3.12/site-packages/pikaur/install_cli.py", line 263, in _handle_refresh
    thread.get()
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 355, in wait
    waiter.acquire()
  File "/usr/lib/python3.12/site-packages/pikaur/main.py", line 430, in handle_stop
    raise KeyboardInterrupt

KeyboardInterrupt: 
△  debug: main_0: Restoring stdout...
△  debug: main_0: nothing to do
△  debug: main_0: Restoring stderr...
△  debug: main_0: nothing to do
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedReader name='<stdin>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x0000796f1ee2cdb0)

Current thread 0x0000796f1eef1b80 (most recent call first):
  <no Python frame>
△  debug: main_60147: Restoring stdout...
△  debug: main_60147: nothing to do
△  debug: main_60147: Restoring stderr...
△  debug: main_60147: nothing to do
```
That traceback is simply from me sending SIGINT (`Ctrl-c`) to stop the command, rather than proceeding with the upgrade.  It'd be nice if the failure would show the HTTP status code returned (I suspect 429, but it's unclear).

**Comment by actionless** [comment]
as you already judged it from the log - the AUR server returns to you 429

so it's a bit weird sending a support request to Pikaur, as i'm not in the control of AUR's server

**Comment by actionless** [comment]
from my side i already did the maximum - Pikaur app lets you just skip that error and proceed

**Comment by tblancher** [comment]
OK, I wasn't sure if this gave you any clues as to whether it's pikaur hitting the Arch Linux News feed too often.

After reflection, I figured out what I think it is:  I have [rss2email](https://github.com/rss2email/rss2email.git) set up to fetch Arch Linux News in my mail fetch loop (using `r2e`, with `imapfilter` and isync/`mbsync` that runs every 15 seconds).  So my laptop on my LAN is hitting https://archlinux.org/feeds/news/ too many times within a short span.  

I confirm that the systemd user service/oneshot unit I just created is indeed getting the 429 when trying to fetch Arch Linux News;  it'd be nice if the pikaur/urllib output would show the HTTP status code as well as the message (since you have to infer the code is 429 from the "Too Many Requests" message).

What I've done is remove `r2e` from this mail loop, and set up a systemd user service/oneshot unit to fetch all of my RSS feeds.  I'll need to wait until my home IP address is unblocked by Arch Linux News to test whether this is a sufficient workaround, then schedule a user timer to trigger this a lot less frequently.

**Comment by tblancher** [comment]
I can confirm my workaround fixed the problem.  When I triggered Arch Linux News to temporarily block my home IP address, `pikaur -Syu` consistently would give the 429 Too Many Requests from all my Arch hosts on my home LAN.

Now that the systemd user unit only pulls all my RSS feeds four times a day (every four hours), I don't get the error anymore.

Just posting this here for posterity in case anyone else runs into it.

**Comment by actionless** [comment]
yup, i had the same problem with AwesomeWM widget for displaying updates and figured out that if pulling it 3 times per hour it still OK:

https://github.com/actionless/awesome_config/blob/master/config/widgets.lua#L125

**Comment by tblancher** [comment]
Since I rarely have much time to check personal email (or even professional 
email) more than once a day at the absolute most frequent, having a user timer 
run `r2e` every four hours is sufficient for me.

In the most degenerate case, I was calling it four times a minute, which seemed 
to be too frequent for the Arch News web server.
