### ISSUE TITLE
Installing split packages with arch "any" fails

### ISSUE THREAD

**Issue by cg505** [actionless/pikaur#85]
`pikaur -S python-path python2-path` will crash pikaur. 

This seems to be due to the check at https://github.com/actionless/pikaur/blob/master/pikaur/build.py#L370: `if arch in each_filename and pkg_name in each_filename:`. In this case, `arch` is `'x86_64'` but the package arch in the filename is "any", so it does not match. So for both python-path and python2-path, the line `full_pkg_name = full_pkg_names[0]` above holds through, and pikaur tries to copy over python-path twice (since it is first listed by `makepkg --packagelist`).

It seems the easy fix would be to match `arch` or `'any'`, but I haven't tried this.

**Comment by actionless** [comment]
thanks for reporting!

**Comment by cg505** [comment]
thanks for the super-speedy fix! works great!
