### ISSUE TITLE
Unnecessary install of make dependency when package is already built

### ISSUE THREAD

**Issue by user202729** [actionless/pikaur#852]
```bash
$ pikaur -Vq
Pikaur v1.30.2
Pacman v7.0.0 - libalpm v15.0.0 - pyalpm v0.10.6
```

##### Description:

When I have an already-built version of mpir in the cache, pikaur still attempt to install the build dependency (yasm), then uninstall it immediately.

E.g.

```bash
pikaur -S mpir
pikaur -R mpir
pikaur -S mpir
```

**Comment by actionless** [comment]
that's by design, because some packages' `pkgver()` function could freely (according to PKGBUILD spec) use any executables defined in the dependencies (ex. https://github.com/actionless/pikaur/issues/318), and pkgver is needed for checking if package is already built
