### ISSUE TITLE
Pikaur stuck in loop when updating with new build deps

### ISSUE THREAD

**Issue by Patschke** [actionless/pikaur#853]
```
[~]$ pikaur -Vq                                      
Pikaur v1.30.2
Pacman v7.0.0 - libalpm v15.0.0 - pyalpm v0.10.6

```

##### [Optional] Prerequisites:
Probably some packages with new build deps that are also updated? I did not debug this and found a way around, I still thought it would be usefull to raise the issue here. 

EDIT: According to #854, it seems like a fresh installation of `python-shiboken2` would cause the same issues. 

##### Description:
When attempting to update using normal `pikaur -Syu`, I'm stuck in a loop. I receive a `warning: New build deps found for pyside2, python-shiboken2 package` before the first question "Proceed with installation? [Y/n]". However, if I confirm, I'll just end up with the very same warning and question again. 

I was able to update by removing the two packages `pyside2` and `python-shiboken2` which have those updated build deps, but somehow I believe that pikaur shouldn't enter this loop anyway. 

##### Attached log:
```
pikaur -Syu --verbose --pikaur-debug --ignore mathematica --ignore vivado 2>&1 | tee /tmp/pikaur.log
[...] (too large for a comment, see file below)
```
[pikaur.log](https://github.com/user-attachments/files/18076480/pikaur.log)

**Comment by HLFH** [comment]
Same issue.
