### ISSUE TITLE
misleading warning about "Dynamic Users feature will be disabled in the upcoming releases."

### ISSUE THREAD

**Issue by Strubbl** [actionless/pikaur#859]
##### Description:
I get the following warning which i do not understand when i call pikaur to update my system.

```
$ pikaur -Syu

warning:
  [build]DynamicUsers = root
Dynamic Users feature will be disabled in the upcoming releases.
Consider either calling Pikaur from your actual user account without `sudo`, or creating `pikaur` user and specifying its UserId in Pikaur config
and set DynamicUsers to `never`
…
$ type pikaur 
pikaur is hashed (/usr/bin/pikaur)
$ file /usr/bin/pikaur
/usr/bin/pikaur: Python script, ASCII text executable
```

I am calling this as user from my actual account without using sudo and also not as root. So i already do what the description of the warning suggests. Why does this warning not go away then?

**Comment by papodaca** [comment]
I was genuinely surprised that my config file specified root (`~/.config/pikaur.conf`). Correcting that to the "default" of "never" corrected the issue, I assume root was the default at sometime in the past?
```toml
[build]
dynamicusers = root
```

**Comment by Strubbl** [comment]
> Correcting that to the "default" of "never" corrected the issue

Yes, i can confirm.

> I eventually ended up deleting that file entirely and letting pikaur generate a new one.

Good idea. I also never changed this config, so a fresh new default one might also the best for me.
