### ISSUE TITLE
Why are those hieroglyphs in pikaur output?

### ISSUE THREAD

**Issue by rafnov** [actionless/pikaur#860]
Can be seen here at the beginning of few lines: https://ibb.co/7Nh46X3
It's XFCE Terminal with encoding set to UTF-8. Pikaur is 1.32. Changing font does not help.

**Comment by actionless** [comment]
> Why

because your terminal doesn't support emoji, i guess, i didn't checked the link

**Comment by rafnov** [comment]
The link is just a part of the screenshot.

![pikaur.png](https://github.com/user-attachments/assets/413633b3-6626-41fb-a0cd-39b0118a16ef)

**Comment by actionless** [comment]
yeah, as i told before either you terminal doesn't support emoji or you don't have an emoji font installed

**Comment by rafnov** [comment]
Ok, thx for the info.

**Comment by ZimbiX** [comment]
Please make the decoration configurable - I'd rather not have a scooter, imho

https://github.com/actionless/pikaur/blob/2ce728e5e0efa48f2c852548dd5ef6e0b666dc50/pikaur/config.py#L50-L54

![image](https://github.com/user-attachments/assets/1c30382a-2a82-4249-9c69-e3c1a2251816)

**Comment by actionless** [comment]
@tepozoa if i recall correctly, firefox have builtin emoji font which is used when system one not installed or not configured properly, but i'm not in the mood helping to configure stuff on your arch desktop setup for free - you could find such help at arch bbs or subreddit

**Comment by actionless** [comment]
> victim-blame

such a vocabulary 👌😸 to express inability to configure emojis at desktop computer in 2024

**Comment by nebulosa2007** [comment]
Actually a lot of users haven't emoji font installed and now sees just broken glyphs. As a decision - please add optional/emplicit dependency to AUR package.

**Comment by actionless** [comment]
@nebulosa2007  mb i should also include into dependencies a video driver, because there are some potential dumbheads who are just sitting in front of blank monitor, not knowing why it's not displaying anything?

that's not what package dependencies for

**Comment by actionless** [comment]
also, i wonder how soon users of one very **wonderful** terminal who just literally crashing on emojis would come and whine here instead of trying to remove the crash from the terminal code

**Comment by actionless** [comment]
hint: all you whining really doesn't matter a bit and ONLY causing annoyance unless prior to whining you contributed any code or money into the project
