### ISSUE TITLE
Option to ignore package architecture when building

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#87]
most of AUR packages have only i686 and x86_64 arches in the PKGBUILD while lots of them are actually buildable on others. So when installing lots of the packages on the alternative arch it's getting quite annoying to edit every PKGBUILD manually.

**Comment by AladW** [comment]
yay has some fancy mechanism where it detects such a case and asks the user if --ignorearch should be specified to makepkg: https://github.com/Jguer/yay/commit/4bcd3a6297052714e91e3f886602ce5c12d15786
