### ISSUE TITLE
Show git commit hash in pikaur --version

### ISSUE THREAD

**Issue by Tyilo** [actionless/pikaur#9]
It only makes sense for `pikaur --version` to only show the version number (`0.5`), if you're running the release version and not some commits after a release.

I think that `pikaur --version` should show `Pikaur 0.5 (<short git hash>)` when not using a release version.

**Comment by actionless** [comment]
i think i'll have to change build procedure to sed config.py and add git has there, idk if there is more elegant way to do that

**Comment by actionless** [comment]
thanks for reporting!
