### ISSUE TITLE
Doesn't let me edit PKGBUILD with requireenterconfirm = no

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#94]
When the config `requireenterconfirm = no` is active and I press `y` when pikaur asks me whether I want to edit the PKGBUILD, it just doesn't care and continues ;-)

**Comment by actionless** [comment]
weird, i can't reproduce it

**Comment by SpineEyE** [comment]
I'm sorry, I meant `no`, I mixed it up.

**Comment by actionless** [comment]
@JakeStanger please have a look

**Comment by JakeStanger** [comment]
I can't even get as far as the pkgbuild selection; it just exits as soon as you hit `y` with `requireenterconfirm = no`
