### ISSUE TITLE
Continues to install dependencies after build error

### ISSUE THREAD

**Issue by SpineEyE** [actionless/pikaur#95]
When executing `pikaur -Syu tageditor`, the build of `reflective-rapidjson` fails. After that, pikaur  successfully removes already installed dependencies, which is awesome and something aurman doesn't do. Afterwards though, it installs two dependencies instead of just exiting.

Here is the complete log file: [bug.txt](https://github.com/actionless/pikaur/files/1856423/bug.txt)

**Comment by actionless** [comment]
please check

**Comment by SpineEyE** [comment]
Thank you, works as expected.

**Comment by actionless** [comment]
thanks for reporting!
